### ISSUE TITLE
Add a way of getting default values from a schema

### ISSUE THREAD

**Issue by Demivan** [fabian-hiller/valibot#105]
It is really useful to populate fields in a form.

Example of this method in `Yup` https://github.com/jquense/yup#schemagetdefaultoptions-object-any

**Comment by fabian-hiller** [comment]
Thank you very much for the hint. I plan to improve this with one of the next versions.

**Comment by fabian-hiller** [comment]
I expect to add this functionality with a new version in the next two weeks.

**Comment by fabian-hiller** [comment]
v0.15.0 is now available.
