### ISSUE TITLE
Missing `intersection` helper

### ISSUE THREAD

**Issue by davidmyersdev** [fabian-hiller/valibot#113]
I noticed there is a `union` helper but no `intersection` helper. Is this intended or just missing? If it's intended, how do you recommend creating an intersection? I tried to use `merge`, but it does not allow the same types to be merged that TypeScript allows.

**Comment by fabian-hiller** [comment]
Can you send me a use case with sample code? I would like to understand how `intersection` can be useful with a schema library.

**Comment by fabian-hiller** [comment]
Until then you can implement `intersection ` on your own if necessary. Due to the modularity of Valibot, almost anything that is not included by default can be extended.

**Comment by davidmyersdev** [comment]
Sure thing. I am using Valibot to validate JSON payloads. These payloads are objects with required properties but also support arbitrary extra properties. E.g.

```js
{
  name: 'David', // required property
  someUnknownValue: 123, // unknown, optional property
}
```

To represent the object in TypeScript, I can use an intersection like this.

```ts
type MyJsonObject = { name: string } & Record<string, unknown>
```

In Valibot, I'd love to be able to do something like this.

```ts
const MyJsonSchema = intersection(
  object({
    name: string(),
  }),
  record(string(), unknown()),
)
```

**Comment by fabian-hiller** [comment]
Thanks for the example. Which schema library did you use before? How did you solve it there?

**Comment by davidmyersdev** [comment]
I've used Zod previously, and it has support for intersections. https://zod.dev/?id=intersections

**Comment by fabian-hiller** [comment]
As soon as I find the time, probably early September, I will implement it. If you want, you can also create a PR.

**Comment by davidmyersdev** [comment]
I appreciate it! I'll see if I can take a look at the codebase sometime this week. Have any specific resources that might help me get started with a PR for this?

**Comment by fabian-hiller** [comment]
The source code of Valibot is very simple. For example, take a look at [`string`](https://github.com/fabian-hiller/valibot/blob/main/library/src/schemas/string/string.ts) and one of the [methods](https://github.com/fabian-hiller/valibot/tree/main/library/src/methods). It may also help to check the implementation of [Zod](https://github.com/colinhacks/zod/blob/v3.22.2/src/types.ts#L3038-L3184).

**Comment by fabian-hiller** [comment]
I took a closer look at this issue and also your PR and I wonder if `intersection` is the right API for your use case. Wouldn't `catchall` like in Zod be better suited?

```ts
const JsonSchema = catchall(object({ name: string() }), record(unknown()));
```

I am not sure about the name `catchall` yet. Maybe names like `catchRest`, `checkRest` or `withRest` are more appropriate.

**Comment by davidmyersdev** [comment]
@fabian-hiller for my specific use case, I think that would make sense (although I agree the name Zod uses could be clearer). That said, is there a reason to _not_ support intersection as a first-class type? Is it because the complexity of various type combinations would be a bit harder to manage on the runtime side?

**Comment by fabian-hiller** [comment]
I don't currently know if I want to add `intersection`, as I don't yet know of a useful use case in the context of a schema library. If you have one, feel free to share it with me.

What would you call the `catchall` function in Valibot? Do you have a favorite among the listed names or maybe even a completely new idea?

**Comment by TuckerWhitehouse** [comment]
This is currently the one piece stopping me migrating from zod.
I make use of `zod.intersection` to combine `zod.object` with `zod.custom` and `zod.union`.

The implementation in #117 worked well, but I'd love to see it built into the library before committing to switching.

**Comment by fabian-hiller** [comment]
I think your comment convinced me to add `intersection`. I'll try to take a closer look at it in the next few days. 🙃

**Comment by Karakatiza666** [comment]
Though you are already convinced, let me leave here another use-case for `intersection` (with current API, atleast):
```
const saslPlaintextSchema = union([saslPassSchema, saslOauthSchema])

export const authParamsSchema = union([
  object({
    security_protocol: optional(literal('plaintext'), 'plaintext')
  }),
  merge([
    object({
      security_protocol: literal('ssl')
    }),
    sslSchema
  ]),
  intersection([
    object({
      security_protocol: literal('sasl_plaintext')
    }),
    saslPlaintextSchema
  ]),
  intersection([
    object({
      security_protocol: literal('sasl_ssl')
    }),
    sslSchema,
    saslPlaintextSchema
  ])
])
```
