### ISSUE TITLE
Type inference making all fields optional

### ISSUE THREAD

**Issue by jack-allocate** [fabian-hiller/valibot#114]
Maybe this is a misunderstanding of how to use the library, but I'm seeing that usage of `Input` to infer the types of a schema makes every field optional.

Here's a stackblitz reproduction: https://stackblitz.com/edit/typescript-yq96uq?file=index.ts

With the code
```ts
const TestSchema = object({
  firstName: string(),
})

type TestSchemaType = Input<typeof TestSchema>
```

I would expect to end up with the type
```ts
type TestSchemaType = {
    firstName: string;
}
 ```
 but instead I get
 ```ts
 type TestSchemaType = {
    firstName?: string;
}
```

**Comment by jack-allocate** [comment]
Did some more investigating and seems this is a result of the changes made in `v0.8.0`. Works fine on `v0.7.0`

**Comment by fabian-hiller** [comment]
Do you have TypeScript strict mode enabled?

https://valibot.dev/guides/installation/#general

```
{
  "compilerOptions": {
    "strict": true
    // ...
  }
}
```

**Comment by jack-allocate** [comment]
Yup, here's the whole config:
```
{
  "compilerOptions": {
    "resolveJsonModule": true,
    "isolatedModules": true,
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "strictNullChecks": false,
    "jsx": "preserve",
    "importHelpers": true,
    "useUnknownInCatchVariables": false,
    "moduleResolution": "node",
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "baseUrl": ".",
    "lib": [
      "esnext",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
}
```

**Comment by jack-allocate** [comment]
Ah, it would seem it's the result of `strictNullChecks` being `false`. Once I enabled it in the stackblitz, it worked fine. Might be worth adding that to the installation instructions.

Unfortunately in my case, I'm not able to enable `strictNullChecks` due to the codebase being quite large. Any thoughts on a workaround?

**Comment by fabian-hiller** [comment]
Thanks! I will investigate this in the next few weeks.

**Comment by fabian-hiller** [comment]
Sorry, I can't offer a workaround at the moment.

**Comment by jack-allocate** [comment]
Unless a change to the package was made to fix it, then this issue still exists

**Comment by fabian-hiller** [comment]
The solution was the Typescript configuration. It has an external origin. There is nothing Valibot can do, is there? Explicitly specifying that `strictNullChecks` must be `true` in our docs doesn't make sense, because then we would have to do that for every record set by `strict`.
