### ISSUE TITLE
`Output` of `withDefault(optional(schema))` should not be `undefined`

### ISSUE THREAD

**Issue by ivanhofer** [fabian-hiller/valibot#118]
Great library! I'm looking into replacing `zod` in a few applications but find some smaller issues that block me from migrating. One of them is:

I would expect that the OutputType of an optional property with a default value to not have `undefined` in the type definition.

Example:
```ts
const schema = object({
	test: withDefault(optional(string()), "value"),
})

type InputType = Input<typeof schema>

type OutputType = Output<typeof schema>

const input: InputType = {}
// @ts-expect-error: Property 'test' is missing in type '{}' but required in type 'OutputType'.ts(2741)
const output: OutputType = {}
```

Here `OutputType` currently resolves to `test?: string | undefined` but I would expect it to be `test: string`.

**Comment by ivanhofer** [comment]
For now I wrote a quick helper to fix it for my use case:

```ts
type Output = Fix<Output<typeof schema>>

type Fix<T extends Record<string, unknown>> = {
	[K in keyof T]-?: Exclude<T[K], undefined>
}
```

> Note: this marks ALL optional properties required and not works when having a nested structure.

I just want to share this if anyone runs into the same isse.

**Comment by fabian-hiller** [comment]
I am aware of the problem. I will try to fix it this weekend.

**Comment by ivanhofer** [comment]
Thanks! Let me know if you need help :)

**Comment by fabian-hiller** [comment]
I deprecated `withDefault` and revised `optional`, `nullable` and `nullish`. With the next version the changes will go live.

**Comment by fabian-hiller** [comment]
v0.15.0 is now available.
