### ISSUE TITLE
https://valibot.dev 404's

### ISSUE THREAD

**Issue by smitssjors** [fabian-hiller/valibot#121]
The site is currently giving me 404 errors.

**Comment by fabian-hiller** [comment]
Seems to be a problem with Netlify's edge network. [Modular Forms](https://modularforms.dev/), which uses the same Netlify account, works normally.

**Comment by fabian-hiller** [comment]
Until the site is back online, the [Wayback Machine](http://web.archive.org/web/20230819083529/https://valibot.dev/guides/schemas/) or the [source code](https://github.com/fabian-hiller/valibot/blob/main/website/src/routes/guides/(main-concepts)/schemas/index.mdx) of the website can be used.

**Comment by fabian-hiller** [comment]
https://answers.netlify.com/t/qwik-deployment-started-responding-with-404/100203

**Comment by brandonpittman** [comment]
Did the adapter get updated with yesterday's Qwik release?

**Comment by fabian-hiller** [comment]
Without me doing anything, we are live again! 🎉
