### ISSUE TITLE
cuid2 built in support

### ISSUE THREAD

**Issue by samualtnorman** [fabian-hiller/valibot#122]
zod has built in support for `z.string().cuid2()`
it would help with migration if valibot also supported this out of the box

**Comment by fabian-hiller** [comment]
Do you want to create a PR? You can follow the implementation of [`uuid`](https://github.com/fabian-hiller/valibot/blob/main/library/src/validations/uuid/uuid.ts).

**Comment by samualtnorman** [comment]
I wouldn't mind creating a PR, the official package itself has a validator https://github.com/paralleldrive/cuid2/blob/fb07094487ba5ad038a51ef67bcb9c5f525c173b/src/index.js#L103, is the plan to bundle in that already existing function (to keep the 0 dependencies) or to reimplement the function like zod does.

if we go down the route implementing another validator, something note is that the official validator is more forgiving than the zod one (https://github.com/colinhacks/zod/blob/f59be093ec21430d9f32bbcb628d7e39116adf34/src/types.ts#L549).

the official implementation allows a-z on the first character and the zod version doesn't.
however the zod version also doesn't appear to check the length of the cuid2 (which is normally 24 unless configured otherwise)

**Comment by fabian-hiller** [comment]
I prefer zero dependencies. We can make 24 the default and implement the ability to change it with the first optional parameter.
