### ISSUE TITLE
Is there a way to transform keys?

### ISSUE THREAD

**Issue by jon9090** [fabian-hiller/valibot#127]
I using valibot to validate env variables in nodejs.

So I made a schema:
```
export const schema = object({
   apiUrl: string()
});

export const config = parse(schema, process.env);
```
But my env is:

```
 API_URL=https://.........
```

Is there a way to transform the keys?

**Comment by fabian-hiller** [comment]
Yes, with `transform`: https://valibot.dev/guides/methods/#transform

```ts
export const schema = transform(
  object({ API_URL: string() }),
  (input) => ({ apiUrl: input.API_URL })
);
```

**Comment by estubmo** [comment]
> Yes, with `transform`: https://valibot.dev/guides/methods/#transform
> 
> ```ts
> export const schema = transform(
>   object({ API_URL: string() }),
>   (input) => ({ apiUrl: input.API_URL })
> );
> ```
This seems to be no longer working, as parse is no longer a function of schemas.

**Comment by fabian-hiller** [comment]
Did it work?

**Comment by jon9090** [comment]
Yes! thank you!
