### ISSUE TITLE
strict() does not work with object that contains optional properties

### ISSUE THREAD

**Issue by FabienDehopre** [fabian-hiller/valibot#131]
The `strict()` method throws a `ValiError` when the schema contains an optional property and the validated object did not contain that optional property.
Here is an example:
```ts
const schema = strict(
  object({
    environment: enumType(['dev', 'acc', 'prd']),
    logLevel: enumType(['ALL', 'TRACE', 'DEBUG', 'INFO', 'WARN', 'ERROR', 'OFF']),
    appInsights: optional(
      strict(
        object({
          instrumentationKey: string(),
          cloudRoleName: string(),
          endpointUrl: optional(string()),
          // more optional properties
        })
      )
    ),
  })
);
const obj = {
  environment: 'dev',
  logLevel: 'INFO',
};
const result = safeParse(schema, obj);
```
The `result.success` property is `false` and the `issues` property contains one issue with the message "Invalid keys".
After some debugging in the library code, I see that the `strict` method is looking for different property count between the input and the output.
Unfortunately, the output looks like this after all the other validations (in the `strict`'s `_parse` function):
```ts
{
  environment: 'dev',
  logLevel: 'INFO',
  appInsights: undefined,
}
```
So, the input has 2 properties and the output has 3 properties.

**Comment by fabian-hiller** [comment]
You are right. We need to improve the tests and implementation. Are you interested in creating a PR?

**Comment by FabienDehopre** [comment]
Sure. I can try to do a PR. Not sure when it would be available because I don't have a lot of free time.

**Comment by fabian-hiller** [comment]
No problem. Don't feel obligated. I can take care of it next week.

**Comment by FabienDehopre** [comment]
I think I've fixed the issue by updating the object schema parser to not assign undefined value to optional properties.

**Comment by fabian-hiller** [comment]
Thank you for your contribution. In the next version the problem is fixed.

**Comment by fabian-hiller** [comment]
v0.14.0 is now available.

**Comment by FabienDehopre** [comment]
Great! I'll have a look later this weekend or next week.
