### ISSUE TITLE
Not possible to set path for issues in a pipeline

### ISSUE THREAD

**Issue by Demivan** [fabian-hiller/valibot#133]
After 0.13.0, it is not possible to set custom path for errors in a pipeline.

Essentially, https://github.com/fabian-hiller/valibot/issues/5#issuecomment-1660056243 does not work because you cannot set custom path on the returned issue.

**Comment by demarchenac** [comment]
Hi! I've been tinkering with this for the past few days in my spare time and it seems that this syntax works! But we need to change the `return` statement from `input` to `{ output: input }` to make it work as expected.

**Comment by fabian-hiller** [comment]
Hi @demarchenac, can you describe what exactly do you mean? I plan to expand the implementation for nested issues this week.

**Comment by demarchenac** [comment]
Ok, it seems that I got confused since on the example that I was working on I'm was throwing a `ValiError` instead of using the `issue` syntax

**Comment by fabian-hiller** [comment]
v0.15.0 is now available.
