### ISSUE TITLE
Using enums as a `record` key

### ISSUE THREAD

**Issue by abd2561024** [fabian-hiller/valibot#134]
I need to migrate from follow Zod construction with **Record**
```ts
const MyRecordSchema = z.record(z.nativeEnum(KEY_NAME), z.array(z.string().min(1)).nonempty());
```

If I change this construction to 
```ts
const MyRecordSchema = record(nativeEnum(KEY_NAME), array(string([minLength(1)]), [minLength(2)]));
```

I got follow TS error 
```ts
Types of property  schema  are incompatible.
Type  "native_enum"  is not assignable to type  "string" 
```

So any idea how to fix this error pls? If I ignore it and run `parse`, it works correctrly, and return error when I try to pass incorrect key (not from `KEY_NAME` object).

**Comment by fabian-hiller** [comment]
Thank you very much for your hint. I will try to fix that next week. Basically I just need to update the types. As you wrote correctly, it already works technically.

**Comment by fabian-hiller** [comment]
v0.15.0 is now available.
