### ISSUE TITLE
Can Valibot Detect the Absence of a Key in an Object Without Specifying it in the Schema?

### ISSUE THREAD

**Issue by jon9090** [fabian-hiller/valibot#139]
I encounter the "Invalid Type" error while working with this code:

```
import { email, minLength, object, type Output, parse, string } from 'valibot'; // 0.87 kB

const schema = object({
  url: string(),
});

parse(schema, { });
```
In reality, the 'url' key and its corresponding value are absent. Is there a way to generate a "missing url key" error? If feasible, I'd prefer not to include it in the schema (for cleanliness). 

Can valibot detect the non-existence of the key within the object?

**Comment by fabian-hiller** [comment]
Yes try out the following code:

```ts
import { object, parse, string } from 'valibot';

const schema = object({
  url: string('"url" is missing or invalid'),
});

parse(schema, {});
```

**Comment by fabian-hiller** [comment]
I assume that this issue has been resolved. If not, let me know.
