### ISSUE TITLE
any chance to support date-io lib integrations?

### ISSUE THREAD

**Issue by userquin** [fabian-hiller/valibot#14]
Working with dates in javascript is horrible since the support is quite bad, there are libraries that know how to manage dates quite well.

There is a project that integrates a few libraries called [date-io](https://github.com/dmtrKovalenko/date-io), would it be possible to add support to be able to handle the dates of the integrations here instead of working with Date from javascript?

The libraries would be the ones listed here: https://github.com/dmtrKovalenko/date-io/tree/master#projects

I use `js-joda` a lot to do operations on dates such as add N day/month/year, date before/after? and the like (to name a few).

**Comment by fabian-hiller** [comment]
How exactly would you imagine the integration in the optimal case? Feel free to make a code example of the API with a schema that uses `date-io`. One advantage of our modular design is that if Valibot doesn't support a type, you can simply write it yourself and use it normally with Valibot's other exports.

Furthermore [`special`](https://github.com/fabian-hiller/valibot/blob/main/library/src/schemas/special/special.ts) and [`specialAsync`](https://github.com/fabian-hiller/valibot/blob/main/library/src/schemas/special/specialAsync.ts) can be used to support individual types. Also I could imagine to add an `instanceof` scheme, like [here](https://zod.dev/?id=instanceof) with Zod, to easily work with custom classes. This would make it even easier to support custom date classes.

```ts
import { instanceof, special } from 'valibot';
import { SpecialDate } from 'special-date';

const SpecialDateSchema1 = special<SpecialDate>((input) => input instanceof SpecialDate);

const SpecialDateSchema2 = instanceof(SpecialDate); // Not yet supported
```

**Comment by fabian-hiller** [comment]
I have added [`instance`](https://valibot.dev/api/instance/) as a schema function. Do you have any other questions or feedback for me or can this issue be closed?
