### ISSUE TITLE
custom type guard

### ISSUE THREAD

**Issue by y-nk** [fabian-hiller/valibot#140]
hello. thanks for the modular approach, it seems v. cool!

i was wondering if it was possible to have a schema which accepts a type guard as input. for example, how would could i reuse the `isFooBar` in a schema so that the key was typed as `FooBar` if valid?

```ts
const FOO_BAR = ['foo', 'bar']

type FooBar = (typeof FOO_BAR)['number']

export function isFooBar(arg: any): arg is FooBar {
  return FOO_BAR.includes(arg)
}
```

**Comment by fabian-hiller** [comment]
For custom schemas there is the `special` function.

```ts
const FooBarSchema = special<FooBar>(isFooBar)
```

**Comment by fabian-hiller** [comment]
I assume that this issue has been resolved. If not, let me know.
