### ISSUE TITLE
If I want to compare two fields, it's possible?

### ISSUE THREAD

**Issue by jon9090** [fabian-hiller/valibot#142]
If I want to compare two fields, it's possible?
```
const userSchema = {
   name: string(),
   password: string(),
  confirmPassword: string()
}
```

**Comment by felixdomingos1** [comment]
The non-strict equals operator (==) determines if two values are effectively equal regardless of their data type. The strict equals operator (===) determines if two values are exactly the same in both data type and value, reason that I can say that it is possible

**Comment by fabian-hiller** [comment]
Hi @felixdomingos1 I am aware of that. What exactly are you trying to tell me? Do you have specific feedback about the source code of Valibot?

**Comment by felixdomingos1** [comment]
Does it works!?

A sexta, 15/09/2023, 4:17 da manhã, Fabian Hiller ***@***.***>
escreveu:

**Comment by felixdomingos1** [comment]
What concretely is your problem with that?

A sexta, 15/09/2023, 4:51 da manhã, Félix S. Domingos <
***@***.***> escreveu:

**Comment by felixdomingos1** [comment]
So I am about to move out . Can we talk in WhatsApp?
This is mine +244 954 208 455
Then my be I am going to help...
And no, I didn't work with that yet..

A sexta, 15/09/2023, 4:51 da manhã, Félix S. Domingos <
***@***.***> escreveu:

**Comment by fabian-hiller** [comment]
Please send me an example with **Valibot code** here on GitHub.

**Comment by felixdomingos1** [comment]
So this schema library  I've been use for validating structural data in my frontend projoct, comparaing to Zod or Yup. now i am using it couse of  his big innovation of Valibot is the modular design of the API and an optimization of the source code for compression

**Comment by felixdomingos1** [comment]
import { email, minLength, object, type Output, parse, string } from 'valibot';

const LoginSchema = object({
  email: string([email()]),
  password: string([minLength(16)]),
});

type LoginData = Output<typeof LoginSchema>; // { email: string; password: string }

parse(LoginSchema, { email: '', password: '' });

parse(LoginSchema, { email: 'jane@example.com', password: 'zxcvbnm123' });

**Comment by fabian-hiller** [comment]
What exactly is your question?

**Comment by fabian-hiller** [comment]
Update: Previously, `check` was not executed if the email field was untyped. This problem can now be solved with our new `partialCheck` action.

```ts
import * as v from 'valibot';

const RegisterSchema = v.pipe(
  v.object({
    email: v.pipe(
      v.string(),
      v.nonEmpty('Please enter your email.'),
      v.email('The email address is badly formatted.'),
    ),
    password1: v.pipe(
      v.string(),
      v.nonEmpty('Please enter your password.'),
      v.minLength(8, 'Your password must have 8 characters or more.'),
    ),
    password2: v.string(),
  }),
  v.forward(
    v.partialCheck(
      [['password1'], ['password2']],
      (input) => input.password1 === input.password2,
      'The two passwords do not match.',
    ),
    ['password2'],
  ),
);
```
