### ISSUE TITLE
feature request: allow additional properties in object schema and allow to refuse additional properties via strict

### ISSUE THREAD

**Issue by FabienDehopre** [fabian-hiller/valibot#143]
Actually, the object schema does not allow additional properties from the input to be "copied" to the output as-is (like zod).
I propose to allow additional properties to be transferred as-is from the input to the output.
Additionally, the strict method should allow to "block" those additional properties (again like zod).
I can provide a PR to implement these feature(s) request(s)

**Comment by FabienDehopre** [comment]
I've added a comment to my PR to answer at your remark but here it is as well:

Here what I propose instead: Leave the default behavior of the object schema parser as it is actually but add a new `extraEntries` array property to the `_parser` result that can be validated by the `strict` method.
Additionally, I would also create 2 new "methods" for the object schema:
- `strip` (or any other name that you see fit): ignores the additional properties given in the input (so no additional properties in the output).
- `passthrough` (or any othe name that you see fit): copies the additional properties from input to the output as-is.

And update the `strict` method to throw an error if the `extraEntries` array isn't empty (more or less the same behavior as now).

What do you think about this proposition?

**Comment by fabian-hiller** [comment]
Thanks for your feedback on this. I will probably have more time for open source again next week and will answer you then in detail.

**Comment by fabian-hiller** [comment]
I added `passthrough` and `strip` in v0.14.0. Thank you for your contribution!
