### ISSUE TITLE
Derive ObjectSchema from class

### ISSUE THREAD

**Issue by sachaw** [fabian-hiller/valibot#147]
Hi, Just getting around to using this library and loving it so far.

What I need to achieve is to constrain my `ObjectSchema` with a class.

Take the following class:
```ts
export declare class Config_PowerConfig {
  isPowerSaving: boolean;
  onBatteryShutdownAfterSecs: number;
  adcMultiplierOverride: number;
  waitBluetoothSecs: number;
  ...
}
```
I am able to constrain the property name like so:
```ts
type PowerConfigRecord = Record<
  keyof Config_PowerConfig ,
  any
>;
```

However I have so far been unsuccessful at inferring the type of the field from the data type on the class.
Is there any way currently that this can be achieved?

Thanks.

**Comment by fabian-hiller** [comment]
Thank you for the hint. I'll check and improve this in the next few days.

**Comment by fabian-hiller** [comment]
I think I have not fully understood your problem. Can you explain it with Valibot code? How does it currently behave with other libraries such as Zod?

**Comment by fabian-hiller** [comment]
Is there still interest in this issue? Otherwise I would close it.

**Comment by sachaw** [comment]
Sorry, have been very busy.

I have made the following (It's still very WIP):

```ts
type PrimitiveToSchema<K> = K extends string
	? StringSchema
	: K extends number | bigint
	? NumberSchema
	: K extends Enum
	? EnumSchema<K>
	: K extends string[]
	? ArraySchema<StringSchema>
	: K extends number[]
	? ArraySchema<NumberSchema>
	: ObjectSchema<ConvertToSchema<K>>;

type ConvertToSchema<T> = {
	[K in keyof T]: PrimitiveToSchema<T[K]>;
};

export type ClassToSchema<T> = ObjectSchema<ConvertToSchema<T>, undefined, any>;

//////////////////////////////////////////////////////////

class MyClass {
	property1: string;
	property2: number;
	property3: string[];
}

const schema:ClassToSchema<MyClass> = object({
	property1: string(),
	property2: number(),
	property3: array(string()),
})
```

It will provide type checking and autocomplete based on the properties and types from the class.
