### ISSUE TITLE
How to pass to next in pipe a valid output even if it is in error?

### ISSUE THREAD

**Issue by crystalfp** [fabian-hiller/valibot#152]
I want to validate an uuid that optionally has an appended hex sequence number in the form `-nnn`.
The example is this:

```ts
import {safeParse, string, uuid, type PipeResult} from "valibot";

const validateSequence = (value: string): PipeResult<string> => {

	if(value.length > 36) {

		const sequence = Number.parseInt(value.slice(37), 16);
		if(Number.isNaN(sequence) || sequence <= 0 || sequence > 0xFFF) {
			return {
				issue: {
					validation: "custom",
					message: "Invalid sequence",
					input: value,
				},
			};
		}
                return {output: value.slice(0, 36)};
	}
	return {output: value};
};

const schema = string([validateSequence, uuid()]);

const ex1 = "2894e3d4-dea9-497d-866c-86c292266068";
const ex2 = "2894e3d4-dea9-497d-866c-86c292266068-001";
const ex3 = "2894e3d4-dea9-497d-866c-86c292266068-zzz";

for(const ex of [ex1,ex2,ex3]) {

	console.log("---", ex);
	const result = safeParse(schema, ex);
	if(result.success) continue;

	for(const issue of result.issues) {
		console.log(`validator: ${issue.validation}; message: ${issue.message}`);
	}
}
```

It works perfectly for `ex1` and `ex2`  but `ex3` generates an error also in the following `uuid()` validator:

```
--- 2894e3d4-dea9-497d-866c-86c292266068
--- 2894e3d4-dea9-497d-866c-86c292266068-001
--- 2894e3d4-dea9-497d-866c-86c292266068-zzz
validator: custom; message: Invalid sequence
validator: uuid; message: Invalid UUID
```

Is it possible to signal an issue but pass to the next validator the corrected string? Currently `uuid()` takes the whole string and not the output of the previous validator.
Maybe changing definition (and usage) of the `PipeResult` type? Well, I tried, but changing the type definition alone is not sufficient to enable the output of the corrected uuid along the issue.
Thanks for looking (and for the library!)
mario

**Comment by crystalfp** [comment]
Besides the general problem above, I have solved my problem by including the uuid test inside my `validateSequence` validator.

**Comment by fabian-hiller** [comment]
I don't quite understand your problem yet. If you return a modified input as output in `validateSequence`, it will be picked up by the next function in the pipeline. If you return an issue, the initial input or the output of the last successful pipeline function is used.

Is your goal to return an issue with an output that will be used as input in the next pipeline function? This is currently not possible.

**Comment by crystalfp** [comment]
Thanks for the explanation, @fabian-hiller !
Anyway, what I was confusedly saying is: 
1) I have in input a two parts composite string.
2) The first validator validate the first part and output the second one
3) The second validator validate the second part
4) This works if the two parts are valid or if the second one is invalid
5) If the first part is invalid, the second validator see the whole composite string and fails
What I tried to suggest is to let the 1st validator output the 2nd part even if it is in error. The `PipeResult` type suggest that this could be possible.
Thanks again for your work!
mario

**Comment by fabian-hiller** [comment]
Ok, I understand. You have to keep in mind that if you change the input, this transformation will affect the whole output of the schema. The pipeline can be used not only for validation but also for transformation. In your case, the validation functions should not change the output, but only extract and validate the respective part of the string.

**Comment by crystalfp** [comment]
Thanks for the explanation! I ended up creating my validation routine for this specific value.
And thanks for continuing improving the library!
mario
