### ISSUE TITLE
[feat]: Parse schema with partial fallback values

### ISSUE THREAD

**Issue by hermanseder** [fabian-hiller/valibot#155]
It would be nice to have a functionality to parse a schema with partial fallback values.

For example, that this input:
```js
const schema = object({
  name: fallback(string(), 'test'),
  age: number(),
});

console.log(parse(schema, {}));
```
results in this output:
```js
{
   age: undefined
   name: 'test'
}
```

Or is such a scenario already possible by combining multiple functions together?

As idea, I implemented here a custom version of partial, which uses `fallback` instead of `optional`:
https://stackblitz.com/edit/valibot-partial-fallback-example

**Comment by fabian-hiller** [comment]
Maybe with `optional`? If not, please describe in more detail what behavior you are looking for. I don't quite understand it yet.

```ts
const schema = object({
  name: optional(string(), 'test'),
  age: number(),
});
```

**Comment by fabian-hiller** [comment]
For what exactly do you need the fallback values? Technically this is possible, but not that easy. Especially it is difficult to make it type safe.

**Comment by hermanseder** [comment]
My intention is, that I can parse a schema, where some of the properties have a fallback value, and some not. From this schema I want to extract, only the properties which has a fallback value, into an object. All other properties, which have no fallback value, should be undefined in the extracted object.

As background, I want to use `Valibot` that different components can define in a generic way their required configuration schema. A further requirement is, that these component can also define a partial default value, and therefore I need to extract these values. Another solution would be to separate the schema and the default configuration. But I thought it would be nice to combine them into one (valibot) configuration object.

**Comment by hermanseder** [comment]
Thanks for your detailed explanation. Then I will implement a custom logic in my project. I thought, such a functionality could maybe be helpful for other users.

**Comment by fabian-hiller** [comment]
Yes, feel free to share your implementation. Maybe I will integrate it in `getDefault` or add another method called `getDefaults`.

**Comment by fabian-hiller** [comment]
Were you able to find a solution to your problem?

**Comment by fabian-hiller** [comment]
I have implemented `getDefaults`. The API will be available in the next version.

**Comment by fabian-hiller** [comment]
v0.20.0 is now available

**Comment by BThomann** [comment]
Awesome thank you! In the end the `getFallbacks` was exactly what we have been looking for!
