### ISSUE TITLE
Incorrect TS types  for `recrod`

### ISSUE THREAD

**Issue by abd2561024** [fabian-hiller/valibot#156]
Hi! I have a problem with TS types after `Output` following construction. 

```TS
const SOME_NAME = {
  FOO: "FOO", 
  BAR: "BAR"
} as const;

const ValibotSchema = record(nativeEnum(SOME_NAME), array(string([minLength(1)]), [minLength(1)]));

type ValibotOutType = Output<typeof ValibotSchema>;

const valibotData: ValibotOutType  = {}; // here error with TS ->  "Type  {}  is missing the following properties from type  { FOO: string[]; BAR: string[]; } :  FOO, BAR"

valibotData[SOME_NAME.FOO] = ['1'];
```

I expect, that  `record(nativeEnum(SOME_NAME), array(string([minLength(1)]), [minLength(1)]))` will get me something like `Partial<Record<keyof typeof SOME_NAME, [string, ...string[]]>>` as it returns in `Zod` with follow code:

```TS
const ZodSchema = z.record(z.nativeEnum(SOME_NAME), z.array(z.string().min(1)).nonempty());
  
type ZodOutType = z.infer<typeof ZodSchema>;

const zodData: ZodOutType  = {}; // here all fine

zodData[SOME_NAME.FOO] = ['1'];

```
I'm not sure, than `Zod` correct outputs `record` keys with an `optional` generic (Here is the [issue](https://github.com/colinhacks/zod/issues/1215) with this problem).  So, is this a correct behavior of `record()` logic and I jsut miss something? Or maybe `valibot` has some ability to make `record` keys not `required`?
Thanks a lot!

P.S. Technically, the `parse` and `safeParse` works correctly, you can specify only part of the keys in `record`

**Comment by fabian-hiller** [comment]
Thank you for creating this issue. I will investigate the types in the coming days.

**Comment by abd2561024** [comment]
@fabian-hiller I created a [PR](https://github.com/fabian-hiller/valibot/pull/184) with fixing types for record schema. Now it would be work as in `Zod` implementation (I mean types, technically `parse` and `safeParse` work great as I wrote early)

Otherwise it could be something like other implementation for `partial` method, which would make `record` keys optional,
```TS
declare function partial<TRecordKey extends RecordKey, TRecordValue extends BaseSchema>(
  schema: RecordSchema<TRecordValue, TRecordKey>,
  pipe?: Pipe<Partial$2<RecordOutput<TRecordKey, TRecordValue>>>
): RecordSchema<TRecordValue, TRecordKey, Partial<RecordOutput<TRecordKey, TRecordValue>>>;
```

or something like this, but I didn't sure that this is a right way for this issue (In my opinion, looks like overhead).

**Comment by abd2561024** [comment]
Fixed in [commit](https://github.com/fabian-hiller/valibot/commit/1e73cad4ff8305773f57bd9f038d467151040f78)
