### ISSUE TITLE
Regex alternating behaviour with global flag

### ISSUE THREAD

**Issue by Acrylic125** [fabian-hiller/valibot#158]
Hey!

JavaScript has this weird behaviour with Regex when the `g` flag is used as brought up here:
https://stackoverflow.com/questions/2630418/javascript-regex-returning-true-then-false-then-true-etc 

I have noticed currently the `regex` method does not cater to this edge case:
https://github.com/fabian-hiller/valibot/blob/main/library/src/validations/regex/regex.ts#L16 

Could there be some way to pass a supplier function that recreates the regex?

**Comment by fabian-hiller** [comment]
Can you explain the problem for Valibot here? What exactly do you suggest to change in `regex`? Feel free to make a code example as well.

**Comment by fabian-hiller** [comment]
Is there still interest in this issue? If not, I would close it.

**Comment by CanRau** [comment]
Wow just learned this about the `g` flag, never had that issue before but discovered basically the same issue as in the linked Stackoverflow 🤯 was also adding the `/g` kinda out of habit.

Maybe it might be interesting to add this detail to the docs at least to not use the `/g` flag until you "really" know what you're doing 😅 

Possible quoting this from [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test#using_test_on_a_regex_with_the_global_flag)

> Using test() on a regex with the "global" flag `/g`
> When a regex has the global flag  set, `test()` will advance the `lastIndex` of the regex. (`RegExp.prototype.exec()` also advances the `lastIndex` property.)
> Further calls to `test(str)` will resume searching `str` starting from `lastIndex`. The `lastIndex` property will continue to increase each time `test()` returns `true`.

What do you think @fabian-hiller?

**Comment by fabian-hiller** [comment]
Hey 👋 thank you for reaching out! Can you share a Valibot playground with a reproduction. And yes, we can add a note the API reference of `regex` and maybe also to the JSDoc comment.

**Comment by CanRau** [comment]
if you run this you get true, false, true, false 😅 
https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgGUmALAUxDI4AXkwA6CBQBWfJjAAUAb3pw4AV1R8orZCD4AucWGBg+8jGI5RgrAObyAlABpxUPrb4APeQHoAegDayAC0AF4AgsEAWgAMwQCcALoIACQ+tg7O9AC+DgyM2NBw8izs8AD6cBDYcOFQUMgAnmK4+EpwpHx2MDyGAKxwuQ5wygCQpRxwbqhqpPCiFqjI2HwACshQmvLc-IIuY6MaWjp6hgBEAGpkwGdO9KO5+eNsqBCdYqQQ9tOzMJZqTCYfFQqDyOXoQA

To clarify, I don't run the validation in a loop, I guess it just needs to run in the same process/context which happens in my case in the browser on form submit and the playground is a new process on each run so I had to loop it to reproduce the issue. If you remove the `g` from the regex it'll work every time as expected

I think I could open a PR a little later today 🤞🤓

**Comment by CanRau** [comment]
Kay I've opened https://github.com/fabian-hiller/valibot/pull/1083

**Comment by fabian-hiller** [comment]
Thank you! I will review and merge it soon.
