### ISSUE TITLE
Weird error 😅

### ISSUE THREAD

**Issue by devbyray** [fabian-hiller/valibot#16]
I love the idea of your library, so let's try some things out to see how it works.

But I found some errors that didn't give me a clear error message; maybe something needs to be fixed on my side or your side.

I created a Runkit example so you can check it out: https://runkit.com/devbyrayray/testing-valibot

**Comment by fabian-hiller** [comment]
I think that `dateOfBirth` is the problem. The value should be `string([isoDateTime()])`. In my editor, TypeScript also gives me a type error at this point.

```ts
const UserProfileSchema = object({
  email: string([email()]),
  firstName: string([minLength(1)]),
  lastName: string([minLength(1)]),
  dateOfBirth: isoDateTime(),
});
```

**Comment by devbyray** [comment]
Thanks, man! That works 👍

If I want my lastName also to have a maximum, is this the way to do it? `string([minLength(1), maxLength(10)])`

**Comment by fabian-hiller** [comment]
Yes, that looks correct. You can also add your own error messages if you want:

```ts
string([minLength(1, 'Please enter your last name.'), maxLength(10, 'Please limit your input to 10 characters.')])
```
