### ISSUE TITLE
type error on combo `trpc` `withDefault` validation

### ISSUE THREAD

**Issue by divndev** [fabian-hiller/valibot#160]
First, thanks for the awesome!

server code
```ts
  .input(
    object({
      limit: withDefault(number([minValue(0), maxValue(20)]), 10),
      cursor: withDefault(number([minValue(0)]), 0),
    }),
  )
```

client code

```ts
const { data, isLoading, isError, hasNextPage } = trpc.workspace.list.useInfiniteQuery(
  {}, // Argument of type '{}' is not assignable to parameter of type 'Omit<{ limit: number; cursor: number; }, "cursor">'.
      // Property 'limit' is missing in type '{}' but required in type 'Omit<{ limit: number; cursor: number; }, "cursor">'.ts(2345)
  {
    getNextPageParam: (lastPage) => lastPage.nextCursor,
  },
)
```

It means if I use `withDefault` without `nullish` in my input schema, the trpc client still expects value for limit input

EXPECT: trpc client do not require limit field without using `nullish`

**Comment by fabian-hiller** [comment]
Please upgrade to the newest Valibot version. `withDefault` has been [deprecated](https://github.com/fabian-hiller/valibot/releases/tag/v0.15.0) in favour of `optional`, `nullable` and `nullish`. Also check the [new way](https://github.com/trpc/trpc/issues/4737) with `wrap` form TypeSchema to use Valibot with tRPC.

```ts
import { wrap } from '@decs/typeschema';
import { string } from 'valibot';
 
const appRouter = router({
  // ...
  userById: publicProcedure
    .input(wrap(string()))
    .query(async (opts) => {
      const { input } = opts;
      // Retrieve the user with the given ID
      const user = await db.user.findById(input);
      return user;
    }),
});
```

**Comment by fabian-hiller** [comment]
I am closing the issue as I suspect the problem has been resolved.
