### ISSUE TITLE
[✨ Feature request]: Allow default value for non-optional schemas

### ISSUE THREAD

**Issue by brandonpittman** [fabian-hiller/valibot#168]
I know we can use `optional()` and supply a default value, but I'd like to make a field be required but still provide a default value. This is helpful for things like a `date` field where you must have a date but would like to default to the current date if one isn't provided.

**Comment by BThomann** [comment]
Maybe you can do this using `fallback`?

**Comment by brandonpittman** [comment]
Sorry. Missed it in the docs.
