### ISSUE TITLE
Discussion about `passthrough` to parse object keeping extra props

### ISSUE THREAD

**Issue by dmorosinotto** [fabian-hiller/valibot#17]
Add  `passthrough` method inspired by [Zod](https://zod.dev/?id=passthrough)  to allow `parse object()` keeping extra props  that are present on original input object but not validated through Schema.

This maybe useful if you want to validate/trasform only _"a portion of an object"_ that you receive from/send to and API, but want to keep all the original extra props present in the object that are not specified in object() schema.

PS: some more discussion points:
1. if you prefer other name please let me know, I just used the same name of Zod... but I'm open to alternative/refactor
2. do you think that it's correct to implement it as a _"wrapper"_  and my modification to `unwrap` or do you prefer other way to [implement it](https://github.com/fabian-hiller/valibot/pull/15/commits/36c06d4a3443755b2df4bcc3cb51f885f2adb3f6) ?
3. about this I was even thinking to implement it changing the `object()` implementation adding another overload with an optional `strict: boolean` param  before error - but to do it I need to change the implementation of `getErrorAndPipe` handling 3 params to discriminate boolean, string, Pipe[] ...  I don't know if you'll approve/prefer this kind of implementation, maybe the result is more clear because the real nature of passthrough is just an `ObjectSchema` that keep the extra params, but don't know if you like it... 
4. Or maybe on the same "idea" i can create other 2 function `objectWithExtraProps` that return ObjectSchema but simply use my parse code to keep props... 

This are all the ideas I came up when implementing it, what's your opinion?

_Originally posted by @dmorosinotto in https://github.com/fabian-hiller/valibot/issues/15#issuecomment-1652418243_

**Comment by fabian-hiller** [comment]
If we decide on a method. Can you think of alternative names besides `passthrough`?

**Comment by dmorosinotto** [comment]
About alternative names I can suggest `keepExtras` or `keepExtraProps`

But I have another question do you think that we can change the implementation of `merge` to make it works with Record + Object? Because actually it allow to merge only `ObjectSchema[]`, but if we can make it works with Record+Object we can achieve the "passtrough" by simply `merge( record(string(),any()) , object({...schema...}) );`

I looked at merge code and record() constructor but the two are not compatible to simply join the parse as it's implemented now... 
Or if you think that this idea maybe good, we can create a new method `extends` to specify merge Record+Object correctly handle the parse and input/output type ;-)

Waiting for your feedback @fabian-hiller  about how do you prefer to procede with this issue

**Comment by fabian-hiller** [comment]
The `merge` method is currently only for objects. I will check if the extension for records makes sense. However, I don't think we should implement the `passthrough` feature internally with `merge`.

Thanks for the alternative names. I will consider them. I haven't had a chance to think about this issue yet. I will try to answer you again here as soon as possible.

**Comment by dmorosinotto** [comment]
Yes I see the `merge` code and totally understand why it works only for object - and if you think that enable it to handle even record is a not desired design, I think that the more simple and effective ways to implement "passthrough" is a new method that enable "merging" ObjectSchema + RecordSchema and maybe calling it **extends** 
with two overload one with optional RecordSchema? as you can decide to pass default `record(string(), any())` if no RecordSchema is passed and extends is even _"coherent"_ with Typescript type because a _TypeX_ **extends** _baseTObj_ if contains all the base props + enabling extras props to exist, and this is my "desired" behaviour of `type Passthrough<T extends object> = T & Record<string, any>`

**Comment by fabian-hiller** [comment]
Thanks for your further feedback. Since `extends` is used in TypeScript, not only for generics, but also for conditional types to check if a type matches or descends from another, the naming may not be perfect. For example, I had the idea of maybe using `extends` as a name for the [type guard](https://github.com/fabian-hiller/valibot/issues/11#issuecomment-1653648718) feature.

For `passthrough` it will be important to also investigate the other methods of Zod, such as `strict`, to then check what is the best overall approach for Valibot.

**Comment by fabian-hiller** [comment]
I added `passthrough` and `strip` in v0.14.0. Thank you for your contribution!
