### ISSUE TITLE
Partial object schema with only select keys

### ISSUE THREAD

**Issue by IlyaSemenov** [fabian-hiller/valibot#170]
As a developer migrating from zod, I would like to create a schema derived from an object schema with only certain (not all) keys marked as optional:

```ts
const schema = v.object({
  name: v.string(),
  age: v.number(),
})

const schema2 = v.partial(schema, { age: true }) // name is required, age isn't
```

This is exactly what zod allows: https://github.com/colinhacks/zod/#partial

**Comment by fabian-hiller** [comment]
You can use `optional`, `nullable` or `nullish`:

```ts
const schema = object({
  name: string(),
  age: optional(number()),
});
```

**Comment by IlyaSemenov** [comment]
No, that's not it. I realiase I can use `optional()` to build a schema with an optional key. The question was not about _building_ a schema, it's about **extending an existing schema**. This is what I deliberately demonstrated with `schema` and `schema2`.

The use case is reusing a common schema for different purposes without repeating the actual keys. For example, a developer may want to create a common model schema and then derive individual "create" and "update" schemas:

```ts
const baseSchema = v.object({
  name: v.string(),
  age: v.number(),
  ref: v.string(),
  is_blocked: v.boolean(),
})

const createSchema = v.partial(baseSchema, { is_blocked: true }) // is_blocked not required when creating a user

const updateSchema = v.partial(baseSchema, { ref: true }) // ref not required when updating a user
```

**Comment by fabian-hiller** [comment]
Yes that is possible. You will find more info in our docs: https://valibot.dev/guides/methods/#object-methods

**Comment by IlyaSemenov** [comment]
Thank you guys for providing the workaround. However, my point here (same in #171) is not resolving my immediate needs. I am listing use cases which I believe are generally needed and deserve first class support even though they can be achieved by composing the existing methods.

Since valibot uses tree shakeable composition (unlike zod which is a single file behemoth), I was thinking more helper methods covering specific reasonably popular scenarios couldn't hurt?

**Comment by fabian-hiller** [comment]
Can you provide sample Valibot code with the APIs you are looking for?

**Comment by lo1tuma** [comment]
I think something like this should work, I haven’t tested it though:


```ts
type SetOptional<TObjectShape extends ObjectShape, TKey extends keyof TObjectShape> = {
  [Key in Exclude<keyof TObjectShape, TKey>]: TObjectShape[Key];
} & {
  [Key in TKey]: OptionalSchema<TObjectShape[Key]>;
};

function setOptional<TObjectSchema extends ObjectSchema<ObjectShape>, TKey extends keyof TObjectSchema['object']>(
  schema: TObjectSchema,
    keys: TKey[]
): ObjectSchema<SetOptional<TObjectSchema['object'], TKey>> {
    const entries = Object.entries(schema.object);
    const newShape = Object.fromEntries(
        entries.map(([key, schema]) => {
          if ((keys as string[]).includes(key)) {
              return [key, optional(schema)];
          }
          return [key, schema];
      })
    ) as SetOptional<TObjectSchema['object'], TKey>

  return object(newShape);
}
```

**Comment by fabian-hiller** [comment]
Can you show the final API for the end user and explain what `setOptional` does? What is the difference to `partial`?

**Comment by lo1tuma** [comment]
While `partial` marks all properties to being optional, `setOptional` let you selectively choose which properties should be set optional. The naming was inspired by [`SetOptional` in type-fest](https://github.com/sindresorhus/type-fest).

The API usage would look like this

```
const base  = object({
    foo: string(),
    bar: number()
});
const baseWithOptionalBarProperty = setOptional(base, [ 'bar' ]); // { foo: string; bar?: number }
```

**Comment by fabian-hiller** [comment]
Thank you for the info. This should also work by combining `pick`, `partial`, `omit` and `merge`. Might be a bit more cumbersome though. It would probably be best if we optionally add the ability to `partial` to select individual keys.

**Comment by fabian-hiller** [comment]
This is now possible. Just specify the entries that should be required by there keys:

```ts
import * as v from 'valibot';

const Schema1 = v.object({
  name: v.string(),
  age: v.number(),
})

const Schema2 = v.partial(Schema1, ['age']);
```
