### ISSUE TITLE
nonEmpty validator

### ISSUE THREAD

**Issue by IlyaSemenov** [fabian-hiller/valibot#171]
As a developer migrating from zod, I am missing the [nonEmpty()](https://github.com/colinhacks/zod#nonempty) guard, which would work like:

```ts
const usernameSchema = v.string([v.toTrimmed(), v.nonEmpty()])
```

I realise I can achieve that with `minLength(1)`, and that I can write own plugin to reduce boilerplate. I actually did:

```ts
import { type ErrorMessage, minLength } from "valibot"

/**
 * Creates a validation functions that ensures a string or an array is not empty.
 *
 * @param error The error message.
 *
 * @returns A validation function.
 */
export function nonEmpty<TInput extends string | any[]>(error?: ErrorMessage) {
  return minLength<TInput>(1, error)
}
```

My question is, is that something you believe could be added to the valibot distribution? I can create a PR, just wanted to ask beforehand if that makes sense.

**Comment by fabian-hiller** [comment]
Currently I don't want to add it, as the same can be achieved with `minLength` and this is not really more cumbersome than `nonEmpty`. However, I can leave this issue open so that other people can give us feedback on this.

**Comment by fabian-hiller** [comment]
That's great. Feel free to add it on our [ecosystem page](https://valibot.dev/guides/ecosystem/) to the utilities.

**Comment by daku10** [comment]
Hello @fabian-hiller,

Firstly, thank you for your efforts in developing this great product.

I would like to discuss the potential for a **Type guard for NonEmptyArray**. I noticed that the [nonEmpty feature in zod](https://github.com/colinhacks/zod#nonempty) is capable of inferring a Type guard for NonEmptyArray, which I find quite useful in some scenarios.

To my understanding, a similar result can be achieved with the following TypeScript code:

```ts
type NonEmptyArray<T> = [T, ...T[]];

export function nonEmptyArray<TItem extends BaseSchema>(item: TItem) {
  return transform(array(item, [minLength(1)]), (value) => {
    return value as NonEmptyArray<Output<TItem>>;
  });
}
```

However, this implementation lacks flexibility, particularly in terms of configuring additional pipe functions. I believe integrating this functionality into the core features might address this issue.

What are your thoughts on this approach? Any feedback or suggestions would be greatly appreciated.

Thank you for your time and consideration.

**Comment by fabian-hiller** [comment]
I think that the same can be achieved with `tuple`. Here is a guide describing the differences to `array`: https://valibot.dev/guides/arrays/

**Comment by fabian-hiller** [comment]
Also I plan to add a `required` or `nonEmpty` validation action. I will investigate this in the next fee weeks.

**Comment by daku10** [comment]
Oh, I missed the `tuple` function.
Your suggestion is very helpful.
Thank you for your quick and kind reply!

**Comment by fabian-hiller** [comment]
`empty` and `nonEmpty` are available in the latest version.
