### ISSUE TITLE
`fallback` returns the defined object, it should probably return a copy

### ISSUE THREAD

**Issue by naturalethic** [fabian-hiller/valibot#173]
Particularly for objects, or arrays, I may want to take control of and use the fallback object.  Mutating the defined fallback object is likely undesired in all cases.

**Comment by fabian-hiller** [comment]
As a library, I don't think it's a good idea to clone the passed object by default. Instead, the user should clone the object:

```ts
const object = { … };

// Clone it statically
const Schema1 = fallback(object({ … }), { ...object });

// Clone it dynamically
const Schema2 = fallback(object({ … }), () => ({ ...object }));
```

In case you disagree. I am happy to receive more details.

**Comment by naturalethic** [comment]
No, you are correct.  Your design is optimal.  I had not noticed the dynamic pattern, which is sufficient.  Thanks for the reply!
