### ISSUE TITLE
Include fallback value in `fallback()` return

### ISSUE THREAD

**Issue by brandonpittman** [fabian-hiller/valibot#174]
https://github.com/fabian-hiller/valibot/blob/f3679064037eae9bd31c97d32aa78517d12b76d9/library/src/methods/fallback/fallback.ts#L15-L37

Similar to how `optional()` returns a `default` key, I'd like to be able to access `fallback()`'s fallback value before parsing because I'd like to supply the fallback value as an initial value to a CLI prompt. Would you be okay if I created a PR to add this?

**Comment by brandonpittman** [comment]
`fallback`'s second arg can be a function that takes input to `_parse` but we can't access that if we just add it to the schema return value. Can we ignore the args to fallback when returning the fallback in the schema return?

Something like:

```ts
export function fallback<TSchema extends BaseSchema>(
  schema: TSchema,
  value:
    | Output<TSchema>
    | ((info: FallbackInfo) => Output<TSchema>)
    | (() => Output<TSchema>)
): TSchema {
  return {
    ...schema,
    ...(value
      ? {
          fallback:
            typeof value === 'function'
              ? (value as () => Output<TSchema>)()
              : value,
        }
      : {}),
```

**Comment by fabian-hiller** [comment]
It may be better to make the arg optional. Feel free to implement it that way. I cannot currently judge how this will work in practice.

```ts
type ValueArg = Output<TSchema> | ((info?: FallbackInfo) => Output<TSchema>)
```

**Comment by brandonpittman** [comment]
Got an error when I just added the `?`.

```
src/methods/fallback/fallback.ts(19,45): error TS2349: This expression is not callable.
  Not all constituents of type '((info?: FallbackInfo | undefined) => Output<TSchema>) | (Output<TSchema> & Function)' are callable.
    Type 'Output<TSchema> & Function' has no call signatures.
```

**Comment by fabian-hiller** [comment]
I believe this is implemented. So I close this issue.
