### ISSUE TITLE
can't use declared symbol to brand types

### ISSUE THREAD

**Issue by samualtnorman** [fabian-hiller/valibot#176]
A trick you can do in zod is
```js
const Dog = z.object({ name: z.string() }).brand<{ readonly $: unique symbol }["$"]>()
```
to guarantee  that you won't have any name clashes.

When migrating from zod to valibot this code can't be easily ported over.

**Comment by fabian-hiller** [comment]
We already habe a `brand` function: 

```ts
const Dog = brand(object({ … }), 'Dog');
```

**Comment by samualtnorman** [comment]
I'm aware valibot has a brand function, that's not what this issue is about

**Comment by fabian-hiller** [comment]
Does this issue refer to the second argument of our `brand` function? Is it about preventing the same string from being used twice?

**Comment by samualtnorman** [comment]
uh yes sort of, although this issue isn't really about strings, it's about declared unique symbols

**Comment by fabian-hiller** [comment]
I think that this could work with `Symbol`:

```ts
const Dog = brand(object({ … }), Symbol('Dog'));
```

If I have misunderstood you, please let me know and send me more details.

**Comment by samualtnorman** [comment]
using a real symbol over a declared symbol could work but now there is an unused symbol value at runtime

**Comment by fabian-hiller** [comment]
That is correct. As far as I know, it is not currently possible to implement it using a generic like Zod. But feel free to examine the code and check again. Otherwise, it should not be too tragic to have an unused symbol at runtime.

**Comment by fabian-hiller** [comment]
I am closing this issue, but may reopen it if there is still interest in discussing it.

**Comment by samualtnorman** [comment]
> That is correct. As far as I know, it is not currently possible to implement it using a generic like Zod. But feel free to examine the code and check again. Otherwise, it should not be too tragic to have an unused symbol at runtime.

It turns out it *is* possible but it's a bit awkard. To get proper type inference, `brand()` has to be a function that returns a function.

```ts
declare const BrandTag: unique symbol

declare function brand<TBrand extends string | symbol>(): <TInput>() =>
	v.TransformAction<TInput, TInput & { [BrandTag]: TBrand }>

const Cuid2Schema = v.pipe(v.string(), v.length(23), v.cuid2(), brand<{ readonly $: unique symbol }["$"]>()())
```

Do you reckon something that implements a type signature like this could be implemented into the valibot library?

Thanks.
