### ISSUE TITLE
Value from the Output of a Schema

### ISSUE THREAD

**Issue by KlausEverWalkingDev** [fabian-hiller/valibot#189]
Hello, Fabian. I'm kinda new to JSON validation but I can say you're doing an excellent job for creating a so concise yet powerful tool for that. That being said, I'm having a hard time to reproduce something similar to typebox's Value.Create(Schema). I've got something similar messing aroung with getOutput, but probably I'm missing some logic. Could you help me? Cheers.

**Comment by fabian-hiller** [comment]
Thank you very much! I plan to add this functionality to our `getDefault` method. Unfortunately, currently it can only be used with a `optional`, `nullable` and `nullish` schema. I haven't thought about the implementation yet. `union` and soon `intersection` could be a problem here, as it is unclear how the default values should be used then.

```ts
const Schema = optional(string(), 'default_value');
const default = getDefault(Schema); // 'default_value'
```

**Comment by KlausEverWalkingDev** [comment]
My use case is using that to use schema to validate on types and to create constants of string in a "as const" fashion. So I think having it on literals and strings would be a great start :D

**Comment by fabian-hiller** [comment]
I don't think I quite follow you. Can you provide a code example?

**Comment by KlausEverWalkingDev** [comment]
For example: I have constant values for Resource like this:
``` typescript
export const Resource = {
  name: 'example1',
  title: 'Example 1',
  url: 'example-1'
} as const
```
so I can use when needed with the format `Resource.title` (I prefer this than enums or classes with `readonly static` properties). It is easy to turn it into a type (using typeof Resource). Using a schema, these would be declared with v.literal(), right? Other use case is similar to that but with objects inside that object:
``` typescript
export const Resource = {
  0: {
    name: 'example1',
    title: 'Example 1',
    url: 'example-1'
  },
  1: {
    name: 'example2',
    title: 'Example 2',
    url: 'example-2'
  },
} as const
```
where I can extract types using
``` typescript
const resources = Object.values(Resource)
export type Resource = (typeof resources)[number]
```
I feel like I didn't explain better yet, but I can give further information once you read the text above ^_^'

**Comment by fabian-hiller** [comment]
How exactly do you plan to use Valibot for this? Validation of the data does not seem necessary in this use case.

**Comment by KlausEverWalkingDev** [comment]
Types and constants generated only with schemas. And I think I found a way to do that, but with superstruct. I didn't try with Valibot yet. (Yes, I'm crazy LOL).

**Comment by KlausEverWalkingDev** [comment]
There it is, done with Valibot too:
![image](https://github.com/fabian-hiller/valibot/assets/3390598/1a37dbbc-24e3-4ec9-8af8-62325cd7c76a)

**Comment by fabian-hiller** [comment]
Maybe it makes sense to replace the outer `v.object` with `v.tuple`. This way you can write `BS.tuple.map(…)` instead of `Object.values(BS.object).map(…)`.

**Comment by fabian-hiller** [comment]
I am closing this topic, but may reopen it if there is still interest in discussing it.
