### ISSUE TITLE
Type of schema with transform remains unchanged

### ISSUE THREAD

**Issue by xinha-sh** [fabian-hiller/valibot#190]
``With Valibot:``
<img width="898" alt="Screenshot 2023-09-30 at 7 25 10 PM" src="https://github.com/fabian-hiller/valibot/assets/107257599/17f9bfe1-7fd1-4de7-ab7e-4561e11fbdb9">

``With Zod:``
<img width="898" alt="Screenshot 2023-09-30 at 7 23 46 PM" src="https://github.com/fabian-hiller/valibot/assets/107257599/d16d09bd-4098-48c8-8748-55a226c3e798">

How to achieve functionality of ``zod`` in ``valibot`` ?

**Comment by fabian-hiller** [comment]
Just replace `Input` with `Output`:

```ts
type xyz = Output<typeof custom>;
```

**Comment by fabian-hiller** [comment]
More details here: https://valibot.dev/guides/infer-types/

**Comment by xinha-sh** [comment]
@fabian-hiller Is there a discord server for Valibot. Trying to switch from zod, have few questions to ask.
1. In zod if I had an object schema ``selectStoreSchema``
```ts
z.array(selectStoreSchema.keyof())
  .default(["id", "slug", "logo", "name"])
  .optional()
```
What's the valibot equivalent ?

**Comment by fabian-hiller** [comment]
For now, just use the issues or discussions in the GitHub repository for questions.

I think that this is what you are looking for:

```ts
const ArraySchema = optional(array(keyof(StoreSchema)), ["id", "slug", "..."]);
```
