### ISSUE TITLE
Question: what is the difference between `value` and `equal` validators 

### ISSUE THREAD

**Issue by lo1tuma** [fabian-hiller/valibot#192]
I’ve just looked at the code and it seems like they are almost identical.

**Comment by fabian-hiller** [comment]
Yes, you are right. In the beginning there was only `equal`. Then later we renamed `minRange` and `maxRange` to `minValue` and `maxValue` and added `value` in the same move so that the approach to the length, byte and size validation functions is consistent. We should probably deprecate `equal`.

**Comment by fabian-hiller** [comment]
Fixed in v0.19.0
