### ISSUE TITLE
Export common type for BaseSchema and BaseSchemaAsync

### ISSUE THREAD

**Issue by IlyaSemenov** [fabian-hiller/valibot#198]
As a developer creating integrations with valibot (not using valibot directly, but creating library solutions for other developers on top of valibot), I am missing an option to accept abstract valibot schema, either sync or async. Currently, I have to use `v.BaseSchema<Input, Output> | v.BaseSchemaAsync<Input, Output>` boilerplate.

Example (simplified) code:

```ts
import * as v from "valibot"

/**
 * Vue composable: validate input and submit if it's valid.
 * Simplified for brevity.
 */
export function useForm<Input, ValidInput = Input>(options: {
  fields: Input
  schema: v.BaseSchema<Input, ValidInput> | v.BaseSchemaAsync<Input, ValidInput>
  submit: (data: ValidInput) => void | PromiseLike<void>
}) {
  const { schema, fields } = options

  return async function submit() {
    const res = await v.safeParseAsync(schema, fields)
    if (res.success) {
      await options.submit(res.output)
    }
  }
}
```

I propose to export a new common type (such as `BaseSchemaMaybeAsync`), so that in the code above it'd possible to write:

```ts
schema: v.BaseSchemaMaybeAsync<Input, ValidInput>
```

**Comment by fabian-hiller** [comment]
Thanks for your feedback on this. I'm not sure yet if I want to add such a type to the library. I think the explicit assignment is better in most cases. As a workaround for now you can create this type yourself.

```ts
type BaseSchemaMaybeAsync<Input, ValidInput> =
  | v.BaseSchema<Input, ValidInput>
  | v.BaseSchemaAsync<Input, ValidInput>;
```

**Comment by IlyaSemenov** [comment]
Thank you for the response. Of course I understand that I can create types and other extensions on my own, especially as trivial as this one. 

If you don't think the use case is relevant (even though I provided an example) and/or that is an anti-pattern, I suppose this issue should be just closed as not planned. I'm inclined to publish some kind of `valibotx` anyway, which will re-export everything from valibot along with the unobtrusive extensions that you don't want (e.g. #171). :)

**Comment by fabian-hiller** [comment]
My spontaneous feedback is that I prefer an explicit assignment. This is also the approach I currently use in the Valibot source code. However, I understand your approach and depending on the context, it may be better.

I'm open to new ideas, and even if I don't directly agree with a change or extension, I leave it open to change my mind if I get feedback from more people. So I will leave the labels as they are for now and maybe change them in a few months.

Feel free to create a package like `valibotx` that extends the functionality of Valibot. Maybe in the long run I will take some ideas and implement them directly into Valibot.

**Comment by fabian-hiller** [comment]
At the moment I still prefer an explicit declaration. Therefore I close this issue. I am still open to discussion and may change my mind in the future.
