### ISSUE TITLE
nothing seems to be exported

### ISSUE THREAD

**Issue by tigawanna** [fabian-hiller/valibot#2]
![image](https://github.com/fabian-hiller/valibot/assets/72096712/d1c911e8-9b14-4782-834d-b58a53c0ce90)
![image](https://github.com/fabian-hiller/valibot/assets/72096712/587694e2-d05f-4ba8-b2ac-ebca788af768)

**Comment by fabian-hiller** [comment]
Please double check again and also look in the `node_modules` directory. Everything seems to work for me and the exports are included in the source code.

**Comment by tigawanna** [comment]
Works in a vite project,but doesn't in a node project

**Comment by userquin** [comment]
https://publint.dev/valibot@0.2.0

**Comment by tigawanna** [comment]
i think i found the issue onmy part , tsconfig  only  ` "moduleResolution": "Node", `  and  `"moduleResolution": "Bundler",`    seem to work
