### ISSUE TITLE
docs: the API reference is almost empty

### ISSUE THREAD

**Issue by kazizi55** [fabian-hiller/valibot#209]
Hi @fabian-hiller ,
if it’s not too much trouble for you, I'm willing to write the API reference together! 😄 
How can I help you?
What's your plan to complete the API reference?

**Comment by fabian-hiller** [comment]
Thank you for creating this issue! Yes, I would appreciate support. If I manage to get a sponsor, I plan to give a part of it to people who support me with the docs.

My current plan is to create the first 1 to 3 API references myself and then get feedback from the community. Once we decide on a consistent format, this can be used as a template to write all further references.

Presumably the API references will be a mix of the docs of [Zod](https://zod.dev/) and the API references of [Modular Forms](https://modularforms.dev/).

**Comment by fabian-hiller** [comment]
Great! Feel free to create a first draft of the `string` API reference (e.g. as a draft PR) and share your ideas there. We can also work together on this. The goal is to have a world-class API reference by the time we reach v1.

**Comment by kazizi55** [comment]
@fabian-hiller 
OK! I'm gonna create the draft of `string` API in the coming days!

**Comment by danielo515** [comment]
So, just to be clear, there are no docs currently for the API ? The link to the API reference points to Any, which is confusing, will be better to have a specific message

**Comment by fabian-hiller** [comment]
@danielo515 on the left (or bottom on mobile) on our website you can navigate to the different APIs and use the link to the source code on GitHub for now. The code is simple and well documented. Otherwise you can also use [TypeBox-Workbench](https://sinclairzx81.github.io/typebox-workbench/) to convert a TypeScript type to Valibot.

We start working on the API reference on our website shortly.

**Comment by danielo515** [comment]
Sure, that's totally fair, but why link the api docs reference to any ?
Wouldn't it be better to not linkt them at all and just add a note about
the current state?

**Comment by fabian-hiller** [comment]
`any` is just the first page (the first API) of our API reference.

**Comment by fabian-hiller** [comment]
@kazizi55 have you started a first draft? If not, I might start working on a draft this weekend. For a faster exchange, feel free to connect with me on Discord (fabianhiller).

**Comment by kazizi55** [comment]
@fabian-hiller 
Sorry for my late reply and a first draft 🙇 

> have you started a first draft?

Yes, I've started a first draft, and maybe will finish making a draft this weekend!

> For a faster exchange, feel free to connect with me on Discord (fabianhiller).

Thanks! I'll connect!

**Comment by wout-junius** [comment]
I am willing to help with the docs as well since I am missing them a lot xD
I'll wait till @kazizi55 PR gets trough to see an example and then I might be able to continue as well ;)

**Comment by fabian-hiller** [comment]
Thank you @wout-junius! That's means a lot to me. Yes, once the first draft is ready it can be used as an template to add all the other references.

**Comment by fabian-hiller** [comment]
I created #287 to coordinate the expansion of our API reference.
