### ISSUE TITLE
`passthrough` type is incomplete

### ISSUE THREAD

**Issue by qcho** [fabian-hiller/valibot#210]
Hi,

I'm trying to use `passthrough` in order to allow an object with some extra keys that are not previously known. The idea is that i know it has a "hash" string. I also know it has several fields that i need to validate against that hash.

```ts
const LoginInputSchema = passthrough(object({
  hash: string(),
}))

type LoginInput = Output<typeof LoginInputSchema>

const payload = parse(LoginInputSchema, { hash: 'xxx', field_1: 'a', field_2: 'b'})
payload['field_1'] // Typescript error

// Real usage
const payloadCheck = []
for (const key of Object.keys(payload).sort()) {
  payloadCheck.push(`${key}=${payload[key]}`)
}
```

I can't access the extra parameters without a typescript error.

It seems the Output type of `LoginInput` should include some sort of `Record<string, unknown>` in order to acomodate for the unknown passedthrough fields. For example:

```ts
Bad: type LoginInput = {
    hash: string;
}

Good: type LoginInput = {
    hash: string;
} & Record<string | number | symbol, unknown>
```

**Comment by fabian-hiller** [comment]
Do you know how Zod types this? As a workaround you can do the following:

```ts
const Schema = intersection([object({ hash: string() }), record(unknown())]);
```

**Comment by fabian-hiller** [comment]
Does the problem still exist or have you found a suitable solution?

**Comment by qcho** [comment]
Hello @fabian-hiller thanks for the feedback!

I've worked-arounded the type issue within my code.

For this report i've created this https://stackblitz.com/edit/typescript-q8ggsi?file=index.ts example. You may play with the example and see the outcomes there with ease.

```ts
const ZodDefaultSchema = z.object({ hash: z.string() });
type ZodDefaultSchemaType = z.output<typeof ZodDefaultSchema>;
const ZodPassthroughSchema = ZodDefaultSchema.passthrough();
type ZodPassthroughSchemaType = z.output<typeof ZodPassthroughSchema>;

const ValiDefaultSchema = object({ hash: string() });
type ValiDefaultSchemaType = Output<typeof ValiDefaultSchema>;
const ValiPassthroughSchema = passthrough(ValiDefaultSchema)
type ValiPassthroughSchemaType = Output<typeof ValiPassthroughSchema>;

const ValiWorkaroundSchema = intersection([ValiDefaultSchema, record(unknown())]);
type ValiWorkaroundSchemaType = Output<typeof ValiWorkaroundSchema>;
```

The results:
* Zod `v3.22.4` passthrough works as expected:
```ts
type ZodPassthroughSchemaType = {
    hash?: string;
} & {
    [k: string]: unknown;
}
```
* Valibot `v0.19.0` passthrough doesn't
```ts
type ValiPassthroughSchemaType = {
    hash?: string;
}
```
* Proposed workaround does work as intended
```ts
type ValiWorkaroundSchemaType = {
    hash?: string;
} & {
    [x: string]: unknown;
}
```

Hope this make this stuff clearer. Maybe just execute the workaround internally ^_^

**Comment by fabian-hiller** [comment]
Yes, thank you. I will have a look at `passthrough` and improve the types.

**Comment by fabian-hiller** [comment]
Thank you for the hint! This issue will be fixed in the next version.

**Comment by fabian-hiller** [comment]
I have added an optional `rest` argument to the `object` schema. Starting with the next version that will be published in the coming days, I recommend using `object({…}, unknown())` instead of `passthrough(object({…}))`. This way the procedure is now consistent with `tuple`. Thank you again for your feedback!
