### ISSUE TITLE
Export PartialSchema

### ISSUE THREAD

**Issue by marek-hanzal** [fabian-hiller/valibot#217]
Hello,

I'm forced to export schema on type-level (because of generics). You have a lot of types already exported (like `NullishSchema`, ...), but one I'm missing is `Partial$2` hidden in the library.

Would it be please possible to export it too?

Thank you!

Just usecase (WIP, you don't see `any`s)
![image](https://github.com/fabian-hiller/valibot/assets/13855126/3864b02d-2bee-45c5-abbd-4b7f6f30a5d1)

I want to provide only Shape and Query, when Shape for update should be Partial (so here I'm asking for the missing type).

**Comment by fabian-hiller** [comment]
Thank you for crating this issue. I will have a look at it.

**Comment by fabian-hiller** [comment]
Starting from the next version on, I will export it as `PartialObjectEntries`.

**Comment by marek-hanzal** [comment]
Olala, that was quick. Thank you!

**Comment by fabian-hiller** [comment]
v0.20.0 is now available
