### ISSUE TITLE
Zod-valibot 1:1 transformation - Type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by marek-hanzal** [fabian-hiller/valibot#221]
Hello, once again me.

I'm moving current Zod source code to valibot, everything at a first glance is cool, but I've a few quite ugly schemas (based on generics), which doesn't like valibot.

This piece was OK on Zod without any changes; moved to valibot, I've got this error (not only here, but over the repository on various places, mainly related to usage of `ObjectSchema`).
![image](https://github.com/fabian-hiller/valibot/assets/13855126/be5039f6-df0d-4f6a-b370-be1dc6ee1133)

Source of schema - there it's based on quite heavy type inference, because it's not simply possible to reconstruct schema on a type level, thus I've to use `ReturnType` which I don't really like.
https://github.com/use-pico/pico/blob/next/packages/source/src/schema/MutationSchema.ts

Here is the place of usage (just this one for a reference)
https://github.com/use-pico/pico/blob/next/packages/job/src/schema/JobMutationSchema.ts

I understand that my source code may not be optimal, but I don't know, how to build this kind of stuff in a better way (because I've generic shape to build up a final schema).

Not sure, if this is directly problem of valibot, but I suppose there could be something hidden as this was running OK on Zod (with zillions of it's internal types).

Thank you!

**Comment by fabian-hiller** [comment]
Can you reduce the problem to a minimum of code? This will make it easier for me to investigate the problem. We have a similar problem with `merge` in #24. There it seems to be a problem on the TypeScript side.

**Comment by marek-hanzal** [comment]
I understand this could be a bit piece of code, but it's real code I'm running, already "quite minimalistic" - the complex part is using generics + factory to create a schema dynamically. Probably worst part is when I put `partial` over shape shema, in that case it fails even earlier :(.

And yes, I saw similar issue on TS side, but they won't make this configurable, the limit is hardcoded.

**Comment by fabian-hiller** [comment]
Do you see any possibility to solve the problem by modifying the source code of Valibot?

**Comment by marek-hanzal** [comment]
I think it may be possible as type inference is quite a deep, mainly related to `ObjectSchema` and when converting `ObjectSchema` to partial. Bud I feel this could be quite a complicated task. Maybe my usecase is a bit on the edge, so it's not necessary to think about it, I'm currently only comparing my experience with Zod (which was able to handle this case) and valibot (which sadly not).

I'm currently doing some experiment with types based on your source, so I'll see, if I can find "bottleneck".

**Comment by fabian-hiller** [comment]
Ok. Feel free to create an issue for any problem you encounter using Valibot. It helps to shape the library in the long run.

**Comment by fabian-hiller** [comment]
I am closing this topic, but may reopen it if there is still interest in discussing it.
