### ISSUE TITLE
(Maybe) too complicated typing without desired result

### ISSUE THREAD

**Issue by marek-hanzal** [fabian-hiller/valibot#222]
Hello, I'm still digging through the code and I've found something interesting, but not sure, if it is not my sleep deficit.

When you're using `object` (schema), an input is strictly defined (no optional properties) by this:
https://github.com/fabian-hiller/valibot/blob/main/library/src/schemas/object/object.ts#L13

So when you're doing magick to remap object types for input/output (here):
https://github.com/fabian-hiller/valibot/blob/main/library/src/schemas/object/types.ts#L72

`TObjectEntries` on input never have question marks, this all the things (type check, Picks and so on) 'round are not necessary as they not only have no effect, but could even break down final typings (losing type information).

I'm searching for solution, something based on `TOutput` in general, checking if it could be undefined and generating resulting type with `keyof...?:` or `keyof...:` to preserve `optionality`.

Or maybe you find out I'm already totally out :).

Thank you!

**Comment by fabian-hiller** [comment]
I still do not fully understand the problem. Feel free to give a concrete code example. With `optional` you can mark items as optional with a question mark.

**Comment by fabian-hiller** [comment]
I am closing this topic, but may reopen it if there is still interest in discussing it.
