### ISSUE TITLE
How to feed Object.keys to the enumtype validator?

### ISSUE THREAD

**Issue by danielo515** [fabian-hiller/valibot#224]
Let's start with the code, I think it's simpler:
```ts
export const openPositions = {
	left: 'Left',
	right: 'Right',
	mainView: 'Main View',
	// modal: 'Modal',
} as const;

const OpenPositionSchema = enumType(Object.keys(openPositions));
```

The problem here is that, Object.keys type is `string[]` while enumType expects what I assume is a guaranteed non empty array. I have to admit that the `[string, ...string[]]` trick is neat to enforce this requirement, but then I will need some constructor of such type of array.
Some libraries have one, so I'm wondering if valibot provides such a thing?

In this case, the amount of keys is small, I can just duplicate it, but I guess this may be a bigger problem for other similar but longer scenarios

**Comment by fabian-hiller** [comment]
In your case the `nativeEnum` schema is the right choices:

```ts
export const openPositions = {
  left: 'Left',
  right: 'Right',
  mainView: 'Main View',
  modal: 'Modal',
} as const;

const OpenPositionSchema = nativeEnum(openPositions);
```

**Comment by fabian-hiller** [comment]
You can also use it with `enum` in TypeScript:

```ts
export enum OpenPositions {
  left = 'Left',
  right = 'Right',
  mainView = 'Main View',
  modal = 'Modal',
}

const OpenPositionSchema = nativeEnum(OpenPositions);
```

**Comment by fabian-hiller** [comment]
However, my previous examples validate against the values and not the keys. Here is another alternative:

```ts
const ObjectSchema = object({
  left: literal('Left'),
  right: literal('Right'),
  mainView: literal('Main View'),
  modal: literal('Modal'),
});

const KeyofSchema = keyof(ObjectSchema);
```

**Comment by danielo515** [comment]
I need to validate on the keys.
The object mapping is just to provide a human readable text in the UI, so
building a schema for it is not going to help either.
Isn't any other workaround?

**Comment by fabian-hiller** [comment]
The main problem is that `Object.keys()` does not type the output correctly. It should be `['left', 'right', 'mainView']` instead of `string[]`. The best workaround for now is to assign the correct type yourself:

```ts
export const openPositions = {
  left: 'Left',
  right: 'Right',
  mainView: 'Main View',
} as const;

const OpenPositionSchema = enumType(
  Object.keys(openPositions) as ['left', 'right', 'mainView']
);
```

Nevertheless, I will have another look at the problem and see if Valibot can do something better.

**Comment by danielo515** [comment]
If I'm going to repeat myself, I think I prefer my slightly safer version:
```ts
const OpenPositionSchema = enumType(['left', 'right', 'mainView']);

export type OpenPosition = Output<typeof OpenPositionSchema>;

export const openPositions: Record<OpenPosition, string> = {
    left: 'Left',
    right: 'Right',
    mainView: 'Main View',
} as const;
```
At least that way I make sure they are properly in sync with the type system

**Comment by fabian-hiller** [comment]
As of v0.23.0, it should be possible to pass an array to `picklist` (aka `enumType`).
