### ISSUE TITLE
Is there a way to access the underlying schema rules?

### ISSUE THREAD

**Issue by YassienW** [fabian-hiller/valibot#225]
I've recently been considering switching to this library for our app's validation. In certain parts of the UI there is a need to display the input rules for the user (i.e: the maximum allowed text length in an input field). Is there a way to access rules (i.e: max length, min length) of a schema after creating it?

**Comment by fabian-hiller** [comment]
We are working on that in #211

**Comment by YassienW** [comment]
Perfect. You have created one of the best validation libraries out there, with this feature added i would put it on top of the list. Thank you!

**Comment by fabian-hiller** [comment]
I will try to ship this feature next weekend

**Comment by fabian-hiller** [comment]
This should now be possible due our new [reflection API](https://github.com/fabian-hiller/valibot/pull/211).
