### ISSUE TITLE
Default value makes optional, nullish, nullable as required

### ISSUE THREAD

**Issue by jozefini** [fabian-hiller/valibot#226]
As soon as i add a default value to `optional`, `nullish`, `nullable`,
these all become required.

To reproduce the error:

No default value, everything works as expected:
```
const schema = object({
  key: string([minLength(1), toTrimmed()]),
  type: optional(string()),
  reserved: optional(boolean()),
})
type SchemaTypes = Output<typeof schema>
```

With default value, now `type` and `reserved` are required:
```
const schema = object({
  key: string([minLength(1), toTrimmed()]),
  type: optional(string(), ''),
  reserved: optional(boolean(), false),
})
type SchemaTypes = Output<typeof schema>
```

**Comment by fabian-hiller** [comment]
Here you have to distinguish between input and output. As you noticed, the output type can no longer be `undefined` when using a default value. Therefore the output type can only be `string`. But it is different for the input. There `type` and `reserved` are still optional:

```ts
// Create schema
const Schema = object({
  key: string([minLength(1), toTrimmed()]),
  type: optional(string(), ''),
  reserved: optional(boolean(), false),
})

// Get input type
type SchemaInput = Input<typeof schema>;

// Get output type
type SchemaOutput = Output<typeof schema>;
```

You can find more info here: https://valibot.dev/guides/infer-types/

**Comment by jozefini** [comment]
Thanks for the explanation, it totally makes sense now
