### ISSUE TITLE
How can I generate dynamic object schema by schema.object type

### ISSUE THREAD

**Issue by kristian-marku** [fabian-hiller/valibot#230]
Hello, I'm trying to understand how I can validate these types with generics. I have these types, and I would like to be able to validate them with Valibot. How can I create a function that returns the correct schema? I've tried different libraries, but I haven't been able to find the right one yet. Maybe I'm doing something wrong.

```ts
export type LessThanOp = { $lt: number }
export type LessThenOrEqualOp = { $lte: number }
export type MoreThanOp = { $mt: number }
export type MoreThenOrEqualOp = { $mte: number }
export type EqualOp = { $eq: string }
export type LikeOp = { $like: string }
export type BetweenOp = { $btw: [number, number] }
export type InOp = { $in: string[] }
export type IsNullOp = { $null: null }
export type NotOp = { $not: Operator | string }
export type Operator = NotOp | LessThanOp | LessThenOrEqualOp | MoreThanOp | MoreThenOrEqualOp | EqualOp | LikeOp | BetweenOp | InOp | IsNullOp


export type QueryWhereValue<Entity> = Entity | Operator
export type QueryWhereAnd<Entity> = { [Key in keyof Entity]?: Entity[Key] extends object ? QueryWhere<Entity[Key]> : QueryWhereValue<Entity[Key]> }
export type QueryWhereOr<Entity> = QueryWhereAnd<Entity>[]
export type QueryWhere<Entity> = QueryWhereOr<Entity> | QueryWhereAnd<Entity>

export const genQueryWhereValueSchema = <E extends EntityBase, S extends BaseSchema<E>>(schema: S) => intersection([schema, operatorSchema]);
export const genQueryWhereAndSchema = <E extends EntityBase, S extends ObjectSchema<any, E>>(schema: S) => object(
mapValues(schema.object,value=> ??????)  //Lodash fun
)
```

I always have this type of situations.
Thanks

**Comment by fabian-hiller** [comment]
Can you break it down a bit more and provide more info? To help you, it helps me to see the final usage (code example) instead of just the implementation.

**Comment by Kristian-Marku** [comment]
```
import { array, BaseSchema, date, intersection, merge, number, object, ObjectSchema, recursive, string, union } from 'valibot';
import { mapValues } from 'lodash';

// My case is mainly for the server side
// Let's pretend we have various endpoints to validate, e.g., /api/users/find and /api/invoices/find, and so on for each database table
// So, we would have an entity schema for each table

type BaseEntity = {
  id: number;
  createdAt: Date;
  updatedAt: Date;
}
export const baseEntitySchema = object({
  id: number(),
  createdAt: date(),
  updatedAt: date(),
}) satisfies BaseSchema<BaseEntity>;

type Users = BaseEntity & {
  name: string;
  surname: string;
  invoices: Invoices[];
}
const usersSchema = merge([
  baseEntitySchema,
  object({
    name: string(),
    surname: string(),
    invoices: recursive((): BaseSchema<Invoices[]> => array(invoicesSchema)),
  }),
]) satisfies BaseSchema<Users>;

type Invoices = BaseEntity & {
  number: string;
  price: number;
  user: Users;
}
export const invoicesSchema = merge([
  baseEntitySchema,
  object({
    number: string(),
    price: number(),
    user: recursive((): BaseSchema<Users> => usersSchema),
  }),
]) satisfies BaseSchema<Invoices>;

// We have operators that can be applied to each search field

type LessThanOp = { $lt: number }
export const lessThanOpSchema = object({ $lt: number() }) satisfies BaseSchema<LessThanOp>;

type LessThenOrEqualOp = { $lte: number }
const lessThenOrEqualOpSchema = object({ $lte: number() }) satisfies BaseSchema<LessThenOrEqualOp>;

type Operator = LessThanOp | LessThenOrEqualOp
const operatorSchema = intersection([lessThanOpSchema, lessThenOrEqualOpSchema]) satisfies BaseSchema<Operator>;

// Now, for each endpoint, we need to have a generic schema that we will validate based on the entity

type Where<E> = { [K in keyof E]?: E[K] extends object ? Where<E[K]> : Operator | E[K] }
const whereSchema = <S extends ObjectSchema<any>>(schema: S) => object(
  mapValues(schema.object, value => value), // Check if it's a Valibot Object or a Recursive Object? Use the whereSchema(value) function, otherwise use the union([value, operatorSchema])
);

type Select<E> = { [K in keyof E]?: E[K] extends object ? Select<E[K]> : boolean }
const selectSchema = <S extends ObjectSchema<any>>(schema: S) => object(
  mapValues(schema.object, value => value),// Check if it is a Valibot Object or a Recursive Object? If true, use the selectSchema(value); otherwise, use booleanSchema.
)

type Relations<E> = { [K in keyof E]?: E[K] extends object ? boolean : undefined }
const relationsSchema = <S extends ObjectSchema<any>>(schema: S) => object(
  mapValues(schema.object, value => value), // Check if it is a Valibot Object or a Recursive Object? If true, use booleanSchema; otherwise, use undefinedSchema.
)

type Find<E> = {
  where?: Where<E>,
  select?: Select<E>
  relations?: Relations<E>,
}
const findSchema = <S extends ObjectSchema<any>>(schema: S) => object({
  where: whereSchema(schema),
  select: selectSchema(schema),
  relations: relationsSchema(schema),
})

// By doing this, we can simply add the generic to get the right type for the request without having to rewrite the schema every time.

type FindUsers = Find<Users>;
const findUsersSchema = findSchema(usersSchema) satisfies BaseSchema<FindUsers>;

type FindInvoices = Find<Invoices>;
const findInvoicesSchema = findSchema(invoicesSchema) satisfies BaseSchema<FindInvoices>;

// Thanks
```

**Comment by fabian-hiller** [comment]
Can you try to break it down into a more simplified and generalized version? Try to write minimal code, regardless of the use case. On the one hand, it saves me time because I don't have to think my way into a specific use case, and on the other hand, my answer will be useful for other developers with other use cases. Then I need to know what is not working as expected. At the moment this seems to be more a TypeScript specific question than a Valibot one. Nevertheless, I am interested in a solution, as I can then weigh whether I should add an example to our documentation.

**Comment by Kristian-Marku** [comment]
> Can you try to break it down into a more simplified and generalized version? Try to write minimal code, regardless of the use case. On the one hand, it saves me time because I don't have to think my way into a specific use case, and on the other hand, my answer will be useful for other developers with other use cases. Then I need to know what is not working as expected. At the moment this seems to be more a TypeScript specific question than a Valibot one. Nevertheless, I am interested in a solution, as I can then weigh whether I should add an example to our documentation.

I'm not sure what you're asking but I'll try again
Something like this?
I didn't handle all the cases, I wrote quickly just to make you understand, but it would be nice if it also allowed the array mapping

```
function map<Schema extends ObjectSchema<any>, From extends BaseSchema, To extends BaseSchema, Recursive extends boolean>(schema: Schema, from: From, to: To, rec?: Recursive) {
  let s: any = object({});
  return Object.keys(schema.object).forEach((key) => {
    if (is(schema.object[key], from)) {
      if (rec) {
        s.object[key] = map(schema.object[key], from, to, rec);
      } else {
        s.object[key] = to;
      }
    } else {
      s.object[key] = schema.object[key];
    }
  });
  return s;
}

const test = object({
  name: string(),
  surname: date(),
  test: object({
    name: string(),
    date:date()
  }),
});

{
  map(test, string(), number(), true);
  const result = object({
    name: number(),
    surname: date(),
    test: object({
      name: number(),
    }),
  });
}

{
  map(test, date(), number(), false);
  const result = object({
    name: string(),
    surname: number(),
    test: object({
      name: string(),
      date:date()
    }),
  });
}
```

**Comment by fabian-hiller** [comment]
So far I understand that you want to create a function that takes a schema as an argument, which is presumably validated inside the function. You want to use generics and get type safety. Please correct me if I am wrong.

```ts
import { type BaseSchema, type Output, parse, object, string } from 'valibot';

// Create example function
function exampleFunction<TSchema extends BaseSchema>(
  schema: TSchema,
  input: unknown
): Output<TSchema> {
  return parse(schema, input);
}

// Create schema and input
const schema = object({ key: string() });
const input = { key: 'value' };

// Use example function
const output = exampleFunction(schema, input);
```

**Comment by fabian-hiller** [comment]
If you want to combine multiple object schemas, you can use `merge`. If you are interested in how `merge` works internally to adapt the functionality to your use case, you can find the source code here: https://github.com/fabian-hiller/valibot/tree/main/library/src/methods/merge

> Please note that Valibot is not yet in v1 and APIs like `schema.object` can change.

**Comment by Kristian-Marku** [comment]
I think I may have explained myself poorly. I would like to overide the values of the keys in an object schema to another type schema, if the value type match, for example, a BooleanSchema if the value is an ObjectSchema, or map it to something else.

For example, given the following input schema:

```javascript
const from = object({
  name: string(),
  obj: object({})
})
```

I want to perform a function like `mapStringSchemaToNumber()` to get the following output schema:

```javascript
const to = object({
  name: number(),
  obj: object({})
})
```

Or, alternatively, perform a function like `mapObjectSchemaToNumber()` to get:

```javascript
const to = object({
  name: string(),
  obj: number()
})
```

**Comment by fabian-hiller** [comment]
Is your goal to override a specific key in an object schema so that, for example, it contains a number schema instead of a string schema? If yes, that's exactly what `merge` does.

**Comment by Kristian-Marku** [comment]
> Is your goal to override a specific key in an object schema so that, for example, it contains a number schema instead of a string schema? If yes, that's exactly what `merge` does.

Not a specific key, because I don't know it, I would like to override each key with a specific type of schema as value, e.g., all StringSchemas inside the ObjectSchema

**Comment by fabian-hiller** [comment]
Ok, now I understand it. That should be possible. But it is not easy to make it type safe. I will try to provide you example code tomorrow.

**Comment by Kristian-Marku** [comment]
> Ok, now I understand it. That should be possible. But it is not easy to make it type safe. I will try to provide you example code tomorrow.

Thanks for the help.
It would be cool to have an Object method like map / mapValues / replace (You choose the name) with parameters from, to or replace condition also deep option. 
If we could have the method, it would be great. I don't know about others, but it would be very useful for me.
Thanks again

**Comment by fabian-hiller** [comment]
What is your use case? Why is method better than create the schema twice with the different types?

**Comment by Kristian-Marku** [comment]
Let's say I have 400 ObjectSchemas.
In each of these, I need to replace every ObjectSchema inside with a BooleanSchema.
Example:
```

const from = {
name: string(),
surname: string(),
address: {
street: string(),
city: string(),
country: string(),
};
const to = {
name: string(),
surname: string(),
address: boolean();
}

```
Now, let's consider a scenario where I need to replace all StringSchemas with a BooleanSchema with the possibility of deep replacement.
Example:
```

const from = {
name: string(),
surname: string(),
address: {
street: string(),
city: string(),
country: string(),
};
const to = {
name: boolean(),
surname: boolean(),
address: {
street: boolean(),
city: boolean(),
country: boolean(),
};
}

```
There are 1000 other possible ways, but this was just an example.
Now, if I had to do this manually, I would have to write 1200 almost identical schemas.
Furthermore, if I make changes to the base schema, I would have to go and modify every other schema, risking errors.

**Comment by fabian-hiller** [comment]
How did you proceed before using Valibot? Did other schema libraries support this functionality?

**Comment by Kristian-Marku** [comment]
In Zod, I had created something like this:

```typescript
type Overrided<T> = { [K in keyof T]?: T[K] extends object ? Overrided<T[K]> : boolean };
const overridedSchema = <TSchema extends ZodObject<any>>(schema: TSchema): Schema<Overrided<z.infer<TSchema>>> => object(
  mapValues<any, any>(schema.shape, (value) => value instanceof ZodObject ? overridedSchema(value) : boolean()),
);
```

Since I really like valibot's style, I would like to replace Zod in my future projects.

**Comment by fabian-hiller** [comment]
Thank you for the code example. The code for Valibot is pretty similarly. I have not tested the code. Maybe you need to make some adjustments. Also, one of the next versions will bring a breaking change, after which you will have to adjust the code slightly.

> 

```ts
type Overrided<T extends ObjectEntries> = {
  [K in keyof T]: T[K] extends ObjectSchema<any>
    ? ObjectSchema<Overrided<T[K]['object']['entries']>>
    : BooleanSchema;
};

const overridedSchema = <
  TSchema extends ObjectSchema<Record<string, BaseSchema | ObjectSchema<any>>>
>(
  schema: TSchema
): ObjectSchema<Overrided<TSchema['object']['entries']>> =>
  object(
    mapValues(schema.object.entries, (value) =>
      'schema' in value && value.schema === 'object'
        ? overridedSchema(value)
        : boolean()
    )
  );
```

**Comment by Kristian-Marku** [comment]
It still doesn't work as I would like. Recursive cases need to be handled as well. I haven't found a library that does this in a simple way yet. I'm still searching.
 I liked the way Valibot handles error messages. I will wait for future updates.
 I hope you consider similar situations and simplify everything. 
 Thank you anyway for the responses and assistance.

**Comment by fabian-hiller** [comment]
Thank you for your feedback. I would love to offer you a solution, especially since I think it's technically possible. Unfortunately, I have midterms this week and very little time. Maybe next week I'll be able to take a look at the code.

**Comment by fabian-hiller** [comment]
I will take another look at this issue in the next few weeks and then give you feedback.

**Comment by Kristian-Marku** [comment]
> I will take another look at this issue in the next few weeks and then give you feedback.

Thanks,
I will also recheck, given the changes in the package, and I will let you know in these days. For now, I have been using Zod to avoid issues, but I prefer Valibot, especially for handling error messages. I also recall an issue with unions that validated only one of the two. As soon as I have time, I'll write something more.
=)

**Comment by fabian-hiller** [comment]
Is this feature still requested? Otherwise, I will close this issue.

**Comment by ciriousjoker** [comment]
Hey @fabian-hiller, you closed this as completed, but I couldn't find a solution. Our use case is this:

Firestore has a concept of `Timestamp` & `FieldValue`. When writing data, you can write FieldValues, for example `serverTimestamp()` to set that field to the server's timestamp instead of `Timestamp.now()` on the local machine.

Therefore I'd like to assert that a type I want to write to Firestore is either "the type" or "the type, but every Timestamp can also be a FieldValue". The Firestore sdk has a type like `WithFieldValues<>` where every type can also be a fieldvalue.

**Comment by fabian-hiller** [comment]
Feel free to provide some example code. I would probably take a look at `union`, `custom` and maybe `instance`.
- https://valibot.dev/guides/unions/
- https://valibot.dev/api/union/
- https://valibot.dev/api/custom/
- https://valibot.dev/api/instance/

**Comment by ciriousjoker** [comment]
@fabian-hiller 
Here's some example code:

```ts
import { FieldValue } from "firebase-admin/firestore";
import { InferOutput, instance, object, union } from "valibot";
import { firestore } from "../firebase";

/**
 * A backoff set, intended to be done right after the last work set of an exercise.
 */
export type Test = InferOutput<typeof TestSchema>;
export const TestSchema = object({
  date: instance(Date),
  dateUnion: union([
    instance(Date),
    instance(FieldValue), // <-- this breaks, because FieldValue is only exported as a type
  ]),
});

async function demo() {
  const ref = firestore().collection("test").doc();

  // This works
  await ref.set({
    date: new Date(),
  });

  // This also works
  await ref.set({
    date: FieldValue.serverTimestamp(), // <-- this is not a Date, it's a FieldValue
  });

  // We'd like to do:
  const test: Test = {
    date: FieldValue.serverTimestamp(), // <-- doesn't compile
  };

  await ref.set(test);
}

```

**Possible semi-solutions:**
1. union with custom validator
2. Stop type checking the data right before writing it

**Issues:**
1. That means we always get back a union instead of a Date when reading stuff from Firestore, which adds unnecessary type checking
2. I guess... But it's really convenient to hook into the Firestore sdk right before writing the data. If we couldn't do that anymore we'd have to validate data before passing it to the `.set()` method

What I envisioned was something like this:
```ts
export const TestSchemaWithFieldValues = wrapWithFieldValues(TestSchema);
```

What way, during the data write-process, we could assert that the data being written matches `wrapWithFieldValues(autodetectedSchemaBasedOnDataLocation)`, which would also mean we don't pollute our exports with meaningless types.
However, I failed when trying to implement something like this :(

**Comment by ciriousjoker** [comment]
@fabian-hiller 
Idk, but we couldn't import FieldValue either way, there are different FieldValue classes for node/browser and importing their server/admin sdk isn't possible in the browser.

I guess I just wish something like this would exist:

```ts deepReplaceAllSchemas(instanceof(Timestamp), union([...]))
```

**Comment by ciriousjoker** [comment]
@fabian-hiller 
Not quite sure what you mean there.

Consider a structure like this:

> apps/web <-- runs on browser
> apps/server <-- runs on node
> libs/shared <-- can be imported from any env, typings go here

We want to import `libs/shared` from the browser as well to share typings, but we cannot do that if one of the typings requires a type (`Timestamp` in this case) that is imported from the `firebase-admin` sdk, since the browser only supports importing from `firebase` (without "-admin").

**Comment by fabian-hiller** [comment]
Thanks for your feedback! Would you recommend us to change or extend the Valibot API? If so, feel free to provide pseudocode showing how you would like to define a Valibot schema in such a case.

**Comment by ciriousjoker** [comment]
Something like this would be convenient and might cover a bunch of other really specific usecases like this as well:

```ts
/**
 * Calls wrapFn on every key of the schema to transform it into a new schema.
 * If you want to do this recursively, do it yourself.
 *
 * @param schema The schema to wrap
 * @param wrapFn A function that transforms the property schema
 */
function wrap<Schema extends BaseSchema, PropBefore extends BaseSchema, PropAfter extends BaseSchema>(
  schema: Schema,
  wrapFn: (propSchema: PropBefore) => PropAfter
): ??? {
  ???
}

// Example:
const SomeSchema = object({
  prop1: string(),
  prop2: object({
    prop3: string(),
  }),
});

// This would not be part of the library, but solves our usecase
function myWrapRecurse(propSchema) {
  if (propSchema.type !== "object") return;
  return union([wrap(propSchema, myWrapRecurse), boolean()]);
}

const SomeWrappedSchema = wrap(SomeSchema, myWrapRecurse);
```

Inferring the correct types might be tricky though :/

@fabian-hiller what do you think? Is this something that should be part of the library?

**Comment by fabian-hiller** [comment]
Does this type signature works?

```ts
import * as v from 'valibot';

function wrap<
  TInputSchema extends v.GenericSchema,
  TOutputSchema extends v.GenericSchema,
>(
  schema: TInputSchema,
  wrapFn: (inputSchema: TInputSchema) => TOutputSchema
): TOutputSchema {
  return wrapFn(schema);
}

const SomeSchema = v.object({
  prop1: v.string(),
  prop2: v.object({
    prop3: v.string(),
  }),
});

const SomeWrappedSchema = wrap(SomeSchema, (schema) => {
  return v.tuple([schema, v.boolean()]);
});
```

**Comment by ciriousjoker** [comment]
@fabian-hiller 
I don't think this works, because the result of wrapFn might be Tuple as in the example, but TOutputSchema needs to update its properties recursively.

I really struggle to write something that iterates over the properties and the different schema variants (record, array, tuple, object, ...). Especially the typescript type inference seems really difficult.

Here's some sample code that hopefully illustrates what I'm trying to do:

<details><summary>Sample code</summary>

```ts
type Some = InferOutput<typeof SomeSchema>;
const SomeSchema = object({
  prop1: string(),
  prop2: object({
    prop3: string(),
  }),
  prop4: array(string()),
  prop5: tuple([string(), string()]),
  prop6: record(string(), object({ prop7: number() })),
});

const someSchemaData: Some = {
  prop1: "Hello World",
  prop2: {
    prop3: "Nested String",
  },
  prop4: ["Item1", "Item2", "Item3"],
  prop5: ["First", "Second"],
  prop6: {
    key1: { prop7: 42 },
    key2: { prop7: 100 },
  },
};

type SomeWrapped = InferOutput<typeof SomeWrappedSchema>;
const SomeWrappedSchema = wrap(SomeSchema, (schema) => {
  return tuple([schema, boolean()]);
});
const someWrappedSchemaData: SomeWrapped = [
  {
    prop1: ["Hello World", true],
    prop2: [
      {
        prop3: ["Nested String", false],
      },
      true,
    ],
    prop4: [
      [
        ["Item1", true],
        ["Item2", false],
        ["Item3", true],
      ],
      false,
    ],
    prop5: [
      [
        ["First", true],
        ["Second", false],
      ],
      true,
    ],
    prop6: [
      {
        key1: [{ prop7: [42, false] }, true],
        key2: [{ prop7: [100, true] }, false],
      },
      false,
    ],
  },
  true,
];

type DeepWrapped<T> = {
  [P in keyof T]: T[P] extends object ? DeepWrapped<T[P]> : [T[P], boolean];
};

// This should compile, because DeepWrapped and the inferred scheme from wrap() should match.
const someWrappedType: DeepWrapped<Some> = someWrappedSchemaData;
```
</details>

**Comment by fabian-hiller** [comment]
For recursive schemas we have: https://valibot.dev/api/lazy/
