### ISSUE TITLE
DONT found getOutput

### ISSUE THREAD

**Issue by VigilioYonatan** [fabian-hiller/valibot#232]
import { getOutput, getPipeIssues, string } from 'valibot'; // 0.54 kB
i dont found  getOutput and getPipeIssues

**Comment by fabian-hiller** [comment]
What version are you using? Please upgrade to the latest version and check the release notes for breaking changes. Currently we are still in v0, so there will be breaking changes from time to time. I expect v1 in January 2024.

**Comment by VigilioYonatan** [comment]
i was using 0.10.0 version. i update latest version 0.20 current. It's fixed. thanks
