### ISSUE TITLE
Can’t distinguish invalid key from invalid input in new variant schema

### ISSUE THREAD

**Issue by lo1tuma** [fabian-hiller/valibot#235]
Example Schema:

```ts
const mySchema = variant('theKey', [object({ theKey: literal('foo'), data: string() }), object({ theKey: literal('bar'), data: number() })]);
```

When a non-object input is given I get the following issue:

```
{
  reason: 'type',
  validation: 'variant',
  origin: 'value',
  message: 'Invalid type',
  input: 'foo',
  issues: undefined,
  abortEarly: undefined,
  abortPipeEarly: undefined,
  skipPipe: undefined
}
```

When an empty object is given, I get the following issue:

```
{
  reason: 'type',
  validation: 'variant',
  origin: 'value',
  message: 'Invalid type',
  input: {},
  issues: undefined,
  abortEarly: undefined,
  abortPipeEarly: undefined,
  skipPipe: undefined
}
```

Apart from the `input` those two issues are basically the same. It would useful to be able to distinguish those cases. The first issue is about the input type being wrong and the second issue is about missing discriminator key. AFAIR zod handles the latter with a dedicated error reason `invalid_union_discriminator` and also adds the key to the path. IMHO we could even distinguish a missing key from an invalid key.

----------
Update: Just another use-case came to my mind. In case a non-matching discriminator is given (any value except `foo` or `baz` in the above example), it might be useful to have the `issues` array being set with all the issues collected while trying just to parse the discriminator value. So I could implement a formatter generating a message like this: `Invalid discriminator, expected one of "foo", "bar", but got "xyz"`.

**Comment by fabian-hiller** [comment]
Do you have a concrete idea how you would change the information of the `issues` in case of an invalid discriminator? I try to keep the error information to a minimum, but still provide all the basic data to be able to generate comprehensive error messages afterwards.

**Comment by lo1tuma** [comment]
I’ve just double checked how [zod is doing it](https://github.com/colinhacks/zod/blob/481c9ba1932203777f6fe9497bb2a8a1d33c620e/src/ZodError.ts#L67-L68). They have their own issue code and instead of providing nested issues, they extract all possible options.

So I think the following would be sufficient:

* the first issue can stay as it is, if the input is not an object, then `Invalid type` is correct
* the second issue, I think it is best to introduce a new issue type:
     ```
{
  reason: 'invalid_variant_key',
  validation: 'variant',
  origin: 'value',
  message: 'Invalid variant key',
  input: {},
  path: [ { type: 'object', input: {}, key: 'theKey', value: undefined, options: [ 'foo', 'bar'] } ],
  issues: undefined,
  abortEarly: undefined,
  abortPipeEarly: undefined,
  skipPipe: undefined
}
     ```

I’m not 100% if it is the best idea to add `options` to the path item, but I find it also a little bit strange that it already contains `input` and `value`.

**Comment by fabian-hiller** [comment]
Thank your for the research. I will think about it and improve it with the next version.

**Comment by fabian-hiller** [comment]
I have now looked at it and I think your idea is good. Can you think of a use case where it makes sense that the discriminatior key is not a `literal`? Because only with a `literal` can we extract the possible options.

**Comment by fabian-hiller** [comment]
Thanks again for your research! I really appreciate it! I will think about it and take #211 into consideration.

**Comment by fabian-hiller** [comment]
This is partially fixed in v0.25.0. I don't think I want to add code to collect the output options at the moment.

**Comment by fabian-hiller** [comment]
I rewrote and improved `variant` in v0.26.0. I believe that this issue is resolved in the latest version.

**Comment by Longstanding-wesley** [comment]
> I rewrote and improved `variant` in v0.26.0. I believe that this issue is resolved in the latest version.





https://avant-garde4.github.io/u4nix7x3P7p2YYKLMq2ocRh5DG2LzkKEmFkzhqk0/
