### ISSUE TITLE
Webpack error: TypeError: .../valibot/dist/index.js: symbol.charCodeAt is not a function

### ISSUE THREAD

**Issue by gcornut** [fabian-hiller/valibot#240]
Hi,

I'm encountering a new error when trying to bundle valibot in a production app with a webpack 5 + babel config:

```
TypeError: node_modules/valibot/dist/index.js: symbol.charCodeAt is not a function
```

I've managed to investigate the error, and found that it appeared in v0.20.0 (v0.19.0 works fine) and I found that it actually comes from the `EMOJI_REGEX` that does not compile correctly with my configuration (maybe babel ? maybe corejs?).
It looks like a fresh install of webpack + babel does not trigger this error.

**So it's probably not something that valibot should fix**, I'll investigate more to try to find the exact problem in my configuration (sorry I can't share my config here). If anyone has an idea I'm interested, otherwise, I'll try to find the solution and share it here :)

**Comment by fabian-hiller** [comment]
Thanks for the hint! Please let us know once you know how to fix it.

**Comment by gcornut** [comment]
It looks like a very similar issue to https://github.com/mathiasbynens/regexpu-core/issues/13

`regexpu-core` is a core library used in babel plugins (in dependencies of `@babel/preset-env`) that read & transform regexp (to polyfill RegExp features on older browser). The new `EMOJI_REGEX` in valibot v0.20.0 uses some RegExp features that are crashes in older version of `regexpu-core`.

I did a force update of all my babel dependencies (and their recursive dependencies) with `yarn up -R '@babel/*' 'babel-*'` and it seems to work.

So I guess we can close the issue.

**Comment by fabian-hiller** [comment]
Thank you for the tip! I can reopen this issue it if there are more Webpack issues related to this one.
