### ISSUE TITLE
Webpack error; Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by kennethrorstromnine** [fabian-hiller/valibot#241]
Hi 
I just installed Valibot in my Nuxt 2 project (vue 2), node 18 - and i'm getting a webpack error .
This is most likely my setup - but i'm a little lost in what the solution could be?  
Any advice would be appreciated.

```
ERROR in /home/node/app/node_modules/valibot/dist/index.js 31:8
Module parse failed: Unexpected token (31:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| // src/error/ValiError/ValiError.ts
| var ValiError = class extends Error {
>   issues;
|   /**
|    * Creates a Valibot error with useful information.
```

**Comment by fabian-hiller** [comment]
What is your current version of Valibot? Did the problem also occur in previous versions? At the moment it looks like a webpack problem. Please let us know if you find a solution. Maybe the problem is also partly related to #240.

**Comment by kennethrorstromnine** [comment]
First time installing - v.0.20.

**Comment by fabian-hiller** [comment]
If the info in #240 does not help you, I suggest you contact Webpack as this seems to be unrelated to Valibot. I am sorry that I cannot provide you with a proper solution.

**Comment by kennethrorstromnine** [comment]
Thanks for quick response - 
For others, my solution was to transpile valibot in my `nuxt.config`.
```
{
  build: {
    ...
    transpile: ['valibot'],
    ...
  }
}
```

**Comment by fabian-hiller** [comment]
Thank you for sharing!
