### ISSUE TITLE
Add support for `function` schema

### ISSUE THREAD

**Issue by Jimdooz** [fabian-hiller/valibot#243]
Hi,

I've been exploring the current features and noticed that `function schema` validation, similar to what's available in Zod, isn't part of the project. I think incorporating this could enhance the functionality for users who rely on strict typing for functions.

I was thinking about something like this

```ts
const MyFunctionSchema = v.function()
  .args(
    v.string()
  )
  .returns(
    v.boolean()
  )

type FunctionSchema = Output<typeof MyFunctionSchema >;
```

**Comment by fabian-hiller** [comment]
Thank your for creating this issue. In Valibot we don't chain methods. Instead it will probably look something like this:

```ts
const MyFunctionSchema = v.function([v.string()], v.boolean());
```

What is your use case for a function schema? I haven't figured that out yet. That's why it's not part of the library. But I am happy to add it.

**Comment by Jimdooz** [comment]
Thank you for your reply!

Yes, you're right, this declaration format will be more in line with current syntax.

My use case involves a list of validators where each has a name and a corresponding validation function. I'm aiming to automate the process of checking argument schemas against these validators. Having function schema validation would streamline this process, ensuring that each function receives the correct type and structure of data before processing.

**Comment by fabian-hiller** [comment]
Thank you for your reply. Can you imagine creating a PR with a `function_` schema function? The code does not have to be perfect. Valibot is implemented very simply. You can copy the basic structure from another schema.

**Comment by Jimdooz** [comment]
Yes I can try :)

**Comment by Kenzo-Wada** [comment]
Hey, how's the progress going? I can't wait for this feature to be released! If it doesn't look like it's going to be implemented, I can develop it myself, what do you think?

**Comment by fabian-hiller** [comment]
I plan to work on this schema this or next week.

**Comment by Kenzo-Wada** [comment]
Thx!

**Comment by fabian-hiller** [comment]
I am not sure if we should implement the `function` schema the same way as Zod. The `function` schema in Zod does three things.

1. It validates that an input is a function
2. It returns a validation function that wraps the given function to validate its arguments and return value
3. It validates the arguments and the returned value when the validation function is called

Step 2 basically transforms the input, and step 3 happens "outside" the schema validation.

To be consistent and uniform with our other schemas, I would prefer that the `function` schema only does step 1. Step 2 could be implemented with a transformation action. This way our users can choose what functionality they really want and need.

```ts
// Only check for function data type
const Schema1 = v.function();

// Returns a new function that validates arguments and return value
const Schema2 = v.pipe(
  v.function(),
  v.argsAndReturn([v.string()], v.number())
);
```

> `argsAndReturn` is just an example name. Feel free to share your ideas!

Note, that both can already be implemented without `function` and `argsAndReturn`. This can be used as a workaround until we make a decision.

```ts
import * as v from 'valibot';

// Simple but less readable version
const Schema1 = v.pipe(
  v.instance(Function),
  v.transform((func) => (arg) => v.parse(v.number(), func(v.parse(v.string(), arg))))
);

// Longer and more readable version
const Schema2 = v.pipe(
  v.instance(Function),
  v.transform((func) => {
    return (arg) => {
      const parsedArg = v.parse(v.string(), arg);
      const return_ = func(parsedArg);
      const parsedReturn = v.parse(v.number(), return_);
      return parsedReturn;
    };
  })
);
```

**Comment by sillvva** [comment]
Is there a reason one would need runtime validation of a function? I think the need to do so would be incredibly rare. You can't load a function from env variables. You don't send functions to or receive them from API endpoints. Forms don't return functions in form data.

Most of the time, a simple TS type would suffice and as Fabian mentioned, function validation is already possible with `instance`

```ts
type CustomFunc = (...args: [string]) => boolean;
```

**Comment by fabian-hiller** [comment]
I agree that it is probably rare, as you should be able to trust your own functions, but I also see that it can add an extra layer of security in special cases. For example, if security is a high priority, you are working with people you cannot fully trust, or you are a library author.

In general, I am fine with adding a `function`, `promise`, and `file` schema because it can improve the developer experience. That's why we already have a `blob` and `date` schema.

Another hint: Instead of using a schema to define your validation functions, you could simply write them yourself. Here is a simple example:

```ts
import * as v from 'valibot';

function toEmailLength(arg: string) {
  const email = v.parse(v.pipe(v.string(), v.email()), arg);
  const length = v.parse(v.pipe(v.number(), v.maxValue(100)), email.length);
  return length;
}
```

**Comment by maranomynet** [comment]
I +1 the idea to have people add this themselves, and even publish as npm plugin libs, if they can't or don't want to use TypeScript for this sort of thing.

**Comment by fabulousgk** [comment]
> Is there a reason one would need runtime validation of a function? I think the need to do so would be incredibly rare. You can't load a function from env variables. You don't send functions to or receive them from API endpoints. Forms don't return functions in form data.
> 
> Most of the time, a simple TS type would suffice and as Fabian mentioned, function validation is already possible with `instance`
> 
> ```ts
> type CustomFunc = (...args: [string]) => boolean;
> ```

I want to give a quick use case.  I am writing a framework for Discord apps.  I dynamically load all the files in a specified directory for the commands, and I need to validate that the objects I am loading are of the correct shape plus type them.

I could also see this being useful in other plugin type implementations.

**Comment by fabian-hiller** [comment]
@fabulousgk what do you think about [this comment?](https://github.com/fabian-hiller/valibot/issues/243#issuecomment-2182514063) Should Valibot provide an `arguments` and `return` validation action?

**Comment by ktkk** [comment]
Just stumbled upon this issue while trying to parse `exports` from a WebAssembly instance.
I think this would be a great usecase for this functionality.
```ts
const ExportsSchema = v.object({
  add: v.pipe(
    v.function(),
    v.argsAndReturn([v.number(), v.number()], v.number()),
  ),
});

const { exports } = wasmInstance;
const { add } = v.parse(ExportsSchema, exports);
console.log(add(1, 2));
```

**Comment by fabulousgk** [comment]
> @fabulousgk what do you think about [this comment?](https://github.com/fabian-hiller/valibot/issues/243#issuecomment-2182514063) Should Valibot provide an `arguments` and `return` validation action?

I think it would be useful, and I think they should be separate so that one, both, or none could be used depending on the use case.  For example, in my current situation, I am not so concerned about the arguments, but I want to ensure it returns a boolean.

**Comment by fabian-hiller** [comment]
Thank you for your feedback! I will think about it.

**Comment by fabian-hiller** [comment]
v1.0.0-beta.1 with `args` and `returns` is available. Both actions are in beta. So feel free to give me feedback. I will add the documentation next week. Here is a code example:

```ts
import * as v from './mod.ts';

const FunctionSchema = v.pipe(
  v.function(),
  v.args(v.tuple([v.string()])),
  v.returns(v.number())
);
```
