### ISSUE TITLE
docs: add a search box

### ISSUE THREAD

**Issue by kazizi55** [fabian-hiller/valibot#244]
I think it would be more convenient to search various methods in docs by using a search box in Valibot doc.
For examples, there is a search box in [Qwik doc](https://qwik.builder.io/docs/), and we can use a search box by clicking the search button at the top of the page, or using a keyboard shortcut (`command + K`).

<img width="1128" alt="スクリーンショット 2023-11-05 16 02 29" src="https://github.com/fabian-hiller/valibot/assets/50566849/2dfca734-41b6-4d3b-b5c9-dc125f8487b6">

<img width="724" alt="スクリーンショット 2023-11-05 16 02 52" src="https://github.com/fabian-hiller/valibot/assets/50566849/97050d17-d4b6-494f-8dae-bcdecfed7e55">

**Comment by kazizi55** [comment]
If this request is approved, I will create a PR for this 😄

**Comment by fabian-hiller** [comment]
This is planned as soon as we finish the API reference. I have already implemented a custom solution for the [Modular Forms](https://modularforms.dev/) website that we can migrate to the Valibot docs written in Qwik.

**Comment by kazizi55** [comment]
> This is planned as soon as we finish the API reference. 

OK! After finishing writing the API reference, I'll create a PR for this 😄

**Comment by fabian-hiller** [comment]
Thanks a lot for all your help. That makes it a lot easier for me to focus on the library code to get v1 ready. 🙏

**Comment by fabian-hiller** [comment]
I am currently in the process of integrating a search box.
