### ISSUE TITLE
Current coerce implementation isn't type safe.

### ISSUE THREAD

**Issue by ivands** [fabian-hiller/valibot#246]
I've been using `superstruct` for a while now, and I'm wanting to switch to `valibot`.
However, I need help to switch over some of my custom schema functions.
I have a JSON schema function that will parse a string and validate a schema against the parsed JSON.

Superstruct example: 
```ts
import { coerce, string, Struct } from 'superstruct'

export const json = <T, S>(struct: Struct<T, S>): Struct<T, S> => {
	return coerce(struct, string(), (value) => {
		try {
			return JSON.parse(value)
		} catch(error) {
			return value
		}
	})
}
```

I would like to know what the recommended way is to write this is valibot.
Because the coerce function of valibot doesn't make much sense to me.
It's giving me a way to transform multiple input types to a single output without the type safety.

Valibot example:
```ts
export const json = <T extends BaseSchema>(schema: T) => {
	return coerce(schema, value => {
		try {
			return JSON.parse(value as string)
		} catch (error) {
			return value
		}
	})
}
```

In the valibot example, we didn't need to include an input schema that is needed for the coerce function to run.
But we could change the API to include something like this:

Expectation:
```ts
const schema = coerce(string(), number(), (v) => v.toString())

Input<typeof schema> // string | number
Output<typeof schema> // string
```

I've also tried to use the `transform` utility, but still got confused:
```ts
export const json = <T extends BaseSchema>(schema: T) => {
	return union([
		schema,
		transform(string(), value => {
			try {
				// We are parsing the string, but how should we validate the output against the schema???
				return JSON.parse(value)
			} catch (error) {
				// How can we add this error to the list of valibot issue's
			}
		}),
	])
}
```

I love the work that's been done so far by the way, and any help would be appreciated. ❤️

**Comment by fabian-hiller** [comment]
You can use `coerce` to change the input before validation and `transform` after validation. In your case, it makes sense to validate if the input is a string first. Otherwise you can't be sure that you are actually passing a string to `JSON.parse()`. That's why I would recommend to use `transform`. Here is an example:

```ts
// Create `json` util
const json = <TSchema extends BaseSchema>(
  schema: TSchema
): SchemaWithTransform<StringSchema, Output<TSchema>> => {
  return transform(
    string(),
    (input) => {
      try {
        return JSON.parse(input);
      } catch (error) {
        return null;
      }
    },
    schema
  );
};

// Use `json` util
const JsonSchema = json(
  object({
    key1: string(),
    key2: number(),
  })
);
```

**Comment by ivands** [comment]
Thanks for the fast help.
This pointed me in the right direction.
Much appreciated.

**Comment by fabian-hiller** [comment]
Reach out if you have more questions. I am happy to help!
