### ISSUE TITLE
Type instantiation is excessively deep and possibly infinite on nested error

### ISSUE THREAD

**Issue by iakovosvo** [fabian-hiller/valibot#253]
Hello, I am getting this TS error when I try to set a reactive `errors` object in Vue with the result of `flatten(error).nested`

`errors.value = flatten(error).nested;`

_Type instantiation is excessively deep and possibly infinite._

**Comment by fabian-hiller** [comment]
Can you provide me with the schema you are using? I can then investigate the problem.

**Comment by iakovosvo** [comment]
> Can you provide me with the schema you are using? I can then investigate the problem.

Hey Fabian, It looks like this

```
const HeavyMaintenanceSchema = object({
  field1: string([maxLength(300)]),
  field2: string([length(5)]),
  field3: string([minLength(1)]),
  field4: string([minLength(1)]),
  field5: string([email()]),
  field6: string([minLength(1)]),
  field7: string(),
  field8: string([
    length(5, 'Field must have at least 5 characters'),
    regex(NUMERIC_VALUE_REGEX, 'Only numbers are allowed.'),
  ]),
  field10: string([minLength(1)]),
  field11: string([minLength(1)]),
  field12: string([minLength(3), maxLength(5)]),
  field13: string(),
  field14: string([minLength(1)]),
});
```
Then I am just parsing the form like this inside a Vue watcher

```
try {
parse(MySchema, newValue);
} catch(error) {
 errors.value = flatten(error).nested;
}
```

**Comment by fabian-hiller** [comment]
I do not have this problem. If you want me to investigate further, please provide me with a StackBlitz playground. You can also try typing `flatten` with your schema.

```ts
try {
  parse(MySchema, newValue);
} catch (error) {
  errors.value = flatten<typeof MySchema>(error as ValiError).nested;
}
```

**Comment by radoslavkarlik** [comment]
Encountered the same but with the usage of union of arrays where each array contains elements of types that went through 3-4 merge operations. And the elements themselves have only 4 properties.

**Comment by fabian-hiller** [comment]
@radoslavkarlik yours is probably related to #24. Feel free to have a look at this issue and share your schema there.
