### ISSUE TITLE
Renaming `Input` type

### ISSUE THREAD

**Issue by yukukotani** [fabian-hiller/valibot#264]
In form components, we often use the `Input` component, and its name is duplicated with Valibot's `Input` type.

Of course, we can use an alias import, but since this is a common use case, renaming the `Input` type can be reasonable. 

ref:
- https://chakra-ui.com/docs/components/input/usage
- https://mui.com/material-ui/api/input/

**Comment by fabian-hiller** [comment]
In fact, this is not a problem. The `type` keyword in the import statement allows you to import `Input` once as a component and once as a type. And as you say, an alias can also be used as an alternative. You even have a third option with a wildcard import.

```ts
// Import as type
import { type Input } from 'valibot';

// Import with alias
import { Input as Infer } from 'valibot';

// Import as wildcard
import * as v from 'valibot'; // v.Input
```

Feel free to send me alternative ideas for the name. I will then think about it.

**Comment by fabian-hiller** [comment]
I am closing this topic, but may reopen it if there is still interest in discussing it.
