### ISSUE TITLE
Async parsing behavior not working as expected

### ISSUE THREAD

**Issue by Saeris** [fabian-hiller/valibot#267]
I'm updating my mocking library [Valimock](https://github.com/Saeris/valimock) and I'm running into issues with all of my async tests.

After some investigation with the help of [Wallabyjs](https://wallabyjs.com/) I was able to verify that my code was behaving correctly, as for example with an async literal schema, I expect it to generate a Promise of the literal value, like so:

```ts
const schema = literalAsync(`bar`)
const result = mockSchema(schema) // -> Promise<"bar">
```

However, I then run into an error trying to parse this result

```ts
await expect(parseAsync(schema, result)).resolves.toStrictEqual(result);
// promise rejected "ValiError: Invalid type { …(1) }" instead of resolving
```

Where I believe `{ ...(1) }` here refers to a positional argument here.

Okay, so at this point I believe the problem is within Valibot and not my library, so next I dug into the parsing code in use here to test my assumptions.

First of all, I assume the use-case for all of the async schemas is that they validate the resolved value of a given Promise (and any nested promises in the case of an object like structure). With the reason that they accept either a BaseSchema or BaseSchemaAsync is that the nested values may or may not be promises, and awaiting a literal value always resolves to the literal value.

So looking at the relevant code here, this is the path we would take:

https://github.com/fabian-hiller/valibot/blob/ce9e7164a67a88c4b7375b6ee69c954b331ef0be/library/src/methods/parse/parseAsync.ts#L18-L28

Here my expectation is that the `_parse` method of the given schema will need to `await` some value, so let's take a look at literalAsync now:

https://github.com/fabian-hiller/valibot/blob/ce9e7164a67a88c4b7375b6ee69c954b331ef0be/library/src/schemas/literal/literalAsync.ts#L34-L53

Okay, now I think I see the problem, `input` could be a Promise but it's never awaited! So of course, the comparison on line 45 here fails and we get the validation error. Are the tests actually using Promises?

https://github.com/fabian-hiller/valibot/blob/ce9e7164a67a88c4b7375b6ee69c954b331ef0be/library/src/schemas/literal/literalAsync.test.ts#L5-L39

Now this also make sense that the parsing logic here is flawed because all of the tests don't work with any async inputs, everything under test here is a literal value. Only the parse function itself is being treated as potentially async.

Taking a cursory look at other async schemas, we can see the same issues in other places, such as BigInt:

https://github.com/fabian-hiller/valibot/blob/ce9e7164a67a88c4b7375b6ee69c954b331ef0be/library/src/schemas/bigint/bigintAsync.ts#L55-L78

In each of these, I think the tests should be wrapping all of the values to be parsed in a `Promise.resolve()`, which would provide a closer match to a real-world use case scenario for these schemas.

Please let me know if this sounds accurate to you @fabian-hiller, then I can start a PR to resolve.

**Comment by fabian-hiller** [comment]
This is intended. Valibot does not modify the incoming data itself and treats it always as it is. The only difference between e.g. `string` and `stringAsync` is that `stringAsync` also allows to validate with asynchronous functions like `customAsync`. This makes it possible, for example, to check a value against some data in the database. Do you know how other schema libraries like Zod behave in this regards?

**Comment by Saeris** [comment]
>  Do you know how other schema libraries like Zod behave in this regards?

`zod` appears to have a Promise schema, which according to it's documentation does validation in a two-step process, first it resolves the value, then it applies validations. [Documented here](https://zod.dev/?id=promises)

`runtypes` appears to handle promises with what it defines as an "AsytncContract", which I couldn't easily find documentation for, but has tests defined [here](https://github.com/pelotom/runtypes/blob/0b86d725ac0143c725a753ebf4b8c8d616468119/src/asynccontract.spec.ts) demonstrating its usage.

A cursory glance at other libraries like arktype, effect/schema, yup, etc indicated that none of them supported async inputs or nested values.

> The only difference between e.g. string and stringAsync is that stringAsync also allows to validate with asynchronous functions like customAsync.

This could be better documented then that `Async` here refers to the validation and/or transformation steps in Valibot, and not that the schemas themselves represent an asynchronous data type (which is an easy assumption to make here).

A solution then could be to add an `promise()` schema type (or `awaited()`, thenable()`, `future()`, or whatever you want to call it otherwise), which would then be an async-only schema type.

**Comment by fabian-hiller** [comment]
Yes, I agree. We should think about adding something like `promise` as a schema. I also agree that we need to document this better. I plan to add an advanced guide for async validation and generally expand the documentation in early 2024. Thank you for your research!
