### ISSUE TITLE
`optional` and related now is maybe undefined using default factory

### ISSUE THREAD

**Issue by anhzf** [fabian-hiller/valibot#271]
Before that, I want to say thank you for building this library

```ts
const UserSchema = object({
  email: string(),
  name: string(),
  // randomAvatarImage() will always return string
  // the old one will have `TOutput: Output<string>`
  // the new one will have `TOutput: Output<string> | undefined`
  image: optional(string(), randomAvatarImage),
});
```

Is it now by design or just a mistake?

**Comment by micha149** [comment]
I think I can confirm, that the behavior of `optional()` has changed from `0.20.1` to `0.21.0`. Since the update, I get some type errors where `optional(array(string()), [])` results in `string [] | undefined`.

**Comment by fabian-hiller** [comment]
I know what the problem is in your case. I will fix it with the next version.

**Comment by anhzf** [comment]
thank you for your work in resolving this, really appreciate it 🥳

**Comment by fabian-hiller** [comment]
v0.22.0 is available.
