### ISSUE TITLE
[Proposal] Each expectation should have own test

### ISSUE THREAD

**Issue by ariskemper** [fabian-hiller/valibot#272]
I have proposal of improving tests and placing each expectation in its own test, because it is a best practice in software testing for several key reasons:

**Clarity and Precision:** Each test should ideally assess only one specific behavior or condition. This clarity helps in quickly identifying what exactly is failing when a test does not pass.

**Easier Debugging:** When a test fails, it's much easier to diagnose the issue if the test is only checking one thing. If a test containing multiple assertions fails, it can be unclear which assertion was the cause, requiring additional time to debug.

**Isolation of Failures:** If a test is checking multiple conditions and one fails, it can mask other failures in the same test. Isolated tests ensure that each failure is reported separately.

**Focused Test Intent:** Each test should have a clear intent or reason for existence, which is easily communicated through its name and structure. This helps other developers understand the purpose of the test and the specific conditions it is designed to check.

**Maintainability:** When tests are focused and isolated, they are easier to maintain and modify. If the functionality changes, you only need to update the relevant tests, without worrying about unintended consequences on unrelated assertions within the same test.

**Avoiding False Positives/Negatives:** Separate tests reduce the risk of false positives (where tests pass when they should fail) or false negatives (where tests fail when they should pass) due to complex interactions between assertions.

**Performance Analysis:** If tests are separated, it's easier to pinpoint performance issues.

**Comment by ariskemper** [comment]
@fabian-hiller i will create a draft PR for string and email. Tests are not included in the main build, my opinion is that libraries should be well tested, so some more boilerplate code in the repo is totally ok. Each test case will be more self explanatory, what actually is testing.

**Comment by fabian-hiller** [comment]
I am looking forward to your implementation and am very happy for your support. Testing is particularly important for a library like Valibot.

**Comment by fabian-hiller** [comment]
Thanks again for your feedback. With the rewrite, we have improved all the tests.
