### ISSUE TITLE
[Question] Is there an equivalent to ".extend" from zod?

### ISSUE THREAD

**Issue by alejandroperezpujante** [fabian-hiller/valibot#275]
I've been searching across the docs and issues to see if there is an equivalent to Zod's ".extend" method for object schemas but I can't seem to find any reference to it.

I use the feature a lot to reuse my schemas and I was wondering if a similar feature is available if Valibot.

Thanks for the great work!

**Comment by fabian-hiller** [comment]
Yes, a similarity functionality should we available with our `merge` method. Let me know if this works for your use case.

```ts
const Schema1 = object({
  name: string(),
  email: string([email()]),
});

const Schema2 = merge([
  Schema1,
  object({
    password: string([minLength(8)]),
  }),
]);
```

**Comment by alejandroperezpujante** [comment]
Huh, I fell stupid for not coming up with that simple word for the method.

Anyways, yes, It does work as I intended to. Thanks for the answer and for all you work!
