### ISSUE TITLE
Tuple option types can get annoying.

### ISSUE THREAD

**Issue by ivands** [fabian-hiller/valibot#279]
Using the union, picklist, and other functions can get annoying when using dynamic arguments.
Example: 
```ts
const values = [1, 2, 3] as const
const schema = union(values.map(i => literal(i)))
```
Examples like this fail because even though the ```values``` array is a tuple, mapping the array will make it a union type instead.
To be fair, I would say TS is failing us here.
But because of this problem, we need to make complex types to get this working.

Could we remove the tuple argument type & make it an array?

Original:
```ts
export type UnionOptions = [BaseSchema, BaseSchema, ...BaseSchema[]];
```
Proposal:
```ts
export type UnionOptions = BaseSchema[];
```

**Comment by fabian-hiller** [comment]
Thank you for creating this issue. I am aware of the problem. I will look into it and then make a decision.

**Comment by fabian-hiller** [comment]
Yes, I agree. I will look into this in the next few days. Thanks for your research!

**Comment by dawidurbanski** [comment]
FYI this should work in plain TypeScript

```ts
const v1 = [1, 2, 3] as const // type [1, 2, 3]
const v2 = v1.map(v => v * 2) as unknown as typeof v1 // type [1, 2, 3]
```

therefore this also should be ok with Valibot

```ts
const values = [1, 2, 3] as const // type [1, 2, 3]
const literals = values.map((v) => literal(v)) as unknown as typeof values // type [1, 2, 3]
const schema = union(literals as unknown as UnionOptions) // works fine
```

still ugly and not best developer experience, but hey, no need to type tuple arguments ourselves

**Comment by ivands** [comment]
@dawidurbanski You are completely losing type inference this way.
```TS
const schema = union(literals as unknown as UnionOptions)
type I = Input<typeof schema> // ???
```
Plus, you lost type safety by casting everything. (The reason for TS in the first place).
I think that if people are typecasting to use the library, we made a mistake with the API.

**Comment by dawidurbanski** [comment]
Oh, right. I didn't thing this through :D

**Comment by fabian-hiller** [comment]
Will have a closer look at this issue in the next days.

**Comment by fabian-hiller** [comment]
I am still unsure if I want to change the typing of the argument from a tuple to an array. The disadvantage is less type safety and the advantage is a better DX when using `.map(...)`. Until I make a decision, I recommend using a small helper function that ensures type safety. Currently there is still a type error with the following solution but with v0.23.0 I will fix this problem.

1. Add `literalsFrom` util to your project

```ts
import * as v from 'valibot';

/**
 * Converts a data tuple to a tuple of literal schemas.
 *
 * @param tuple The data tuple.
 *
 * @returns A tuple of literal schemas.
 */
export function literalsFrom<
  TTuple extends Readonly<[v.Literal, v.Literal, ...v.Literal[]]>
>(
  tuple: TTuple
): {
  [TTupleKey in keyof TTuple]: v.LiteralSchema<TTuple[TTupleKey]>;
};

/**
 * Converts a data tuple to a tuple of literal schemas.
 *
 * @param tuple The data tuple.
 * @param key The data key.
 *
 * @returns A tuple of literal schemas.
 */
export function literalsFrom<
  TTuple extends Readonly<
    [
      Record<TDataKey, v.Literal>,
      Record<TDataKey, v.Literal>,
      ...Record<TDataKey, v.Literal>[]
    ]
  >,
  TDataKey extends keyof TTuple[number]
>(
  tuple: TTuple,
  key: TDataKey
): {
  [TTupleKey in keyof TTuple]: v.LiteralSchema<TTuple[TTupleKey][TDataKey]>;
};

export function literalsFrom<
  TTuple extends Readonly<[any, any, ...any[]]>,
  TDataKey extends keyof TTuple[number]
>(tuple: TTuple, key?: TDataKey) {
  return tuple.map((literal) => v.literal(key ? literal[key] : literal));
}
```

2. Use `literalsFrom` in your schema

```ts
import * as v from 'valibot';
import { literalsFrom } from 'utils';

// With direct values
const options1 = ['foo', 'bar'] as const;
const Schema1 = v.union(literalsFrom(options1));

// With simple object
const options2 = [{ value: 'foo', label: 'Foo' }, { value: 'bar', label: 'Bar' }] as const;
const Schema2 = v.union(literalsFrom(options2, 'value'));
```

**Comment by ivands** [comment]
To be honest, I wouldn't say I like this solution.
1. We now need to learn about helper functions to work around TS.
2. This helper function example only fixes the single-use case of providing a list of literals. Unions can have all kinds of types inside them.
3. I would argue that the type-safety provided by the tuple isn't necessary.
It might be weird to create a union type with a single entry or to use picklist with just a single string.
But that's just what might happen when providing a dynamic argument.

I guess I just disagree with the safety provided by the tuple.
A minimum of 2 arguments feels wrong to me.
