### ISSUE TITLE
Another blocking change to custom pipeline validator

### ISSUE THREAD

**Issue by crystalfp** [fabian-hiller/valibot#283]
The following custom validator was working without problems in 0.21.0 (after reading the migration guide...).
Now after upgrading to 0.22.0 it complains that  '"valibot"' has no exported member named getPipeIssues and getOutput.
```
const validateUuidWithSequence = (): BaseValidation<string> => {
	return {
		async: false,
		message: "Invalid UUID with sequence",
		_parse(value: string) {
			if(value.length > 36) {

				const sequence = Number.parseInt(value.slice(37), 16);
				if(Number.isNaN(sequence) || sequence <= 0 || sequence > 0xF_FF) {
					return getPipeIssues("custom", "Invalid sequence", value);
				}
			}
			return getOutput(value);
		},
	};
};
```
It is used in schema this way:
```
const projectSchema = object({
	documents: array(object({
		id: string([validateUuidWithSequence()]),
	}))
});
```
There is no warning anywhere in the documentation nor a migration guide about this showstopper. How should I modify my validator?
Thanks!
mario

**Comment by crystalfp** [comment]
I have to dig in GitHub to find that:
getPipeIssues -> actionIssue
getOutput -> actionOutput
Hope this is the sole change to these routines and no other hidden difference exists.

**Comment by fabian-hiller** [comment]
I had renamed the utility functions. I apologize for not documenting this better. The breaking changes will be less with the next minor releases. I think we are on the right track.
