### ISSUE TITLE
How validate object with hyphen in the keys

### ISSUE THREAD

**Issue by tjhoo** [fabian-hiller/valibot#29]
Hi
May I know how to create a schema to validate an object with hyphen in the key, e.g. `X-API-Key`
```javascript
const ApiKeySchema = object({
  headers: object({
    "X-API-Key": string("API key is missing", [minLength(1)]),
  }),
});
```

**Comment by fabian-hiller** [comment]
Your scheme looks good and works. I have tested it in my test environment. Are you experiencing any problems with it?

You can improve the error messages in your scheme:

```ts
const ApiKeySchema = object({
  headers: object({
    'X-API-Key': string('API key must be a string', [
      minLength(1, 'API key is missing'),
    ]),
  }),
});
```

**Comment by tjhoo** [comment]
@fabian-hiller You're right, there is nothing wrong with `valibot` but my schema used in `Express.js` middleware.
To conclude this issue, the following is the working schema to validate the `X-API-Key` in the request headers
```
const ApiKeySchema = object({
  headers: object({
    "x-api-key": string("API key must be a string", [
      minLength(1, "API key is missing"),
    ]),
  }),
});
```
The key must be a lowercase `x-api-key`, and not `X-API-Key`.
