### ISSUE TITLE
Allow schema serialization

### ISSUE THREAD

**Issue by MatanYadaev** [fabian-hiller/valibot#30]
Schema serialization will make this package a good alternative for JSON schema.

Example:
```ts
import { serialize, deserialize, parse } from 'valibot';

const serializedLoginSchema = serialize(LoginSchema);
const deserializedLoginSchema = deserialize(serializedLoginSchema);

const parsedData = parse(deserializedLoginSchema, { email: 'jane@example.com', password: '12345678' })

console.log(parsedData); // { email: 'jane@example.com', password: '12345678' }
```

Serialization won't be possible if `transform` or any other method that has JS callbacks.

**Comment by fabian-hiller** [comment]
Related to #23

**Comment by fabian-hiller** [comment]
Thanks for the suggestion about the API. JSON to schema is technically not a problem. However, schema to JSON will be a challenge with major changes, since a schema at the moment is composed of different functions and that is not serializable.

**Comment by fabian-hiller** [comment]
A native Valibot to JSON schema or JSON schema to Valibot implementation is not currently planned. Technically, however, it is largely possible through our new [reflection API](https://github.com/fabian-hiller/valibot/pull/211) and can be covered by third-party packages like [valibot-json-schema](https://github.com/gcornut/valibot-json-schema/). If JSON Schema is important to you, I suggest you take a look at [TypeBox](https://github.com/sinclairzx81/typebox).

I am therefore closing this issue. However, you can still contact me through this issue if you have any questions or feedback.

**Comment by gadicc** [comment]
Hi all, I vibe-coded something like this over the weekend.  Let's see where it goes :)

https://github.com/gadicc/valibot-serialize
