### ISSUE TITLE
Small bundle size starting at less than 300 bytes

### ISSUE THREAD

**Issue by yamiteru** [fabian-hiller/valibot#31]
First of all I recommend turning on discussions since technically speaking this is not an issue.

I'd like to ask how those 300 bytes in README in a sentence "Small bundle size starting at less than 300 bytes" were determined.

Did you import only let's say string? Or number? Or something else?

Thank you.

**Comment by fabian-hiller** [comment]
Exactly. Basically, this number should roughly describe at how many bytes the bundle size starts at. Would you handle that differently?

**Comment by yamiteru** [comment]
No I think this is a completely valid way. I'd just add more info about how you determined that number. Something like this:

```ts
import { string } from "valibot" // 300 bytes
```

**Comment by fabian-hiller** [comment]
Good idea, I will do that.
