### ISSUE TITLE
`partial(record(...))` is not possible

### ISSUE THREAD

**Issue by genki** [fabian-hiller/valibot#313]
I have tried to define a schema of partial record like this, but it couldn't:

```ts
const Names = ["foo", "bar", "baz"] as const;
const NameSchema = picklist(Names);
const NameCountSchema = record(NameSchema, number());
const PartialNameCountSchema = partial(NameCountSchema); // <- type error
```
https://stackblitz.com/edit/typescript-xv6oqj?file=index.ts

Currently the `partial()` only for applicable to `object()`?

**Comment by fabian-hiller** [comment]
Thanks for bringing this up. That's right, `partial` is currently limited to `object` and I'm not sure if we should change that. Is there even a need to use `partial` with `record`? The entries of `record` with `picklist` are already optional.

**Comment by genki** [comment]
I see, indeed all my use cases were enough by using the `picklist`.
If I am going to come up with something, I will reopen.
