### ISSUE TITLE
About controlling multiple fields with custom and forward methods.

### ISSUE THREAD

**Issue by nio-p** [fabian-hiller/valibot#314]
@fabian-hiller 

Hello,

I have an issue about controlling 2 fields with `forward` and `custom` method.

This is my sample code.

### schema.ts

```ts
export const FormSchema = object(
  {
    test: string(),
    test_amount: number(),
  },
  [
    forward(
      custom(
        (input) => input.test.length !== 0 && input.test_amount >= 100,
        'Please input test_amount value over 100.',
      ),
      ['test_amount'],
    ),
  ],
);

export type FormType = Output<typeof FormSchema>;
```

### Form.tsx

```tsx
import modules...;

export const ContractForm = () => {
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors, isValid, isSubmitting },
  } = useForm<FormType>({
    mode: 'onBlur',
    resolver: valibotResolver(FormSchema),
  });

  const test = watch('test');

  const onSubmit = handleSubmit(async (data) => {
    console.log(data);
  });

  return (
    <form className="flex flex-col gap-8" method="post" onSubmit={onSubmit}>
      <div className="flex flex-col gap-2">
        <Label htmlFor="test">
          Test<Tag>Optional</Tag>
        </Label>
        <TextField
          autoComplete="off"
          id="test"
          inputMode="text"
          placeholder=""
          type="text"
          {...register('test')}
        />
        {errors.test && <ErrorText>{errors.test.message}</ErrorText>}
      </div>

      {test && (
        <div className="flex flex-col gap-2">
          <Label htmlFor="test_amount">
            test_amount<Tag isRequired>Required</Tag>
          </Label>
          <TextField
            autoComplete="off"
            id="test_amount"
            inputMode="numeric"
            placeholder=""
            type="number"
            {...register('test_amount')}
          />
          {errors.test_amount && <ErrorText>{errors.test_amount.message}</ErrorText>}
        </div>
      )}

      <Button disabled={!isValid || isSubmitting} size="lg" type="submit" variant="primary">
        Submit
      </Button>
    </form>
  );
};

```

Looks like ok, but `errors.test_amount` returns only `Invalid type`.
Why errors does not return `Please input test_amount value over 100.`.

If you have any tips on how to solve this problem, could you please let me know?

Thanks,

**Comment by fabian-hiller** [comment]
If the schema returns `Invalid type` for `test_amount`, this means that `test_amount` is not a number. Since the `pipe` of `object` is typesafe, we can only execute it if `test_amount` is a number. To work around this, you could give `test_amount` an initial or default value of `0`, or change the schema to `optional(number())`.

**Comment by nio-p** [comment]
@fabian-hiller 

Thank you for quick response!
I misunderstood about `forward` behavior.

The sample code I gave is fragmentary; in reality there are many input fields.
And I found that `forward` will not fire until all fields are filled.

For my part, I wanted the `forward` to fire even if not all fields were filled in.
Do you have an idea to resolve this issue?

**Comment by fabian-hiller** [comment]
Yes, try to mirror your form completely with the schema, taking into account the input and output value of your form. For example, change your schema to the following. This will fill undefined values with appropriate default values.

```ts
export const FormSchema = object(
  {
    test: optional(string(), ''),
    test_amount: optional(number(), 0),
  },
  [
    forward(
      custom(
        (input) => input.test.length && input.test_amount >= 100,
        'Please input test_amount value over 100.',
      ),
      ['test_amount'],
    ),
  ],
);
```

**Comment by nio-p** [comment]
@fabian-hiller 

Thanks to your advice I have successfully solved this problem !!
I really appreciate it.
Thanks for the great product 👍
