### ISSUE TITLE
Benchmarks and comparisons

### ISSUE THREAD

**Issue by yamiteru** [fabian-hiller/valibot#32]
It'd be really nice to see comparative benchmarks with other similar libs and how they compare with valibot.

**Comment by fabian-hiller** [comment]
Here #19 you will find a first answer. I'll be adding more information to the documentation over the next few weeks.

**Comment by icebob** [comment]
An alternative benchmark: https://github.com/icebob/validator-benchmark

**Comment by icebob** [comment]
Wow, nice job 10x speed.
