### ISSUE TITLE
Issue with Email Sign-Up Due to "+" Character

### ISSUE THREAD

**Issue by ollebergkvist** [fabian-hiller/valibot#333]
We recently received a support ticket from a client who faced difficulties signing up for our app because their email contained a "+". The valibot validation for the email() method prevented the sign-up process.

I'm aware that many email providers do not permit the use of the "+" character. However, I'd like to highlight that reputable providers, such as ProtonMail, now allow its usage in email addresses (https://proton.me/mail).

**Comment by ariskemper** [comment]
@ollebergkvist could you provide more context, because valibot supports email in format like name+surname@example.com ?

**Comment by fabian-hiller** [comment]
Thank you for creating this issue. I will take a look at it once we have more details. As a workaround, you can use one of these regex along with our `regex` validation function:

W3C Working Draft Regex from [w3.org](https://www.w3.org/TR/2012/WD-html-markup-20120329/input.email.html):

```
/^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/
```

HTML Standard Regex from [whatwg.org](https://html.spec.whatwg.org/multipage/input.html#valid-e-mail-address):

```
/^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/
```

**Comment by sqmasep** [comment]
> @ollebergkvist could you provide more context, because valibot supports email in format like [name+surname@example.com](mailto:name+surname@example.com) ?

It seems that it doesn't work when a `+` is at the end of the input. If i'm not mistaken, some emails allow this, so that might be the problem

**Comment by fabian-hiller** [comment]
Thanks for the info. That could be the problem. Let's wait for @ollebergkvist's reply.

**Comment by fabian-hiller** [comment]
And maybe take a look at issue #204 to understand why `email` intentionally does not accept every valid email address.

**Comment by ariskemper** [comment]
@sqmasep @fabian-hiller i added a test here [#276 ](https://github.com/fabian-hiller/valibot/pull/276/files) and, it is working for + in the begining and ending of local part. Maybe it is no the issue in '+'character @ollebergkvist? So we would need more context on it.

**Comment by ollebergkvist** [comment]
Sorry, I've been away for a couple of days.

The email that triggered the error is:
xv4rgx+larm@pm.me

Running:
 "valibot": "^0.19.0",

**Comment by ollebergkvist** [comment]
I invested additional time in debugging the problem. The validation error triggered by valibot for emails with a '+' symbol didn't occur due to the validation process rejecting emails containing '+'. Instead, the issue stemmed from our oversight in encoding/decoding the query parameter passed to valibot. Consequently, valibot misinterpreted the '+' symbol as a space.

Thanks and sorry for the false alarm here!
