### ISSUE TITLE
Branded schema doesn't provide the type guard thru the `is`.

### ISSUE THREAD

**Issue by genki** [fabian-hiller/valibot#341]
Here is an example

```ts
const UserIDSchema = brand(string([length(12)]), "UserID");
type UserID = Output<typeof UserIDSchema>;

const logUserID = (uid:UserID) => {
  console.log(uid);
}

const foo = "123456789012";
if (is(UserIDSchema, foo)) {
  logUserID(foo); // <-- Type Error
}
```

https://stackblitz.com/edit/typescript-53auwg?file=index.ts

**Comment by fabian-hiller** [comment]
As written [here](https://valibot.dev/guides/parse-data/#type-guards), `is` has some limitations. One of them is that it can only secure the input type, but not the output type. Therefore you need to change `Output` to `Input`. With the current implementation, only the output type is branded. Therefore `is` does not work with `brand`. If there are good reasons to also brand the input type, I will be happy to take a closer look at the implementation.

```ts
import * as v from 'valibot';

const UserIDSchema = v.brand(v.string([v.length(12)]), 'UserID');
type UserID = v.Input<typeof UserIDSchema>; // <-- Change here

const logUserID = (uid: UserID) => {
  console.log(uid);
};

const foo = '123456789012';
if (v.is(UserIDSchema, foo)) {
  logUserID(foo);
}
```

**Comment by genki** [comment]
@fabian-hiller Ah, I see.
I will use `Input` instead of `Output`.
Thank you :)
