### ISSUE TITLE
Reporting of Errors (ValiError Format compared with ZodError Format)

### ISSUE THREAD

**Issue by WtfJoke** [fabian-hiller/valibot#344]
We currently use zod and wanted to give this library a try to utilize the tree-shakeability features of it.
In comparsion valibot seems to be less expressive compared to zod when dealing with parsing errors . Are there plans to change/improve that?

Zod parse error:
```javascript
ZodError: [
  {
    "code": "invalid_string",
    "validation": "datetime",
    "message": "Invalid datetime",
    "path": [
      "timestamp"
    ]
  }
]
```

Valibot parse error:
```javascript
ValiError: Invalid date-time
```

**Comment by sexnine** [comment]
When parsing, valibot should throw a `ValiError` that contains an array of `Issue` if it encounters an error.

From the docs:
> The [parse](https://valibot.dev/api/parse/) method will throw a [ValiError](https://valibot.dev/api/ValiError/) if the input does not match the schema.

```ts
type Issue = {
  reason: IssueReason;
  validation: string;
  origin: IssueOrigin;
  message: string;
  input: any;
  path?: PathItem[];
  issues?: Issues;
  abortEarly?: boolean;
  abortPipeEarly?: boolean;
  skipPipe?: boolean;
}
```

Printing `error.issues` you should find the kinda result you're expecting :)

**Comment by fabian-hiller** [comment]
Please take a look at the following guide and contact me if you need further help. I am happy to assist you. https://valibot.dev/guides/issues/

**Comment by WtfJoke** [comment]
Thanks for the super fast response, appreciate that!

Yeah I saw that the inside object is pretty identical to the structure, I like that :)
For some validation test scenarios we like to use matchininlinesnapshot and there it was quiet a difference (see below).

```javascript
  it("should fail with invalid timestamp", async () => {
    const event = {
      timestamp: "2020-01-01T00:00:00.000",
    };

    await expect(valibotHandler(event)).rejects.toThrowErrorMatchingInlineSnapshot(
      `"Invalid timestamp"`
    );
  });

  it("should fail with invalid event", async () => {
    const event = {
      timestamp: "2020-01-01T00:00:00.000",
    };
    await expect(zodHandler(event)).rejects.toThrowErrorMatchingInlineSnapshot(`
      "[
        {
          "code": "invalid_string",
          "validation": "datetime",
          "message": "Invalid datetime",
          "path": [
            "timestamp"
          ]
        }
      ]"
    `);
  });
  ```
But an unhandled ValiError during runtime looks pretty similar to the similar serialized structure, so I guess I'll close the issue. Thanks!
