### ISSUE TITLE
isoTimestamp only supports decimal fraction up to 3 digits

### ISSUE THREAD

**Issue by WtfJoke** [fabian-hiller/valibot#348]
While testing I figured that valibot handles isoTimestamps a bit stricter than zod.

Given following valibot snippet:
```javascript
import { isoTimestamp, object, parse, string } from "valibot";
const dEventStructure = object({
  timestamp: string([isoTimestamp()]),
});
const { timestamp } = parse(dEventStructure,  {
      timestamp: "2020-01-01T00:00:00.0030Z",
})
```

This is a valid timestamp: `"2020-01-01T00:00:00.000Z"`
This is not considered a valid timestamp by valibot, but on zod it is: `"2020-01-01T00:00:00.0030Z"`

Comparable zod snippet:
```javascript
const zEventStructure = z.object({
  timestamp: z.string().datetime(),
});
 const { timestamp } = zEventStructure.parse( {
      timestamp: "2020-01-01T00:00:00.0030Z",
});
```

According to stackoverflow the ISO 8601:2014 standard doesnt say anything about the fraction of the seconds...
https://stackoverflow.com/a/25876314/2970422
>ISO 8601:2004 doesn't specify the number of digits in the decimal fraction.
>4.2.2.4 Representations with decimal fraction
>>The interchange parties, dependent upon the application, shall agree the number of digits in the decimal fraction. The format shall be [hhmmss,ss], [hhmm,mm] or [hh,hh] as appropriate (hour minute second, hour minute, and hour, respectively), with as many digits as necessary following the decimal sign. A decimal fraction shall have at least one digit.

The newest revision ISO 8601:2019 state something different, but I honestly dont quiet grasp it (maybe its too late...)
https://www.iso.org/obp/ui/en/#iso:std:iso:8601:-1:ed-1:v1:en:term:3.1.3.8
>3.1.3.8
representation with decimal fraction
expansion of a [date and time representation (3.1.3.2)](https://www.iso.org/obp/ui/en/#iso:std:iso:8601:-1:ed-1:v1:en:term:3.1.3.2) by addition of a decimal fraction to the lowest order [time scale component (3.1.3.3)](https://www.iso.org/obp/ui/en/#iso:std:iso:8601:-1:ed-1:v1:en:term:3.1.3.3)

P.S:  I hope you dont mind I'll just opened another issue :D

**Comment by fabian-hiller** [comment]
Is there any problem with the current implementation for real world usage? It should support any string `new Date().toISOString()` returns.

**Comment by WtfJoke** [comment]
In our current project another system sends events with timestamps in this format (and needed to rollback the change). 

I currently cant tell how they get created (I suspect a Java class)

**Comment by WtfJoke** [comment]
Java `Instant.now().toString()` returns `2024-01-04T17:40:21.157953900Z`
> A string representation of this instant using ISO-8601 representation.

from the `Instant.toString()` [Javadoc](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/time/Instant.html#toString())

Since `new Date("2024-01-04T17:40:21.157953900Z").toISOString()` works, I think valibot should support that format as well.

**Comment by fabian-hiller** [comment]
In my tests Java's `Instant.now()` returned `2024-01-05T00:48:36.037Z`. I am not sure if we should change the regex of `isoTimestamp` or rather recommend `regex` with a custom regex in such cases because it seems to me that the precision is only very rarely greater than 3.

**Comment by fabian-hiller** [comment]
I thought 3 digs was the standard. If that's wrong, you're right and we should probably extend that.

**Comment by WtfJoke** [comment]
Since the standard doesnt specify it explicitly, there seems to be no real standard and therefore it differs 🙈

**Comment by fabian-hiller** [comment]
Thank you for the information you provided. I will review everything again next week and then probably merge your PR. Until then, you can use `regex` as a workaround.
