### ISSUE TITLE
Document minimum typescript version

### ISSUE THREAD

**Issue by johanndev** [fabian-hiller/valibot#351]
Hi!

The documentation is missing a note about the minimum typescript version that is required for valibot to work (5.0.2?)
This should probably be documented on the installation page.

If you could confirm the minimal typescript version, I can provide a PR for the website - thanks!

**Comment by fabian-hiller** [comment]
Do you know if there is a way to figure out the minimum TypeScript version required? I think the most advanced feature we are using ist the [`const` modifier](https://github.com/microsoft/TypeScript/pull/51865) that was shipped with v5.

**Comment by johanndev** [comment]
I'm not aware of a programmatic way of determining the required TS version - I found 5.0.2 as the min version just by trial and error.

**Comment by fabian-hiller** [comment]
We could add the following to the "General" section of the [installation guide](https://valibot.dev/guides/installation/) below the `tsconfig.json` text.

> The minimum required TypeScript version is v5.0.2.

If you are interested, feel free to create a draft PR for an integration test.

**Comment by johanndev** [comment]
> We could add the following to the "General" section of the [installation guide](https://valibot.dev/guides/installation/) below the tsconfig.json text.

Yes, that sounds perfect 👍

> If you are interested, feel free to create a draft PR for an integration test.

I'm gonna do some research first, I'll get back to you :)

**Comment by fabian-hiller** [comment]
I added the min version info to the docs.

**Comment by johanndev** [comment]
I created a draft PR: #354

As the original issue was addressed, I'm gonna close this discussion.

**Comment by fabian-hiller** [comment]
Thank you!
