### ISSUE TITLE
Nextjs build  Failed

### ISSUE THREAD

**Issue by mahersalhani** [fabian-hiller/valibot#352]
Checking validity of types  .Failed to compile.

./node_modules/valibot/dist/index.d.ts:1980:27
Type error: Type parameter declaration expected.

  1978 |  * @returns A picklist schema.
  1979 |  */
> 1980 | declare function picklist<const TOptions extends PicklistOptions>(options: TOptions, message?: ErrorMessage): PicklistSchema<TOptions>;
       |                           ^
  1981 | /**
  1982 |  * See {@link picklist}
  1983 |  *
error Command failed with exit code 1.

I use 
"valibot": "^0.25.0",

**Comment by fabian-hiller** [comment]
Can you send me your schema? But it seems like this is an external problem.

**Comment by ZilvinasAbr** [comment]
I've got similar issue when trying to use valibot inside of a server action for validating form submission with Next.js app router.

The issue happens when trying to build the next.js application.

Code looks something like this:
```ts
'use server'

import { object, parse, string } from 'valibot'

const schema = object({
  name: string(),
})

export const submit = async (formData: FormData) => {
  const parsedFormData = parse(schema, {
    name: formData.get('name'),
  })

  // Rest of the code
}

```

I get the error when building:
```
n [ValiError]: Invalid type

...

issues: [
    {
      reason: 'type',
      validation: 'enum',
      origin: 'value',
      message: 'Invalid type',
      input: undefined,
      issues: undefined,
      abortEarly: undefined,
      abortPipeEarly: undefined,
      skipPipe: undefined,
      path: [Array]
    }
  ]

```

**Comment by fabian-hiller** [comment]
Something seems to be wrong here. A `ValiError` should only be thrown when validating data, not when bundling your application. Valibot is just a simple JavaScript library that exports some functions. We have no dependencies. So I assume there is a problem in your code, configuration or build process. Feel free to share a minimal reproduction via Stackblitz so I can debug the problem.

**Comment by mahersalhani** [comment]
> Can you send me your schema? But it seems like this is an external problem.

import { object, string, minLength, toTrimmed, type Output } from 'valibot';

export const DesignFormSchema = object({
  name: string(undefined, [toTrimmed(), minLength(3, 'design.name_required')]),
});

export type DesignFormData = Output<typeof DesignFormSchema>;


When I used "valibot": "^0.19.0" it's worked

**Comment by fabian-hiller** [comment]
What version of TypeScript are you using? [`picklist`](https://valibot.dev/api/picklist/), the function in the error messages, uses the [`const` modifier](https://github.com/microsoft/TypeScript/pull/51865). This is a feature introduced in TypeScript v5. It looks like your build process can't handle it.

Tip: You can remove `undefined` as the first argument of [`string`](https://valibot.dev/api/string/).

**Comment by mahersalhani** [comment]
I use  `"typescript": "4.9.4"` .
I updated to  `"typescript": "^5.3.3"` and it worked
