### ISSUE TITLE
Optional Objects with Literal Fields and Raw Default Result in "| undefined" Type

### ISSUE THREAD

**Issue by mutewinter** [fabian-hiller/valibot#363]
## Objects with Literal Fields and a Raw Default Return Invalid Type from v.Output

```typescript
const RawDefaultSchema = v.optional(
  v.object({ type: v.literal('1'), x: v.number() }),
  { type: '1', x: 1 },
);

// Incorrect type
type RawDefault = v.Output<typeof RawDefaultSchema>; // { type: "1"; x: number; } | undefined
```

This seems to only occur when the object includes a `literal` value.

## Expected Behavior

The `RawDefault` type above would not include `| undefined`.

## Workaround

Define the default as a function

```typescript
const FunctionDefaultSchema = v.optional(
  v.object({ type: v.literal('1'), x: v.number() }),
  () => ({ type: '1', x: 1 }),
);

// Correct type
type FunctionDefault = v.Output<typeof FunctionDefaultSchema>; // { type: "1"; x: number; }
```

**Comment by fabian-hiller** [comment]
Thanks for reporting this issue. It seems that TypeScript is not able to detect the default value as it should. I will investigate this. Another workaround is to add `as const` to the literal value.

```ts
import * as v from 'valibot';

const RawDefaultSchema = v.optional(
  v.object({ type: v.literal('1'), x: v.number() }),
  { type: '1' as const, x: 1 } // <--
);

type RawDefault = v.Output<typeof RawDefaultSchema>;
```

**Comment by fabian-hiller** [comment]
This should be fixed in the latest RC version! Thank you!
