### ISSUE TITLE
A GPT companion for the Zod to Valibot conversion

### ISSUE THREAD

**Issue by okomarov** [fabian-hiller/valibot#370]
I wanted to migrate to Valibot a while back but didn't have much time, especially to handle `transform`s or `refine`s. 

I now put quickly together a [GPT companion](https://chat.openai.com/g/g-7keavCEM4-zod-to-valibot) which hopefully can get people going faster and help them bridge that gap. 

Far from perfect, so happy to address feedback and fix this in that GPT.

**Comment by fabian-hiller** [comment]
That's great! Thank you very much. Is it only available with GPT Plus? Once the output is correct in most cases, we could mention in the repo or docs.

**Comment by cannap** [comment]
@fabian-hiller  those custom gpts  only work with GPT Plus

**Comment by fabian-hiller** [comment]
Thank you for the information!

**Comment by fabian-hiller** [comment]
I will close this issue for now.
