### ISSUE TITLE
`union()` of object with overlapping field drops other fields

### ISSUE THREAD

**Issue by FujishigeTemma** [fabian-hiller/valibot#371]
When using union() with objects that have overlapping fields, it seems that fields that are not common between the objects are being dropped unexpectedly. 

### Minimal Reproduction
```ts
const A = object({
	x: string(),
});

const B = object({
	x: string(),
	y: number(),
});

const C = union([A, B]);

safeParse(C, { x: "foo", y: 1 });
```
```ts
{
	"typed": true,
	"success": true,
	"data": { "x": "foo" }, // expected: { "x": "foo", "y": 1 }
	"output": { "x": "foo" } // expected: { "x": "foo", "y": 1 }
}
```

### Additional Informations
![image](https://github.com/fabian-hiller/valibot/assets/49122148/dd05fe19-13fd-42b6-9402-4398014be264)
![image](https://github.com/fabian-hiller/valibot/assets/49122148/485c809c-6bf6-4b8c-b207-433637d3ba74)
---
```ts
const A = object({
	x: string(),
});

const B = object({
	x: boolean(), // works fine with "same name but different type" field
	y: number(),
});

const C = union([A, B]);

safeParse(C, { x: "foo", y: 1 });
```
```ts
{
	"typed": true,
	"success": true,
	"data": { x: "foo", "y": 1 }
	"output": { x: "foo", "y": 1 }
}
```
---
```ts
const A = object({
	x: string(),
	y: number(),
});

const B = object({
	x: string(),
	y: number(),
	z: boolean(),
});

const C = union([A, B]);

safeParse(C, { x: "foo", y: 1, z: true });
```
```ts
{
	"typed": true,
	"success": true,
	"data": { "x": "foo", "y": 1 },
	"output": { "x": "foo", "y": 1 }
}
```

**Comment by fabian-hiller** [comment]
This is expected and not a bug. The "problem" is in this case that `object` ignores and removes unknown entries by default. That's why the validation of `A` is also successful with `{ x: "foo", y: 1 }` as input. You can change this behavior by making the validation of `object` strict with the rest argument. More information can be found here: https://valibot.dev/guides/objects/

```ts
import * as v from 'valibot';

const A = v.object({ x: v.string() }, v.never());

const B = v.object({ x: v.string(), y: v.number() }, v.never());

const C = v.union([A, B]);
```

**Comment by FujishigeTemma** [comment]
Thank you @fabian-hiller for your quick response! I finally understand how do they work.

Can I ask about one more thing? As you kindly suggested, if I add `never()` for one of objects, the code below worked perfect.
```
const A = object(
	{
		x: string(),
	},
	never(),
);

const B = object(
	{
		x: string(),
		y: number(),
	},
);

const C = union([A, B]);
```

But if I add `never()` to both of them,`y` is dropped from inferred type again (parse result is OK). Is this also expected?
```
const A = object(
	{
		x: string(),
	},
	never(),
);

const B = object(
	{
		x: string(),
		y: number(),
	},
	never(),
);

const C = union([A, B]);
```
![image](https://github.com/fabian-hiller/valibot/assets/49122148/a91e928f-53d6-41a5-ba1a-9dfe3c035baa)

**Comment by fabian-hiller** [comment]
This is a bug, but I checked the implementation and it seems that TypeScript is the problem here. There is no difference between `undefined` and `never()` for the rest argument in our implementation.

```ts
import * as v from 'valibot';

const A = v.object({ x: v.string(), y: v.number() });
type TA = v.Output<typeof B>; // { x: string; y: number; }

const B = v.object({ x: v.string(), y: v.number() }, v.never());
type TB = v.Output<typeof B>; // { x: string; y: number; }
```

But I found a workaround. By making the argument read-only using `as const`, TypeScript resolves the type correctly.

```ts
import * as v from 'valibot';

const A = v.object({ x: v.string() }, v.never());

const B = v.object({ x: v.string(), y: v.number() }, v.never());

const C = v.union([B, A] as const); // <--

type TC = v.Output<typeof C>; // { x: string; } | { x: string; y: number; }
```

**Comment by FujishigeTemma** [comment]
I see. Thank you!
