### ISSUE TITLE
Support non-string array in `picklist`

### ISSUE THREAD

**Issue by hyunbinseo** [fabian-hiller/valibot#378]
According to the [docs](https://valibot.dev/guides/enums/), `picklist` does not seem to limit the element's type.

> For a set of values represented by an array, you can use the `picklist` schema function. 

```ts
import * as v from 'valibot';

const Index = [0, 3, 7] as const; // readonly [0, 3, 7]
const IndexSchema = v.picklist(Index); // Error ts(2345)
```

However, passing a number array shows the following error.

> Type `readonly [0, 3, 7]` is not assignable to type `readonly string[]`.

**Comment by fabian-hiller** [comment]
Thank you for reporting this issue. I will review and improve the documentation. What is your use case for using numbers? Maybe we should extend `picklist` to all primitive literal values.

**Comment by hyunbinseo** [comment]
I am currently using this type guard inside my application

```ts
export const grades = [1, 2, 5, 6] as const;
export type Grade = (typeof grades)[number];
export const isValidGrade = (grade: number): grade is Grade => grades.includes(grade as Grade);
```

When validating the submitted form data, this is the best I have replicated.

```ts
coerce(number([custom(isValidGrade)]), Number);

const grade = parsed as Grade; // type casting is required.
```

**Comment by fabian-hiller** [comment]
Maybe an `union` is the right choices in your use case:

```ts
import * as v from 'valibot';

const Schema = v.union([
  v.literal(1),
  v.literal(2),
  v.literal(5),
  v.literal(6),
]);
```

**Comment by fabian-hiller** [comment]
I will nevertheless investigate whether it makes sense to extend `picklist`.
