### ISSUE TITLE
customAsync not resolved inside issues? 

### ISSUE THREAD

**Issue by cannap** [fabian-hiller/valibot#379]
Hi, i have this 

```ts
export const insertUserSchenma = objectAsync({
	id: string(),
	email: stringAsync([email(), customAsync(uniqueEmail, 'Email Adresse schon vorhanden')]),
	password: string([minLength(5, 'Die Minimum länge beträgt 5'), maxLength(254)]),
	username: string([
		regex(
			/^[A-Za-z0-9_-]{4,20}$/,
			'Der Benutzername ist ungültig. Er muss zwischen 4 und 20 Zeichen lang sein und darf nur Buchstaben, Zahlen, Unterstriche und Bindestriche enthalten.'
		)
	]),
	createdAt: date(),
	updatedAt: date()
});
```

```ts
export const uniqueEmail = async (email: string): Promise<boolean> => {
	const result = await db.query.userTable.findFirst({
		where: (userTable, { eq }) => eq(userTable.email, email)
	});

	return !result;
};
```

Then i safeParseAsync 

```ts
	const formData = await event.request.formData();
		const formValues: Pick<TInsertUserSchema, 'password' | 'username' | 'email'> = decode(formData);
		const parsedValues = await safeParseAsync(
			pickAsync(insertUserSchenma, ['username', 'password', 'email']),
			formValues
		);
```

This is how i handle the parsedValues 

```ts
	if (parsedValues.success) {
			const hashedPassword = await new Argon2id().hash(parsedValues.output.password);

			const userId = generateId(15);
			const currentDate = new Date();
			await db.insert(userTable).values({
				...parsedValues.output,
				id: userId,
				password: hashedPassword,
				createdAt: currentDate,
				updatedAt: currentDate
			});
			//return redirect(301, ' /');
			return;
		} else {
			console.log(parsedValues.issues);
			return fail(403, { message: 'Fail', issues: parsedValues.issues });
		}
```

The output from issues is: 

```ts
[
  {
    reason: 'string',
    validation: 'email',
    origin: 'value',
    message: 'Invalid email',
    input: 'fwefewfewfewfewfewf',
    requirement: /^[\w+-]+(?:\.[\w+-]+)*@[\da-z]+(?:[.-][\da-z]+)*\.[a-z]{2,}$/iu,
    path: [ [Object] ],
    abortEarly: undefined,
    abortPipeEarly: undefined,
    skipPipe: undefined
  },
  {
    reason: 'string',
    validation: 'custom',
    origin: 'value',
    message: 'Email Adresse schon vorhanden',
    input: 'xxxxxx',
    requirement: [AsyncFunction (anonymous)], <--- HERE why is this not resolved? did i do something wrong 
    path: [ [Object] ],
    abortEarly: undefined,
    abortPipeEarly: undefined,
    skipPipe: undefined
  }
]
```

since the asynction is not resolved 

Error: Data returned from action inside /signup **is not serializable: Cannot stringify a function (data..issues[0].requirement)**

did i miss something?

thanks

**Comment by fabian-hiller** [comment]
There is nothing wrong. The requirement for `custom` is the function passed as the first argument. See the [implementation](https://github.com/fabian-hiller/valibot/blob/v0.26.0/library/src/validations/custom/customAsync.ts#L15). For the `email` validation it is a regex instead. Why are you passing the whole issues to the client? I recommend formatting the issues and only passing what the client really needs.

**Comment by cannap** [comment]
oh you are right i dont know i pass the whole thing back i need to format it thanks

**Comment by fabian-hiller** [comment]
You can also use `flatten` to format the output. Read more about this [here](https://valibot.dev/guides/issues/#formatting). If your client only needs the error message, I recommend passing only that part of the issue. I plan to add another utility function that converts issues into more meaningful error messages.

**Comment by cannap** [comment]
yea thank you i will try it and look later what i really need

**Comment by cannap** [comment]
I have other question as example ich have 


sharedValidation.ts

export const insertUserSchenma = objectAsync({
	id: string(),
	password: string([minLength(5, 'Die Minimum länge beträgt 5'), maxLength(254)]),
	username: string([
		regex(
			/^[A-Za-z0-9_-]{4,20}$/,
			'Der Benutzername ist ungültig. Er muss zwischen 4 und 20 Zeichen lang sein und darf nur Buchstaben, Zahlen, Unterstriche und Bindestriche enthalten.'
		)
	]),
	createdAt: date(),
	updatedAt: date()
});

on client.js i use this pure sharedValidation


on server 

i want to add this check 

email: stringAsync([email(), customAsync(uniqueEmail, 'Email Adresse schon vorhanden')]),

since the uniqueEmail code is not possible to run on client

how can i do that i looked for extend or something but cannot find 

thanks

**Comment by fabian-hiller** [comment]
I think I would not add `uniqueEmail` to the schema in this case. I would probably parse the schema and then check the email for uniques.

**Comment by cannap** [comment]
ok then i will do it since i work with superforms this will be easy :D
