### ISSUE TITLE
Is there a way to quickly compare schemas for equality?

### ISSUE THREAD

**Issue by vicimpa** [fabian-hiller/valibot#382]
Good afternoon. Is there any way to quickly compare schemes on eual? 
Type:
```ts
const schemaA = object({
 name: string(),
 age: number()
})

const schemaB = object({
 name: string(),
 age: number()
})

const schemaC = object({
 name: string(),
 age: number(),
 date: date()
})

schemaA.isEqual(schemaB) // true
schemaA.isEqual(schemaC) // false
schemaC.isEqual(schemaA) // false
```

This may be necessary to implement a strongly typed data store. For example localStorage or a text settings file.

**Comment by fabian-hiller** [comment]
Thank you for creating this issue. Why is it necessary to compare two schemas in this use case? In this case the schemas are known and you know whether they are the equal.

**Comment by vicimpa** [comment]
For example my prototype store:
```ts
import { BaseSchema, parse } from "valibot";

const MAPPED_SCHEMA = new Map<string, BaseSchema>();

export const valistore = <T>(
  key: string,
  schema: BaseSchema<T>,
  initial: T
) => {
  if (MAPPED_SCHEMA.has(key)) {
    if (MAPPED_SCHEMA.get(key) !== schema)
      throw new Error(`Key alerdy used another schema`);
  } else {
    MAPPED_SCHEMA.set(key, schema);
  }

  var isInit = false;
  var value!: T;

  return ({
    get value(): T {
      if (isInit)
        return value;

      try {
        const data = localStorage.getItem(key) ?? '';
        return value = parse(schema, JSON.parse(data));
      } catch (e) {
        return this.value = value = initial;
      } finally {
        isInit = true;
      }
    },
    set value(value: T) {
      const json = JSON.stringify(parse(schema, value));
      localStorage.setItem(key, json);
    }
  });
};
```

For using:
```ts
const myStore = valistore('MY_STORE_KEY', boolean(), false);
myStore.value = true;
```

I want give exception for using key for another schema:
```ts
const myStore1 = valistore('MY_STORE_KEY', boolean(), false); // This ok
const myStore2 = valistore('MY_STORE_KEY', string(), 'Default string'); // This except
```

Since most custom schemas are used as expressions, you need to implement validation. In the example above, I'm simply comparing the schema, hoping to use the same schemas based on identifiers, but this is a "temporary patch"

**Comment by fabian-hiller** [comment]
Do you want to restrict the type of schemas that can be passed to `valistore'? If so, you can make it type safe by using `BooleanSchema` instead of `BaseSchema`.

**Comment by vicimpa** [comment]
No. I don't need restrictions.

**Comment by fabian-hiller** [comment]
Were you able to find a workaround? You can also write your own `equal` function. Each schema returns an object with information that you can compare.

**Comment by vicimpa** [comment]
I am trying later =)

**Comment by fabian-hiller** [comment]
At the moment I don't think this is a feature I have time to work on. So I am closing this issue. If more people request this, I will reconsider my decision.
