### ISSUE TITLE
Unhelpful parsing error

### ISSUE THREAD

**Issue by pihentagy** [fabian-hiller/valibot#384]
If you omit mandatory attributes or provide string instead of object, you get an unhelpful message:

Even when you have `Uncaught ValiError: Invalid email`, it should state what's the problem with email.

```
> import {email, minLength, array, literal, number, object, optional, parse, string, Output} from 'https://deno.land/x/valibot/mod.ts';
undefined
> const LoginSchema = object({
  email: string([email()]),
  password: string([minLength(8)]),
});
undefined
> parse(LoginSchema, { });

Uncaught ValiError: Invalid type
    at parse (https://deno.land/x/valibot@v0.26.0/src/methods/parse/parse.ts:20:11)
    at <anonymous>:1:22
> parse(LoginSchema, {email:'', password:'' });

Uncaught ValiError: Invalid email
    at parse (https://deno.land/x/valibot@v0.26.0/src/methods/parse/parse.ts:20:11)
    at <anonymous>:1:22
> parse(LoginSchema, '{}');

Uncaught ValiError: Invalid type
    at parse (https://deno.land/x/valibot@v0.26.0/src/methods/parse/parse.ts:20:11)
    at <anonymous>:1:22
> 
```

**Comment by fabian-hiller** [comment]
The default error messages of Valibot are minimal to keep the package size as small as possible. But every issue that Valibot returns contains all the details to create custom error messages with more details. Also, with our new i18n feature, it will be possible to pass an error message generation function to customize the messages to your needs. Read more about issues here: https://valibot.dev/guides/issues/

**Comment by pihentagy** [comment]
Ok, so the way is:

```ts
try {
  parse(LoginSchema, {password:"abcdefgh"}); // Throws an error
} catch (error) {
  console.log(flatten<typeof ObjectSchema>(error));
}
```

```text
{ nested: { email: [ "Invalid type" ] } }
```

Still would like to be more verbose and see what it parsed, and what it got instead. Or maybe a verbose global switch, which exposes all details by default.

Compare this with zod:

```text
ZodError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "email"
    ],
    "message": "Required"
  }
]
```

That one truly contains every piece of information!

**Comment by fabian-hiller** [comment]
Valibot should reveal more information than Zod. The problem is your code. Try the following:

```ts
try {
  parse(LoginSchema, {password:"abcdefgh"}); // Throws an error
} catch (error) {
  console.log(error.issues);
}
```

**Comment by pihentagy** [comment]
Thanks, that helped. I wonder if I can obtain this information without having to write a custom catch clause for every call of `parse`. Is it possible?

```
[
  {
    reason: "type",
    validation: "string",
    origin: "value",
    message: "Invalid type",
    input: undefined,
    path: [
      {
        type: "object",
        input: { password: "abcdefgh" },
        key: "email",
        value: undefined
      }
    ],
    issues: undefined,
    abortEarly: undefined,
    abortPipeEarly: undefined,
    skipPipe: undefined
  }
]
```

**Comment by fabian-hiller** [comment]
Yes, this is possible with our non-exception-based API `safeParse`. Read more about parsing data here: https://valibot.dev/guides/parse-data/

**Comment by pihentagy** [comment]
And what if throwing is fine for me?

**Comment by fabian-hiller** [comment]
Then I recommended sticking with `parse`. If you have ideas for a better API, I would be happy if you could share them with us.

**Comment by pihentagy** [comment]
I guess you optimise for speed, that's why the error is unprintable by default. Am I right?

Or I don't know, since there is a switch for short-circuiting validation after the first error.

I guess there are 2 cases:
- I don't care about runtime cost, show me all errors at once, help me as much as you can (developer mode)
- I care somewhat about performance, so one error at a time is okay, but still need precise error location (production mode)

The setting could be global IMHO.

What do you think? Or what other opinions did you encounter?

**Comment by fabian-hiller** [comment]
The main focus of Valibot is bundle size, type safety and developer experience. For performance, we try to get the maximum out of our API design.

I think the behavior you describe can be controlled with `abortEarly` and `abortPipeEarly`. This can be configured when calling `parse` or `safeParse`. At the moment this is not globally configurable, but we may change that.

**Comment by pihentagy** [comment]
For me, some other flag is needed, like verbose. So that a "plain" throws shows all details

**Comment by fabian-hiller** [comment]
What exactly do you expect the functions to return? Can you give a concrete code example?

**Comment by pihentagy** [comment]
I'd like to call `MySchema.parse(input)`, not add any "extra" catch block and see it in the stacktrace what was the problem.

So something like:
```
Expected field email to be "string" but got "undefined
```
Not necessary in English, could be an AST like message, but contains
- error path
- validation rule, that failed
- the out of bound value (or any other proof how it is not valid)

**Comment by fabian-hiller** [comment]
You can do the following:

```ts
import * as v from 'valibot';

const issue = v.safeParse(MySchema).issues?.[0];
const message = issue?.message;
```

**Comment by pihentagy** [comment]
I can tuck into a custom function (but that's a workaround), but what I expected from the library:
- get out of my way (so just `const result = v.parse(MySchema)` and consume result)
- include all details it the rare case when validation fails (getting just `Uncaught ValiError: Invalid type` is not fine, when it could have at least missing attribute)

**Comment by fabian-hiller** [comment]
So basically you are only interested in the first issue and don't want to write `.issues?.[0]` because you see it as a workaround, right? Maybe we can add a function for you that only returns the first issue. Do you have any ideas for the name?

**Comment by pihentagy** [comment]
I'd like to call `MySchema.parse(input)`, not add any "extra" catch block and see it in the stacktrace what was the problem. IMHO it does not need extra method, just a custom `toString` implementation.

So something like:
```
Expected field email to be "string" but got "undefined"
```
Not necessary in English, could be an AST like message, but contains
- error path
- validation rule, that failed
- the out of bound value (or any other proof how it is not valid)

**Comment by fabian-hiller** [comment]
I plan to improve the error messages. You can find more info in #397.

**Comment by fabian-hiller** [comment]
I think that with the expansion of the issue information and the improvement of our error messages in #397, this issue has been resolved.

**Comment by dgreensp** [comment]
I came across this issue of unexpectedly poor error messages after using Valibot for about 15 minutes.  It is telling me the type of error—for example, "Expected string but received undefined"—but not the key/path.  So apparently error messages used to be worse, based on what I'm reading here, but the repeated request in this thread was to include the path in the message by default, and that seems to have gone unaddressed?  Because of fear of making the bundle too big?

Anyway, I don't mind using a wrapper function in my codebase, so in case anyone else wants one, or has suggestions, here is what i came up with, now having used Valibot for about 50 minutes total, including reading docs and GitHub issues (the following is in the form of Deno/TypeScript code):

```ts
import {
  BaseSchema,
  BaseIssue,
  InferOutput,
  safeParse,
  flatten,
} from "jsr:@valibot/valibot";

export function validate<
  const TSchema extends BaseSchema<unknown, unknown, BaseIssue<unknown>>
>(schema: TSchema, input: unknown): InferOutput<TSchema> {
  const result = safeParse(schema, input);
  if (result.issues) {
    const { root, nested, other } = flatten(result.issues);
    const nestedKeys = nested && Object.keys(nested);
    if (root) {
      throw new Error(root[0]);
    } else if (nested && nestedKeys?.length) {
      const dotPath = nestedKeys[0];
      throw new Error(nested[dotPath]![0] + " (at path: " + dotPath + ")");
    } else {
      throw new Error(other![0]);
    }
  } else {
    return result.output;
  }
}
```

So now if you are trying to validate an object that is supposed to have `asdf: string` but doesn't, you will get:

```
Error: Invalid type: Expected string but received undefined (at path: asdf)
```

instead of:
```
Error: Invalid type: Expected string but received undefined
```

I don't know why this is such a big deal to build into Valibot, but there you have it, folks!

**Comment by dgreensp** [comment]
Oh, even better:

```ts
import {
  BaseSchema,
  BaseIssue,
  InferOutput,
  safeParse,
  getDotPath,
} from "https://deno.land/x/valibot@v0.42.1/mod.ts";

export function validate<
  const TSchema extends BaseSchema<unknown, unknown, BaseIssue<unknown>>
>(schema: TSchema, input: unknown): InferOutput<TSchema> {
  const result = safeParse(schema, input);
  if (result.issues) {
    const firstIssue = result.issues[0];
    let message = firstIssue.message;
    const dotPath = getDotPath(firstIssue);
    if (dotPath) {
      message += " (at path: " + dotPath + ")";
    }
    throw new Error(message);
  } else {
    return result.output;
  }
}
```

Maybe you could even add something like this to the `ValiError` constructor?

Instead of `super(issues[0].message)`, something like:

```ts
let message = issues[0].message;
const dotPath = getDotPath(issues[0];
if (dotPath) {
  message += " (at path: " + dotPath + ")";
}
super(message);
```

**Comment by fabian-hiller** [comment]
I don't think we should add the path to the error message by default. This is because some libraries, like form libraries, already display the error message at the respective field and showing a path by default would be very confusing. But Valibot provides all necessary information to format the error messages afterwards to add such information.

You can either flatten the issues with our `flatten` method to create a flat object containing dot paths as keys, or you can format the issues on your own to, for example, append the path to the error messages. Here is how I would write it:

```ts
import * as v from 'valibot';

const Schema = v.object({
  email: v.pipe(v.string(), v.email()),
  password: v.pipe(v.string(), v.minLength(8)),
});

const result = v.safeParse(Schema, {
  email: 'jane@example.com',
  password: '1234567',
});

if (result.issues) {
  const formattedIssues = result.issues.map((issue) => {
    if (issue.path) {
      return {
        ...issue,
        message: `${issue.message} at path "${v.getDotPath(issue)}"`,
      };
    }
    return issue;
  });
  // More code here...
}
```

Try it out in our [playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgGUmALAUxDI4AXkwA6CBQBWfJjAAUAb3pw4A5MFIAucWGBg+8jGI5RgrAObyAlABpx6zTbsq4YNKgDu0ACY7jegZGJjBmljb2xiDmADJ8ljA88gAc1i4AvtYMzGwccFB8qACupPCixqjI2HwACshQqIbc-IL2yqqO2kRSyKx8AAJ8AB7I4KR8YiwghLau7qhevjqEAIwATADMACwArABsAOwz9JnZwNhw8gXFpWLAC0WF1nDtcCzs8NjQgjAwfD4ASQehRE+UKJRgd2BqDEgjA8nk92KfGewgAfC9XKpzpckY8xO5Es9XqpVAUYEUoKxMaTaXAxAy8XxZnTSSBCpULHwdAADAAkiiZsI5yC56RQ8EJPDgACIBcYuTAACLUOqJRHA6zpGU8ll09IMWnpLFgilUuBMw1wU6ud6oCDjMR8KB4KDyL5QH5-QHQrInehAA)!

Hint: If you only care about the first error you should set the `abortEarly` option of `parse` or `safeParse` to `true` to improve performance.
