### ISSUE TITLE
[Custom] How to match valibot custom to zod custom in this case bellow

### ISSUE THREAD

**Issue by harrytran998** [fabian-hiller/valibot#39]
Hi @fabian-hiller, your libs are amazing! But can you share with me how to custom property in an object like Zod does?

I have a generic typing function like this

```ts
export const baseQuerySchema = <T>() =>
  object({
    order: custom<`${string & keyof T}:${"asc" | "desc"}`>((val) =>
      /\w+:(asc|desc)/.test(val as string),
    ),
    pageSize: optional(transform(useDefault(string(), "20"), (v) => parseInt(v, 10))),
    pageIndex: optional(transform(useDefault(string(), "0"), (v) => parseInt(v, 10))),
  })
  ```

How can I transform `order` filed to valibot 😆 The typescript compiler complains

```bash
No overload matches this call.
  Overload 1 of 2, '(object: ObjectShape, pipe?: Pipe<{ [x: string]: any; }>): ObjectSchema<ObjectShape, { [x: string]: any; }>', gave the following error.
    Type '(input: `${string & keyof T}:asc` | `${string & keyof T}:desc`, info: ValidateInfo) => `${string & keyof T}:asc` | `${string & keyof T}:desc`' is not assignable to type 'BaseSchema<any, any>'.
  Overload 2 of 2, '(object: ObjectShape, error?: string, pipe?: Pipe<{ [x: string]: any; }>): ObjectSchema<ObjectShape, { [x: string]: any; }>', gave the following error.
    Type '(input: `${string & keyof T}:asc` | `${string & keyof T}:desc`, info: ValidateInfo) => `${string & keyof T}:asc` | `${string & keyof T}:desc`' is not assignable to type 'BaseSchema<any, any>'.ts(2769)
```

Thanks for reading this!

**Comment by fabian-hiller** [comment]
With Valibot you have to use [`special`](https://github.com/fabian-hiller/valibot/blob/main/library/src/schemas/special/special.ts) because [`custom`](https://github.com/fabian-hiller/valibot/blob/main/library/src/validations/custom/custom.ts) is already reserved for custom validations. [`special`](https://github.com/fabian-hiller/valibot/blob/main/library/src/schemas/special/special.ts) works similar to `z.custom` in Zod.

**Comment by harrytran998** [comment]
Humm, seeming the`special` function is not well enough in typing.

```
export const baseQuerySchema = <T>() =>
  object({
    order: special<`${string & keyof T}:${"asc" | "desc"}`>((val) =>
      /\w+:(asc|desc)/.test(val as string),
    ),
    pageSize: optional(transform(useDefault(string(), "20"), (v) => parseInt(v, 10))),
    pageIndex: optional(transform(useDefault(string(), "0"), (v) => parseInt(v, 10))),
  });

export type BaseQueryModel = Output<ReturnType<typeof baseQuerySchema>>;
```
The `order` property turn to `never` 😆

![image](https://github.com/fabian-hiller/valibot/assets/24296018/b2508612-37fe-44aa-9dc0-5e4955351940)

Hope you can check this.

**Comment by fabian-hiller** [comment]
It should not be like that. I will investigate this as soon as I find time. Thank you very much for the hint.

**Comment by fabian-hiller** [comment]
I think the problem is your code or TypeScript. I can't find any error in Valibot's code. If you change the generic of your function to `T extends Record<string, any>` for example, the type will be displayed correctly.

**Comment by harrytran998** [comment]
Hmm - seem weird 😆. It worked when I put  `T extends Record<string, any or unknow>`.  With Zod everything ok 🤔.  FYI, I use TS v5.1.6.

**Comment by fabian-hiller** [comment]
Is this issue resolved? Do you have any questions? Is there anything Valibot can do better at this point? Thank you for your contribution!

**Comment by harrytran998** [comment]
Yeah, this was resolved! Thank for your kind response 😆.
