### ISSUE TITLE
Add resolver for react-hook-form

### ISSUE THREAD

**Issue by NixBiks** [fabian-hiller/valibot#4]
Looks great. Congrats with the initial release. 

I bet it would be a good idea to add a [resolver for react-hook-form](https://github.com/react-hook-form/resolvers) - helpful to gain additional traction I think.

**Comment by fabian-hiller** [comment]
I will have a look at it as soon as I have time. If someone wants to help with this, just contact me here.

**Comment by lucaschultz** [comment]
> If someone wants to help with this, just contact me here.

I could take a look later today

**Comment by fabian-hiller** [comment]
Thank you @lucaschultz! Have a look at the [`ValiError`](https://github.com/fabian-hiller/valibot/blob/main/library/src/error/ValiError/ValiError.ts) class and maybe it helps to have a look at the [adapter](https://github.com/fabian-hiller/modular-forms/blob/main/packages/react/src/adapters/valiForm.ts) I built for Modular Forms. If needed you can use [`flatten`](https://github.com/fabian-hiller/valibot/blob/main/library/src/error/flatten/flatten.ts) to convert the errors to a dot path object.

**Comment by lucaschultz** [comment]
Okay, I got a prototype working. Have a look at [this file](https://github.com/src/lib/utils/valibotResolver.ts) for the source and [this file](https://github.com/lucaschultz/valibot-resolver-playground/blob/main/src/app/ExampleForm.tsx) to see it in action. I'm using it very similar to how I would use a Zod schema including importing it as `v`. You can play around with the deployed version [here](https://valibot-resolver-playground.vercel.app/). Of course the idea is to add it to the [hook form resolvers](https://github.com/react-hook-form/resolvers). But I needed a playground first. 

I was wondering about the `issues` property of the [`ValiError`](https://github.com/fabian-hiller/valibot/blob/main/library/src/error/ValiError/ValiError.ts). Does it contain sub issues? It does not seem to be used when e.g. a string fails multiple validations? 

Also:

- Does Valibot support preprocessing and/or refinements?
- Does it support catchall schemas on objects?
- The default error messages don't really lend themselves as validation messages. Zod has the concept of custom error maps which we use at work to get validation messages from out language files. Is there such a concept yet or do all the messages have to be defined alongside the *form schema*?

Sorry for the questions. I had no time to have a closer look at the source. Great work on Valibot 😊

**Comment by fabian-hiller** [comment]
[Here](https://github.com/lucaschultz/valibot-resolver-playground/blob/22191a0385a1002bf7ea93784ffd2579a9e494f1/src/lib/utils/valibotResolver.ts#L9) I would, to be on the safe side, not use a wildcard import, because I don't know if every bundler can still split the code.

[Here](https://github.com/lucaschultz/valibot-resolver-playground/blob/22191a0385a1002bf7ea93784ffd2579a9e494f1/src/lib/utils/valibotResolver.ts#L60-L62) you can simplify the code and change it to the following. Normally I recommend not to use `schema.parse` because it is an internal API of Valibot. But in this use case it is ok to reduce the code and the bundle size.

```ts
const data = await schema.parse(values);
```

**Comment by fabian-hiller** [comment]
> I was wondering about the issues property of the ValiError. Does it contain sub issues?

This could be related with issue #18. What behavior from Valibot would you expect here. I think by default Valibot behaves almost the same as Zod here.

> Does Valibot support preprocessing and/or refinements?

Yes, preprocessing with `coerce` and refinements with our [pipeline feature](https://valibot.dev/guides/schemas/#pipelines) eg. with `custom` or any custom code.

> Does it support catchall schemas on objects?

No, not yet. You are welcome to create an issue for this feature.

> The default error messages don't really lend themselves as validation messages. Zod has the concept of ...

Currently Valibot does not support this yet. Please create a new issue and send me a pseudo sample code with your desired API.

**Comment by fabian-hiller** [comment]
@lucaschultz thanks a lot for working on the React Hook Form resolver 💙

**Comment by fabian-hiller** [comment]
@lucaschultz are there any updates about the resolver for React Form Hook?

**Comment by lucaschultz** [comment]
I'll have some time on my hands tomorrow and continue working on it 🙂

**Comment by joaopedrodcf** [comment]
Just new about this library a few days ago this would make its usage skyrocket for sure with a resolver for react-hook-form great work with it 🥇

**Comment by lucaschultz** [comment]
@fabian-hiller, it looks like someone else was quicker in opening a [pull request](https://github.com/react-hook-form/resolvers/pull/602).

The resolver has already been released. 🎉
