### ISSUE TITLE
building object based on options

### ISSUE THREAD

**Issue by doomedramen** [fabian-hiller/valibot#402]
```ts
const base = v.object({
  alwaysHere: v.string(),
  alsoAlwaysHere: v.number(),
});

const productA = v.object({
  specificToProductA: v.number(),
  // ... other things specific to this product
});

const productB = v.object({
  specificToProductB: v.number(),
  // ... other things specific to this product
});

const productC = v.object({
  specificToProductC: v.number(),
  // ... other things specific to this product
});


```

# situation
I am doing form validation with Valibot and react-hook-form

# wanted behaviour
user selects that they want product A and product B.

the schema needs to include `base` as default as well as any items from the products they have selected (A and B in this example).
all of which are required (not optional).

Worst case scenario I am happy having all items from all products in the final schema but just the ones from the selected products (A + B) be required (the rest optional).

I also need to be able to inter TS types.

**Comment by fabian-hiller** [comment]
Thank you for using Valibot. Here is one possible solution:

```ts
import * as v from 'valibot';

const BaseSchema = v.object({
  alwaysHere: v.string(),
  alsoAlwaysHere: v.number(),
});

const VariantSchema = v.variant('type', [
  v.merge([
    BaseSchema,
    v.object({ type: v.literal('a'), specificToProductA: v.number() }),
  ]),
  v.merge([
    BaseSchema,
    v.object({ type: v.literal('b'), specificToProductB: v.number() }),
  ]),
  v.merge([
    BaseSchema,
    v.object({ type: v.literal('c'), specificToProductC: v.number() }),
  ]),
]);
```

Read more about unions in the docs: https://valibot.dev/guides/unions/

**Comment by fabian-hiller** [comment]
Yes, but you can of course change the schema to also reflect this use case. Reach out if you need help.

**Comment by doomedramen** [comment]
That is where I have been struggling to determine which parts of valibot to use to achieve.

the real-world use case is that on the web page i know what options the user has previously selected (provided by the backend) and so I need the schema to adjust to those options (combination of product a, be and or c).

any links or help you could provide would be very beneficial.

Thank you

**Comment by fabian-hiller** [comment]
How would you represent the type for this in TypeScript?

**Comment by doomedramen** [comment]
The best ts example I could come up with is:

annoyingly its easier to do in typescript than zod;

interface ProductA {
  guestDamage: boolean;
}

interface ProductB {
  homeRepair: boolean;
}

interface ProductC {
  legalAssistance: boolean;
}

type ItemMap = {
  productA: ProductA;
  productB: ProductB;
  productC: ProductC;
};

const wantedItems = ["productA", "productB"] as const;

type CombinedItems = {
  [K in (typeof wantedItems)[number]]: K extends keyof ItemMap
    ? ItemMap[K]
    : never;
}[(typeof wantedItems)[number]];

// Usage example
const combinedProduct: CombinedItems = {
  guestDamage: true,
  homeRepair: true,
};

**Comment by fabian-hiller** [comment]
If I understand your code correctly `CombinedItems` is an union between `ProductA` and `ProductB`.

```ts
type CombinedItems = ProductA | ProductB;
```

Here is the example from above but instead of `variant` we are using `union`.

```ts
import * as v from 'valibot';

const BaseSchema = v.object({
  alwaysHere: v.string(),
  alsoAlwaysHere: v.number(),
});

const UnionSchema = v.union([
  v.merge([
    BaseSchema,
    v.object({ type: v.literal('a'), specificToProductA: v.number() }),
  ]),
  v.merge([
    BaseSchema,
    v.object({ type: v.literal('b'), specificToProductB: v.number() }),
  ]),
  v.merge([
    BaseSchema,
    v.object({ type: v.literal('c'), specificToProductC: v.number() }),
  ]),
]);
```

**Comment by doomedramen** [comment]
This is looking much closer, thank you.

unless I am misunderstanding that would still force the resulting schema to be ether a, b OR c. no combination of the 3:


e.g.

import * as v from "valibot";

const BaseSchema = v.object({
  alwaysHere: v.string(),
  alsoAlwaysHere: v.number(),
});

const ProductASchema = v.object({
  type: v.literal("a"),
  specificToProductA: v.number(),
});
const ProductBSchema = v.object({
  type: v.literal("b"),
  specificToProductB: v.number(),
});
const ProductCSchema = v.object({
  type: v.literal("c"),
  specificToProductC: v.number(),
});

const UnionSchema = v.union([
  v.merge([BaseSchema, ProductASchema]),
  v.merge([BaseSchema, ProductBSchema]),
  v.merge([BaseSchema, ProductCSchema]),
]);

type Merged = v.Output<typeof UnionSchema>;

const thisWorks: Merged = {
  specificToProductA: 4,
  type: "a",
  alsoAlwaysHere: 4,
  alwaysHere: "",
};
const thisWorks2: Merged = {
  specificToProductB: 4,
  type: "b",
  alsoAlwaysHere: 4,
  alwaysHere: "",
};

const thisWorks3: Merged = {
  specificToProductC: 4,
  type: "c",
  alsoAlwaysHere: 4,
  alwaysHere: "",
};

const whatIWant: Merged = {
  type: ["a", "b"], //doesnt have to be written as this, but i need to conditionally get the types of 1-3 of the products
  specificToProductA: 4,
  specificToProductB: 2,
  alsoAlwaysHere: 1,
  alwaysHere: "some text",
};

const whatIWant2: Merged = {
  type: ["c", "a"], //doesnt have to be written as this, but i need to conditionally get the types of 1-3 of the products
  specificToProductA: 4,
  specificToProductB: 2,
  alsoAlwaysHere: 1,
  alwaysHere: "some text",
};


also, congratulations on the netlify backing.

**Comment by fabian-hiller** [comment]
I think I would stick with `variant` for this use case. I would create an object schema for each possible option with a specific discriminator key. This will make your data set accessible and maximally type-safe.

> I used `.entries` instead of `merge` because of #24

```ts
import * as v from 'valibot';

const BaseProductSchema = v.object({
  alwaysHere: v.string(),
});

const ProductASchema = v.object({
  ...BaseProductSchema.entries,
  specificToProductA: v.number(),
});

const ProductBSchema = v.object({
  ...BaseProductSchema.entries,
  specificToProductB: v.number(),
});

const ProductCSchema = v.object({
  ...BaseProductSchema.entries,
  specificToProductC: v.number(),
});

const VariantSchema = v.variant('type', [
  v.object({
    ...ProductASchema.entries,
    type: v.literal('a'),
  }),
  v.object({
    ...ProductBSchema.entries,
    type: v.literal('b'),
  }),
  v.object({
    ...ProductCSchema.entries,
    type: v.literal('c'),
  }),
  v.object({
    ...ProductASchema.entries,
    ...ProductBSchema.entries,
    type: v.literal('ab'),
  }),
  v.object({
    ...ProductASchema.entries,
    ...ProductCSchema.entries,
    type: v.literal('ac'),
  }),
  v.object({
    ...ProductBSchema.entries,
    ...ProductCSchema.entries,
    type: v.literal('bc'),
  }),
  v.object({
    ...ProductASchema.entries,
    ...ProductBSchema.entries,
    ...ProductCSchema.entries,
    type: v.literal('abc'),
  }),
]);
```

**Comment by doomedramen** [comment]
Fantastic, thank you for all your help
