### ISSUE TITLE
Superstruct?

### ISSUE THREAD

**Issue by shellscape** [fabian-hiller/valibot#403]
Hey there. A user of a package of mine stopped by and mentioned valibot. I started checking it out and couldn't help but notice that the implementation looks _a lot_ like superstruct, which has tended to stand on its own while zod, yup, et al prefer chained, verbose implementaitons.

Was there any inspiration drawn from superstruct for valibot?

**Comment by fabian-hiller** [comment]
Great question. I remember hearing about Superstruct before I implemented Valibot, but I could be wrong. Superstruct was not an inspiration when I implemented the library. I hadn't used Superstruct before and hadn't looked at its source code at the time.

As far as I can tell, only the definition of types e.g. with `string()` or `number()` is similar, the rest, e.g. Valibot's pipelines or the internal implementation seems to be completely different. Also Valibot's individual bundle sizes seams zu be smaller. Feel free to reach out if you have more questions.

**Comment by shellscape** [comment]
Thanks for that information. Zod and yup definitely need viable competition, and superstruct has not been able to be that project. Will do what I can to help boost valibot.

**Comment by fabian-hiller** [comment]
Thank you so much! This means a lot to me! Right now I am working full time on Valibot. Soon we will reach v1 and I also plan to put a lot of effort into documentation and education. I will work hard to grow the project 10x this year.
