### ISSUE TITLE
The forwardAsync method is not available

### ISSUE THREAD

**Issue by bertez** [fabian-hiller/valibot#412]
Although the forwardAsync method appears in the documentation and code, I believe it is not included in the latest build... or could I be mistaken about something? Thank you very much.

**Comment by fabian-hiller** [comment]
You a right! Thank you very much for creating this issue. I will fix that with the next version.

**Comment by fabian-hiller** [comment]
v0.28.0 is available

**Comment by bertez** [comment]
Thank you!!
