### ISSUE TITLE
Docs: Add ctrl + k hotkey for search to enable searching on windows (cmd is reserved)

### ISSUE THREAD

**Issue by Hugos68** [fabian-hiller/valibot#432]
It's common for websites to add a cmd + k hotkey to bring focus to the search of a website, I would like to see this on the valibot website too.

I am willing to take a stab at it, if that's ok, let me know!

Thanks for the amazing library.

**Comment by fabian-hiller** [comment]
This should be implemented already. Does it not work for you? It works for me. Here is the source code: https://github.com/fabian-hiller/valibot/blob/v0.28.1/website/src/components/DocSearch.tsx#L291

**Comment by Hugos68** [comment]
Ah, I see you are using the ``meta`` key that only works on mac, on windows the meta key is reserved for some windows popup, on windows it's common to use ctrl instead, I have implemented it like this (for different website):
```js
	function keydownHandler(event: KeyboardEvent) {
		if (event.key !== 'k' || !(event.ctrlKey || event.metaKey)) {
	            return;
		}
		event.preventDefault();
                searchDialog.open();
	}
```

**Comment by fabian-hiller** [comment]
Thank you for creating this issue! I will investigate and fix this!

**Comment by Hugos68** [comment]
Awesome, thank you for the quick response!

**Comment by Hugos68** [comment]
I've edited the issue to be more accurate (I wasn't aware it was already implemented at the time of creating the issue)

**Comment by fabian-hiller** [comment]
Can you check if it works on Windows now?

**Comment by Hugos68** [comment]
It works but you need to prevent the default, otherwise the browser will bring focus to the search bar:
![image](https://github.com/fabian-hiller/valibot/assets/63101006/f18309d9-f4fb-4ead-9da0-ebce624d3508)

**Comment by fabian-hiller** [comment]
Thanks for the hint. Unfortunately, I can't implement it at the moment. Our current Qwik version does not allow us to call `event.preventDefault()` in a fine-grained way. We can only call it for every keydown event, and that breaks the website. I will have to upgrade to the latest Qwik version first, but that will take a few weeks because other things are more important at the moment.

**Comment by fabian-hiller** [comment]
@Hugos68 can you check if this is fixed now?

**Comment by Hugos68** [comment]
@fabian-hiller Just checked, all works properly now, thanks!
