### ISSUE TITLE
[i18n] Add Dutch

### ISSUE THREAD

**Issue by Hugos68** [fabian-hiller/valibot#437]
I'd like to contribute the dutch language to i18n, since I'm a native dutch person. If this has already been done you can close this issue, if not, I'd gladly add it to valibot! If there is a list of currently supported languages please share it!

**Comment by fabian-hiller** [comment]
That would be great! Have a look at: https://github.com/fabian-hiller/valibot/blob/main/packages/i18n/README.md

**Comment by Hugos68** [comment]
Awesome, thanks for the guide

**Comment by Hugos68** [comment]
@fabian-hiller The develop branch seems to not have the i18n folder, should I start a PR that merges into main?

**Comment by Hugos68** [comment]
I've gone ahead and create one anyways so that it's atleast in git history somewhere haha: https://github.com/fabian-hiller/valibot/pull/438

**Comment by fabian-hiller** [comment]
Yes, please merge into main
