### ISSUE TITLE
Enable `v.recursive()` getter to accept a `value` to improving usage flexibility

### ISSUE THREAD

**Issue by Mini-ghost** [fabian-hiller/valibot#440]
We sometimes need to adjust schemas based on input values. 

[`yup.lazy()`](https://github.com/jquense/yup?tab=readme-ov-file#lazyvalue-any--schema-lazy) lets us do this by using a getter function to choose different schemas depending on the input type, as shown below:

```typescript
const node = yup.object({
  id: yup.number(),
  child: yup.lazy(() => node.default(undefined)),
});

let renderable = yup.lazy((value) => {
  switch (typeof value) {
    case 'number':
      return yup.number();
    case 'string':
      return yup.string();
    default:
      return yup.mixed();
  }
});

const renderables = yup.array().of(renderable);
```

This is great for flexible and dynamic schemas. I'm wondering if `valibot` is thinking about adding something similar for `recursive` methods, like this:

```typescript
const schema = v.recursive((value) => {
  switch (typeof value) {
    case 'number':
      return v.number();
    case 'string':
      return v.string();
    default:
      return v.any();
  }
});
```

This would make schemas even more flexible for complex data. If `valibot` is open to it, I'd love to help by contributing this feature.

**Comment by fabian-hiller** [comment]
@Mini-ghost do you have an opinion on renaming `recursive` to `lazy`? Do you have any other alternative ideas in mind?

**Comment by Mini-ghost** [comment]
I fully support this idea. 🙌

In fact, when I work on my projects, my initial instinct is to use `lazy`. However, it was only after consulting the documentation that I discovered the function name used in valibot is `recursive`. This initially seemed a bit unintuitive to me, so changing it to `lazy` would be excellent!

Regarding `switch` of `zod`, I haven't yet delved deeply into understanding it, so I will need some time to fully grasp its context."

**Comment by fabian-hiller** [comment]
As far as I understand it, `z.switch` seems to be exactly the same as `z.lazy`. I am currently planning to rename `recursive` to `lazy`. Thanks for your feedback on this.

**Comment by fabian-hiller** [comment]
Before renaming `recursive` to `lazy`, I'd like to know what your use case is for using `recursive` for a non-recursive schema, to investigate if your goal can be better achieved with another schema function of Valibot. It seems to me that the example above can be rewritten with `union`.

**Comment by Mini-ghost** [comment]
@fabian-hiller 

The example I provided was extracted from the documentation of yup.lazy, primarily to highlight the capability to adjust the schema based on the input.

In addition to the reasons mentioned in #441, I'd like to offer a real-world example for further clarification:

```ts
const order = {
  placeOfBirth: 'Taichung',
  idCard: 'B123456789'
}
```

In Taiwan, the first letter of the ID card number indicates the place of birth, hence different `placeOfBirth` values correspond to different `idCard` formats. If the getter of `v.recursive()` could accept parameters, then it could be written as follows:

```ts
const schema = recursive((input) => {
  if (input.placeOfBirth === 'Taipei') {
    return object({
      placeOfBirth: string(),
      idCard: string([custom((value) => /^A\d{9}$/.test(value), 'Should be A followed by 9 digits')])
    })
  } else if (input.placeOfBirth === 'Taichung') {
    return object({
      placeOfBirth: string(),
      idCard: string([custom((value) => /^B\d{9}$/.test(value), 'Should be B followed by 9 digits')])
    })
  } else {
    return object({
      placeOfBirth: string([minLength(1, 'Place of birth is required')]),
      idCard: string([minLength(1, 'ID card is required')])
    })
  }
})
```

This approach allows for the `idCard` format to be determined based on the value of `placeOfBirth`.

If the validation rules are defined dynamically based on the values being validated, I think the name `lazy` might be more intuitive in this context, as it suggests a sort of on-demand generation. I have reviewed the examples in the documentation and understand the rationale behind naming it `recursive`. Is there a possibility to either keep `recursive` or allow both names to coexist?

I hope this case study is helpful to you.

**Comment by fabian-hiller** [comment]
Thank you very much! I think your schema is better implemented with `variant`. However, I still see advantages and flexibility in a `lazy` schema in special cases.

```ts
import * as v from 'valibot';

const Schema = v.variant('placeOfBirth', [
  v.object({
    placeOfBirth: v.literal('Taipei'),
    idCard: v.string([
      v.regex(/^A\d{9}$/u, 'Should be A followed by 9 digits'),
    ]),
  }),
  v.object({
    placeOfBirth: v.literal('Taichung'),
    idCard: v.string([
      v.regex(/^B\d{9}$/u, 'Should be B followed by 9 digits'),
    ]),
  }),
  v.object({
    placeOfBirth: v.string([v.minLength(1, 'Place of birth is required')]),
    idCard: v.string([v.minLength(1, 'ID card is required')]),
  }),
]);
``

**Comment by Mini-ghost** [comment]
Thank you for your reply. I will look further into the method of `variant`, as it truly seems fantastic.

Additionally, if you decide to rename `recursive` to `lazy`, I would be happy to contribute to this change.

**Comment by fabian-hiller** [comment]
Thank you very much! Feel free to contact me if you have any questions on `variant`.
- https://valibot.dev/guides/unions/
- https://valibot.dev/api/variant/

I have already implemented the changes for renaming it to `lazy` since it is a lot of work in the documentation.

If you are familiar with Yup, you could write a [migration guide](https://valibot.dev/guides/migrate-from-yup/) similar to the one I wrote for [Zod](https://valibot.dev/guides/migrate-from-zod/).

**Comment by fabian-hiller** [comment]
v0.29.0 is available
