### ISSUE TITLE
Tree shaking is not performed on `RegExp` in Webpack

### ISSUE THREAD

**Issue by mxdvl** [fabian-hiller/valibot#447]
The regular expressions from `regex.ts` are not dropped by tree-shaking in Webpack.

[Sample built file](https://assets.guim.co.uk/assets/2412.client.web.51cf4e24ee56d7a7d96d.js), with its [associated source](https://github.com/guardian/dotcom-rendering/blob/fb0a370861e619f42b001090ec5304de935854eb/dotcom-rendering/src/lib/discussion.ts#L1-L19)

**Comment by fabian-hiller** [comment]
You are right. But that's a problem with the webpack configuration and not with Valibot, right?

**Comment by mxdvl** [comment]
There's nothing readily apparent, but I wondered if the lack of pure annotations prevented tree-shaking of literal regular expressions.

Let me do a reproduction repository with popular bundlers.

**Comment by mxdvl** [comment]
[Unable to reproduce with a basic Webpack setup](https://stackblitz.com/edit/mxdvl-valibot-webpack?file=dist%2Fmain.js)

**Comment by fabian-hiller** [comment]
Thank you for your research! Yes, it seems that there is nothing Valibot can do and the problem is related to `ts-loader` or Webpack.
