### ISSUE TITLE
Custom validator: what to put in expect and actionIssue arguments

### ISSUE THREAD

**Issue by crystalfp** [fabian-hiller/valibot#448]
Recompiling my application after long time gives errors on my custom validator (simplified):
```
const validateUuidWithSequence = (): BaseValidation<string> => {
  return {
    async: false,
    message: "Invalid UUID with sequence",
    expects: null,     // <------ what goes here?
    _parse(value: string) {
      if(value.length < 36) {
	  return actionIssue("custom", "Invalid UUID", value); // <----- What arguments?
      }
      return actionOutput(value);
    },
  };
};
```
Remember I changed "getPipeIssue" to "actionIssue" and this was working without problems, but now complains that "Expected 4-5 arguments, but got 3."

Also the "expect" return field was missing before, now putting here a null, solved the problem, but don't know if it is correct.

Maybe the more recent typescript version is more picky?

The versions in use are:
    "valibot": "^0.29.0",
    "typescript": "^5.3.3",

Thanks for looking!
mario

**Comment by fabian-hiller** [comment]
Here is the updated code. We changes some internal implementations.

```ts
import * as v from 'valibot';

function validateUuidWithSequence(): v.BaseValidation<string> {
  return {
    async: false,
    message: 'Invalid UUID with sequence',
    expects: null,
    _parse(value: string) {
      if (value.length < 36) {
        return v.actionIssue(this, validateUuidWithSequence, value, 'UUID');
      }
      return v.actionOutput(value);
    },
  };
}
``
