### ISSUE TITLE
Add possibility to convert entries to input types if possible

### ISSUE THREAD

**Issue by throrin19** [fabian-hiller/valibot#449]
Hello,

I'm using Joi and I try to migrate to valibot but it is one important feature I don't see in Valibot : Possibility to coerce directly all input part, not only for primitive or specific object.

I explain : In API validation, we have queryString : all value are seen as string but we use a schema declaring the types actually expected, even if everything is in string at the input. For example this is a type of schema : 

```js
const paginationSchema = Joi.object().keys({
    page     : Joi.number().integer().min(1).description('Current page'),
    pageSize : Joi.number().integer().min(5).description('Elements per pages'),
    search   : Joi.string().optional().description('Search criteria'),
    order    : Joi.array().items(Joi.array().items(Joi.string())).optional().description('ordering result'),
    lite     : Joi.boolean().default(false).description('False : return complete objects. True : return lite version'),
}).meta({ className : 'pagination' });
```

And queryString return this like : 

```js
{
    page : '0',
    pageSize: '25',
    lite: 'true'
}
```

- for Boolean we have `'1'`, `'0'`, `'true'`, `'false'`,
- for number we have `'123'`

I saw the `coerse` function but I want one thing made it automatically if we pass our schema in queryString part in our code: for example one schema can be used in query part, or other validation part, and for this, coerse is not required.

To make this with Joi, we just have to add option `{ convert : true }` to schema validation.

It is possible to made this ? If not maybe in the future ?

**Comment by fabian-hiller** [comment]
Thanks for creating this issue! No, Valibot does not provide an option to automatically coerce or transform string values into other data types. With Valibot you have to use `coerce` to transform a value before validation or `transform` to do the same afterwards.

**Comment by kibertoad** [comment]
@fabian-hiller Would you consider adding such functionality, though? Not having it severely limits usefullness of valibot for validating REST API requests.

**Comment by fabian-hiller** [comment]
How would you design the API for this? Feel free to share sample code (how you want to write the schema) with me. Keep in mind that this library follows a modular design.

**Comment by kibertoad** [comment]
all coercedX types first attempt the coercion based on the hardcoded rules, then validate the coercion result, then apply any more granular rules defined.

**Comment by kibertoad** [comment]
We've implemented a bunch of coercion rules in TS back in the day when zod didn't have any, feel free to reuse any of the code if it helps:
https://github.com/lokalise/zod-extras/tree/main/src/utils

**Comment by fabian-hiller** [comment]
This is already possible with `coerce`. Do you prefer your solution for DX reasons? Read more here: https://valibot.dev/guides/methods/#coerce

```ts
const UserSchema = object({
  age: v.coerce(v.number([toMinValue(8)]), Number),
  isEmployed: v.coerce(v.boolean(), Boolean),
  // ...
});
```

Note: I plan to remove `coerce` when merging #502. The reason for this is that `coerce` is insecure because the input can be anything. This can lead to bugs and security risks, especially when used by less experienced developers. The new API to accomplish the same goal will look like this:

```ts
const UserSchema = v.object({
  age: v.pipe(v.unknown(), v.transform(Number), v.toMinValue(8)),
  isEmployed: v.pipe(v.unknown(), v.transform(Boolean)),
  // ...
});
```

This approach requires that the input type be explicitly defined. If you know you will always expect a string, you should change the scheme to the following

```ts
const UserSchema = v.object({
  age: v.pipe(v.string(), v.transform(Number), v.toMinValue(8)),
  isEmployed: v.pipe(v.string(), v.transform(Boolean)),
  // ...
});
```

**Comment by kibertoad** [comment]
@fabian-hiller This is neat, thanks!
One use-case which this doesn't seem to cover is array coercing. When you are dealing with request params, and you receive an array of strings consisting of a single elements, frameworks will parse that as just string. In that case you can't define a string schema, your input might be a string (which you want to convert to an array with one element) or an array with 2+ elements (in which case you just accept it as-is.
Would it be possible to either skip first validation step or have a check for XorArrayOfX? And to have a transform for arrays which does nothing if already correct type?

**Comment by kibertoad** [comment]
Would `groups: v.pipe(v.unknown(), v.transform(Array)` work correctly for both arrays and strings?

**Comment by throrin19** [comment]
@fabian-hiller `coerce` works fine but I agree with you, it's insecure because it accept all possible value. I create functions `toBoolean`, `toNumber` to convert correctly only if source is string. Otherwise, I return the passed value to avoid unwanted conversion of type : For example, `Number(null)` return `0` and `Number(undefined)` return `NaN`
