### ISSUE TITLE
[i18n] equal is still present in translations

### ISSUE THREAD

**Issue by Ashyni** [fabian-hiller/valibot#474]
Hello, 
Equal validation is still present in all translations, which lead to potential issue when importing an entire language.
Can't find when it was actually being moved definitely to value.

```ts
import "@valibot/i18n/en";
```
```
@valibot+i18n@0.8.0_valibot@0.30.0/node_modules/@valibot/i18n/en/equal.js:1
import { setSpecificMessage, equal } from "valibot";
                             ^^^^^
SyntaxError: The requested module 'valibot' does not provide an export named 'equal'
```

**Comment by fabian-hiller** [comment]
Thank you very much! I will fix this in the version I will release today.
