### ISSUE TITLE
Union of literals

### ISSUE THREAD

**Issue by p-christ** [fabian-hiller/valibot#479]
Is this the only way to specify that something that can be 3 different literals?

```
union([literal('system'), literal('user'), literal('assistant')])
```

i'd quite like to do it like this instead, is it possible?

```
literal('system', 'user', 'assistant')
```

**Comment by xcfox** [comment]
You might be looking for [picklist](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgCUJSBTOALyYAdGGBMA1uQ4AKANqFUATw68QhADREArql5RNRNKmAdkrGgF0AlIxhKw-AJLc+gkQHltMMN4A89o4Q2HCuvAB8QA):
```ts
picklist(['system', 'user', 'assistant'])
```
