### ISSUE TITLE
Consider "ctx.addIssue" style rather than throwing ValiError

### ISSUE THREAD

**Issue by naruaway** [fabian-hiller/valibot#48]
Throwing errors is really expensive operation so even if we can make `parse` fast for "success" case, "failure" case will be still slow. This means if we use Valibot for server side validation logic, malicious people might be able to attempt DoS by sending "failure" payload.

I created this issue to discuss architectural / philosophical possibility to stop throwing ValiError without compromising other factors such as bundle size and code simplicity.

**Comment by fabian-hiller** [comment]
Thank you for this insight. Do you have an idea how the implementation could look like here? With a global object or array? Or a parameter that is passed through and modified directly?

**Comment by fabian-hiller** [comment]
Thank you for the code example! I will give it some thought.
