### ISSUE TITLE
Ability to extend existing declared schemas without redefining

### ISSUE THREAD

**Issue by saturnonearth** [fabian-hiller/valibot#482]
Going through converting from `zod` to `valibot` - and I love all the new primitives! I used to take existing zod schema's, and add onto them, like...

```ts
const schema = z.object({
  name: z.string();
});

const refinedSchema = schema.refine({...});
```

This does not seem possible with Valibot as you can't extend schemas once they are created, unless I am missing something?

You would need to do:

```ts
const schema = v.object({
  name: v.string();
});

const refinedSchema = v.object({
  ...schema.entries
}, v.custom(...));
```

This also affects working with Drizzle as you are to re-define the schema type instead of being able to "add on" to it, which could cause you trouble down the line if you are trying to keep one source of truth (being Drizzle).

For example:

zod-drizzle:
```ts
const insertUserSchema = createInsertSchema(users, {
  id: (schema) => schema.id.positive(),
  role: z.string(),
});
```

valibot-drizzle:
```ts
const insertUserSchema = createInsertSchema(users, {
  id: (schema) => v.number([v.minValue(0)]),
  role: v.string(),
});
```
Notice how with "id", you have to refine it as `v.number()` as opposed to just using `schema.id.number()`

Hopefully this makes sense?

**Comment by fabian-hiller** [comment]
I am not sure if I fully get it, but I think this proposal makes Valibot more composable, since the `pipe` function can be nested: https://github.com/fabian-hiller/valibot/discussions/463

**Comment by saturnonearth** [comment]
> I am not sure if I fully get it, but I think this proposal makes Valibot more composable, since the `pipe` function can be nested: #463

Ah yes! If you are able to do something like this:
```ts
const schema = v.pipe(
  v.object({
    name: z.string();
  });
);

const refinedSchema = v.pipe(schema, v.custom(...));
```

Then that'd be great - if I am understanding the proposal correctly.

**Comment by fabian-hiller** [comment]
Yes, this will be possible 🙌

**Comment by fabian-hiller** [comment]
I plan to publish a first version of the `pipe` function in about two or three weeks.
