### ISSUE TITLE
Allow errorMap (like zod) message for literal

### ISSUE THREAD

**Issue by ruiaraujo012** [fabian-hiller/valibot#489]
```ts
const PTFormSchema = v.object({
  codConcelho: v.string([v.minLength(1, 'required.county')]),
  codPais: v.literal('PT', 'required.country'),
  codigoPostal2: v.string([v.minLength(1, 'required.postalCode')]),
  concelhoEstrangeiro: v.unknown(),
});

const NotPTFormSchema = v.object({
  codConcelho: v.unknown(),
  codPais: v.string('required.country', [v.minLength(1, 'required.country')]),
  codigoPostal2: v.unknown(),
  concelhoEstrangeiro: v.string([v.minLength(1, 'required.county')]),
});

const FormSchema = v.variant('codPais', [PTFormSchema, NotPTFormSchema])
```

<img width="314" alt="image" src="https://github.com/fabian-hiller/valibot/assets/16304685/4d5bde85-b261-4f82-97da-a4d6c71e0de8">

**Comment by fabian-hiller** [comment]
We support advanced errors too but they work a bit differently. Have a look at this guide: https://valibot.dev/guides/internationalization/

```ts
import * as v from 'valibot';

v.setGlobalMessage((issue) => ...);
```

**Comment by fabian-hiller** [comment]
Please reach out if you can’t achieve your goal. I am happy to further improve the library.

**Comment by ruiaraujo012** [comment]
It's not the solution that I was looking for, because I would like to change the message for each case (if I have more), like "You need to choose a country" and in other cases "You need to choose a nationality". I would like to see an option to customize that message for the specific field.
Something like:
```ts
const PTFormSchema = v.object({
  codConcelho: v.string([v.minLength(1, 'required.county')]),
  codPais: v.literal('PT', 'required.country', {errorMap: () => 'My message'}), // It could be other format, like a cusom method ([v.errorMap(() => 'My message')])
  codigoPostal2: v.string([v.minLength(1, 'required.postalCode')]),
  concelhoEstrangeiro: v.unknown(),
});
```

**Comment by fabian-hiller** [comment]
I did not quite understand your use case. Why don't you use pass the message as a string, or define it globally a pass its variable. Another option would be to use an i18n library like Paraglide JS. Your code does not look secure to me. If you change a key, you never know if your code is broken. There is no secure mapping between an error map and the specified keys.

**Comment by ruiaraujo012** [comment]
Well, I'm using react-hook-forms and valibot to validate, then, I'm using react-i18next to translate the error messages. For each `literal` I would like to have an option to configure an error message in case of the value don't match that specific `literal`.

For now, what I'm doing is this, but it would be nice to change this string created by valibot:
```json
{
  "Invalid type: Expected \"PT\" | string but received \"\"": "O campo é obrigatório",
  "Invalid type: Expected true | false but received \"\"": "O campo é obrigatório"
}
```

**Comment by fabian-hiller** [comment]
If you only support one language I would not do the overhead of using an i18n library and just pass the error message directly to Valibot. If it is necessary to support multiple languages I would have a look at [Paraglide JS](https://inlang.com/m/gerre34r/library-inlang-paraglideJs) and pass the error message as described [here](https://valibot.dev/guides/internationalization/) directly to Valibot.

Valibot is still in active development. I am happy to receive feedback to further improve custom error messages before we reach v1 in the next weeks.

```ts
import * as v from 'valibot';

// Option 1 (similar to an error map)
const messages = {
  'required.county': 'Your message',
  // ...
};
const Schema = v.object({
  codConcelho: v.string([v.minLength(1, messages['required.county'])]),
  // ...
});

// Option 2 (better for tree shaking)
const REQUIRED_COUNTRY = 'Your message';
const Schema = v.object({
  codConcelho: v.string([v.minLength(1, REQUIRED_COUNTRY)]),
  // ...
});
```

**Comment by ruiaraujo012** [comment]
I need support for multiple languages and since we are using react-i18next already, we can't change. 
I would like to just have an option to configure a message (directly on the `literal`) in case of the value is other than the expected.

Imagine `literal(false)` and receive `''`, instead of the default `Invalid type: Expected false but received \"\"`, valibot could use the message that I define.

It could be something like:
```ts
foo: v.literal(false, 'required.foo', <invalid literal error message>)
```

**Comment by fabian-hiller** [comment]
[`literal`](https://valibot.dev/api/literal/) should not return the default message when the second argument is specified. In your case it should return `'required.foo'`. But maybe I'm misunderstanding you.

**Comment by ruiaraujo012** [comment]
No problem, I can understand, I'll post here a MRE. Thank you.

**Comment by ruiaraujo012** [comment]
[Here](https://codesandbox.io/p/devbox/xwhd2n?file=/src/App.tsx:16,55) it is, if you try to submit without changing anything.

**Comment by ruiaraujo012** [comment]
Oh, I'm sorry, I just found that you can use `v.variant('field', [Schema1, Schema2], 'Message')` that's what I want. I'm sorry for the misunderstood.
