### ISSUE TITLE
`isoTimestamp` only accepts UTC timestamps

### ISSUE THREAD

**Issue by macarie** [fabian-hiller/valibot#495]
It looks like `ISO_TIMESTAMP_REGEX` validates only UTC timestamps (ending with `Z`). But the standard also [defines the possibility of having offsets](https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC).

From my understanding, the following formats should all be considered as valid ISO timestamps:
- `<time>Z`
- `<time>±hh:mm`
- `<time>±hhmm`
- `<time>±hh`

If you consider it a bug, I'd happily open a PR 🙂

**Comment by fabian-hiller** [comment]
Thank you for creating this issue! Do you have a use case for this functionality? Can you share some example code?

**Comment by macarie** [comment]
@fabian-hiller, while working with a Rails backend, we get timestamps with offsets like this: `2023-08-09T18:04:15.582+02:00`.

The idea was to validate the field using `string([isoTimestamp()])`, but the validation fails as it doesn't have the expected format (→ ending with `Z`).

The offset is valuable in some use cases, as it can be used to determine the _event_'s local time without pulling data from other sources (geolocation, etc.). For example, when selling tickets for a concert in the US, just the offset would be enough to show both the _event's local time_ and the _user's local time_. But this example can be extended to flights, conferences, etc.

Considering that [it seems to be part of the accepted standard](https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC), I think this should be handled by the default regex.

**Comment by fabian-hiller** [comment]
Should be fixed 🙌
