### ISSUE TITLE
Search fails to work

### ISSUE THREAD

**Issue by scarf005** [fabian-hiller/valibot#499]
![image](https://github.com/fabian-hiller/valibot/assets/54838975/67b98040-e1d4-47ab-9a1f-01586d7fc88d)

## To reproduce

1. visit https://valibot.dev
2. search for `_types`
3. search fails to work.

## Additional context

![image](https://github.com/fabian-hiller/valibot/assets/54838975/d534e5f7-2ebe-4882-a294-c609008e9dfd)

there was no errors on console or network tab.

**Comment by fabian-hiller** [comment]
Thank you for reporting this issue. I will look into it next month.
