### ISSUE TITLE
Timestamp regex doesn't support timezone other than Zulu

### ISSUE THREAD

**Issue by brandonpittman** [fabian-hiller/valibot#500]
https://github.com/fabian-hiller/valibot/blob/6ca70b2a24eadf0e7e00923fa3b75f5657d0b8f5/library/src/regex.ts#L81-L82

Should support a time like `2024-04-02T08:52:31+07:00`.

**Comment by fabian-hiller** [comment]
Thank you! This seems related to #495.

**Comment by brandonpittman** [comment]
Okay, nevermind.
