### ISSUE TITLE
Can't use Valibot with H3 Data validation

### ISSUE THREAD

**Issue by DylanThomasFr** [fabian-hiller/valibot#504]
Reference from H3 : https://h3.unjs.io/examples/validate-data

With zod for example we validate a query like so : 

`const query = await getValidatedQuery(event, userSchema.parse)`
`const params = await getValidatedRouterParams(event, userSchema.parse)`
`const body = await readValidatedBody(event, userSchema.parse)`

The parse method is used to parse the formatted data against the schema.

The Valibot parse method requires a schema and the data to validate so it can't be used with H3 validation.

H3 is used for Nuxt and is used by a large number of developers. Would be nice to have Valibot compatible with H3.

Hope this will be helpful

**Comment by fabian-hiller** [comment]
You could use a little helper function:

```ts
import * as v from 'valibot';

function valibot<TSchema extends v.BaseSchema>(schema: TSchema): v.Output<TSchema> {
  return (input: unknown) => v.parse(schema, input);
}

const query = await getValidatedQuery(event, valibot(YourSchema));
```

**Comment by fabian-hiller** [comment]
Not sure if it is up to date, but there is also a dedicated community library: https://github.com/Intevel/h3-valibot

**Comment by DylanThomasFr** [comment]
@fabian-hiller 

Yes this is what I have done for now but I figured it would be nice to have it built in Valibot.

Then developers don't need to make it themselves and it can be added nicely to the H3 doc later on.

**Comment by IlyaSemenov** [comment]
The code excerpt above is not actually a provider for a specific library. It's a generic schema curry helper, and I believe it indeed deserves a method in Valibot.

```ts
import * as v from "valibot"

const schema = v.object({ ... })

const validate = v.parser(schema) // new method: convert a schema to an unary parser function

const input = validate(unsafeInput) // this logic is not related to h3, it's generally useful
```

The naming is a subject for discussion of course, but the actual idea quite makes sense.

**Comment by fabian-hiller** [comment]
Thank you for your feedback! Adding it might actually fix some problems with other libraries as well. If we find a good name, I might add such a utility.

**Comment by fabian-hiller** [comment]
This is available in v0.31.0-rc.8

**Comment by MickL** [comment]
Sorry but what is the right way to do it? This should be correct innit?

```ts
const validatedBody = await readValidatedBody(event, (body) =>
      v.safeParse(mySchema, body),
);
```

Just wanted to add that H3 is a great server that is also used by Nitro, not just within Nuxt context :)

**Comment by sandros94** [comment]
@MickL in the context of `h3` and `Nitro` I would suggest to go for the first one.

To simplify things further I've made some changes to `h3-valibot` and soon a new release will be available.

In the meantime you can refer to the [source code for `useValidatedBody` server util](https://github.com/Intevel/h3-valibot/blob/be3b186df074af0ab1932ba653aa2355acf5fb3e/src/parsers.ts#L61-L83) to have a basic understanding on a reliable approach.

@fabian-hiller feel free to ping me if anyone comes by asking about h3/Nitro/Nuxt questions (and yes, `createError` is provided by h3)
