### ISSUE TITLE
optional string field with string min/max options set wrong meta in veevalidate

### ISSUE THREAD

**Issue by yudinmaxim** [fabian-hiller/valibot#505]
I'm not sure if this is a valibot problem, but it could be.
Valibot version 0.27

I make a record of the scheme like this:
```javascript
const deviceSchema = object({
  imsi: imsi(),
  imei: optional(string([
    minLength(1, 'Необходимо ввести IMEI'),
    minLength(15, 'IMEI должен быть не менее 15 цифр'),
  ])),
  description: optional(string()),
})
```
Next, I use the scheme in conjunction with veevalidate:
```javascript

const { handleSubmit, meta, errors, defineField, resetForm } = useForm<tDevice>({
  validationSchema: toTypedSchema(deviceSchema),
})
```
And I get that `meta` does not have the correct flag if the imei does not meet the length requirements, despite the fact that the field is optional.

I assume that the scheme in which the optional field has length requirements (or others) does not work correctly.
But this is just a guess.

**Comment by fabian-hiller** [comment]
Feel free to try it out in our playground: https://valibot.dev/playground/

**Comment by yudinmaxim** [comment]
Yes - this is problem with veevalidate
In valibot playground all looks OK
