### ISSUE TITLE
Function to support for json type

### ISSUE THREAD

**Issue by thanhtamha** [fabian-hiller/valibot#525]
Most database currently support column with data type is JSON or JSONB.
So before insert data to database, usually we use Schema validation to validate this type.
So if it possible, can consider this as good to have feature.
Thanks

**Comment by fabian-hiller** [comment]
You can already build a JSON schema with the current schema functions and reuse it throughout your project. I will consider adding such a schema function or providing common prebuilt schemas in the long run.

```ts
import * as v from 'valibot';

const LiteralSchema = v.union([v.string(), v.number(), v.boolean(), v.null_()]);

type Literal = v.Output<typeof LiteralSchema>;

type Json = Literal | { [key: string]: Json } | Json[];

const JsonSchema: v.BaseSchema<Json> = v.lazy(() =>
  v.union([LiteralSchema, v.array(JsonSchema), v.record(JsonSchema)])
);
```

**Comment by CamilleHbp** [comment]
This isn't valid with the last version. Could you update the example for **JsonSchema**, @fabian-hiller? Thank you very much for your hard work! 🙏

**Comment by fabian-hiller** [comment]
Yes, here is the updated code:

```ts
import * as v from 'valibot';

const LiteralSchema = v.union([v.string(), v.number(), v.boolean(), v.null_()]);

type Literal = v.InferOutput<typeof LiteralSchema>;

type Json = Literal | { [key: string]: Json } | Json[];

const JsonSchema: v.GenericSchema<Json> = v.lazy(() =>
  v.union([
    LiteralSchema,
    v.array(JsonSchema),
    v.record(v.string(), JsonSchema),
  ])
);
```
