### ISSUE TITLE
Number literal don't trigger variant validation

### ISSUE THREAD

**Issue by ruiaraujo012** [fabian-hiller/valibot#536]
This schema:
```ts
import * as v from 'valibot';

const CommonFormationSchema = v.object({
  localidade: v.string('required.locality', [v.minLength(1, 'required.locality')]),
});

const OtherAcademicDegreeSchema = v.object({
  idGrauAcademico: v.literal(9000),
  outroGrau: v.string('required.otherAcademicDegree', [v.minLength(1, 'required.otherAcademicDegree')]),
});

const NotOtherAcademicDegreeSchema = v.object({
  idGrauAcademico: v.number('required.academicDegree'),
});

const FormationSchema = v.intersect([
  CommonFormationSchema,
  v.variant('idGrauAcademico', [OtherAcademicDegreeSchema, NotOtherAcademicDegreeSchema], 'required.academicDegree'),
]);

const FormSchema = v.object({
  formations: v.array(FormationSchema),
});

const result = v.safeParse(FormSchema, {
  formations: [
    {
      idGrauAcademico: 9000,
      localidade: "Portugal",
      outroGrau: ""
    }
  ]
});
```

Give this result:
```ts
{
  typed: true,
  success: true,
  output: {
    formations: [
      {
        localidade: "Portugal",
        idGrauAcademico: 9000
      }
    ]
  },
  issues: undefined
}
```

But it should have an issue saying that the `outroGrau` is required.

**Comment by fabian-hiller** [comment]
This is because `9000` matches `v.literal(9000)` as well as `v.number('required.academicDegree')`. To make it work you need to make the `object` schemas strict by adding `v.never()` as the `rest` argument. Test it in our [playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgGF8Q2AxaCGQxgbAMpMAFgFMhcALyYAdBAoAraUxgAKAN704cUhCZlgAE2TnpALmUcowVgHNthKNICOAV2AfzSsam5DAAnoQANHAA2hhKIE4AMtIuMJLaAIxR7l6+-oEmZmGEAJQAuiUR9AC+JQzMbBxwAPJp0lAAgqbWCUwAItLOHtISMnKKcaoaWnoGcBYA4lDI3l1WssAsdnEh7WTaAJwADCeVcxDeMHhLK9tKDk6uOT5+0gHUMp3dG-2Dw5ExOIJVjJVLpLJEDwvfIfdprHqbAZDaTSUoVKrVKJxVjSDDtbQlOqMFjseAAOWorU+8J+SOGo1kyAUyimmh0+kMi2Wq2+vQgd1Y3hAFHxzzybyUyF5iL+KNKGKxShxeKgBKJDVJcAEUCEInEUkZzLiThg7VQbO00Tm3BAvFY2t1olYDKEVUMcRIjmQrB0hC5KxpfIB0SpcOlv2RIwNrrgFJgoa+616dJRLuQZWyUPFASlSZlkfl9Aq9RJTQdaaNKnUFo5OEEwidqDuyCgy1C2gdDf1Y2QZ1qJca8A8qG8pHgE3uyGw0gACi3zR3BGmorXsPW9ew7FbDIZazv5uYbjy81s4McTm790ZCuRLNY7AAiGfQGDeZxkB+X-cXK4QI+Ph85kMao5jKGp1VLCBSGkApXGHUcYDqIA).

**Comment by fabian-hiller** [comment]
By default, `object` ignores unknown entries. This makes validation faster, and it's probably the behaviour most people expect. Use `never` whenever you want to make your object validation strict to not allow unknown entities. Note: This API and behavior may change in the next release.

**Comment by ruiaraujo012** [comment]
When you say unknown properties, are the ones not specified in the schema, or the ones with `v.unknown()`? The first case, right?

>Note: This API and behavior may change in the next release.

It's good to know that. Can I ask when are you planing to release it?

**Comment by ruiaraujo012** [comment]
> This is because `9000` matches `v.literal(9000)` as well as `v.number('required.academicDegree')`. To make it work you need to make the `object` schemas strict by adding `v.never()` as the `rest` argument. Otherwise, `object` will remove unknown entries. Test it in our [playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgGF8Q2AxaCGQxgbAMpMAFgFMhcALyYAdBAoAraUxgAKAN704cUhCZlgAE2TnpALmUcowVgHNthKNICOAV2AfzSsam5DAAnoQANHAA2hhKIE4AMtIuMJLaAIxR7l6+-oEmZmGEAJQAuiUR9AC+JQzMbBxwAPJp0lAAgqbWCUwAItLOHtISMnKKcaoaWnoGcBYA4lDI3l1WssAsdnEh7WTaAJwADCeVcxDeMHhLK9tKDk6uOT5+0gHUMp3dG-2Dw5ExOIJVjJVLpLJEDwvfIfdprHqbAZDaTSUoVKrVKJxVjSDDtbQlOqMFjseAAOWorU+8J+SOGo1kyAUyimmh0+kMi2Wq2+vQgd1Y3hAFHxzzybyUyF5iL+KNKGKxShxeKgBKJDVJcAEUCEInEUkZzLiThg7VQbO00Tm3BAvFY2t1olYDKEVUMcRIjmQrB0hC5KxpfIB0SpcOlv2RIwNrrgFJgoa+616dJRLuQZWyUPFASlSZlkfl9Aq9RJTQdaaNKnUFo5OEEwidqDuyCgy1C2gdDf1Y2QZ1qJca8A8qG8pHgE3uyGw0gACi3zR3BGmorXsPW9ew7FbDIZazv5uYbjy81s4McTm790ZCuRLNY7AAiGfQGDeZxkB+X-cXK4QI+Ph85kMao5jKGp1VLCBSGkApXGHUcYDqIA).

But now I'm having another issue, if you put a valid schema like [this](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgGF8Q2AxaCGQxgbAMpMAFgFMhcALyYAdBAoAraUxgAKAN704cUhCZlgAE2TnpALmUcowVgHNthKNICOAV2AfzSsam5DAAnoQANHAA2hhKIE4AMtIuMJLaAIxR7l6+-oEmZmGEAJQAuiUR9AC+JQzMbBxwAPJp0lAAgqbWCUwAItLOHtISMnKKcaoaWnoGcBYA4lDI3l1WssAsdnEh7WTaAJwADCeVcxDeMHhLK9tKDk6uOT5+0gHUMp3dG-2Dw5ExOIJVjJVLpLJEDwvfIfdprHqbAZDaTSUoVKrVKJxVjSDDtbQlOqMFjseAAOWorU+8J+SOGo1kyAUyimmh0+kMi2Wq2+vQgd1Y3hAFHxzzybyUyF5iL+KNKGKxShxeKgBKJDVJcAEUCEInEUkZzLiThg7VQbO00Tm3BAvFY2t1olYDKEVUMcRIjmQrB0hC5KxpfIB0SpcOlv2RIwNrrgFJgoa+616dJRLuQZWyUPFASlSZlkfl9Aq9RJTQdaaNKnUFo5OEEwidqDuyCgy1C2gdDf1Y2QZ1qJca8A8qG8pHgE3uyGw0gACi3zR3BGmorXsPW9ew7FbDIZazv5uYbjy81s4McTm790ZCuRLNY7AAiGfQGDeZxkB+X-cXK4QI+PhMHzmQxqjmMoanVUsIFIaQClcYdRxgOogA), you got an error saying `"Invalid type: Expected never but received \"Portugal\"` for every valid field.

**Comment by fabian-hiller** [comment]
> When you say unknown properties, are the ones not specified in the schema

Yes, that's exactly what I mean.

> It's good to know that. Can I ask when are you planing to release it?

Unfortunately not. But you can follow the progress in #502.

> But now I'm having another issue...

You are right. Sorry for that. I have another solution for you with `v.number([v.notValue(9000)])`. Check it out in our [playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgGF8Q2AxaCGQxgbAMpMAFgFMhcALyYAdBAoAraUxgAKAN704cUhCZlgAE2TnpALmUcowVgHNthKNICOAV2AfzSsam5DAAnoQANHAA2hhKIE4AMtIuMJLaAIxR7l6+-oEmZmGEAJQAuiUR9AC+JQzMbBxwAPJp0lAAgqbWCUwAItLOHtISMnKKcaoaWnoGcBYA4lDI3l1WssAsdnEh7WTaAJwADCeVcxDeMHhLK9tKDk6uOT5+0gHUMp3dG-2Dw5ExOIJVjJVLpLJEDwvfIfdprHqbAZDaTSUoVKq1eosdjwABy1Fan3hPyRw1GsmQCmUU00On0hkWy1W316EDurG8IAo7TcULybyUyBZiL+KIBsSUrGoADUyN5pIcTkdymdMYxsU0BFAhCJxFIKVS4k4YO1ULTtNE5twQLxWFqdaJWOShFVDHESI5kKwdIRGStiazxYS4cLfsiRvqXXB8TBg191r1SSjncgytk+a8AkKEyLw6UqhUsY14PaU4aVOpzfScIJhI7UHdkFBlqFtPa63qxshVXV1cW4B5UN5SPAJvdkNhpAAFJtmtuCFNRavYWu69h2S2GQzVrfzcw3Zk5rZwY4nV27oyFciWax2ABEU+gMG8zjId-Pu4uVwgB-vcbvcyGNUcxlDUvYNOwECkNIBSuIOw4wHUQA).

**Comment by ruiaraujo012** [comment]
Yes, it works, thank you for your answer.

Have a continuation of a good work.
