### ISSUE TITLE
Email regex pattern does not allow all valid characters

### ISSUE THREAD

**Issue by skinread** [fabian-hiller/valibot#543]
Thanks for this library!

My use case is basic form field validation, and have use the `v.email()` pipeline in a few. places. It turns out that the regex in use can be a little narrow with characters allowed before the `@` symbol.

The [local-part of the email address](https://en.wikipedia.org/wiki/Email_address#Local-part) can accept `! # $ % & ' * + - / = ? ^ _ { | } ~`

Would you consider changing current regex pattern:
```/^[\w+-]+(?:\.[\w+-]+)*@[\da-z]+(?:[.-][\da-z]+)*\.[a-z]{2,}$/iu```

to be more permissible with characters, such as:

```/^[\w!#$%&'*+\/=?^_`{|}~-]+(?:\.[\w!#$%&'*+\/=?^_`{|}~-]+)*@[\da-z]+(?:[.-][\da-z]+)*\.[a-z]{2,}$/iu```

There's also the potential to have a regex pattern that allows international unicode characters as well, but I don't have a solid reference.

**Comment by fabian-hiller** [comment]
Thank you for creating this issue and contributing to Valibot. This issue is similar to #204. It may make sense to continue this conversation there.
