### ISSUE TITLE
feature: add transform and validate method

### ISSUE THREAD

**Issue by zkulbeda** [fabian-hiller/valibot#55]
Let's imagine I expect a string "10 ms" on input and want to validate both string and number parts of it, and expect output as number 10
Currently it could be written something like this
```ts
transform(string([endsWith(" ms")]), (value) =>
  parse(coerce(number([maxValue(20)]), Number), value.split(" ")[0]),
);
```

 Add a third optional argument to transform func as transform output schema or introduce `transformAndValidate` method
```ts
transform(
  string([endsWith(" ms")]), 
  (value) => value.split(" ")[0], 
  coerce(number([maxValue(20)]), Number)
);

**Comment by fabian-hiller** [comment]
I think I would validate `X ms` with [`regex`](https://github.com/fabian-hiller/valibot/blob/main/library/src/validations/regex/regex.ts). Then it is not necessary to use `parse` in `transform`. Are there any other use cases where such a feature could be useful? Thank you for your contribution!

**Comment by fabian-hiller** [comment]
I find this discussion exciting and am waiting for feedback from others on this. Basically, everything can be validated using our [pipeline](https://valibot.dev/guides/pipelines/#custom-validation) feature, including your URL example.

**Comment by PoisnFang** [comment]
I am not fully following the ask here. Could you use custom() for this?

**Comment by fabian-hiller** [comment]
Yes, you can use `custom` for special validation cases. The first argument ist a function that returns `true` if the input is valid or `false` otherwise. I plan to rename `custom` to `check` in the next version.

**Comment by fabian-hiller** [comment]
I think, that I can close this issue since we expanded `transform` with a `pipe` argument in #197.
