### ISSUE TITLE
Not correct lang after set globally lang

### ISSUE THREAD

**Issue by ncodealex** [fabian-hiller/valibot#576]
Hello ! Thanks for you package! 

I have  problem when i set globally lang in valibot. 

Expected behavior: after using shema._parse issues have validation message in set globally lang
Actual behavior: language validation messages is "EN"

Reproducing the problem:

https://stackblitz.com/edit/vitejs-vite-scmsnl?file=src%2FApp.vue

**Comment by fabian-hiller** [comment]
`._parse` is an internal API and should not be used directly. If you parse your schema with `parse` or `safeParse`, it should work as expected: https://valibot.dev/guides/parse-data/

**Comment by ncodealex** [comment]
Thanks for answer! 

I use valibot in  nuxt ui forms 

https://ui.nuxt.com/components/form#valibot

Under the hood they use `._parse`

[#https://github.com/nuxt/ui/blob/main/src/runtime/components/forms/Form.vue](https://github.com/nuxt/ui/blob/main/src/runtime/components/forms/Form.vue#L263)

Please see string 263.

Should i create issue in  nuxt/ui ?

**Comment by fabian-hiller** [comment]
Yes, please create an issue at nuxt/ui. Feel free to link me so I can help if there are any questions.
