### ISSUE TITLE
New fields in existing schema 

### ISSUE THREAD

**Issue by chertik77** [fabian-hiller/valibot#589]
![image](https://github.com/fabian-hiller/valibot/assets/129002577/22504430-589e-46a6-8fb8-d83cbb553564)

Hey how i can add new field `avatar` to `PartialSignupSchema` but not like an object... 

```
type PartialSignupSchema = {
    name?: string | undefined;
    email?: string | undefined;
    password?: string | undefined;
} & Record<string, {
    avatar?: File | undefined;
}>
```

**Comment by fabian-hiller** [comment]
With the `rest` argument of `object`.

```ts
const Schema = v.object({ ... }, v.optional(v.instance(File)));
```

**Comment by chertik77** [comment]
> ```ts
>  avatar: v.optional(v.instance(File)),
> ```

Thanks you so much 😀

**Comment by chertik77** [comment]
Also, I do merge title to card schema 

```
export const TitleSchema = v.object({
  title: v.string([
    v.toTrimmed(),
    v.minLength(3, 'Please enter at least 3 characters.')
  ])
})

```

```
export const CardSchema = v.object({
  ...TitleSchema.entries,
  description: v.string([
    v.toTrimmed(),
    v.minLength(3, 'Please enter at least 3 characters.')
  ]),
  priority: v.picklist(priorities),
  deadline: v.date()
})
```

but `description` has same properties as title, how i can merge title properties but keep `description` as a title.

**Comment by chertik77** [comment]
And here i"m getting object instead of actual string 

```
type HelpSchema = {
    email: {
        email: string;
    };
    comment: string;
}
```

```
export const HelpSchema = v.object({
  email: v.pick(SigninSchema, ['email']),
  comment: v.string([
    v.toTrimmed(),
    v.minLength(5, 'Please enter at least 5 characters.')
  ])
})
```

**Comment by fabian-hiller** [comment]
If you have just started using Valibot, I recommend using the release candidate we just released: https://valibot.dev/guides/migrate-from-v0.30.0/

> but `description` has same properties as title, how i can merge title properties into desc field but keep `description` as a title. 

```ts
const StringSchema = v.string([
  v.toTrimmed(),
  v.minLength(3, 'Please enter at least 3 characters.')
]);

export const TitleSchema = v.object({
  title: StringSchema,
});

export const CardSchema = v.object({
  ...TitleSchema.entries,
  description: StringSchema,
  priority: v.picklist(priorities),
  deadline: v.date()
});
```

> And here i"m getting object instead of actual string

`pick` is similar to `Pick` in TypeScript. It's the wrong procedure for what you are aiming for.

```ts
export const HelpSchema = v.object({
  email: SigninSchema.entries.email, // <--
  comment: v.string([
    v.toTrimmed(),
    v.minLength(5, 'Please enter at least 5 characters.')
  ])
})
```

**Comment by chertik77** [comment]
Thanks, u're a lifesaver, i'm new here, but i like it
