### ISSUE TITLE
Can't run test code using 0.31.0-rc

### ISSUE THREAD

**Issue by chimame** [fabian-hiller/valibot#596]
When I install the 0.31.0-rc version and try to run the test code using Vitest, I get the error

```
 SyntaxError: Invalid regular expression flags
```
![image](https://github.com/fabian-hiller/valibot/assets/7520815/28c405bd-f0da-4e9a-b847-8c80da6cd747)

I've created a minimal sample code that will cause this to happen [here](https://github.com/chimame/valibot-test). The sample code simply outputs the valibot API `string` to the log. Of course, there is no error when using 0.30.0. Is there anything special I need to do from 0.31.0 onwards?

```ts
import { describe, it, expect } from 'vitest'
import { string } from 'valibot'

describe('sample', () => {
  it('should pass', () => {
    console.log(string) // <-- After deleting it, the test can be executed normally.
    expect(1 + 1).toBe(2)
  })
})
```

**Comment by fabian-hiller** [comment]
I know what the problem is. What JavaScript runtime and version are you using?

**Comment by chimame** [comment]
Thank you for your quick response!

My Node.js version was `18.18.2`. I changed it to `20.13.1` and the test ran normally. Does 0.31.0 support Node.js versions 20 or higher?

**Comment by fabian-hiller** [comment]
I have started to use an advanced regex function to improve and simplify the `emoji` regex. Unfortunately, this is not supported in Node.js v18 or older.

**Comment by chimame** [comment]
Thanks for your answer!
I'll keep in mind that supported versions of Node.js change.

**Comment by fabian-hiller** [comment]
If there are people who can't upgrade, I will reconsider this change and reschedule it for a later date. On the other hand, as far as I know, upgrading from v18 to v20 shouldn't cause any problems.
