### ISSUE TITLE
Add an advanced `refine` method (similar to Zod's `superRefine`)

### ISSUE THREAD

**Issue by ruiaraujo012** [fabian-hiller/valibot#597]
Currently, there is no way to directly add custom/global issues to the validation, for example:

```json
{
    "primaryEmail": "foo@email.com",
    "otherEmails": ["bar@email.com", "foo@email.com"]
}
```
To validate that the `primaryEmail` is not present in `otherEmails` there is no method that allows it, because I need some actions that add issues globally.

The `forward` action doesn't work because I cannot put the key and index of the duplicated email, in this case `otherEmails.1`.

One possible solution is a method that allow us to add issues to the list of issues already created by valibot validations. Something like: 
```ts
v.someMethod((inputs, ctx) => {
// ...(my custom validation with ctx.addIssue())...
return ctx.issues // Or other type of return
}) 
```

---
Related: #487, #546

**Comment by jansedlon** [comment]
Just wanna say that this is the thing that would allow me to completely switch over to valibot :)

**Comment by jansedlon** [comment]
Awesome 🤩

**Comment by ruiaraujo012** [comment]
Hello @fabian-hiller, from what I can tell, the codemod worked well to me, but I cannot finalize the migration because of this feature request. I don't want to rush you, I just wanted to know if you have an estimate of when it will be ready.

Thanks :)

**Comment by fabian-hiller** [comment]
Probably next week, as I should migrate some old docs pages first. Sorry for the delay.

**Comment by ruiaraujo012** [comment]
It's ok, just to be aware ;)

**Comment by fabian-hiller** [comment]
What should we call this super action? One idea is to call it `refine`, similar to Zod, and another is to just call it `action`.

**Comment by ruiaraujo012** [comment]
I'm not sure, `refine` seems to represent better what it does, but I like `action` 🙈

**Comment by jansedlon** [comment]
I'd call it refine

**Comment by ruiaraujo012** [comment]
Yeah, `refine` is better.

**Comment by fabian-hiller** [comment]
`action` might make sense because it gives direct access to the underlying action API. `refine` might make sense as it has a stronger meaning and makes the code more readable. Do you have alternative names in mind?

**Comment by jansedlon** [comment]
Action gives me the impression of a single action or a single purpose thing but idk 😄

**Comment by ruiaraujo012** [comment]
What about `enhance`? Not sure, but came to my mind.

**Comment by fabian-hiller** [comment]
I will think about it. Thank you for your feedback!

**Comment by fabian-hiller** [comment]
I like the names `refine` and `enhance` because they are short and match well with the names of the other actions. On the other hand, we distinguish between validation actions and transformation actions, and already support two actions with `check` and `transform`, which gives you full control over validation and transformation. Therefore it might make sense to add two functions instead of one as transformations are handled differently than validations.

For example, we could add two functions with the same name but a prefix in front. Since both give you access to the raw implementation a prefix like `raw`, `super` or `power` might make sense. So `check` and `transform` are the high level implementation with a nice DX and `rawCheck` and `rawTransform` are the low level version giving you full control over the dataset of the pipeline. What do you think of this idea?

**Comment by ruiaraujo012** [comment]
The `raw` prefix is more self explanatory than `refine` or `enhance` and you're right, this method is no more than a `check` with an option to access the error layer and change it by adding new errors.

So I think the `rawCheck` and `rawTransform` would be a better name, even if less fancy than `enhance` or `refine`.

**Comment by fabian-hiller** [comment]
`rawCheck` and `rawTransform` are now available. Please give me feedback about the DX! There is no documentation yet, but here is a simple example showing the API.

```ts
import * as v from 'valibot';

const Schema1 = v.pipe(
  v.number(),
  v.rawCheck(({ dataset, addIssue }) => {
    if (dataset.typed && dataset.value <= 0) {
      addIssue({ message: 'Error!!!' });
    }
  })
);

const Schema2 = v.pipe(
  v.string(),
  v.rawTransform(({ dataset, addIssue, NEVER }) => {
    const length = dataset.value.length;
    if (length < 3) {
      addIssue({ message: 'Error!!!' });
      return NEVER;
    }
    return length;
  })
);
```

**Comment by ruiaraujo012** [comment]
I will try soon, but I have a question, if I apply `rawCheck` to an object, what will be the field with the error? Is it possible to add an issue to a field?

**Comment by fabian-hiller** [comment]
You can still wrap `rawCheck` in our [`forward`](https://valibot.dev/api/forward/) method or specify the path by hand next to the message.

**Comment by ruiaraujo012** [comment]
Oh, I didn't remember the `forward`.

Using the second options:
```ts
const Schema = v.pipe(
  v.object({
    email: v.pipe(v.string(), v.email()),
    password: v.pipe(v.string(), v.minLength(8)),
  }),
  v.rawCheck(({ dataset, addIssue }) => {
    if (dataset.typed && dataset.value.email.length < 10) {
      addIssue({
        input: dataset.value.email,
        message: 'Error!!!',
        path: [
          {
            input: dataset.value,
            key: 'email',
            origin: 'value',
            type: 'object',
            value: dataset.value.email,
          },
        ],
      });
    }
  }),
);
```
It's a bit bad in DX having to populate all those values in `path`

**Comment by ruiaraujo012** [comment]
Otherwise, I find that while you don't have the `items` method, [this](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgGUmALAUxDI4AXkwA6MMDB8AFPTjiIFAFZ8mMGQG95CuAOTBSALnGTpMjGI5RgrAOYyAlABpx+w05c6F70qhOWyFBQyACeFhJSspbWtg4u4iC2ADJ89jA8MgAcjrnOOgC+XgqWIQDuAML8TADWMlpwACbIMGh8MK7IjY0AkqioAK58cEUiAHxw2rpwwNhwMs2tqO1iMKHSjY6T3ros7PBQfNItfL2sjXwAHnz+cKwDIBR8UADaALoicO8MOwqLbTAxCRSEMxL5UGJsNAAKLIXj1XyuWwXS5bYQTKbTXSzea+ETCUT-ZaA4Gg3xbTFY3SHY4wU49c5XG4SAaoTLIq6OBhUhQFX4jLmMKk4mQ0vgnM4o5mkNJ2DJwCYABgp-IUYolDKlEKhUFh8JkHNR422PN0XV6-SGWlVWNsYAGMBMRJWpL4YMEhlQ+VN0xAN1QyDsfBMAAMAEpHcV0xpwAAkmkNBRD3p9CjALR4JheNqplNT2NY9sdTRaAKBZDJHr8KfzuhqfFCJkNNdrcGgwDsthMxArfEILdra2k3aCIVC-ZzPNdTtLxPLILd4JehreA59BTXVNXk6K3J5u-5fOmR4F+UFzDYHDgh0GpHgohiyGwfAACkFljJuPxBK5Mb5u8oyCsHwAACVzIOAMpiCwIATj4Va3C8hCAcBACMYGXBBYBQTB-ZEChoHgZBbq4a4yFAXwADMGFYTh+CENuB4XuwEBQaQEAODeAx3lyQA) work well:

```ts
const Schema = v.pipe(
  v.object({
    email: v.pipe(v.string(), v.email()),
    emails: v.array(v.pipe(v.string(), v.minLength(8))),
  }),
  v.rawCheck(({ dataset, addIssue }) => {
    if (dataset.typed) {
      const repeatedIndexes: number[] = [];

      dataset.value.emails.forEach((email, index) => {
        if (email === dataset.value.email) {
          repeatedIndexes.push(index);
        }
      });

      if (repeatedIndexes.length > 0) {
        repeatedIndexes.forEach((index) => {
          addIssue({
            input: dataset.value.emails,
            message: `Repeated ${index}`,
            path: [
              {
                input: dataset.value.emails,
                key: index,
                origin: 'value',
                type: 'array',
                value: dataset.value.emails[index],
              },
            ],
          });
        });
      }
    }
  }),
);

const result = v.safeParse(Schema, {
  email: 'jane@example.com',
  emails: ['jane1@example.com', 'jane@example.com', 'jane3@example.com'],
});
```

I'll try that with `react-hook-forms` soon

**Comment by fabian-hiller** [comment]
Thank you for your feedback!

> It's a bit bad in DX having to populate all those values in `path`

I agree, but the other option would be to increase the bundle size and make it less powerful with less control by using a key path as with `forward`.

**Comment by ruiaraujo012** [comment]
I can see that, it's ok, I think this method will be less used, so probably it won't hurt much. Thank you for this addition.

**Comment by fabian-hiller** [comment]
Thank you! Feel free to share more feedback in the long run. In the end, I am interested in the best solution and feedback helps me a lot to make the best decisions.

**Comment by jansedlon** [comment]
@fabian-hiller good job on the progress! One question, how does this play out with i18n in general? What about specifying custom error message in different scenarios using this new function?

**Comment by ruiaraujo012** [comment]
> @fabian-hiller good job on the progress! One question, how does this play out with i18n in general? What about specifying custom error messages using i18next in different scenarios using this new function?

I usually create a namespace only for forms, and then use it in the schemas.

```json
{
    "validation": {
        "email": "The email is not valid."
        ...
    },
    "required": {
        "email": "The email is required."
        ...
    },
}
```

Then in the schemas

```ts
const Schema = v.object({
    email: v.pipe(v.string(), v.nonEmpty('form:required.email'), v.email('form:validation.email'))
})
```

And then, using react I pass the message from valibot to `t(message)`

**Comment by jansedlon** [comment]
@ruiaraujo012 thank you for the example. Coming from zod-i18next, what's honestly truly the best is that you just pass `params` in `addIssue` where you define namespace and key and it's almost magically translated. If there was something close to this, it would be amazing. What do you think @fabian-hiller , could you look at that? Or I can try to find out how that params works exactly.

**Comment by ruiaraujo012** [comment]
Oh, I see, I looked into zod-i18next, actually it'll be a nice addition. I think you could open an issue describing that and.

**Comment by jansedlon** [comment]
Will do :)

**Comment by fabian-hiller** [comment]
Have you read [this guide](https://valibot.dev/guides/internationalization/)? Paraglide JS looks nice. I am happy to answer questions about i18n.

**Comment by jansedlon** [comment]
@fabian-hiller Yeah, i know about Paraglide, however we don't really have the time to migrate to paraglide a i had some issues with it 🙈 We have (probably) thousands of translations keys right now and the migration would take a lot of time.

In valibot i use `setSpecificMessage` right now which is bounded to a specific validator, e.g.
```ts
v.setSpecificMessage(v.url, (issue) =>
    t("url", { received: issue.received, ns: "valibot" }),
  );
```

In `zod-i18next` you register error map like this

```ts
z.setErrorMap(
    makeZodI18nMap({
      // @ts-ignore
      t: t,
      ns: ["zod", "custom-zod"],
    }),
  );
```

and then when you're doing validation (like with `rawCheck`) you're passing the translation key and it uses the `t` function passed above, e.g.

```ts
function createSchema(
  intent: Intent | null,
  constraints?: {
    isEmailUnique?: (email: string) => Promise<boolean>;
  },
) {
  return z
    .object({
      email: EmailSchema.pipe(
        z.string().superRefine((val, ctx) => {

          return constraints.isEmailUnique(val).then((isUnique) => {
            if (!isUnique) {
              ctx.addIssue({
                code: "custom",
                params: {
                  i18n: "custom-zod:emailIsTaken",
                },
              });
            }
          });
        }),
      ),
    })
}
```

In this example it's not bound to any existing validator, which is really useful. I can just type `namespace:translation-key` in `params.i18n` key.

Is there a similar way in valibot now?

As of now, i call a global function like
```ts
setValibotTranslations(t);
```

which sets global messages for existing translations

```ts
export function setValibotTranslations(t: TFunction<["valibot"]>) {
  v.setSpecificMessage(v.bic, (issue) =>
    t("bic", { received: issue.received, ns: "valibot" }),
  );

  // Other translations...
}
```

**Comment by jansedlon** [comment]
I'm wondering if there's a way around that. From the type definition of `IssueInfo$1` which is type interface i can pass to `addIssue` in valibot, there's no `type` property. This could be used to differentiate things. Like if `{type: 'custom', message: 'namespace:key'}` i could catch that in the `setValibotTranslations` and parse the message as a translation key and use the `t` function to translate it 🤔

**Comment by fabian-hiller** [comment]
> i could catch that in the `setValibotTranslations` and parse the message as a translation key

This will not work because the `message` of `rawCheck` is more specific. So `setSpecificMessage` is ignored in this case.

You could try to create a function that takes a `code` as the first argument and returns another function that matches our `ErrorMessage` type. This way you could pass this function as the last optional argument to any schema or action to translate the error message. You can try it out in [this playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6YBPMAUzgBUpkA7VUshjAIvAMIQAJhwC89OHAA+RNiGTBSALmC8S5SYXlKVajZuzQ1NI8sJg0qAO7RJ23WWAGbRe6icvNUjZeAHMYAAs6RgBjUVR4GB5+QWE4zTgAJTZYqEkAHnioHRCAGkzslzzuPgEhEXEpNjLC4oA+VrgZOABvI2D03oUFQlV1LR09T0J0wk5wjlGNOHC0OAiORzxQuEkhZDXWNkISo2HFrQsoK2miOYXTUjhgdApkSVJmHEshGDYDE6GPgczlybkmBhmdzgvn8uWWq3WcE2ohCOz2B3Yx1OQL8INcQVCERus3m0OBLie6BgEAgcFQ4WgNABcAAvszpANsSMHmCPBCiAARYAcACiAFoALJjeHwaS8HBkVDRebygVCYIsMBYwHcsbmb40GZC0WS6XPeDYRXKr5XOpsWDaoZ2cmgiZ84lq9AABRd8BWsuCCtISpVcDVv14msdwxheMCwTCkSNqx9uMZlPgAC8AK5wADW2agmcdbPoLIY9Gw2d40VS8pgAApYhyuElanWJNIAJTpDAAOhFUDwUAlbD8yBCbDy-YAQmg2ABJPzZqfVvO8CCOXjtHpGKBsGCF+UN56oFddzodRI1FL1VAAbVPK77gm2ilswUIAF0APx9+-NmwX5wD+P6UmebB9iAY6oBObAMCyMRxPAADKyqjJ0mB9hAFAAFbZI2gxwOcvZ9mAwDsA2-YtKEDaNrqZhuvohBdl2ZT9ucdENgxFwGixrHMrGARYeRlHYtRiTFFxzppq67jMQJ4lQToAAyCYRA2AAcZT0UJoIEom-HMmxZZdhW1EHgA4qQOFkBIvDYMAIQNt0cCviEMzSIQrJmUh-DwPuZ6kPAXTUcg2BsD6UCoGwDZofMahlERJFELhfBsGwAAeyDgEEfaxCAjp6a4cAAIwAEwAMwACwnCyvn0LE-AQHlNnOYF2bBb5QA).

```ts
import * as v from 'valibot';

type TranslationCode =
  | 'email:invalid'
  | 'email:format'
  | 'password:invalid'
  | 'password:length';

const translations: Record<string, Record<TranslationCode, string>> = {
  en: {
    'email:invalid': 'The email has the wrong data type',
    'email:format': 'The email is badly formatted',
    'password:invalid': 'The password has the wrong data type',
    'password:length': 'The password is too short',
  },
  de: {
    'email:invalid': 'Die E-Mail hat den falschen Datentyp',
    'email:format': 'Die E-Mail ist falsch formatiert',
    'password:invalid': 'Das Passwort hat den falschen Datentyp',
    'password:length': 'Das Passwort ist zu kurz',
  },
};

function t(code: TranslationCode): v.ErrorMessage<v.BaseIssue<unknown>> {
  return (issue) => translations[issue.lang || 'en']?.[code] ?? issue.message;
}

const Schema = v.object({
  email: v.pipe(v.string(t('email:invalid')), v.email(t('email:format'))),
  password: v.pipe(
    v.string(t('password:invalid')),
    v.minLength(8, t('password:length')),
  ),
});
```

**Comment by ruiaraujo012** [comment]
@fabian-hiller Just to let you know that I've migrated today all the codebase of a project I'm working on to version v0.32.0, and it went well with the help of `rawCheck`. There are some places where I will change the `checkItems` when it's ready, but I was able to do a workaround with `rawCheck` for now.

Thank you.
