### ISSUE TITLE
EMOJI_REGEX throws Invalid regular expression flags on node v18

### ISSUE THREAD

**Issue by AlexXanderGrib** [fabian-hiller/valibot#599]
Hello, the [following line](https://github.com/fabian-hiller/valibot/commit/c1ac794cdb83c2a445c4e204bf8ea4aa60b149b2#diff-719c798c633ba19bf1cd1a2bc6f37756f66c7ff6c16ba1b8b9c8d6619219fdd4R25) breaks projects running on node 18

```typescript
export const EMOJI_REGEX = /^\p{RGI_Emoji}+$/v;
```

[Node js 18 does not support regex /v flag](https://node.green/#ES2024-features-RegExp--v--flag) so node throws an error
```
SyntaxError: Invalid regular expression flags 
```

Easy fix:
```typescript

export const EMOJI_REGEX = (() => { 
  try { 
    return new RegExp('^\\p{RGI_Emoji}+$', 'v'); 
  } catch { 
    return /^[\p{Extended_Pictographic}\p{Emoji_Component}]+$/u; 
  } 
})();

```

**Comment by fabian-hiller** [comment]
The bigger question is whether we should stick with the current code and force people to upgrade to Node.js v20. I don't plan to implement a try/catch workaround, but I can consider not using this feature until v2 of Valibot to give devs more time.

**Comment by fabian-hiller** [comment]
Thanks for your research! Since this regex is not too important, I think I will follow your recommendation.
