### ISSUE TITLE
Publish to deno.land/x

### ISSUE THREAD

**Issue by BastiDood** [fabian-hiller/valibot#6]
Hello there! Awesome project here. I'd really love to try this library out on my Deno projects. Although I may already do so by directly importing the TypeScript files from GitHub itself, it would be great to have them officially published at [deno.land/x](https://deno.land/x) for better discoverability.

**Comment by fabian-hiller** [comment]
Thanks for the tip. I will try to publish Valibot on Deno as soon as possible.

**Comment by fabian-hiller** [comment]
Hey! We are on Deno! 🎉 Please let me know if it works. https://deno.land/x/valibot

```ts
// With individual imports
import { … } from 'https://deno.land/x/valibot/mod.ts';

// With a wildcard import
import * as v from 'https://deno.land/x/valibot/mod.ts';
```
