### ISSUE TITLE
feature: validate extended ISO datetimes

### ISSUE THREAD

**Issue by josemarcilio** [fabian-hiller/valibot#60]
Trying to validate the datetime "2023-08-05 14:41:39.589Z" with isoDateTIme validator, I got an error so, inspecting the implementation I found there is no case to considering an ommited separator and ISO 8601-1:2019 allows the T to be omitted in the extended format.

Maybe it could be the case of creating a extendedIsoDateTime validator in validations folder?

**Comment by fabian-hiller** [comment]
In which cases do you use the extended format instead of the normal one?

**Comment by josemarcilio** [comment]
Some services, APIs, or frameworks, like the one I'm using (Pocketbase), adopt it. But, to be honest, after reviewing the code again, I'm not entirely sure if creating a new validator is necessary. The isoDateTime validation is performed with regex, so I believe using the regex validator would be sufficient. Creating new validators for slightly different formats could lead to an indeterminate amount of date validators.

**Comment by fabian-hiller** [comment]
Thank you for for the info. Yes, I agree with you. I think that Valibot should contain the most important validations and somewhat more special cases should be covered independently or by external libraries.
