### ISSUE TITLE
TypeScript: InferInput always infers intersect as 'never'

### ISSUE THREAD

**Issue by naveen-bharathi** [fabian-hiller/valibot#601]
For any valibot schema that uses intersect, `InferInput` always infers `intersect` as type `never`

For the below code, the `v.InferInput` infers `typeof eventSchema` as `never`

This started in the first pre-release [v0.31.0-rc.0](https://github.com/fabian-hiller/valibot/releases/tag/v0.31.0-rc.0) and still happens in the latest pre-release [v0.31.0-rc.4](https://github.com/fabian-hiller/valibot/releases/tag/v0.31.0-rc.4)

```typescript
import * as v from 'valibot'

const eventSchema = v.intersect([
  v.pipe(
    v.object({
      name: v.pipe(
        v.string(),
        v.trim(),
        v.maxLength(128),
      ),
      startDate: v.date(),
      endDate: v.date(),
    }),
    v.check(({ startDate, endDate }) => startDate < endDate),
  ),
  v.variant('hasCelebrity', [
    v.object({
      hasCelebrity: v.literal(true),
      celebrity: v.literal('Fabian Hiller'),
    }),
    v.object({
      hasCelebrity: v.literal(false),
      celebrity: v.null_(),
    }),
  ]),
])

type EventSchemaT = v.InferInput<typeof eventSchema> // infers as 'never' (all the time)
```

## Screenshot from VSCode Intellisense
<img width="742" alt="SCR-20240525-igfe" src="https://github.com/fabian-hiller/valibot/assets/32498535/b4589185-1f74-48ec-9db9-4a07150a1732">

**Comment by fabian-hiller** [comment]
Thanks for reporting this. I will fix it and release a new version.

**Comment by fabian-hiller** [comment]
v0.31.0-rc.5 is available

**Comment by naveen-bharathi** [comment]
Many Thanks @fabian-hiller 
You're a super star ⭐
