### ISSUE TITLE
Enum error with React Hook Form

### ISSUE THREAD

**Issue by chertik77** [fabian-hiller/valibot#610]
```typescript
export enum EnumPriority {
  Low = 'Low',
  Medium = 'Medium',
  High = 'High',
  WithoutPriority = 'Without priority'
}

```
```typescript
export const CardSchema = v.object({
  ...TitleSchema.entries,
  description: v.string([
    v.toTrimmed(),
    v.minLength(3, 'Please enter at least 3 characters.')
  ]),
  priority: v.enum_(EnumPriority),
  deadline: v.date()
})
```

```typescript
useAppForm<CardSchema>(CardSchema, {
      defaultValues: { priority: 'Without priority', deadline: new Date() }
    })
```
    
`Type '"Without priority"' is not assignable to type 'EnumPriority | undefined'`

**Comment by fabian-hiller** [comment]
What version are you using? It works in v0.30.0 as well as with our new RC. See this [playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6B6JuAdWBgAs4ADAUwB2AVxAB9XoyGi4AUREgAClGDROATzgBvenDgAZCAHc4AXiKGjhADS64AWX4ATYDPOFHL0TbsAJYADmPO7+QT56HNwQwjDKqiowmu6RXNHwYCpqiYT0AL6MAMYQgqjwAMLIUE4AygVc-CDIAIxmmAB0EBQAVvwFMAAUOnoZ8RoAXO3S4v3yonFZ6gCUtrmLDPSJYPxwFVW19Y0t5hhtAJKC2PxQ52AxADyb-BDYO5U1dQ3NAHzrRSXwBTeAHlur0YE0Jrt3gdmq0hnARgsJrMlJkEuo2ik0vN0St1ix2JweLwwMACgBrcilST0P6lV57D6NABMrROnR6fUGdkR6ImJ1JFKpAwA2oRLDYiJ5XCBJYRQlw5ViYgi0RpCABdZZ5NaMR4M6GfVnHM4XK43e6PZ4G-ZGn6FYr0wFVEGcmDMyFvW0suE8tWJCaEZXpf3qHy5WhAA).

```ts
import * as v from "valibot";

// With `enum_`

enum EnumPriority {
  Low = "Low",
  Medium = "Medium",
  High = "High",
  WithoutPriority = "Without priority",
}

const CardSchema1 = v.object({
  priority: v.enum_(EnumPriority),
});

type CardSchema1 = v.Input<typeof CardSchema1>;

const cardObject1: CardSchema1 = {
  priority: EnumPriority.WithoutPriority,
};

// With `picklist`

const CardSchema2 = v.object({
  priority: v.picklist(["Low", "Medium", "High", "Without priority"]),
});

type CardSchema2 = v.Input<typeof CardSchema2>;

const cardObject2: CardSchema2 = {
  priority: "Without priority",
};
```

**Comment by fabian-hiller** [comment]
I do not recommend using `Object.values(Enum)` because it may also return the keys of the enum. In `enum_` we use the following code to extract the values:

```ts
const options = Object.entries(enum__)
    .filter(([key]) => isNaN(+key))
    .map(([, value]) => value) as (keyof TEnum)[];
```
 
Do you have any other questions or problems that I can help you with?

**Comment by chertik77** [comment]
> I do not recommend using `Object.values(Enum)` because it may also return the keys of the enum. In `enum_` we use the following code to extract the values:
> 
> ```ts
> const options = Object.entries(enum__)
>     .filter(([key]) => isNaN(+key))
>     .map(([, value]) => value) as (keyof TEnum)[];
> ```
> 
> Do you have any other questions or problems that I can help you with?

So it wont work with Object.values() ? and it first example i'm also not able to get ts intellisense without actually using enum?

**Comment by chertik77** [comment]
I think it should be possible to pass Enum priority and get full type safety in actual component without importing enum again and again

**Comment by chertik77** [comment]
even though, i dont get type safe when passing with constant

` priority: v.picklist(['Low', 'Medium', 'High', 'Without priority']),`

![image](https://github.com/fabian-hiller/valibot/assets/129002577/6dd3ca48-f9af-4848-8a13-d50f2151ac4c)

priority: v.picklist(priorities),

![image](https://github.com/fabian-hiller/valibot/assets/129002577/44bf29c8-3ea8-46db-9954-419623cb45f1)

**Comment by chertik77** [comment]
So, quick recap, it works with

  `priority: v.enum_(EnumPriority)`, but i should import enum everywhere when i want to write a priority, in my opinion it should also work without it, but  `priority: v.picklist(priorities),` also doesnt work because it is a constant , it works only when u hard code all values into `v.picklist()` like this:  `priority: v.picklist(['a', 'b']),` and only in this case there is a type safe, what should i do to achieve the best approach?

**Comment by fabian-hiller** [comment]
> even though, i dont get type safe when passing with constant

Have you tried this? It works in our [playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XjCmGmBgE84AXjgBtAEQAZCAHdxAGjjiAsgFMAJsACuIBUoASwAOYALPeIDqfExC2duvAeIC6KdC3YwGzNhzgBhZCh1AGUmE1UQZGFMADoICgArVSYYAAoAb3o4OC4ebgEALjiwYCYAa3IONLzHfgBKeXoAX3rvATBVAKDQ8MjokQxYgElWbFUoUbA7AB4O1QhsbuCwiKiAPlogA).

```ts
import * as v from "valibot";

const priority = ["Low", "Medium", "High", "Without priority"] as const;

const CardSchema = v.object({
  priority: v.picklist(priority),
});
```

**Comment by chertik77** [comment]
> > even though, i dont get type safe when passing with constant
> 
> Have you tried this? It works in our [playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XjCmGmBgE84AXjgBtAEQAZCAHdxAGjjiAsgFMAJsACuIBUoASwAOYALPeIDqfExC2duvAeIC6KdC3YwGzNhzgBhZCh1AGUmE1UQZGFMADoICgArVSYYAAoAb3o4OC4ebgEALjiwYCYAa3IONLzHfgBKeXoAX3rvATBVAKDQ8MjokQxYgElWbFUoUbA7AB4O1QhsbuCwiKiAPlogA).
> 
> ```ts
> import * as v from "valibot";
> 
> const priority = ["Low", "Medium", "High", "Without priority"] as const;
> 
> const CardSchema = v.object({
>   priority: v.picklist(priority),
> });
> ```

yes, it works, but I use priority array also for mapping, so i cannot use as const 🥲

**Comment by fabian-hiller** [comment]
Can you give an example? Something like [this](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XjCmGmBgE8AjHAC8cANoAiADIQA7pIA0cSQFkApgBNgAVxBKVACWABzABaSAuinQt2MBszYc4XHtwEAmUa+68BggB0IMhgABRhYACUogB8rnAA1ESehDZwAAYAJADeAmDqENi+7nxC4qx6FOpQlgC+nhlRjnYuAMLIUJoAykxm6iE+GIEQFABW6kwwYTn0cCX+-ABcmIFgwEwA1uQckX4e-J5RivR1zYz56nAdXb39g2LDAJKs2DUvYDowADyXRdedHp9AbIWK0IA) works for me.

**Comment by chertik77** [comment]
> Can you give an example? Something like [this](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XjCmGmBgE8AjHAC8cANoAiADIQA7pIA0cSQFkApgBNgAVxBKVACWABzABaSAuinQt2MBszYc4XHtwEAmUa+68BggB0IMhgABRhYACUogB8rnAA1ESehDZwAAYAJADeAmDqENi+7nxC4qx6FOpQlgC+nhlRjnYuAMLIUJoAykxm6iE+GIEQFABW6kwwYTn0cCX+-ABcmIFgwEwA1uQckX4e-J5RivR1zYz56nAdXb39g2LDAJKs2DUvYDowADyXRdedHp9AbIWK0IA) works for me.

Thanks a lot! Finally works
