### ISSUE TITLE
Reduce boilerplate for custom actions

### ISSUE THREAD

**Issue by IlyaSemenov** [fabian-hiller/valibot#614]
Before the new pipe API, I was creating ad-hoc validators with [something like](https://github.com/IlyaSemenov/valibotx/blob/e69851832a837776c8bb320f4faf81b64475ff8d/src/validations/nonEmpty.ts):

```ts
export function nonEmpty<TInput extends string | any[]>(error?: ErrorMessage) {
  return minLength<TInput, 1>(1, error)
}
```

after the update, the least I could come up with was:

```ts
// Not exported by valibot, need to redefine this.
type LengthInput = string | unknown[]

export function nonEmpty<TInput extends LengthInput, const TMessage extends
  | ErrorMessage<MinLengthIssue<TInput, 1>>
  | undefined>(message?: TMessage): MinLengthAction<TInput, 1, TMessage>

export function nonEmpty(message = "Non-empty value required.") {
  return minLength(1, message)
}
```

If I remove the function definition boilerplate and only keep the last 3 lines, it works but it's not typed properly:

<img width="1257" alt="image" src="https://github.com/fabian-hiller/valibot/assets/128121/44dc0b3b-64ce-4cb9-b109-010e0249e35e">

---

My question is, can we come up with some kind of approved recipe and/or reduced boilerplate for trivial library extensions such as above? In my perfect world, it should be possible to come up with multitude of similar one-liners, not having to toss unreadable mess of copy/pasted generics.

**Comment by fabian-hiller** [comment]
Thanks for the feedback. I will check if I want to export these types, but in general it is probably a good idea. `nonEmpty` is now natively supported out of the box, so you don't have to add it yourself.

In general, there is no difference from before. The only difference is that the API has become more type-safe, which requires more precious typing, resulting in more TypeScript code. But if you don't care, you can write it much the same way as before. Here is an example. You can test it in this [playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6YBPMAUzgBk2A7AcxgALAJI8wAV3gBeOKhhRg-OAB844ngGseEAO48A2gF0G9bOoDGMYBB5xtPAKLgWAHgAqoifDYAPGLwATdG5+IU9JAD4ACno4OBA2VFRkPjYALll5RT44GUIAORsAWjZnZkwycQ4oNgBHcWAagIA6QnoASgyMZoBZRRCBQQBBS2sed3CYABo4AEYZuQV+CLgAb1i4GphxKFtukH7eQaj5+MTk1PaGAF9Gcxs5OABlc0FS5FzMZrBgdijuxbZKLtGb2JxgFjAq70IA).

```ts
import * as v from 'valibot';

type LengthInput = string | unknown[];

function nonEmpty<TInput extends LengthInput>(
  message: string = 'Non-empty value required.'
): v.MinLengthAction<TInput, 1, string> {
  return v.minLength(1, message);
}
```

If you prefer precise types, I have rewritten your code to make it a bit simpler. You can test it in this [playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6YBPMAUzgBk2A7AcxgALAJI8wAV3gBeOKhhRg-OAB844ngGseEAO48A2gF0G9bOoDGMYBB5xtPAKLgWAHnpw4AFVET4bAB4wvAAm6Nz8Qj6SADTucOY2cl4AsmyoqMh8HAFBPKGYAHQOUHhQqemZbC4YBcmK4QIi6eJV3mIxcACMAHzdsd0AFHEgaRlZAFwpo5VwMoQAcjYAtGzOzJhkLXBQbACO4sA7wQWEKOie5WNs9ACUkzV1PA1CAIKW1jwubb7RXb8X0yy3TgAG84jsYOIoLYaiB6rxGgNOr8RhUsjcGABfRgJHhJADK5kEq2Qs0KYGA7AGNTkCn4Axuv3sTjALAZGPoQA).

```ts
import * as v from 'valibot';

type LengthInput = string | unknown[];

function nonEmpty<
  TInput extends LengthInput,
  const TMessage extends v.ErrorMessage<v.MinLengthIssue<TInput, 1>>,
>(
  message: TMessage = 'Non-empty value required.' as TMessage
): v.MinLengthAction<TInput, 1, TMessage> {
  return v.minLength(1, message);
}
```

**Comment by IlyaSemenov** [comment]
Another use case is:

```ts
export function integerNumber<TMessage extends v.ErrorMessage<v.NumberIssue>>(message?: TMessage) {
  return v.pipe(v.number(message), v.integer())
}
```

is there a better way to type this? Most of the schemas use function overload to distinguish between the message and undefined:

```ts
declare function number(): NumberSchema<undefined>;
declare function number<const TMessage extends ErrorMessage<NumberIssue> | undefined>(message: TMessage): NumberSchema<TMessage>;
```

Is there a way to proxy this contract somehow to the extending one-liners?

**Comment by fabian-hiller** [comment]
As I understand it, this is not possible without drawbacks. That's why I use overload signatures.

**Comment by fabian-hiller** [comment]
I added `ContentInput`, `ContentRequirement`, `LengthInput`, `SizeInput` and `ValueInput` to the exports.
