### ISSUE TITLE
Error while downloading codemod

### ISSUE THREAD

**Issue by hyunbinseo** [fabian-hiller/valibot#631]
Cannot download codemod for migration.

```shell
npx codemod valibot/migrate-to-v0.31.0
```

> ✖ Downloading the "valibot/migrate-to-v0.31.0" codemod
>
> Error while downloading codemod valibot/migrate-to-v0.31.0: Error: Error getting download link for codemod

Reproducible on multiple devices. Would there be a workaround?

**Comment by fabian-hiller** [comment]
Thank you! I have forwarded this issue to the Codemod team.
