### ISSUE TITLE
Form submission proceeds despite validation errors using check in Valibot, causing formValue to be lost

### ISSUE THREAD

**Issue by yamatohagi** [fabian-hiller/valibot#632]
https://github.com/react-hook-form/resolvers/issues/690

**Describe the bug**
When using the `check` function (formerly `custom`) in Valibot for validation, if validation fails without a `path` in the error object, the form submission proceeds and `formValue` is lost. This results in `submit {}` being logged, even though validation errors are present.

**To Reproduce**
1. Go to the form with Valibot validation.
2. Set `isCustomerCancelNotify` to `true` and leave `customerCancelNotifyEmail` as an empty string.
3. Submit the form.
4. Observe that the form is submitted with an empty `formValue` and the console logs `submit {}`.

**[My Codesandbox ](https://codesandbox.io/p/devbox/valibot-rhf-bug-forked-6xt8fl?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clx4kg70i00063b6iytxxpfsj%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clx4kg70h00023b6io63lq7c8%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clx4kg70i00043b6itvve9w5f%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clx4kg70i00053b6in5xatlqm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clx4kg70h00023b6io63lq7c8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx4kg70h00013b6is9qwn7qi%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clx4kg70h00023b6io63lq7c8%2522%252C%2522activeTabId%2522%253A%2522clx4kg70h00013b6is9qwn7qi%2522%257D%252C%2522clx4kg70i00053b6in5xatlqm%2522%253A%257B%2522id%2522%253A%2522clx4kg70i00053b6in5xatlqm%2522%252C%2522activeTabId%2522%253A%2522clx4kr4wh00e63b6i8o7q846n%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clx4kr4wh00e63b6i8o7q846n%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clx4kg70i00043b6itvve9w5f%2522%253A%257B%2522id%2522%253A%2522clx4kg70i00043b6itvve9w5f%2522%252C%2522activeTabId%2522%253A%2522clx4kg70i00033b6iii82g710%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx4kg70i00033b6iii82g710%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clx4kg7bo000adaf837apenpq%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clx4kgg92007d3b6iiypv2g2i%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clx4kgg92007e3b6iq7qeufbf%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)**
Include a codesandbox will help us to investigate the issue quicker.

**Expected behavior**
The form should not submit when validation fails, and appropriate error messages should be displayed without losing `formValue`.

**Additional context**
Here are examples of the objects returned during validation:

"NG":
```json
{
    "issues": [
        {
            "kind": "validation",
            "type": "check",
            "input": {
                "isCustomerRsvNotify": false,
                "customerRsvNotifyEmail": "l32@gmail.comww",
                "isCustomerCancelNotify": true,
                "customerCancelNotifyEmail": ""
            },
            "expected": null,
            "received": "Object",
            "message": "Please enter a notification email address",
            "abortPipeEarly": true
        }
    ]
}
```

"OK":
```json
{
    "issues": [
        {
            "kind": "schema",
            "type": "union",
            "input": "ll32",
            "expected": "string | \"\"",
            "received": "\"l32\"",
            "message": "Invalid type: Expected string | \"\" but received \"l32\"",
            "path": [
                {
                    "type": "object",
                    "origin": "value",
                    "input": {
                        "isCustomerRsvNotify": false,
                        "customerRsvNotifyEmail": "l32",
                        "isCustomerCancelNotify": false,
                        "customerCancelNotifyEmail": ""
                    },
                    "key": "customerRsvNotifyEmail",
                    "value": "ll32"
                }
            ]
        }
    ]
}
```

The first object lacks a `path`, causing the submission to proceed despite validation errors.

I am willing to help fix this bug if guidance on the approach or the codebase is provided. Thank you for your assistance.

**Comment by fabian-hiller** [comment]
This is because the React Hook Form resolver implementation ignores errors that are not related to a nested field. This is not a bug in Valibot. The resolver should add root or unknown errors to a global error message, but I'm not sure if this is supported by React Hook Form.

**Comment by yamatohagi** [comment]
Thank you very much for the prompt reply, and also for providing such a wonderful library.

I largely agree with what you said, but I think it would be beneficial if the check method in Valibot had a mechanism to specify the path where the error should be displayed. What do you think?

**Comment by fabian-hiller** [comment]
This is possible with `forward`: https://valibot.dev/api/forward/

**Comment by yamatohagi** [comment]
Thank you very much. I was able to get it working correctly.
