### ISSUE TITLE
Conditionally validate using pipes

### ISSUE THREAD

**Issue by ttonyh** [fabian-hiller/valibot#645]
Now that the new version is released, what's the proper way to handle conditional validation? What's the best way to handle it based on parameters external to the schema (ie. not the typical scenario of "password" / "verify password")?

**Comment by fabian-hiller** [comment]
Update: Previously, `check` was not executed if the email field was untyped. This problem can now be solved with our new `partialCheck` action.

```ts
import * as v from 'valibot';

const RegisterSchema = v.pipe(
  v.object({
    email: v.pipe(
      v.string(),
      v.nonEmpty('Please enter your email.'),
      v.email('The email address is badly formatted.'),
    ),
    password1: v.pipe(
      v.string(),
      v.nonEmpty('Please enter your password.'),
      v.minLength(8, 'Your password must have 8 characters or more.'),
    ),
    password2: v.string(),
  }),
  v.forward(
    v.partialCheck(
      [['password1'], ['password2']],
      (input) => input.password1 === input.password2,
      'The two passwords do not match.',
    ),
    ['password2'],
  ),
);
```

**Comment by selrond** [comment]
Is it the recommended approach for performing conditional validation based on external (not another form field) condition as well?

**Comment by fabian-hiller** [comment]
It depends on the use case, but in most cases, you need a callback-based schema function like `lazy` or `custom`, or a validation action like `check`, `rawCheck`, or `partialCheck`. This ensures that the validation logic always uses the latest external data.

**Comment by selrond** [comment]
@fabian-hiller is it somehow possible to use methods / schemas / actions after the partial check?
For instance — I have a form field that can be nullable, and if it’s not null, I want to perform some complex validations on it — it seems that I’m on my own once I’m inside the forward method, and can’t make use of any valibot methods / schemas / actions

**Comment by fabian-hiller** [comment]
Sorry for the late reply. If you still have this issue feel free to share a minimal version of your schema. I am happy to help you.
