### ISSUE TITLE
Issue with enums

### ISSUE THREAD

**Issue by ispyinternet** [fabian-hiller/valibot#650]
tyring to use `_enum`

with javascript objects. It seems to me that it is only possible to successfully validate your value if the object key value pairs are the same. E.G:

This object works:

export const role = {
	'Admin': 'Admin',
	'User': 'User'
} as const;

but this one doesn't:

export const role = {
	'ADMIN': 'Admin',
	'USER': 'User'
} as const;

Unless of course I am doing something wrong 🫤

**Comment by fabian-hiller** [comment]
What does not work? It works for me. Take a look at [this playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1Xj1IFM4BeOAG96hAIIARALIBJAHKEAXEVEATEMFaEANCICqAZQCiAJUVFdqblEL0AvinQt2MBszYc4+pgAtuIZPyYAHTcrACuIAD6ABRc3ACUrk4eUNyoYaTwAhhBqMjY3AAKyFCW0V6+-lpwcUESMrKJjMkQPEGkEADmsWkZMIlAA).

**Comment by ispyinternet** [comment]
hmm, I'm using this in conjuction with superforms. Do you think there is anywhere this could cause the problem, otherwise I guess it must be user error.

**Comment by fabian-hiller** [comment]
Are you using the latest version of Valibot and Superforms?

**Comment by ispyinternet** [comment]
It's a user error. I was expecting to be able to validate with the key 🤦‍♂️ 

Is there a pattern that would make this easy to do?

**Comment by fabian-hiller** [comment]
What is your use case? Have you read the [enum guide](https://valibot.dev/guides/enums/)?
