### ISSUE TITLE
Suggestion to Use nil Instead of null_ for Primitive Value

### ISSUE THREAD

**Issue by samocodes** [fabian-hiller/valibot#656]
I would like to propose using `nil` as a replacement for `null_` for primitive values. This change would provide better clarity and readability.

**Comment by fabian-hiller** [comment]
Thank you for your feedback! Is it because of the underscore? If so, note that there are a few more schemas with the underscore suffix. `nil` is not part of JavaScript and TypeScript. That's why I used `null_` instead.

**Comment by samocodes** [comment]
I think It will also valid if its in uppercase, `NULL`

**Comment by fabian-hiller** [comment]
That's true but that we have a mix of lowercase and uppercase names for similar things. I prefer the underscore suffix in this case.

**Comment by fabian-hiller** [comment]
But what we can do is to add the alias export `export { null_ as null };` to the end of the `null.ts` file. Using a wildcard import you can write `v.null()` this way. It only does not work for direct imports.

**Comment by fabian-hiller** [comment]
The only confusing thing might be that VS Code recommends both `v.null` and `v.null_` when typing the function.
