### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by fabulousgk** [fabian-hiller/valibot#664]
Is there are Valibot Discord server?  Or maybe a server where Valibot sorta lives for support?

If not, would you all like to have one setup?

**Comment by fabian-hiller** [comment]
No, there is no Valibot Discord yet. Yes, if you are interested you can do the setup. 🙏 Let me know if you need anything.

**Comment by fabulousgk** [comment]
Here we go: https://discord.gg/sGhSfMWPgW

Real basic right now, can grow as desired.

**Comment by fabian-hiller** [comment]
Thank you very much! Do you have time and are you interested in moderating our Discord?

**Comment by fabulousgk** [comment]
I am glad to do so.  I am a Discord app dev (not Discord itself, like bots and other apps).

**Comment by fabian-hiller** [comment]
Thank you very much! I will close the issue. We can continue our conversation on Discord.
