### ISSUE TITLE
[bug] Decimal schema is expecting null

### ISSUE THREAD

**Issue by CestDiego** [fabian-hiller/valibot#665]
Decimal schema is broken on both pre-0.31 and 0.31 versions:

Repro steps in the [playground](https://valibot.dev/playground/):
```typescript
import * as v from 'valibot';

const DecimalSchema = v.pipe(
  v.string(),
  v.decimal('The decimal is badly formatted.')
);

const result = v.safeParse(DecimalSchema, "8.0");

console.log(result.issues);
```

<img width="1317" alt="image" src="https://github.com/fabian-hiller/valibot/assets/3291619/88ac7b27-5869-4e9a-928b-352a7a4f074d">

I would expect that 8.0 is a decimal. Am I holding this wrong?

**Comment by CestDiego** [comment]
Oh wait.. i just realized that "decimal" actually means it's just a base ten number. :')

What should I use if I want to make sure that my string `'8.0'` is indeed a number? and not only that but also a floating number?

**Comment by fabian-hiller** [comment]
> Oh wait.. i just realized that "decimal" actually means it's just a base ten number. :')

👍

> What should I use if I want to make sure that my string `'8.0'` is indeed a number? and not only that but also a floating number?

At the moment I recommend using `regex` or `check`, but if you have a great name I am happy to add a new action to validate if a string is a valid number.
