### ISSUE TITLE
"Issues" field of SafeParseResult shows up in ts autocomplete after the type was narrowed with `.success`

### ISSUE THREAD

**Issue by dearlordylord** [fabian-hiller/valibot#684]
It's a minor devex issue but I believe can be easily avoided; default expectation from libs is that the "errors" ("issues" in this case) field is not present after it's clear that the discriminated union is not a error-ish.

<img width="572" alt="Screenshot 2024-06-29 at 5 17 35 PM" src="https://github.com/fabian-hiller/valibot/assets/947595/1ea64ac7-da2e-4e86-ae3a-caccca57aa7e">

Maybe just removing https://github.com/fabian-hiller/valibot/blob/2d2e553b1ad18e0e68bcfb2870dd138c8987982d/library/src/methods/safeParse/types.ts#L33 solves it?

(thanks for the lib, it's so far really pleasant API to use)

**Comment by fabian-hiller** [comment]
This is intended. Our `SafeParseResult` type basically represents exactly the data that is returned and `.issues` is always present as you can see [here](https://github.com/fabian-hiller/valibot/blob/v0.35.0/library/src/methods/safeParse/safeParse.ts#L34).
