### ISSUE TITLE
First-person voice in the docs are a pain read

### ISSUE THREAD

**Issue by jsudelko** [fabian-hiller/valibot#687]
The first-person Valibot voice seems cute but has been a terrible experience when you just want to get work done and some random sentence is written in first person. I'm often broken out of flow often to translate into third person to understand what it means. 

> In addition, I can help you to perform more detailed validations and transformations with the [pipe](https://valibot.dev/api/pipe/) method.

😒

1) It is harder to read. It is likely often 0 value for developers and in my case almost always negative value.
2) It _probably_ harder to write for you (and contributors). Writing in first-person likely needs you to mentally translate from a "regular" voice only for us readers to mentally translate it back.

Please write docs normally. No first-person please.

**Comment by fabian-hiller** [comment]
Thank you for your feedback. I will consider it in the long run.

**Comment by benweier** [comment]
For what it's worth, I love the personality this brings to the docs but can understand it's not for everyone

**Comment by fabian-hiller** [comment]
I agree. Up until now, the current approach has had many benefits for the project. It has helped us tell a story and differentiate ourselves from other projects.

**Comment by vladshcherbin** [comment]
Oh wow, I also wanted to create same issue long time ago.
Reading the docs always felt so weird, happy to see I'm not the only one 😅
Never had such issue with other libraries docs though.

**Comment by fabian-hiller** [comment]
Thank you for your feedback!

**Comment by naourass** [comment]
This is something that annoys and confuse me too when reading the documentation. I really can't follow the storytelling style, to the point that I try to completely avoid reading it. That being said, I still use Valibot as the main validation library in my project and I'll continue to use it.

BTW, here's a HN discussion about someone not wanting to consider Valibot just for that:
https://news.ycombinator.com/item?id=41790418

**Comment by fabian-hiller** [comment]
Thank you for your feedback! I will probably change this before our v1 release.

**Comment by onecreative** [comment]
Too bad. I found it refreshing and fun.

**Comment by benweier** [comment]
😢 

> Too bad. I found it refreshing and fun.

I'm with you, mate. It made the docs enjoyable to read.

**Comment by fabian-hiller** [comment]
Sorry 😌

**Comment by onecreative** [comment]
There's no way you're going to please everybody. 😄

**Comment by naourass** [comment]
I believe that:
- People who tolerate the story telling style could still use the docs easily without it.
- People who don't tolerate the story telling style would have a very hard time using the docs.

So it's a wise decision to drop it and this will make the docs usage experience decent for both categories.

**Comment by fabian-hiller** [comment]
I kept the first-person voice in the README and the introduction guide. I think it is a good mix.
