### ISSUE TITLE
Attempted import error: 'getDotPath' is not exported fom 'validbot' (imported as 'o')

### ISSUE THREAD

**Issue by cosmemarins** [fabian-hiller/valibot#689]
Error when running yarn dev

package.json:

    "react-hook-form": "^7.51.3",
    "@hookform/resolvers": "^3.3.4",
    "valibot": "^0.30.0"

Login.tsx:

    import type { SubmitHandler } from 'react-hook-form'
    import { valibotResolver } from '@hookform/resolvers/valibot'
    import * as v from 'valibot'

![image](https://github.com/fabian-hiller/valibot/assets/20206057/5ddf2191-53e4-4847-9e9c-6669dc41b29f)

**Comment by fabian-hiller** [comment]
Please downgrade `@hookform/resolvers` or upgrade `valibot`

**Comment by himanshu007-creator** [comment]
Hey @fabian-hiller , please update here once the fix is made.

**Comment by fabian-hiller** [comment]
The fix is to downgrade `@hookform/resolvers` or upgrade `valibot`
