### ISSUE TITLE
Typesafe introspection

### ISSUE THREAD

**Issue by joshuajaco** [fabian-hiller/valibot#690]
Sorry to reopen the [introspection discussion](https://github.com/fabian-hiller/valibot/issues/258) again, but I've been wondering if there should be support for introspecting schemas without listing them all in a union yourself.

In the meantime I've created [valibot-introspection](https://github.com/joshuajaco/valibot-introspection), which essentially is just a [large union of all schemas ](https://github.com/joshuajaco/valibot-introspection/blob/main/src/schema.ts).

Here's an example of how it could be used to generate [constraint validation](https://developer.mozilla.org/en-US/docs/Web/HTML/Constraint_validation) attributes from a valibot schema: [TS Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAIg2QBtgAjCGQgbgFgAoUSWOAbzmADsY9UwAUwDG8AL448BYmUrUAtDz4QBImMAjc6TJjACeQuAGFNqPsiXoAvByZw4UQQEcArsEcATAPwAuOFQhSQWRuBkZ7EB4g7gBzGAALXzhuFxAKQSgwiOQAD2i4xL8UtIywsTCmbBduUQ1uOBjBGAAxYEFSDxNuMygLXlQAHgAVAFFeKDb0QRyYQW4PdAwAOgB5CgArNTG+SYA+AAo7OFRheMEQZD9ltc3RAGVT8+Rh7YnBVAAaFG49XY+j7jIECCPwAa0Eegg2Dgo3Gk3+jAAlH4uj0+jB0OwjkF4Ng2h0HmcLnAbEp+EJRPsTkTkEs5jt3gBtQHAgC6iKycGEpng3O65ksKJ5vUsJI45R04S40P2ePaHkJTyW+kMVjVRAgYHUmjIhERtil9jlBMexNJ4xUFJgsvxCtNtIA7r0wEIPByjhJ2qhBAb7PY+WjLEtHK53IIPGK+C5BJyxJL7MAZYQwMAhIQuPVjXaafqsYauTy4JFuPkEgBBWqaMVZxUXJYpoRLPHzQ75+z7YCzED6qy7LhdpagngRtU2GTkDzIbVaOAAMln-fOyoMPtHRGLAH1S-FCAi-XB3YwjgmZcXtxXp7nj36AwL+ksz3MCmLH7Fy5XuMHnG5HMDeJz7DjI981vItcnPD9q1tWtaQbQQm2HVt93bTtzh7PtUJAQdhxJdVx2ASdp3TedFywlVVzwi4ci3J8El3a9D2vRM4H2KiIMvX1kNvEV7zY2j4hfcD+IvOov1DX96QAuAgMA+MHCaFwoHqbj0VQMpJVA7BoBAGCxWWCANjUfY83sFkQUwetU0EfZlh6HgYn2REvmWYsABl+P2ABGJyLKo9y33ifYAFYAAZEScgFgGEUEADkgXM-StTqMgbMsoRUrs2JHOch9cn8govJCsLwoRMRGMYUCzNRO8MTFRoWltaqeIxWVtJgr5CDMvUwkqqLYviprVLqppWnlQbLFaqAdPtDruD6uLgW6jTTECeDSAgBzOCq4VVK+ObooWwRxv6aTDyAA) 

Let me know if this is something you are interested in supporting, or if it should stay as a separate library.

**Comment by fabian-hiller** [comment]
Personally, I recommend specifying `GenericSchema` and/or any specific schema type you support. This gives you more control over your code and allows you to specify what kind of schema your function supports. Note that we have added an `isOfKind` and `isOfType` type guard utility for better DX.
