### ISSUE TITLE
Empty email field validation

### ISSUE THREAD

**Issue by robodna** [fabian-hiller/valibot#697]
I have a form with 2 email fields.  I added the following validation:

`        email_work: v.pipe(v.string(), v.nonEmpty(), v.email()),
        email_home: v.nullish(v.pipe(v.string(), v.email())),`

I'm using ModularForms with SolidJS.

When I add an exclamation mark to the email_home field, it shows an error as I expect.  If i delete the exclamation mark and leave the email_home field empty, an error remains showing Invalid email: Received "".  I expect no validation error as I used v.nullish.

Any ideas on what I may be doing wrong or does this look like a bug?

Thanks,

**Comment by fabian-hiller** [comment]
Here is a fix. Try it out in our [playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgGUmALAUxDI4AXkwA6CBQBWfJjAAUAb3pw4A5MFIB9AO7QA1gC5xYYGD7yMYjlGCsA5vICUAGnHrNz1yrWDNWnnw+YysAV1ZgNnkAbStyGD4oMnlCQlcTMwsrGztHdKsPUi8AXW8AXycGZjYOOCg+VFDSeFFs5Gw+AAVkKFQLbn5BN2VVQt0DY0IpZFY+AAE+AA9kcFI+MRYQQhcfMcCQYKJt+gqqlnYINbFSCEd6xubKoA).

```ts
const Schema = v.object({
  email_work: v.pipe(v.string(), v.email()),
  email_home: v.union([v.literal(''), v.pipe(v.string(), v.email())]),
});
```
