### ISSUE TITLE
Enum type returns string

### ISSUE THREAD

**Issue by jdgamble555** [fabian-hiller/valibot#70]
I have a schema like this:
```ts
const postSchema = object({
    status: optional(enumType(['publish', "future", "draft", "pending", "private", "trash", "auto-draft", "inherit"]))
});
```
However, this returns a string type.  While it does validate this correctly, the typing is not the correct type.

This is not the expected result as 'string' and 'enum' are completely different.  If I pass the `result.data.status` to an enum type, I get an error because it is a string type, while technically validated.

J

**Comment by fabian-hiller** [comment]
Does it work with `as const`?

```ts
const postSchema = object({
  status: optional(
    enumType([
      'publish',
      'future',
      'draft',
      'pending',
      'private',
      'trash',
      'auto-draft',
      'inherit',
    ] as const)
  ),
});
```

**Comment by jdgamble555** [comment]
Yes, that seems to fix the problem.  Shouldn't this be done automatically under the hood?

J

**Comment by fabian-hiller** [comment]
If it is possible, then yes. Maybe I can do the conversion to readonly in the library code. I will check this.

**Comment by fabian-hiller** [comment]
I was able to solve the problem. With the next update the changes will go live.
