### ISSUE TITLE
Codemod with `toTrimmed` fails

### ISSUE THREAD

**Issue by hyunbinseo** [fabian-hiller/valibot#717]
This code does not work with codemod:

```js
// Original
import { minLength, object, string, toTrimmed } from 'valibot';
const FormSchema = object({ 'given-name': string([toTrimmed(), minLength(1)]) });
```

```js
// Modified
import { minLength, object, string, trim, pipe } from "valibot"bot';
const FormSchema = object({ 'given-napipe(string(), trim() , minLength(1))ength(1)]) });
```

## Notes

Received the following error in another repository. Cannot reproduce in this MRE.

> Error: Cannot split a chunk that has already been edited (31:26 – "toTrimmed")

I might be using an outdated codemod? It automatically used the cached version.

```shell
pnpm dlx codemod valibot/migrate-to-v0.31.0
```

```
✔ Successfully fetched "valibot/migrate-to-v0.31.0" from local cache.
╭───────────────────────────────────────────────────────╮
│                                                       │
│                                                       │
│      Codemod: valibot/migrate-to-v0.31.0@0.2.2        │
```

**Comment by fabian-hiller** [comment]
Thank you for reporting this. I am not sure we can fix this. This looks like a bug in the libraries our codemod is based on.

**Comment by hyunbinseo** [comment]
You can close this issue as `closed as not planned`.

I am fine as long as people can search this issue and reference it.

I personally still have Valibot v0.29 projects to migrate from :)
