### ISSUE TITLE
Recursive schema

### ISSUE THREAD

**Issue by ZerNico** [fabian-hiller/valibot#72]
Hello there!
At the moment there seems to be no way to use a recursive schema.

Zod for example does it like this:
```typescript
const baseCategorySchema = z.object({
  name: z.string(),
});

type Category = z.infer<typeof baseCategorySchema> & {
  subcategories: Category[];
};

const categorySchema: z.ZodType<Category> = baseCategorySchema.extend({
  subcategories: z.lazy(() => categorySchema.array()),
});
```

Maybe there even is a way to do this without having to manually define a type, I know some validation lib had that feature, I just can't remember which one it was. It might not be possible with the way Valibot works, though.

**Comment by fabian-hiller** [comment]
This should work with [`recursive`](https://github.com/fabian-hiller/valibot/blob/main/library/src/schemas/recursive/recursive.ts).

**Comment by ZerNico** [comment]
Awesome, I even looked through the code, must have totally overlooked it then, thanks!

Is this the right approach to use it then?

```typescript
import { BaseSchema, object, recursive, string, parse, Output, merge, array } from "valibot";

const baseCategorySchema = object({
  name: string(),
});

type Category = Output<typeof baseCategorySchema> & {
  subcategories?: Category[];
};

const categorySchema: BaseSchema<Category> = merge([baseCategorySchema, object({ subcategories: recursive(() => array(categorySchema)) })]);

const result = parse(categorySchema, {
  name: "People",
  subcategories: [
    {
      name: "Politicians",
      subcategories: [
        {
          name: "Presidents",
          subcategories: [],
        },
      ],
    },
  ],
});
```

**Comment by fabian-hiller** [comment]
Looks good. Does it work as expected?

**Comment by ZerNico** [comment]
Jup seems to work fine. An example like this could probably be added to the docs then.
This is exactly the example from Zod but converted to Valibot.

**Comment by fabian-hiller** [comment]
As soon as I find the time, I'll probably add advanced guides to the docs and include that. Thanks for your contribution!

**Comment by firxworx** [comment]
Random (related) question/confirmation as I check out valibot for the first time :) ...

I was curious to see if the following would be the right approach to parsing a general JSON value with Valibot?

```ts
import {
  type BaseSchema,
  type Output,
  union,
  boolean,
  number,
  string,
  nullType,
  recursive,
  array,
  record,
} from 'valibot'

export type JsonPrimitive = Output<typeof vJsonPrimitive>
export type Json = JsonPrimitive | { [key: string]: Json } | Json[]

export const vJsonPrimitive = union([number(), boolean(), string(), nullType()])

export const vJson: BaseSchema<Json> = union([
  vJsonPrimitive,
  recursive(() => array(vJson)),
  recursive(() => record(vJson)),
])
```

Note zod's docs have a similar example (https://github.com/colinhacks/zod#json-type):

```ts
const literalSchema = z.union([z.string(), z.number(), z.boolean(), z.null()])
type Literal = z.infer<typeof literalSchema>
type Json = Literal | { [key: string]: Json } | Json[]
const jsonSchema: z.ZodType<Json> = z.lazy(() => z.union([literalSchema, z.array(jsonSchema), z.record(jsonSchema)]))
```

This is a common use-case... let me know if you are open to adding it to the docs (I am happy to make a PR if I can confirm this is the right approach with valibot :) ).

**Comment by fabian-hiller** [comment]
The code looks good to me. For the docs, the most I would change is some naming. However, at this point I don't know where I would add it to the docs. Right now the focus is not on the docs. But that will change in the next few weeks. It might even make sense to add a `json` schema to Valibot instead of adding this functionality to the docs.

**Comment by fabian-hiller** [comment]
Also, it might be interesting to add some kind of `json` validation function to be able to check in a string pipeline if a input corresponds to stringified JSON.

**Comment by fabian-hiller** [comment]
Lazy (formerly recursive) schemas are now documented here:
- https://valibot.dev/guides/other/#lazy-schema
- https://valibot.dev/api/lazy/
