### ISSUE TITLE
Complex error messages using enums

### ISSUE THREAD

**Issue by shossk** [fabian-hiller/valibot#722]
Hello, @fabian-hiller 

I am very fond of Valibot and am very pleased that it can be integrated into various projects.

There is one thing I don't understand how to do, so I would appreciate it if you could help me.

I want to define an enum so that only certain values pass the check. For other values, I want to display different error messages based on the enum values. Is this possible?

For example:

- Pass if it is ValueA
- Do not pass if it is ValueB, and display the error message “Did you think it was ValueB?”
- Do not pass if it is ValueC, and display the error message “Why did you think it was ValueC?”

That’s the kind of image I have in mind.

Here is the code that is close to what I tried.

```JS
const EnumSchema = union([
  literal('ValueA'),
  literal('ValueB'),
  literal('ValueC'),
]);

const Schema = object({
  value: pipe(
    EnumSchema,
    check((input) => input === 'ValueA'),
    check((input) => input !== 'ValueB', 'Did you think it was ValueB?'),
    check((input) => input !== 'ValueC', 'Why did you think it was ValueC?'),
  ),
});
```

**Comment by devcaeg** [comment]
Check:

https://valibot.dev/api/enum/
https://valibot.dev/api/picklist/

**Comment by shossk** [comment]
@devcaeg 
Thank you! I thought the way I was using Enum might be incorrect, but I believed that turning this into a Picklist or Enum wouldn’t directly solve the issue of handling error messages individually. I also checked the documentation, but it seemed there was no method to display error messages separately.

**Comment by devcaeg** [comment]
You can do it in these two ways, if I am not mistaken, you are on the right track.

```ts
enum EnumSchema {
  ValueA = 'ValueA',
  ValueB = 'ValueB',
  ValueC = 'ValueC',
}

const Schema = object({
  value: pipe(
    enum_(EnumSchema),
    check((input) => input === EnumSchema.ValueA),
    check(
      (input) => input !== EnumSchema.ValueB,
      'Did you think it was ValueB?',
    ),
    check(
      (input) => input !== EnumSchema.ValueC,
      'Why did you think it was ValueC?',
    ),
  ),
});
```

OR

```ts
const EnumSchema = ['ValueA', 'ValueB', 'ValueC'] as const;

const Schema = object({
  value: pipe(
    picklist(EnumSchema),
    check((input) => input === 'ValueA'),
    check((input) => input !== 'ValueB', 'Did you think it was ValueB?'),
    check((input) => input !== 'ValueC', 'Why did you think it was ValueC?'),
  ),
});
```

**Comment by fabian-hiller** [comment]
Thanks for your help @devcaeg!

**Comment by shossk** [comment]
@devcaeg 

```JS
const EnumSchema = ['ValueA', 'ValueB', 'ValueC'] as const;

const Schema = object({
  value: pipe(
    picklist(EnumSchema),
    check((input) => input === 'ValueA'),
    check((input) => input !== 'ValueB', 'Did you think it was ValueB?'),
    check((input) => input !== 'ValueC', 'Why did you think it was ValueC?'),
  ),
});
```
If you do this, you will get the following message in the case of ValueB
message: “Invalid input: Received \”ValueA\“”,.
error should appear.
Is there a cleaner answer?

Maybe what I'm looking for is something like zod's ZodErrorMap where you can customize the error message with return.

If you have difficulty understanding what I am saying, please let me know. I will describe it in more detail.

**Comment by shossk** [comment]
@fabian-hiller 
Thank you very much! It looks like we can make it happen!
Ideally, I would like to use enum for literal as well, so that I can't do literal(“ValueD”), and I would like the completion of ValueB and ValueC to work for issue.input as well, is this possible?
Also, for future reference, what should go in issue.message?

**Comment by fabian-hiller** [comment]
> Also, for future reference, what is in `issue.message`?

This is the default error message that Valibot creates internally. It is used as a fallback in this schema for any other value.

> Ideally, I would like to use enum for literal as well, so that I can't do literal(“ValueD”), and I would like the completion of ValueB and ValueC to work for issue.input as well, is this possible?

I do not fully understand you? Can you give an example or describe the behavior of the schema when different inputs are used?

**Comment by shossk** [comment]
@fabian-hiller 
Sorry for the confusion, but I would like to solve the problem of `issue.input` being unknown in this case, is it impossible?

```JS
const EnumSchema = ['ValueA', 'ValueB', 'ValueC'] as const;

const Schema = v.object({
  value: v.pipe(
    v.picklist(EnumSchema),
    v.literal('ValueA', (issue) =>
    issue.input === 'ValueB' // this issue.input type is unkwnon
      ? 'Did you think it was ValueB?'
      : issue.input === 'ValueC'
        ? 'Why did you think it was ValueC?'
        : issue.message,
  )
  ),
});
```
[playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgFFWBXEAZSYALAKYhkcALxwA2oQBqZHiICChADRFFpZQCENWpSIDChALop0LdjAbM2HOINHipmAHQQKAKxFMYABQA3vRwmEYAXB5gwGAiAaFh0cBMANbkHAHcfM5iyACU6olhGO7kMCJQZAEKRmqaAcCoqMr5UgB8xXBNLSLuwKxgPPCSo4Y6IvpwAPTTcDBCTd3Nyv2Dw-MAnnHLcDysqQDurGxdYQD8RAAiwAAmcJsQPPOLB93wh2hw2nrnhGdwKI9VYDIYjMa1CamAEXIgAdSEmzgtzuDyeLwGqXecE+6B+Jj+MMBy167hAImayAA5iIimF8olCvQAL75OzWRxQCk8UgjDyoZDYEQABWQUFQ8Vy4k0QXCEyikL0hDgrPZDggpD6pAgVICXJavLZ9CAA)

**Comment by fabian-hiller** [comment]
Yes, this is possible, but I am not sure if it really makes sense to use `picklist` or `enum` in this case. Checkout [this playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgGUmALAUxDI4AXkwA6CBQBWfJjAAUAb3pxMZAK58AXOLDAwfeStW7gTANbkO8gNqEAahr4BBQgBoij0poBC7z04AwoQAugCUbsaqGGK8suZGJibywKxg6jBhIgB8cKnp8MJFAd4u7lHJwKiomlnC2RVJVTV8YvkZIsUOTn6NSXAA-EQAIsAAJnAAnhDqcDA8qeZ58ADuaHBevgOEfUk6hADqPJNwY+NTM3MLrEvAq+ubfIHbkUkRxu8AvmEMzGwccCgfBqpEK4lQyGwfAACsgoKhDNx+IIPIo1KV9o8-HBvr8WOwIKRWqQIABzeRAkGZBhAA).

```ts
import * as v from 'valibot';

const Schema = v.object({
  value: v.pipe(
    v.picklist(['ValueA', 'ValueB', 'ValueC']),
    v.check(
      (input) => input === 'ValueA',
      (issue) =>
        issue.input === 'ValueB'
          ? 'Did you think it was ValueB?'
          : 'Why did you think it was ValueC?',
    ),
  ),
});
```

**Comment by shossk** [comment]
@fabian-hiller @devcaeg 
Thank you very much.
This will now be resolved. Thank you for responding to my question.
