### ISSUE TITLE
 Error: 'pipe' not found in imported namespace 'v'

### ISSUE THREAD

**Issue by cosmemarins** [fabian-hiller/valibot#723]
Error when running npm run build or yarn build

package.json:

    "react-hook-form": "7.51.5",
    "@hookform/resolvers": "3.6.0",
    "valibot": "0.31.1"

I tried too:

    "react-hook-form": "7.51.5",
    "@hookform/resolvers": "3.6.0",
    "valibot": "0.36.0"

![image](https://github.com/user-attachments/assets/f8a1298e-a1ef-440f-92dd-6ede6fcafa4e)

Login.tsx page

![image](https://github.com/user-attachments/assets/a8155571-b0ba-4470-acc1-0a714ea16e23)

**Comment by fabian-hiller** [comment]
Please try again after updating everything to the latest version.

```
"react-hook-form": "7.52.1",
"@hookform/resolvers": "3.9.0",
"valibot": "0.36.0"
```

**Comment by cosmemarins** [comment]
I tried but it didn't work

The error is only on production, locally it works

It worked for me by separating the import pipe

    import * as v from 'valibot'
    import { pipe } from 'valibot'
    ...
    const schema = v.object({
      email: pipe(v.string('É preciso digitar um email'), v.email('Email inválido')),
      password: pipe(v.string('É preciso digitar uma senha'), v.minLength(5, 'A senha deve conter no mínimo 5 caracteres'))
    })

**Comment by fabian-hiller** [comment]
Thanks for the info. I will leave this open for now to see if more people encounter this problem.

**Comment by mxa0079** [comment]
I am also running into this issue (or am I missing something?). The workaround did not work for me:

![image](https://github.com/user-attachments/assets/977af7dc-771c-4220-8528-653a727fcd80)

Dependencies versions:

```
    "react-hook-form": "^7.52.2",
    "@hookform/resolvers": "^3.9.0",
    "valibot": "^0.37.0",
    "@typeschema/valibot": "^0.13.5",

```

**Comment by mxa0079** [comment]
Update, the workaround did work by downgrading to version 0.36:

![image](https://github.com/user-attachments/assets/7f860d33-5ffd-4db7-8e6f-20870ff19a40)

**Comment by fabian-hiller** [comment]
Yes, I think the problem is that some packages may use a different version of Valibot.

**Comment by mxa0079** [comment]
Some packages as in the hookform resolvers?

**Comment by fabian-hiller** [comment]
Could be. If more people encounter this problem, I will look into it.

**Comment by outranker** [comment]
i am also facing a similar issue. in my case, it is throwing `TypeError: Cannot read properties of undefined (reading 'object')` error.
this is how i am using it:
```
import v from 'valibot';

key: v.pipe(v.string(), v.transform(input=>input))
```
i have other fields as well but the error is being thrown only from v.string in the pipe.

**Comment by fabian-hiller** [comment]
Can you try to change your import to `import * as v from 'valibot';`?

**Comment by outranker** [comment]
> Can you try to change your import to `import * as v from 'valibot';`?

it is working if i do it that way. thank you

**Comment by fabian-hiller** [comment]
This seems to be fixed.
