### ISSUE TITLE
Proposal to Make Prettify Type in Valibot Overridable for Better Developer Control

### ISSUE THREAD

**Issue by devcaeg** [fabian-hiller/valibot#728]
The `Prettify` type is an internal type used by `Valibot`. It acts as a “trick” in `TypeScript` to “unroll” the types, making them easier for the end user to understand. However, the `Prettify` type can cause issues because it “decomposes” the types, potentially leading to uncommon errors in `TypeScript`. Therefore, I propose that this type be declared in a `declare module 'valibot'` block. This would allow developers to override the type in their projects if, for example, they want to negate its effects.

```ts
declare module 'valibot/types' {
    export type Prettify<TObject> = {
        [TKey in keyof TObject]: TObject[TKey];
    } & {};
}
```

**Comment by fabian-hiller** [comment]
Thanks for bringing this up! I agree and will look into it, but it may take some time as other things have a higher priority for me right now.

**Comment by devcaeg** [comment]
@fabian-hiller 

I just created a pull request, feel free to review it when you have time. Thank you very much!
