### ISSUE TITLE
Valid emails being flagged as invalid

### ISSUE THREAD

**Issue by ray73864** [fabian-hiller/valibot#730]
There are quite a few valid email addresses according to the standard that this flags as invalid.

A big one that I use quite a fair bit is the 'tag' feature
```email+tag@example.com```

Gmail for instance will send the email to the correct email address, in this case 'email@example.com' and label it with the 'tag' label.

So for instance, if you are subscribed to a newsletter, you could do 'fred+newsletter@gmail.com' and it will be auto-labelled with the label 'newsletter'.

It also fails with mailhost style routing, eg ```mailhost!test@example.com```

**Comment by fabian-hiller** [comment]
Emails like `email+tag@example.com` should work. Take a look at [this playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgGUmALAUxDI4AXkwA6MMDB8AFBjEcowVgHMZASgA04gcmCkN6hszYc4UPqgCupeKPmpk2PgAVkUVLO79B2wrv0AahhkFQABPgAPZHBSPjEWEEIjRhZ2CDixUgg1C2tbIyA).

Our `email` action is intentionally limited to "normal" email addresses. See #204 for more details.
