### ISSUE TITLE
General variant key override

### ISSUE THREAD

**Issue by vladshcherbin** [fabian-hiller/valibot#735]
Hey :wave:

I'm trying to validate data:

```js
const data = {
  properties: [
    { name: 'brand', value: 'Aito' },
    { name: 'immobilizer', value: true },
    { name: 'esp', value: true }
  ]
}
```

I want to validate only **some** of values:

- if name `brand` - value should be `string`
- if name `immobilizer` - value should be `boolean`
- other objects with other names can have any value

I've tried to validate using `variant` - [playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgBNkZk4BeOAG96cOGDxgAprGBTUALjgBtUWOFxWyEFKWEKUZK06EANJjIBXXUQCCwGBEJwAvqbVihm7TcKgQEBTA5ABeMmYWpNZKMFDWru7qGlo6evJgESRRNrHxLmoAuvT5zGwccKhMABZSIHyCGAB0gQBWUkwwABQiYhIQ0rLySk3IUIYAnp0emI0kUMBGXYQpUhGqSWJNre1dPRtiK8ON5DAyZJ36hsaEAJSJ+5HRMxzzrADmnTfTYi533zPbDrdf4HHxHE5nUgXfyBYLAMJQW73fZZJ5NKgQUhSIyff6-ZHqLYUNpAvb7Q7PWLAd6fAlJVE2JqWVgAa1YEAA7qxcftftMCl8xF8+aV2PAoPJLKR4A1GmBRqgpJ1KjU6uZuLwvqLUJipMcIB8JagpTAbrQgA)

It works, however using `v.string()` as a key overrides any `v.literal()`  values used before, so any object with any key or value will pass - [playground with invalid type but no error](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgBNkZk4BeOAG96cOGDxgAprGBTUALjgBtUWOFxWyEFKWEKUZK06EANJjIBXXUQCCwGBEJwAvqbVihm7TcKgQEBTA5ABeMmYWpNZKMFDWru7qGlo6evJgESRRNrHxLmoAuvT5zGwccKhMABZSIHyCGAB0gQBWUkwwABQiYhIQ0rLySk3IUIYAnp0emI0kUMBGXYQpUhGqSWJNre1dPRtiK8ON5DAyZJ36hsaEAJSJ+5HRMxzzrADmnTfTYi533zPbDrdf4HHxHE5nUgXfyBYLAMJQW73fZZJ5NF7Ad6ff6-ZHqLYUNpAvb7Q7PWKYj5-B6PGxNSysADWrAgAHdWNj9r9pgUvmIvtzSux4FB5JZSPAGo0wKNUFJOpUanVzNxeF8hagIKQpMcIB9RahxTAbrQgA)

When I remove general `v.string()` key variant the validation works correctly but I can't have objects with keys I've not defined:

- [correct validation playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgBNkZk4BeOAG96cOGDxgAprGBTUALjgBtUWOFxWyEFKWEKUZK06EANJjIBXXUQCCwGBEJwAvqbVihm7TcKgQEBTA5ABeMmYWpNZKMFDWru7qGlo6evJgESRRNrHxLmoAuvT5zGwccKhMABZSIHyCGAB0gQBWUkwwABQiYhIQ0rLySk3IUIYAnp0emI0kUMBGXYQpUhGqSWJNre1dPRtiK8ON5DAyZJ36hsaEAJSJ+5HRMxzzrADmnTfTYi533zPbDrdf4HHxHE5nUgXfyBYLAMJQW73fZZJ5NF7Ad6ff6-aYFL5iL640rseBQeSWUjwBqNMCjVBSTqVGp1czcXhfEmoCCkKTHCAfcmoSkwG60IA)
- [invalid key error playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgBNkZk4BeOAG96cOGDxgAprGBTUALjgBtUWOFxWyEFKWEKUZK06EANJjIBXXUQCCwGBEJwAvqbVihm7TcKgQEBTA5ABeMmYWpNZKMFDWru7qGlo6evJgESRRNrHxLmoAuvT5zGwccKhMABZSIHyCGAB0gQBWUkwwABQiYhIQ0rLySk3IUIYAnp0emI0kUMBGXYQpUhGqSWJNre1dPRtiK8ON5DAyZJ36hsaEAJSJ+5HRMxzzrADmnTfTYi533zPbDrdf4HHxHE5nUgXfyBYLAMJQW73fZZJ5NKgQUhSIyff6-aYFL5iL740rseBQeSWUjwBqNMCjVBSTqVGp1czcXhfMmoTFSY4QD6U1DUmA3WhAA)

I've tried using other options like `tuple`, `union` or even `pipe` but I can't figure out how to do this 😭

**Comment by fabian-hiller** [comment]
There are a few ways to fix this. One of them is to `pipe` `string` with `notValue`. Check out [this playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgBNkZk4BeOAG96cOGDxgAprGBTUALjgBtUWOFxWyEFKWEKUZK06EANJjIBXXUQCCwGBEJwAvqbVihm7TcKgQEBTA5ABeMmYWpNZKMFDWru7qGlo6evJgESRRNgCMAEwAzAlqALruLgzMbBxwqEwAFlIgfIIYAHSBAFZSTDAAFCJiEhDSsvJK7chQhgCefR6YbSRQwEb9hClSEapJYu1dPf2Du2KbE23kMDJkffqGxoQAlIknkdGLHCusAOZ9zwtiFz-E77CjdXoDAHqM6LS7XUi3fyBYLAMJQJ4vEFWGztKgQUhSIx-THqIEkvYdMGHSGvbypRZgYDSea0imfYA-YlQpLtVjUABq2NuBiMJmBrN5AqFfhAASCoXC4pOSt2WXe7UsrAA1nyAO6sLknMkLEri-5AyosdjwKDySykeCtNpgKaoKR9OqNZrmbi8R6W6r4qQXCC-W2oe0wf30IA).

```ts
import * as v from 'valibot';

const schema = v.object({
  properties: v.array(
    v.variant('name', [
      v.object({
        name: v.literal('brand'),
        value: v.string(),
      }),
      v.object({
        name: v.literal('immobilizer'),
        value: v.boolean(),
      }),
      v.object({
        name: v.pipe(
          v.string(),
          v.notValue('brand'),
          v.notValue('immobilizer'),
        ),
        value: v.unknown(),
      }),
    ]),
  ),
});
```

**Comment by vladshcherbin** [comment]
@fabian-hiller holy moly, man, it works! I've actually thought to search for some kind of `not` method but tried to figure out it the standard way. I have less than 10 params and can live with this workaround, thank you! 🎉 

Do you think it can be somehow improved?
Like a special case for `variant` or maybe a special method?
I feel like it's a pretty common case - e.g. when you receive a product via API with params and only want to validate some while the rest you don't care.

**Comment by fabian-hiller** [comment]
Yes, since we put a lot of effort into type safety, you can easily extract the names of a variant schema in a type-safe way. You can then use this information to validate unknown data using our `custom` schema or `check` action. Check out [this playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgGUmALAUxDIAjHAC8mAHQkowZKxgAKQq2Qg+hADRwA2vTiSIFAFZ8migN579cFWoBck8jD5QySiq9YATQgEoNVvokpACufA4YEhwyrADmCv5WAL6JQRKGJmYKltY2quGOwM6upEqgIIbA5ABeLn4BucFhERJUEKR8cgkNcCkBALq+DMxsHHAAIgCiAGIAggCqADIAKgD6AHKzALKTnA7RwHHa-WJw3PyCQulgMMCjEoJgClYKEDd3rL5iAHxwb7dsCR8eQyPioCS2PgSJwuMgBIaMFjsLi8ATIABMp0i0lk8iUkM0Ois5zRQh6kQypgsgTy9kkYGAYD4z1yaQOcW6NLSqKYAGsFApDmAQjAvqJfgBCKZzJZrTY7TgSQ5MUJeMGC1jC0Wpaw6oJkZqSEKsXmsCAAd1YnP0fXog2GSLGUDBIVI8HEkTAyCgqGZJME6K05lpBUIHjkPi0TQKQnRAGZegiRux2lDSBB4s7UK7RQwgA).

```ts
import * as v from 'valibot';

const Schema1 = v.variant('name', [
  v.object({
    name: v.literal('brand'),
    value: v.string(),
  }),
  v.object({
    name: v.literal('immobilizer'),
    value: v.boolean(),
  }),
]);

const DEFAULT_NAMES: string[] = Schema1.options.map(
  (option) => option.entries.name.literal,
);

const Schema2 = v.variant('name', [
  Schema1,
  v.object({
    name: v.pipe(
      v.string(),
      v.check((input) => !DEFAULT_NAMES.includes(input)),
    ),
    value: v.unknown(),
  }),
]);
```

**Comment by vladshcherbin** [comment]
@fabian-hiller thank you, this helps a lot 🤗
