### ISSUE TITLE
Catch/Fallback

### ISSUE THREAD

**Issue by FlorianDevPhynix** [fabian-hiller/valibot#74]
zod's [`default()`](https://zod.dev/?id=default) only works with undefined and not null, which this library perfectly mimics. [Zod Sandbox Example](https://stackblitz.com/edit/node-zod-default-catch?file=index.ts)

Thanks to `catch()` on the other hand, it is possible to have a default value when validation fails. But Valibot seems to not have [`catch()`](https://zod.dev/?id=catch). 
It is one of the most useful functions of zod (atleast to me) and I use it a lot. Especially with react, where I want the ensure the app always has certain pieces of data.

Thanks to the simplicity of Valibot is was able to quickly write a catch method.

``` ts
import type { BaseSchema, Output } from 'valibot';
import { ValiError } from 'valibot';

function Catch<TSchema extends BaseSchema>(
  schema: TSchema,
  value: Output<TSchema>,
  callback?: (err: Error) => void
): TSchema {
  return {
    ...schema,
    parse(input, info) {
      try {
        return schema.parse(input, info);
      } catch (err: any) {
        if (typeof callback === 'undefined') {
          console.error(err);
        } else {
          callback(err);
        }
        return value;
      }
    },
  };
}
```
[Sandbox](https://stackblitz.com/edit/valibot-node?file=fallback.ts) with usage examples
`npm run fallback`

This method could also be called fallback. I originally called it that, but to stay true to zod's naming I changed it to Catch, just not catch (reserved word).

**Comment by fabian-hiller** [comment]
Thank you very much for the hint. I will add this functionality as soon as possible. I think `fallback` is a good alternative name for `catch`.

**Comment by MineLPPhynix** [comment]
I read some of the performance issues and the proposed changes to move away from error throwing to some form of context being passed around, might make this function more complex. Should still work very similar though, if the previous validation issues are not passed down, only up. Catching those would be almost the same.
