### ISSUE TITLE
Allowing valibot configuration in Vee-validate

### ISSUE THREAD

**Issue by jakecodev** [fabian-hiller/valibot#743]
Hi, I would like to pass configuration in vee-validate and tried to add a few lines myself: https://github.com/logaretm/vee-validate/pull/4825. 

The pr checks failed but I do not know tell why🥲. Could you please help? Thank you very much.

**Comment by fabian-hiller** [comment]
I think you forgot to import the `InferIssue` type at the top of the file.

**Comment by jakecodev** [comment]
Thank you very much.
