### ISSUE TITLE
[TypeScript?/Question] Cannot use `SchemaWithPipe` in the `options` argument of `variant()`

### ISSUE THREAD

**Issue by eyemono-moe** [fabian-hiller/valibot#746]
When passing a `SchemaWithPipe` that has an appropriate `ObjectSchema` as the root schema to the `options` argument of `variant()`, the following error occurs: `Type 'SchemaWithPipe<[ObjectSchema<{ ... }, undefined>, ...>' is not assignable to type 'VariantOption<"...">'.`
However, the parsing itself works as expected.

Is this a type error, or is it intended behavior that this usage is not allowed?

reproduction: https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgBUBPMAUwCMAZSYALPiGRwAvJgB0ECgCs+TGAAoA3vThwYvPgC555GHyhl1hffwGEAlABodmMgFcj8jlGCsA5upO9AC+9gzMbBxwPPwATCLikjLyYMD86i4YCsqqGtq6ujaeWabmltYGsQ7OBa6kHgLGWaxuIBTmgTUFJPV8sU1yLW0dQbqhXVkwFuzY0CDq6sD2MgB8cFouuj0exsBy24JwANRwewexXaFBYYwA9LfRBkQJEsgA6sAwogAKaXwAPABtADyOTUL0k-00cCgfGQABM2KRuHoDMYADKfMqkCHIf4AIiKsXxjjgblY8L42F8fHhK1oMLhiNYyLqDWMADlWu0oLj-uTKdTWLT6YyEUiUedOdzzHyBVSaXSGcFSfKhSLSZxpqhZlAQABBNTANj-ORmlYAXRWhFO6FY1BQqFQwD8rGQFFIfD0EFR-CIADVkD5kKwYMCwDBjawCUV8da5BF2PBccksiRg6GrEVCKTATFBLjNZVcRabiwk4zUG5SDABKm5KhkNg+N8g6g+OpC3B8r7PBVbDnMu4+2YOIPQuFy6gIJ65KQIAFYVWawIy5F4EvqzBYvXG83W1B252xK9ST2isZ+31B1th404LEAAwTYf9B8XEI3RPT2fzxd8ZdtxuIA

In this reproduction, the root schema of `Type2Schema` is an `ObjectSchema` that includes the key `type`, but an error indicates it cannot be assigned to `VariantOption<"type">`.

**Comment by fabian-hiller** [comment]
The current implementation expects the input and output types to contain the discriminator key. I will investigate in the long run if we can improve the types to allow your use case.

As a workaround for now, you can just copy over the `type` key to remove the TS error. Here is an example:

```ts
const Type2Schema = v.pipe(
  v.object({
    type: v.literal('type2'),
    value1: v.number(),
    value2: v.number(),
  }),
  v.transform((i) => ({
    type: i.type, // <--
    value: i.value1 + i.value2,
  })),
);
```
