### ISSUE TITLE
Help with checking if minimum 1 element of the array doesn't have empty string. 

### ISSUE THREAD

**Issue by devdomsos** [fabian-hiller/valibot#755]
Hello, 

Could I get some guidance on how would I validate an array? I would need to make sure that minimum the 1st element of an array doesn't have an empty string. 

TS2322: Type '{ id: string; }[]'

 `buyers: [{ id: "" }, { id: "" }, { id: "" }],`
 
 
```
const CompletionContactSchema = object({
  id: pipe(string(), minLength(1, "Please select minimum one person"))
});
buyers: pipe(array(CompletionContactSchema), minLength(1)),
```

This checks if all elements of the buyers array have minLength 1. How can I specify the first element of the array? 

Thank you!

**Comment by fabian-hiller** [comment]
Here is an example. Check out [this playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgDFgoOBJGAFMQAZSYALYcjgBeTADowwMIIAU9OAuRQoyAJ6qM8iBQBWgpjFUBvOMAAmALgUcowVgHNVASjgBfb28AGg0FEHcAGUFPGHFVAEZg0KMJCwBrVVVgIRBUXxkAPjgAQmLs4VQAbQAGAF15ByTvBmY2DjgRfEEBYTFJEGk5IyUVdU0jbV0DIxNzSxs7JxcYN08ff0CQ8flw1iiYuMStly6ekEzykHyi0suG+yaWlnZ4KEFUAFdSeCH5VGRsIIAAraVBqbi8GBnPpSIJwSqhWwOZyEbAQCCEfzHJFLQiYvzYxYo-EhWrNRjPVAQUiCeSkCBeN6fb7koA).

```ts
import * as v from 'valibot';

const FirstItemSchema = v.pipe(
  v.array(v.object({ id: v.string() })),
  v.minLength(1),
  v.check((items) => !!items[0].id),
);

const SomeItemSchema = v.pipe(
  v.array(v.object({ id: v.string() })),
  v.minLength(1),
  v.someItem((item) => !!item.id),
);
```

**Comment by devdomsos** [comment]
Hey @fabian-hiller, 

Thanks for a quick reply! I appreciate it. 

So I have used the Schema as you suggested: 

```
const FirstItemSchema = pipe(
    array(object({ id: string() })),
    nonEmpty(),
    check((items) => {
      console.log(items, "items")
      return !!items[0].id
    }),
);
```

`buyers: FirstItemSchema,`

The interesting thing is that my `useForm` now doesn't submit, nothing happens when I click on the submit button and it doesn't show any error messages for buyers. 

Should the `console.log(items, "items") ` that I used in the check function be visible in Chrome console? Right now it is not displaying `items`.

**Comment by fabian-hiller** [comment]
Which form library are you using? I suspect you can fix this by [forwarding](https://valibot.dev/api/forward/) the issue to the appropriate field:

```ts
import * as v from 'valibot';

const FirstItemSchema = v.pipe(
  v.array(v.object({ id: v.string() })),
  v.nonEmpty(),
  v.forward(
    v.check((items) => !!items[0].id),
    [0, 'id']
  )
);
```

**Comment by devdomsos** [comment]
Using react-hook-form from here https://github.com/react-hook-form/react-hook-form/releases/tag/v7.52.1

With `forward` it worked now that it is displaying "Invalid input: Received Array" when array has objects with empty id strings. 

How could I chain it now to show a custom error message instead with the forward? 

Thanks for the help!

**Comment by fabian-hiller** [comment]
```ts
import * as v from 'valibot';

const FirstItemSchema = v.pipe(
  v.array(v.object({ id: v.string() })),
  v.nonEmpty(),
  v.forward(
    v.check((items) => !!items[0].id, 'Your custom message'),
    [0, 'id']
  )
);
```

**Comment by devdomsos** [comment]
YAS! It worked. Thank you ever so much for help!
