### ISSUE TITLE
Using variant with a nested key

### ISSUE THREAD

**Issue by NoelOConnell** [fabian-hiller/valibot#781]
Hi, I'm trying to create a schema for a location object which has country and state. If the `country.code` has a value of 'US' then I want to make the `state` object required, otherwise it can be null.

Is `variant` the best way to achieve this or is there another api I should be looking for?

I'm using it like this: `location: variant('country.code', [locationWithState, locationWithoutState])`

https://valibot.dev/playground/?code=JYWwDg9gTgLgBAbwFBzgUwHYFcQH0A0KcANsDGlAIbGGoiUAeAMpgOYwAWtcGEGAouBgBPbtmKkAzlyIQARgCs0AYxjcIYGMD7VuYYGDTdJMKMAytup0NwBulM5QxqiIw3ACSGAGYUA8lgwYIFIAL5w3lAQIHAA5PakchAwsUhIynwmJBDKlFp8AOpkHADKMHlocAC8cPJKqgAURMioqMpkwgBccPqGTa2tJmYWDQCU3AO8AkLCDbEAwh1wwJJwUGgAjljA6wAmseNEA-TMbJwNAIwArAAM+HGLInC5GDzJ6AzKaGi7cNc3zw4DkoqgokgORzghwGGSwzigXVqihUMAaLQGzwguzQ3VI5CoxDmAFUSgcJq0MJQQDiegY0A0huZWGN7lNBJpZgsIHDTMIeFTKis1pttnsDqNIaFoYNyuRunUUWjIW0sTTevTGSNxm9phy5mUKpjsctVustjsfuLyahKdTuuqGdYtay+OyRPrZZVbYLTSKLftRhKBlKiKFuLEmDk8tpXkKzaLLUgJelMvBiFH8hgipxuTADeRqkj6qjmpD2iJ7XT+hjNczpZNXTM5o8+XG-WL660TiwLOd-vcFksXm94GhPt9fv9AcDQVBwUHWp3YfDEQrGuiYarK31ayydW7OfNuSujT7heaO52bQLtxqnXWXbr3VyeQj+dSTeeEwGF6gpeSTAqbpxCkDhqwGNdUQ3DEMmxW9HWGB99ybWJ80qWCz3jf0rWVCkb1pHd7z3NkULQ99MPbS1A1wkMBgXMMiAjDMY0-LCxSTNIx0gWBMQwLIACl5C8bxoHoTMSmUDg0HoQtIKVVAtBgYg1SrSFd1iAAVMhlNYyiA3JawQBZSESL1TTtIoi8qPJbszjAi4bjuOItKU9CnBHD4vh+P5HOnKhZ3nIhpVychWGgREQJWMDITk6DUGAXZ5U0GNqAQpkxivcikszVLd2o4MF21OAiGIJxWCwShWBpWKyy3Ai70QuYmDKiqqt0qz9LgQziMbMyXJ0tsOpwyZ8IdPLHwPJqWsqr0BXa79xVDaV0xCmNunsRxnDmZdeQAOgw2J7gAbRW6NCmKND7lOzNsw4XM0IAXQlEMgA

Thanks

**Comment by fabian-hiller** [comment]
Currently we do not support nested keys. Feel free to create an issue, but don't expect a quick response as other things have higher priority at the moment. Just use `country` as the discriminator in the meantime. The main problem for your schema is that the string `'US'` matches both `literal('US')` and `string()`. So make sure you exclude `'US'` by writing `pipe(string(), notValue('US'))`.
