### ISSUE TITLE
May we make `function_()` generic?

### ISSUE THREAD

**Issue by JuerGenie** [fabian-hiller/valibot#790]
It seems like `function_<Template extends (...args: any[]) => any = (...args: unknown[]) => unknown>()` could be beneficial. If it were generic, we could use it like this:

```typescript
const OptionsSchema = v.object({
  onComplete: v.optional(v.function<() => void>()),
  onProgress: v.optional(v.function<(progress: number) => void>()),
});
type OptionsSchema = v.InferInput<typeof OptionsSchema>;

function createByOptions(options: OptionsSchema) {
  const { onComplete, onProgress } = v.parse(options, OptionsSchema);

  createTimer((progress) => {
    onProgress?.(progress);
    if (progress >= 1) onComplete?.();
  });
}

createByOptions({
  onProgress: (ctx: object) => { /* ... */ }, // <-- take a type error!
});
```

In my opinion, the function's type would just serve as a hint, because ECMAScript is inherently dynamic :D

---

As my solution now, I use a `declare` that looks like this:

```typescript
declare module "valibot" {
  export function function_<TInput extends (...args: any[]) => any = (...args: unknown[]) => unknown>(): v.CustomSchema<
    TInput,
    undefined
  >;
}
```

**Comment by fabian-hiller** [comment]
Thank you for creating this issue. The problem with your idea is that the schema may output a wrong type. It does not validate that `onProgress` really has a `progress` argument that is a number. This can lead to errors at runtime if the wrong function is passed. But there is a workaround for this. Please take a look at [this comment](https://github.com/fabian-hiller/valibot/issues/243#issuecomment-2182514063) and give me feedback.

**Comment by JuerGenie** [comment]
> Thank you for creating this issue. The problem with your idea is that the schema may output a wrong type. It does not validate that `onProgress` really has a `progress` argument that is a number. This can lead to errors at runtime if the wrong function is passed. But there is a workaround for this. Please take a look at [this comment](https://github.com/fabian-hiller/valibot/issues/243#issuecomment-2182514063) and give me feedback.

Thanks for your reply, I see... :D
But when users write scripts in javascript without any compiler (like `tsc` or `babel`), there might not be enough metadata for the validator to work properly. So, adding a generic param to help developers get type hints with `JSDoc` before the question of `how to proceed` is resolved might be considered--just my two cents ;-)

**Comment by fabian-hiller** [comment]
For custom types you can use `custom`. Here it is your own responsibility to make them match the validation. https://valibot.dev/api/custom/

**Comment by JuerGenie** [comment]
> For custom types you can use `custom`. Here it is your own responsibility to make them match the validation. https://valibot.dev/api/custom/

got it👌
