### ISSUE TITLE
As of 0.38.0 `transform` breaks `pipe` in some cases

### ISSUE THREAD

**Issue by alecmev** [fabian-hiller/valibot#796]
[Playground link](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6MA6MYMAUwAp65NnUMKMAB2Acy4BKADS9+Q5CNTZoILlwAekuAF4AfHA26dOoioiE4AfjgBGAEwBmOAC44AVxEATDtlEcvGTkWURgOMQ4oKVlJBiZWdm5ggSFRCSC+FgUlFSg1TW19Q2NTQnNLGwdnN0Iqwgz+EXcQCkjo+lj6IA).

```ts
import * as v from 'valibot';

v.pipe(
  v.string(),
  v.transform((x) => x === 'foo' ? 123 : undefined),
  v.integer(),
);

v.pipe(
  v.string(),
  v.transform((x) => x === 'foo' ? 123 : '123'),
  v.number(),
);
```

Error for the first example:

```
Argument of type 'IntegerAction<number, undefined>' is not assignable to parameter of type 'BaseSchema<123 | undefined, unknown, BaseIssue<unknown>> | BaseValidation<123 | undefined, unknown, BaseIssue<unknown>> | BaseTransformation<123 | undefined, unknown, BaseIssue<...>> | BaseMetadata<...>'.
  Type 'IntegerAction<number, undefined>' is not assignable to type 'BaseValidation<123 | undefined, unknown, BaseIssue<unknown>>'.
    Types of property '_run' are incompatible.
      Type '(dataset: Dataset<number, BaseIssue<unknown>>, config: Config<IntegerIssue<number>>) => Dataset<number, BaseIssue<unknown> | IntegerIssue<number>>' is not assignable to type '(dataset: Dataset<123 | undefined, BaseIssue<unknown>>, config: Config<BaseIssue<unknown>>) => Dataset<unknown, BaseIssue<unknown>>'.
        Types of parameters 'dataset' and 'dataset' are incompatible.
          Type 'Dataset<123 | undefined, BaseIssue<unknown>>' is not assignable to type 'Dataset<number, BaseIssue<unknown>>'.
            Type 'TypedDataset<123 | undefined, BaseIssue<unknown>>' is not assignable to type 'Dataset<number, BaseIssue<unknown>>'.
              Type 'TypedDataset<123 | undefined, BaseIssue<unknown>>' is not assignable to type 'TypedDataset<number, BaseIssue<unknown>>'.
                Type 'number | undefined' is not assignable to type 'number'.
                  Type 'undefined' is not assignable to type 'number'.(2345)
```

Worked in 0.37. `v.nonOptional` around `v.transform` also raises an error and `v.notValue(undefined)` doesn't narrow.

**Comment by fabian-hiller** [comment]
This is intentional. The behavior in <=v0.37.0 was a bug. See #669.

The `integer` action should only be used to validate numbers. Anything that isn't a number would fail anyway.

Your second example is a bit different. It makes no sense to transform the input to `'123'` if you know you only accept numbers. You should rewrite your schema to block values that are not `'foo'`. Of course, I know that this is just a very simple example. If someone comes up with an example that demonstrates that this would actually be a cool feature, I will consider supporting this pattern.

**Comment by alecmev** [comment]
To give a real example:

```ts
const toNumber = (x: string): number | undefined => x // ...

const PORT_SCHEMA = v.optional(
  v.pipe(
    v.string(),
    v.transform((x) => toNumber(x)),
    v.integer(),
    v.minValue(0),
    v.maxValue(65_535),
  ),
)
```

How do I rewrite this for 0.38? As mentioned, I tried wrapping `transform` in `nonOptional`, which results in this:

```
Argument of type 'NonOptionalSchema<BaseSchema<unknown, unknown, BaseIssue<unknown>>, undefined>' is not assignable to parameter of type 'BaseSchema<string, unknown, BaseIssue<unknown>> | BaseValidation<string, unknown, BaseIssue<unknown>> | BaseTransformation<string, unknown, BaseIssue<unknown>> | BaseMetadata<...>' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
  Type 'NonOptionalSchema<BaseSchema<unknown, unknown, BaseIssue<unknown>>, undefined>' is not assignable to type 'BaseSchema<string, unknown, BaseIssue<unknown>>' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
    The types of '_types.input' are incompatible between these types.
      Type 'unknown' is not assignable to type 'string'.ts(2379)
```

**Comment by fabian-hiller** [comment]
Can you provide the full code for `toNumber`? I would make sure to validate the string beforehand so that the transformation always returns a number.

**Comment by alecmev** [comment]
Sure!

```ts
function toNumber(string: string): number | undefined {
  if (/[^\d\s+.E-]/iu.test(string)) return undefined;
  const number = Number(string);
  if (!Number.isFinite(number)) return undefined;
  return number;
}
```

> I would make sure to validate the string beforehand

I wouldn't want to cover all edge cases of IEEE 754 in a regular expression or something 😛

**Comment by EltonLobo07** [comment]
One possible solution is to use the `check` action as shown in the code block below
```ts
const isNumber = (x: string) => {
  return !/[^\d\s+.E-]/iu.test(x) && Number.isFinite(Number(x));
}

const PORT_SCHEMA = v.optional(
  v.pipe(
    v.string(),
    v.check(isNumber, "The input cannot be converted to a number."),
    v.transform(Number),
    v.integer(), 
    v.minValue(0), 
    v.maxValue(65_535)
  ),
)
```
I am not sure if its idomatic but definitely a possible solution.

**Comment by fabian-hiller** [comment]
Does this work?

```ts
const PORT_SCHEMA = v.optional(
  v.pipe(
    v.string(),
    v.regex(/[^\d\s+.E-]/iu),
    v.transform(Number),
    v.finite(),
    v.integer(),
    v.minValue(0),
    v.maxValue(65_535),
  ),
);
```

**Comment by alecmev** [comment]
Thanks for the suggestions!

@EltonLobo07 Negligible perf-wise, of course, but introducing a runtime penalty of calling `Number` twice only to appease a type-checker feels wrong.

@fabian-hiller Looks reasonable, but the downside is that now there is a second implementation of `toNumber`. I could put the regex in a shared constant, but it's still two pieces of code doing the same thing, that could potentially get out of sync in the future (e.g., could at some point find out that `isFinite` is insufficient, and forget to update the Valibot pipeline).

In general, okay, this could be solved for `toNumber`, but what's wrong with `transform` returning `undefined` and any other value it likes? I guess it comes down to `NumberSchema`'s `TInput`:

https://github.com/fabian-hiller/valibot/blob/d5d05468ab3260d493c052b31567c55f5d42dbed/library/src/schemas/number/number.ts#L30-L32

Must it be `number`? Can it not accept anything?

**Comment by fabian-hiller** [comment]
> the downside is that now there is a second implementation of `toNumber`

Why is there a second implementation? Because you use `toNumber` somewhere else in your codebase?

> what's wrong with `transform` returning `undefined` and any other value it likes

There is nothing wrong. You can return whatever you want. Our current TS implementation just forces you to use pipeline items that match the output of the previous one, but as written at the end of [this comment](https://github.com/fabian-hiller/valibot/issues/796#issuecomment-2307381999), I can imagine changing this behavior for schemas.

**Comment by alecmev** [comment]
> Why is there a second implementation? Because you use `toNumber` somewhere else in your codebase?

Exactly, it's a part of our "standard library", used in non-validation contexts.

> Our current TS implementation just forces you to use pipeline items that match the output of the previous one

Okay, I think I understand the current design. Seems like there's a bit of a mismatch between what `TInput` originally meant, and how it's being used in pipes now. There should maybe be a separate generic, representing what `_run` can take, which `pipe` would compare to `TOuput` of the previous item?

**Comment by fabian-hiller** [comment]
It's actually much simpler than that. By changing `TInput` in [this](https://github.com/fabian-hiller/valibot/blob/v0.39.0/library/src/types/pipe.ts#L33) and [this](https://github.com/fabian-hiller/valibot/blob/v0.39.0/library/src/types/pipe.ts#L40) line to `unknown`, any schema can be used anywhere in the pipeline. Since any schema can handle `unknown` input, it is safe to use any schema anywhere in the pipeline. I think I will "fix" this with the next release.

**Comment by alecmev** [comment]
Alright, sounds good, thanks! 😉

**Comment by fabian-hiller** [comment]
I was about to implement it until I found out that schemas are already less strict and allow partially matching schemas as successors. Your `toNumber` schema does not give me any errors. Can you confirm this?

```ts
import * as v from 'valibot';

function toNumber(string: string): number | undefined {
  if (/[^\d\s+.E-]/iu.test(string)) return undefined;
  const number = Number(string);
  if (!Number.isFinite(number)) return undefined;
  return number;
}

v.pipe(v.string(), v.transform(toNumber), v.number());
```

In simple words, if the input type of the successor extends the output type of the predecessor, it works:

```ts
v.pipe(
  v.union([v.string(), v.number()]),
  v.number()
);
```

But in all other cases (mostly invalid schemas) it fails as expected:

```ts
v.pipe(
  v.union([v.string(), v.number()]),
  v.boolean() // <- TS error here
);
```

**Comment by alecmev** [comment]
Oh, my bad! Was using `v.integer` right after `v.transform`. If I put `v.number` between them then there's no error. Not sure why I didn't try that, as my playground had both, but not together 😄 Thank you for the investigation. I'll close this then, to be re-opened if somebody comes back with examples beyond `... | undefined`.
