### ISSUE TITLE
Integrate with Superforms, and toward a validation standard

### ISSUE THREAD

**Issue by ciscoheat** [fabian-hiller/valibot#8]
Hello Fabian and the rest of the team, I'm Andreas, the author of the SvelteKit [Superforms](https://superforms.rocks) library. Nice project you've got going! You talked about integrations in your introductory post, it would be very nice to be able to use valibot in Superforms, as I'm planning to support multiple validation libraries in v2.0.

It's not as simple as providing schema validation though, for a complete integration there need to be some schema introspection available. I've started a discussion at typeschema about the requirements: https://github.com/decs/typeschema/issues/9

It would be interesting to hear your thoughts about this. I'm frankly a bit worried that such a basic problem as form validation has become so fragmented, with a dozen libraries doing the same thing differently, instead of focus being on standards.

**Comment by fabian-hiller** [comment]
Hey, with [Modular Forms](https://modularforms.dev/), my own form library, I had decided to rely on adapters for schema validation. This makes it theoretically possible to connect any validations library. This approach also has the smallest footprint in bundle size, as only the adapter that is used ends up in the bundle. The adapter basically only maps the errors into a uniform structure for the form library.

For example, here is the code of the `valiForm` adapter: https://github.com/fabian-hiller/modular-forms/blob/main/packages/react/src/adapters/valiForm.ts

**Comment by ciscoheat** [comment]
That looks like the approach that typeschema is taking, which works in the relatively simple case of schema validation - error mapping. But schema *introspection*, its requirements and specification, goes beyond that. It needs to be supported by the library, since we build the schemas directly in them.

This per-library DSL causes the fragmentation I'm mentioning in the typeschema issue. So either an agnostic schema definition must be used, which can be adapted or directly supported by each library, or a validation library must support introspection according to some specification. I'm hoping for the latter, since the schema definition belongs to the library.

Given the number of JS validation libraries it's obviously quite easy to create one and deploy it into the wild, but it also should assume some responsibility regarding the above. Otherwise, Zod is the only option I have for Superforms.

**Comment by fabian-hiller** [comment]
I haven't quite understood why the approach I use with Modular Forms doesn't work for Superforms. Modular Forms supports Zod and Valibot in this way and allows you to connect any other library. Maybe you can make a code example.

I know that React Hook Form uses `resolvers`, which is probably the same as Modular Forms under a different name.

**Comment by fabian-hiller** [comment]
Here you can find a code example with Modular Forms: https://modularforms.dev/react/guides/validate-your-fields#schema-validation

In fact, with Qwik this approach works so well that the same scheme can be used for validation in the browser and on the server, and everything works even if JavaScript is disabled in the browser: https://modularforms.dev/qwik/guides/enhanced-forms

**Comment by ciscoheat** [comment]
It works, but that's just the validation itself - a rather simple interface that typeschema is unifying for many other libraries as well. But since every validation library also locks consumers into their DSL (the schema definition), the need for introspecting this schema becomes important when you're using it in form validation, for example. This is what I'm discussing here: https://github.com/decs/typeschema/issues/9

Is there any schema introspection available for Valibot that covers these cases?

**Comment by fabian-hiller** [comment]
I have read through your posts and understand what you mean. No, this approach is currently not possible with Valibot. This is due to the fact that a schema in Valibot is composed of different functions and Valibot does not collect validation information about them in advance.

However, I believe it would be technically possible. However, it would increase the bundle size and make the source code more complex. Currently I don't know if this is a functionality I want to support with Valibot. However, I am keeping it in mind as this functionality would also allow serializing a schema in JSON.

**Comment by ciscoheat** [comment]
Ok, glad to know that it's in the back of your head for the future! I hope it is doable, as said the alternative is to make a schema standard, so introspection can be made independent of library, and adapters for each library to transform the schema to the library-specific one.

**Comment by fabian-hiller** [comment]
Issue is related to: #23

**Comment by fabian-hiller** [comment]
Hey 👋 I think when #211 is merged Valibot will support the functionality you asked for.

**Comment by fabian-hiller** [comment]
v0.21.0 is now available. Presumably not everything is perfect yet. So please let us know if you have any ideas for improvements.
