### ISSUE TITLE
useDefault is treated as a React hook unintentionally

### ISSUE THREAD

**Issue by naruaway** [fabian-hiller/valibot#80]
When using Valibot in a React project, as demonstrated by [this StackBlitz example](https://stackblitz.com/edit/stackblitz-starters-ao3yvo?file=index.js),
Just using `useDefault` at top-level like `const schema = useDefault(string(), 'test')` causes the following ESLint error:

```
 3:16  error  React Hook "useDefault" cannot be called at the top level. React Hooks must be called in a React function component or a custom React Hook function  react-hooks/rules-of-hooks
```
This error is caused by [eslint-plugin-react-hooks](https://www.npmjs.com/package/eslint-plugin-react-hooks), which is maintained by the React team and [recommended officially in the doc](https://react.dev/learn/editor-setup#linting).
Basically every well maintained React projects should have installed this ESLint rule.

Semantically, `useSomeIdentifierHere` is considered as a React hook by its naming convention and tools like the ESLint rule is [following this definition](https://github.com/facebook/react//blob/cb3404a0ccd8b5edf5d2b90bd844742090e38f42/packages/eslint-plugin-react-hooks/src/RulesOfHooks.js#L13-L32). Note that this is not only about ESLint, other tools such as Fast Refresh implementation is also relying on this naming convention. People might be confused since `useDefault` looks like a React hook as well.

Usually it's weird to be constrained by "just a single framework" such as React but React is used extremely a lot and it would be nice if Valibot can be a good companion of React.

I searched Valibot repo and did the following Ripgrep search:
```
$ valibot/library rg  'use[A-Z]'
src/methods/index.ts
14:export * from './useDefault/index.ts';

src/methods/useDefault/index.ts
1:export * from './useDefault.ts';

src/methods/useDefault/useDefault.test.ts
4:import { useDefault } from './useDefault.ts';
6:describe('useDefault', () => {
8:    const schema1 = useDefault(string(), 'test');

src/methods/useDefault/useDefault.ts
11:export function useDefault<TSchema extends BaseSchema | BaseSchemaAsync>(
```

So we only need to think about an alternative name of `useDefault`.
My suggestion so far is to rename it to something like `withDefault` but there might be a better name

**Comment by fabian-hiller** [comment]
Thank you for the info. Since `default` is a reserved word, I had the choice between `useDefault` and `withDefault`. However, I had not thought of this problem back then. Maybe we can find some more alternatives. Otherwise it will probably change it to `withDefault`.

**Comment by MineLPPhynix** [comment]
`withDefault` makes more sense to me. It describes what happens, a schema **with** a default value.

**Comment by fabian-hiller** [comment]
I think I will change it later or tomorrow and publish a new version.

**Comment by fabian-hiller** [comment]
`useDefault` is now deprecated and `withDefault` is available 🎉
