### ISSUE TITLE
`GenericSchema` where `TOutput` does not default to `TInput`

### ISSUE THREAD

**Issue by hyunbinseo** [fabian-hiller/valibot#803]
Currently, the `GenericSchema` uses `TOutput = TInput` in the generics.

Only providing `<TInput>` forces the input and output type to be identical, unless `TOutput` is specified.

Would it be possible to:

- check if the `TInput` is compatible with the schema
- and use the schema output as the `TOutput` type?

```ts
import { GenericSchema, minLength, object, pipe, string, transform } from 'valibot';

const formObject = {
  userId: '' as FormDataEntryValue | null,
};

// Works
const Schema1 = object({
  userId: pipe(string(), minLength(2)),
}) satisfies GenericSchema<typeof formObject>;

// Works
const Schema2 = object({
  userId: pipe(
    string(),
    transform((v) => Number(v)),
  ),
}) satisfies GenericSchema<Record<keyof typeof formObject, unknown>>;

//  Type 'number' is not assignable to type 'FormDataEntryValue | null'.
const Schema3 = object({
  userId: pipe(
    string(),
    transform((v) => Number(v)),
  ),
}) satisfies GenericSchema<typeof formObject>;
```

**Comment by fabian-hiller** [comment]
I would change it to `GenericSchema<typeof formObject, unknown>` since you probably don't care about the output in this case.

**Comment by hyunbinseo** [comment]
Thanks! Added to the `@hyunbinseo/tools` documentation:

- https://github.com/hyunbinseo/tools?tab=readme-ov-file#formdata-to-object-with-types
- https://github.com/hyunbinseo/tools/commit/79b32f5dac0bbe328ed36882f520768d33d90fc3
