### ISSUE TITLE
bug: `transform` output type inside an object is broken on v0.39

### ISSUE THREAD

**Issue by cruzdanilo** [fabian-hiller/valibot#806]
in v0.39, the output type of an object field with a transform is not working properly, returning the original type before the transformation. execution works as expected, but the typescript compiler fails. here is a reproduction example:

```typescript
import { array, nullish, object, parse, pipe, string, transform } from "valibot";

function f({ a }: { a: string[] }) {
  console.log(a);
}

const Schema = object({ a: pipe(nullish(array(string())), transform((x) => x ?? ["default"])) });


const output = parse(Schema, { a: null });

f(output);
```

execution output:
```log
[ 'default' ]
```

tsc output:
```log
index.ts:12:3 - error TS2345: Argument of type '{ a?: string[]; }' is not assignable to parameter of type '{ a: string[]; }'.
  Property 'a' is optional in type '{ a?: string[]; }' but required in type '{ a: string[]; }'.

12 f(output);
     ~~~~~~
```

i pushed this same repro to a git repo: https://github.com/cruzdanilo/repro-valibot-transform
you can see this same output in the ci workflow log: https://github.com/cruzdanilo/repro-valibot-transform/actions/runs/10614474287/job/29420466950

**Comment by fabian-hiller** [comment]
Thank you for creating this issue. I recommend that you change your schema. This will also fix this problem. However, I will investigate this problem and may change the current implementation.

You can try my code in [this playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgGUmALAUxDI4AXkwA6CBQBWfJjAAUAb3pw4Aaz4BPAFzjWAV1LlUPeRjHIoUZJrNiOUYKwDm8gJRuANHADahACZ82MiGNAC6XvQAvm4M9DCaYHxwAJKsYPrwouZp2HxQaRkwADwJSRDYcNz8ggB8DGXJAPKZRSLiufktMEWliXwVVbwCyPWMLOzwUHyooe3mqMh5AAqWqHzy1SPeiupauvqsgdhOfP5wMXETqBCkfGKkEK7Ts6QwsfRAA).

```ts
import * as v from 'valibot';

const Schema = v.object({
  key: v.nullish(v.array(v.string()), ['default']),
});

type Input = v.InferInput<typeof Schema>;
type Output = v.InferOutput<typeof Schema>;
```

**Comment by fabian-hiller** [comment]
I agree. When an optional input is transformed to a non-optional value, the output type should reflect this information. I have improved the implementation and added new type test. Thanks for your feedback!
