### ISSUE TITLE
Return type of `getDotPath` function is `null` for schemas with `pipeAsync`

### ISSUE THREAD

**Issue by declanlscott** [fabian-hiller/valibot#814]
Thank you for creating this excellent library! This is the first time I've come across any issue after using valibot for some time.

### Issue
When using the `getDotPath` function with an async pipe schema, the resulting return type is `null`. I have verified this is _not_ the behavior when using a non-async pipe schema.

### Minimal reproduction
I also created a [minimal reproduction in the playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgGUmALAUxDI4AXkwA6MMDB8AgqgCerJgAp6ccRAoArPkxjKA3mvVwByYKQBc4ydOUYxHKMFYBzZQEoANOLMXP3sbqYGioAO7QACbWDrZ89o4wzm6ePg4gLgAyfG4wPMoAHB6B6gC+JeLY0GHIUJFyiipBNrUwwGQAwvxMANYNSqomJgDawwBEfqRjALrTXs3qaI1wniIAfHAACngZqHxiUHyoEKQY8dhkexVDYy4k5JGmghZjzddw45Mzxh70v8xsDhwQ6oACupHgomQNWA8AcqGQ2D4m1qe36Km4-EEPiM6km1kIWmQrD4AAE+AAPZDgUj7FggQjzYKhCJ1AkARgATABmAAsAFYAGwAdgKjPo5QY9GA2BWAEIQeCYI5QUwmEdUB44Li4Cx2PBgKgwcjkHl0KJFRCxIbjagxIIwAlXHwYAARagovIAHhg8mkEFlmLMa3+6j1x1pYlIEHcBjgNtBJrNcElEsY4ZO+2j7ktMA8QA) where you can see hovering over the `issuePaths` variable reveals `null[]`. The function returns the correct values, as shown in the logs after running the playground, but the return type is not consistent with this.

### Investigation
I did some preliminary investigation and it _seems_ like the [condition in the first line](https://github.com/fabian-hiller/valibot/blob/1fddd5771311aa50949819cdfe78abd2d002b5cc/library/src/types/issue.ts#L316) of the `IssueDotPath` type definition fails, eventually resolving the type to `never`. I'm not sure why this would be happening though?

If this is the expected behavior or if I'm missing something in my implementation, please let me know!

**Comment by fabian-hiller** [comment]
This is a bug. Thank you for creating this PR. It seems to happen whenever `pipeAsync` contains an async action, but I think I could fix it by changing the following code in the `IssueDotPath` type:

```diff
-TSchema extends SchemaWithPipe<infer TPipe> | SchemaWithPipeAsync<infer TPipe>
-  ? IssueDotPath<FirstTupleItem<TPipe>>
-  : ...
  
+TSchema extends SchemaWithPipe<infer TPipe>
+  ? IssueDotPath<FirstTupleItem<TPipe>>
+  : TSchema extends SchemaWithPipeAsync<infer TPipe>
+    ? IssueDotPath<FirstTupleItem<TPipe>>
+    : ...
```

Before releasing a new version, I need to investigate if the same happens for other parts of the `IssueDotPath` type.

**Comment by fabian-hiller** [comment]
This will be fixed with the next release

**Comment by fabian-hiller** [comment]
v0.42.0 is available
