### ISSUE TITLE
How to create a typescript type for an arg of type v.object or v.pipe ?

### ISSUE THREAD

**Issue by Mairkur** [fabian-hiller/valibot#815]
Hi ! 

I'm trying to develop a function that allow to create automatically a form based on a valibot schema.

So I would like to create a function that accept a schema as args.

I actually don't know which type should my function arg be. The schema will often change.
I saw there is multiple type like ObjectSchema or AnySchema but I'm not able to use it properly.

Any help on this would be largly appreciated !

Here is a example schema :

```
export const registerSchema = v.object({
    username: v.pipe(
        v.string('error-must-be-string'),
        v.minLength(3, 'error-too-short')
    ),
    email: v.pipe(
        v.string('error-must-be-string'),
        v.nonEmpty('error-is-empty'),
        v.email('error-invalid-email')
    ),
    password: v.pipe(
        v.string('error-must-be-string'),
        v.nonEmpty('error-is-empty'),
        v.minLength(5, 'error-password-too-short')
    )
});
```

And here is the function I would like :

```typescript
export const Form = ({
    onSubmit,
    valibotSchema,
}: {
    onSubmit: (data: unknown) => unknown;
    valibotSchema: unknown;
}) => {
    const inputNames = Object.keys(valibotSchema.entries);

    const {
        register,
        getValues,
        formState: { errors, isValid },
    } = useForm({ mode: 'all', resolver: valibotResolver(valibotSchema) });

    useEffect(() => {
        const data = getValues();
        onSubmit(data);
    }, [isValid, getValues, onSubmit]);

    return (
        <form>
            {inputNames.map((inputName) => (
                <FormInput
                    key={inputName}
                    inputId={inputName}
                    label={inputName}
                    register={register(inputName, { required: true })}
                    errorKey={errors?.[inputName]?.message?.toString()}
                />
            ))}
        </form>
    );
};
```

**Comment by fabian-hiller** [comment]
I recommend using our `v.GenericSchema` type in this case. To allow async validation, you can create a union with the `v.GenericSchemaAsync` type. If the schema needs to match a specific input or output type, you can use the optional generics of these types: `v.GenericSchema<{ email: string; password: string }>`.

**Comment by Mairkur** [comment]
> I recommend using our `v.GenericSchema` type in this case. To allow async validation, you can create a union with the `v.GenericSchemaAsync` type. If the schema needs to match a specific input or output type, you can use the optional generics of these types: `v.GenericSchema<{ email: string; password: string }>`.

Thanks for your answer !

```
export const Form = ({
    onSubmit,
    valibotSchema,
}: {
    onSubmit: (data: unknown) => unknown;
    valibotSchema: unknown;
})
```
If I change valibotSchema type by GenericSchema typescripts says 

```Property 'entries' does not exist on type 'GenericSchema<unknown, unknown, BaseIssue<unknown>>``` 

on this line
```
const inputNames = Object.keys(valibotSchema.entries);
```
How should I use GenericSchema to force as args a schema (v.object) that has .entries to allow me to generate my form based on the entries ?

**Comment by fabian-hiller** [comment]
If you only want to allow object schemas, I recommend using `v.ObjectSchema<v.ObjectEntries, v.ErrorMessage<v.ObjectIssue> | undefined>` instead of `v.GenericSchema`.
