### ISSUE TITLE
Add clear property to indicate invalid property path

### ISSUE THREAD

**Issue by ZilvinasAbr** [fabian-hiller/valibot#818]
First of all, thanks for a great library!

There is a small improvement I thought would help me and others. A common case of using Valibot is to parse environment variables. I often get valibot errors on build time since I forget to add some env variables. An issue is that on deployment logs it does not tell which property has failed to be parsed. Example log I just recently got:

```
#14 89.87 web:build: {
#14 89.87 web:build: kind: 'schema',
#14 89.87 web:build: type: 'string',
#14 89.87 web:build: input: undefined,
#14 89.87 web:build: expected: 'string',
#14 89.87 web:build: received: 'undefined',
#14 89.87 web:build: message: 'Invalid type: Expected string but received undefined',
#14 89.87 web:build: requirement: undefined,
#14 89.87 web:build: path: [Array],
#14 89.87 web:build: issues: undefined,
#14 89.87 web:build: lang: undefined,
#14 89.87 web:build: abortEarly: undefined,
#14 89.87 web:build: abortPipeEarly: undefined
#14 89.87 web:build: }
```

I guess the failed key would be seen in the `path`, but the issue is that in logs it does not expand the Array and just show `[Array]`.

Is there any way possible to maybe somehow show the failed property path?

**Comment by fabian-hiller** [comment]
Thank you for your kind words. Can you share your code that logs this information to the console? Maybe [`flatten`](https://valibot.dev/api/flatten/) or [`getDotPath`](https://valibot.dev/api/getDotPath/) is what you are looking for.

**Comment by ZilvinasAbr** [comment]
@fabian-hiller Hi, thanks for suggestions, they might work, will try them when I have time. Though in my case I am actually not handling the errors. And an issue might be that I am doing the parsing in file global scope, e.g.:
```ts
// serverEnvs.mjs

const serverEnvsSchema = object({
  SOME_ENV_VARIABLE: string()
})

export const serverEnvs = parse(serverEnvSchema, { SOME_ENV_VARIABLE: process.env['SOME_ENV_VARIABLE'] })

// next.config.mjs
import { serverEnvs } from "./serverEnvs"

// Importing it here makes it validate on build-time of Next.js
```

**Comment by fabian-hiller** [comment]
You can try if this works?

```ts
import * as v from 'valibot';

const ServerEnvsSchema = v.object({
  SOME_ENV_VARIABLE: v.string(),
});

const result = v.safeParse(ServerEnvsSchema, process.env);

if (result.issues) {
  console.error('Issues:', v.flatten(result.issues).nested);
  throw new Error('Invalid environment variables');
}

export const serverEnvs = result.output;
```

**Comment by ZilvinasAbr** [comment]
Yeah, silly me, this looks exactly what I would need, thank you! I guess we can close the issue since no changes to `valibot` are necessary to be made

**Comment by fabian-hiller** [comment]
Yeah, my first attempt was also with try/catch 🙃

**Comment by fabian-hiller** [comment]
Note that you can also write a loop to freely format and log the issues:

```ts
for (const issue of result.issues) {
  console.error(v.getDotPath(issue), issue.message);
}
```
