### ISSUE TITLE
Returned Type of startsWith is still string

### ISSUE THREAD

**Issue by CordlessWool** [fabian-hiller/valibot#824]
I am using TypeIds and want to validate if the given string is validateing the typeId. This is at least not a problem write now. But I use the typeId also in types, so my id type is `x-${string}` for example. The InferOutput is a string for this type. 

If I use transform I can set the type correctly, but then I have a transform for just converting the typescript type, seem to be unnecassery? I also did not find a genreic param to define the return type.

**Comment by fabian-hiller** [comment]
Can you share a [playground link](https://valibot.dev/playground/) with an example? Maybe [`custom`](https://valibot.dev/api/custom/) is what you are looking for.

**Comment by nktnet1** [comment]
Ran into a similar issue - `v.custom` does indeed solve it.

Using @CordlessWool's example,

<img width="955" height="222" alt="Image" src="https://github.com/user-attachments/assets/a5adc3a8-e439-4d6d-96c2-d5b5b70bbd3e" />

<br />
<br />

<details close>
<summary>source code</summary>

```ts
import * as v from 'valibot';

const schema = v.custom<`x-${string}`>(
  (input) => typeof input === 'string' && input.startsWith('x-'),
);

const value = v.parse(schema, 'x-some-value');
console.log(value);
```

</details>

**Comment by AgarwalPragy** [comment]
Note that this issue still exists

[playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgGUmALAUxDI4AXkwA6CBQBWfJjAAUAb3pw4A5MFIAucWGBg%208jGI5RgrAObyAlABpxHZLFQB1YDB7zCYKH2zAADwBaQms7egBfawZGWJgATwM4c2w%20KF8AExFxAElWVKgAeQBXGDBSgB4EgwhsOG5%20QQA%20eiA)

<img width="1583" height="766" alt="Image" src="https://github.com/user-attachments/assets/b33c3439-a60b-4a43-ba1e-7f6084825978" />

The workaround by @nktnet1 works, but the broader question of why ``startsWith` doesn't narrow down the type still remains.

**Comment by fabian-hiller** [comment]
@dosu please explain why. There should be an issue or PR where I explain it. Please find it and link it.
