### ISSUE TITLE
docs: Some more use cases

### ISSUE THREAD

**Issue by Haberkamp** [fabian-hiller/valibot#83]
Hey,

There are also more use cases for valibot. One would be to validate the data that is stored in the Localstorage. And another use case would be to validate the schema of your URL search parameters.

**Comment by fabian-hiller** [comment]
Thanks a lot! Good idea! As soon as I have time, I will include it in the docs.

**Comment by fabian-hiller** [comment]
Thanks for your contribution. I have added the use case to the documentation.
