### ISSUE TITLE
Is it possible to create an error/warning on a field which is non blocking?

### ISSUE THREAD

**Issue by ankit-b-tanna** [fabian-hiller/valibot#840]
I have a field where a validation is to check if the date is in past. If the date is in past, form and field is still valid but I want to show a non-blocking warning message. Is it possible to do that using valibot?

Thanks,
Ankit

**Comment by fabian-hiller** [comment]
I need more context. Are you using a form library or just custom code? Does validation happen when the form is submitted? Where should the non-blocking warning be displayed?

**Comment by c-harding** [comment]
I would find this useful too. For example, if I receive a response with an unexpected enum value, I might not want to completely break the parse (and lose any transformations etc). I can imagine a method `const { object, warnings } = parseWithWarnings(MySchema)`, where warnings has a similar interface to errors, but only containing items that I have explicitly downgraded (e.g. `v.pipe(v.string(), v.warn(v.enum(MyEnum)))` for an enum that only errors if it is not a string).

The errors should only be kept from the happy path (i.e. not in union variants that do not match), and should not influence which variants are taken.

Calling a logger as part of a parser would not help, as this would also be called on other variants. However, a similar pattern could apply:

```ts
v.pipe(
  v.string(),
  v.ifChosen((value, context) =>
    ['a', 'b'].includes(value) ||
      context.logger.log('Unexpected value found at', context.path, value))
)
```

**Comment by fabian-hiller** [comment]
Somewhat related: Even if the validations fails your output might still be typed. You can check that with `.typed` when using Valibot. This allows you to parse a string and check e.g. with `check` whether it matches a specific value or format. If this fails the output is still typed and you can use it for further processing.

We can look into building a dedicated warning feature if many devs requests it or if someone is willing to sponsor it.
