### ISSUE TITLE
Is there a way to get the metadata as type?

### ISSUE THREAD

**Issue by JustGreg** [fabian-hiller/valibot#841]
I want to do something like this:

```typescript
const UserSchema = v.pipe(v.object({
    email: v.pipe(v.string(), v.email()),
    password: v.pipe(v.string(), v.minLength(8)),
  }),
  v.title('user')
);

type UserTitle = v.InferMeta<typeof Schema, 'title'>
// UserTitle = 'user'
```

**Comment by fabian-hiller** [comment]
We do not have a utility type for this yet, but this should work. Check it out in our [playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgFVUBTKAZSYALHiGRwAvJgB0YYGB4AKenBkQKAKx5MYigN4rVcUcmCkAXDLkLFGaRyjBWAc0UBKADQyTZ958OqYGioAO7QACaWdtZKdg5Orp4yIE4AMjwuMEKKABxu-qoAvgUyMMAwpEqEAK68UIT+bgz0MACeCnDcfAAq5ZWScACiAB4wUMg6ADyGim0KENiddYIiYm4A2oQxhAC666zVIBR8Ox6GenBzPJaEZRU8hHCF9AB8m3eVuwxAA).

```ts
import * as v from 'valibot';

const UserSchema = v.pipe(
  v.object({
    email: v.pipe(v.string(), v.email()),
    password: v.pipe(v.string(), v.minLength(8)),
  }),
  v.title('user'),
);

type UserTitle = Extract<
  (typeof UserSchema)['pipe'][number],
  { type: 'title' }
>['title'];
```
