### ISSUE TITLE
Expose `pipe` rest parameter argument type

### ISSUE THREAD

**Issue by ruiaraujo012** [fabian-hiller/valibot#852]
### Discussed in https://github.com/fabian-hiller/valibot/discussions/851

<div type='discussions-op-text'>

<sup>Originally posted by **ruiaraujo012** September 26, 2024</sup>
I have an array of password validations that came from the BE when the app starts, the array is something like this:
```js
[
    {
        "id": 0,
        "mensagem": "Deve conter pelo menos 8 caracteres",
        "descricao": "8 caracteres",
        "valor": "/^.{8,}$/",
        "estado": {
            "id": 2,
            "codigo": null,
            "label": "Ativo"
        }
    },
    {
        "id": 1,
        "mensagem": "Deve conter pelo menos 1 letra minúscula",
        "descricao": "1 minúscula",
        "valor": "/(?=.*[a-z])/",
        "estado": {
            "id": 2,
            "codigo": null,
            "label": "Ativo"
        }
    },
    {
        "id": 2,
        "mensagem": "Deve conter pelo menos 1 letra maiúscula",
        "descricao": "1 maiúscula",
        "valor": "/(?=.*[A-Z])/",
        "estado": {
            "id": 2,
            "codigo": null,
            "label": "Ativo"
        }
    },
    {
        "id": 3,
        "mensagem": "Deve conter pelo menos 1 número",
        "descricao": "1 número",
        "valor": "/(?=.*\\d)/",
        "estado": {
            "id": 2,
            "codigo": null,
            "label": "Ativo"
        }
    },
    {
        "id": 4,
        "mensagem": "Deve conter pelo menos 1 caracter especial (@$!%*?&)",
        "descricao": "1 caracter especial",
        "valor": "/(?=.*[@$!%*?&])/",
        "estado": {
            "id": 2,
            "codigo": null,
            "label": "Ativo"
        }
    }
]
```
It would be nice if I could iterate over it and return one validation for each, like: 

```ts
export const PasswordSchema = v.pipe(
  v.string('required.password'),
  v.nonEmpty('required.password'),
  ...usePasswordRulesStore
    .getState()
    .rules.filter((rule) => rule.valor)
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    .map((rule) => v.regex(new RegExp(rule.valor!.replaceAll('/', '')), rule.mensagem)),
);
```

is that possible?</div>

**Comment by fabian-hiller** [comment]
Thank you for creating this issue. I will try to investigate in the next few weeks if we can support such a use case.

**Comment by ruiaraujo012** [comment]
Thank you.

It's not an important feature to me, it's more of a nice to have. But it would be nice.

**Comment by fabian-hiller** [comment]
This will be possible 🔜

**Comment by ruiaraujo012** [comment]
Thank you.

**Comment by fabian-hiller** [comment]
v1.0.0-beta.4 is available

**Comment by ruiaraujo012** [comment]
TS still complains about it "A spread argument must either have a tuple type or be passed to a rest parameter.ts(2556)"

I'm forced to use `as [v.RegexAction<string, string>]`

**Comment by fabian-hiller** [comment]
Can you share a [playground](https://valibot.dev/playground/) link?

**Comment by ruiaraujo012** [comment]
Well, I'm unable to replicate, so it could be something with my codebase. If I manage to replicate, I'll share it here.

Thank you.

**Comment by fabian-hiller** [comment]
Okay. Because I have tested different use cases. As long as the array or action output is typed correctly, it should work. Note that it only works if the data type stays the same. Transformations are not allowed because they can't be tracked with TypeScript in this way.

**Comment by ruiaraujo012** [comment]
Yes, it's probably something with my type definitions or because I'm using the return type of the zustand store.
