### ISSUE TITLE
Capitalized variables

### ISSUE THREAD

**Issue by merlindru** [fabian-hiller/valibot#86]
Not that important, but why do the docs capitalize the names of schema variables?

E.g. why `EmailSchema`, not `emailSchema`?

**Comment by fabian-hiller** [comment]
As you say, it basically doesn't matter which approach you take here. The capitalization can theoretically have the advantage that, as with classes, the schema has the same name as the output type. This could allow the schema and type to be imported together.

```ts
import { email, minLength, object, type Output, string } from 'valibot';

export const LoginData = object({
  email: string([email()]),
  password: string([minLength(8)]),
});

export type LoginData = Output<typeof LoginData>;
```

However, I haven't had the time yet to think about the long-term procedure in the documentation of Valibot. I am therefore happy about feedback on this in this issue. Which approach do you prefer? What speaks in favor of this approach.

**Comment by merlindru** [comment]
Wow, I didn't even think about that. Yeah, I'll definitely use capitalized variables going forward :)

Thanks!

**Comment by fabian-hiller** [comment]
Yes. I use `Scheme` as a suffix in the documentation so it is clear what it is.

**Comment by fabian-hiller** [comment]
I have now documented the naming convention that we recommend: https://valibot.dev/guides/naming-convention/
