### ISSUE TITLE
TypeScript assertion function

### ISSUE THREAD

**Issue by gcornut** [fabian-hiller/valibot#862]
Hello,

Recently I've been adding an `assert` utility function in my projects that is simply the Valibot parse function wrapped and types as a [TypeScript assertion function](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions).

```ts
export function assert<TSchema extends v.GenericSchema>(
    schema: TSchema,
    value: unknown,
    config?: v.Config<v.InferIssue<TSchema>> | undefined,
): asserts value is v.InferInput<TSchema> {
    v.parse(schema, value, config);
}

function main(something: unknown) {
  assert(v.string(), something, { message: 'Can only lower case a string' });
  return something.toLowerCase();
}

console.log(main(4));
```

([in the playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh7sBXAOwGMZgJWVVUAprAA8AFQDK7ABYCQyOAIAeMAawAm6DADoA4qqHB2kmXIB8ACnpw4qabOQAuOBLtyANFcxlmAp8lYAnh4AlH78QjCa3gJwwJpaAJKs2EJJYMwwYsb2pnAA3p7aYMhQgua2JshuXqQ+wQwAvowsHFw8cHLArOX4AjBSXQDmTmwA1qwQAO6swfmeaIKw5tqoMFBD5sHVqL39Q9V5HQL8yIO+RADC-nA8pAFwpFNCcOxoMfKr66yDhHAN9Z4oH1mFBeDsQH0Bt8tDAIAAZJ5QK5lAFNejsHg7UgCLSPQbmTrdAAswQBQA))

It's pretty useful to do type narrowing with abort and the Valibot error messages. Maybe this method could be used in the Valibot library ?

**Comment by fabian-hiller** [comment]
Sorry for the late reply. I will try to have a look and give you feedback in the next few days.

**Comment by fabian-hiller** [comment]
Great idea! Will implement it!

**Comment by fabian-hiller** [comment]
v1.0.0-beta.1 with the `assert` method is available
