### ISSUE TITLE
beta version has been marked as latest

### ISSUE THREAD

**Issue by kouhin** [fabian-hiller/valibot#865]
@fabian-hiller I've noticed that the latest beta version, 1.0.0-beta.0, has been marked as `latest` on npm. 
This has led to some unexpected behavior in our project.

It might be helpful to consider tagging the beta version as 'beta' on npm, while restoring the 'latest' tag to the previous stable release (v0.42.1). 
This could help prevent potential issues for other users.

**Comment by fabian-hiller** [comment]
Thanks for the tip! I thought npm would automatically detect prereleases. This is now fixed.

**Comment by sbreiler** [comment]
Hey, if you freshly install Valibot, you get version 1.0.0-beta from npm, which is quite unexpected because the documentation isn't up to date (which is, in turn expected for beta stuff). Also, this release is marked as a pre-release on GitHub. Is this intentional? It certainly threw me off.

**Comment by fabian-hiller** [comment]
Our documentation should be up to date. Only some internal APIs may be missing or out of date. There are no changes to our external API between the latest v0 and v1 beta. I decided to mark it as `latest` on npm to get more feedback and get a better and more stable v1 release faster. I know this is a bad DX at the moment and I am very sorry for that. But this will be fixed soon when we release our stable v1.

**Comment by lukeed** [comment]
This is still true. The publish CI is missing `--tag [value]` so it's defaulting to `--tag=latest`

You can verify this by viewing [npm versions](https://www.npmjs.com/package/valibot?activeTab=versions) or `npm dist-tags valibot`. As of now:

```sh
$ npm dist-tags valibot
# beta: 1.0.0-beta.8
# latest: 1.0.0-beta.11
```

**Comment by fabian-hiller** [comment]
I intentionally started to mark the beta version as latest. This is because v0 is kind of beta too and our ecosystem has largely upgraded to our beta version. Using the beta as the latest will allow us to integrate feedback faster and thus make a better v1 release. The reason why Valibot is not yet in v1 RC is that I need to get Standard Schema into v1 RC first. I hope both will happen this month.

**Comment by lukeed** [comment]
Ok but note that this is very very uncommon and effectively makes no difference between beta and latest. Doing so has made all `npm install valibot` reroute to beta, breaking changes and all

**Comment by fabian-hiller** [comment]
I know this is unusual, and it will not happen again after v1 is released. Sorry for the inconvenience. Looking back, I probably should have stayed in v0 longer, but I couldn't know that getting the Standard Schema spec right would take a little longer than expected.
