### ISSUE TITLE
Type inference on findItem when using type predicates

### ISSUE THREAD

**Issue by cberthou** [fabian-hiller/valibot#867]
For now, findItem returns the input type event when trying to narrow the typing using type predicates. For example :
```ts
import * as v from 'valibot';

type Animal = 'cat' | 'dog';

const isAnimal = (v: string): v is Animal => v === 'cat' || v === 'dog';

const schema = v.pipe(
  v.array(v.string()),
  v.findItem(isAnimal)
)

const animal = v.parse(schema, ['apple', 'cat', 'screw']);
// animal is type string | undefined
```

It would be cool to get better type narrowing. For now, you have to do this, which feels weird given that findItem exists :
```ts
const schema = v.pipe(
  v.array(v.string()),
  v.transform((array) => array.find(isAnimal)),
)
```

**Comment by fabian-hiller** [comment]
Thank you for creating this issue and your PR! I am very interested in improving it. I will try to have a closer look in about two weeks.

**Comment by fabian-hiller** [comment]
This is now implemented and will be available with the next version.

**Comment by fabian-hiller** [comment]
v1.0.0-beta.4 is available
