### ISSUE TITLE
Multiple brands schema results to never

### ISSUE THREAD

**Issue by zkulbeda** [fabian-hiller/valibot#87]
Hi! Current implementation of branded types uses single symbol for single branded type, that results to never type in tests

https://github.com/fabian-hiller/valibot/blob/ce49b0b4809a62035767c4b7697fabddd871392c/library/src/methods/brand/brand.test.ts#L32-L38

![image](https://github.com/fabian-hiller/valibot/assets/24959171/495b589d-c746-4748-83f3-e8ad9187552a)

It happends because typescript resolves `{ [symbol]: "1"} & { [symbol]: "2" }` to `never`. 

I'll make a pr for fix, that replaces single value to object of values

**Comment by fabian-hiller** [comment]
Thank you! Can you also add a test that checks this?
