### ISSUE TITLE
Type issue with nested generic type

### ISSUE THREAD

**Issue by hanakannzashi** [fabian-hiller/valibot#878]
I don't understand why TypeScript tell me a error, I think this is a common use case

<img width="896" alt="type" src="https://github.com/user-attachments/assets/526b9d46-d7ba-41f2-a20d-65ba3ce46457">

**Comment by fabian-hiller** [comment]
Can you provide a playground link? I am sure this is fixable. https://valibot.dev/playground/

**Comment by hanakannzashi** [comment]
> Can you provide a playground link? I am sure this is fixable. https://valibot.dev/playground/

https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6YBPMAUzgGUBjACzZDI4AXkwA6AEJo2PfoIA8AVwB2Aa2UQA7soA0cFeq27xU1GwCSqVIrZK1G7QD5HDethXcYwCMrgw2qDDynHBsAB7+ygAm6LICyI4AFKh88QBcXACUcADe9HBwUGwwilC+GGJgwOyJFRBgXj5kyamCmXoVqdyqiYnZwo5+UDaZmQwAvvRAA

**Comment by fabian-hiller** [comment]
I would like to replace `never` with `undefined`, but the problem is that this does not work for our `nullish` schema because there is a difference between providing `undefined` as a default value and providing no default value. Providing `undefined` as the default for `nullish` would change every `null` input to `undefined`. That's why we can't specify `.default` as `undefined`, because that would lead to a bug with its output type. I know that `never` is a hacky solution, but I don't know what else to do. Do you have any idea?

In the meantime you have two workarounds. You could add `undefined` as a default value or you could ignore the TS error and cast the output type.

```ts
import * as v from 'valibot';

function mySchema<T extends v.GenericSchema>(schema: T) {
  return v.pipe(v.optional(schema, undefined), v.check(() => true));
}

const schema = mySchema(v.number());
```

```ts
import * as v from 'valibot';

function mySchema<T extends v.GenericSchema>(schema: T) {
  // @ts-expect-error
  return v.pipe(
    // @ts-expect-error
    v.optional(schema),
    v.check(() => true),
  ) as v.SchemaWithPipe<
    [
      v.OptionalSchema<T, never>,
      v.CheckAction<v.InferOutput<T> | undefined, undefined>,
    ]
  >;
}

const schema = mySchema(v.number());
```

**Comment by hanakannzashi** [comment]
> I would like to replace `never` with `undefined`, but the problem is that this does not work for our `nullish` schema because there is a difference between providing `undefined` as a default value and providing no default value. Providing `undefined` as the default for `nullish` would change every `null` input to `undefined`. That's why we can't specify `.default` as `undefined`, because that would lead to a bug with its output type. I know that `never` is a hacky solution, but I don't know what else to do. Do you have any idea?
> 
> In the meantime you have two workarounds. You could add `undefined` as a default value or you could ignore the TS error and cast the output type.
> 
> ```ts
> import * as v from 'valibot';
> 
> function mySchema<T extends v.GenericSchema>(schema: T) {
>   return v.pipe(v.optional(schema, undefined), v.check(() => true));
> }
> 
> const schema = mySchema(v.number());
> ```
> 
> ```ts
> import * as v from 'valibot';
> 
> function mySchema<T extends v.GenericSchema>(schema: T) {
>   // @ts-expect-error
>   return v.pipe(
>     // @ts-expect-error
>     v.optional(schema),
>     v.check(() => true),
>   ) as v.SchemaWithPipe<
>     [
>       v.OptionalSchema<T, never>,
>       v.CheckAction<v.InferOutput<T> | undefined, undefined>,
>     ]
>   >;
> }
> 
> const schema = mySchema(v.number());
> ```

I think this is because the definitions of `null` and `undefined` as a value or as a symbol of non-existence are unclear. I think `null` is a value, `undefined` is a non-existence symbol, so `default` should ONLY work for `undefined`, not for `null`. Actually, Zod handles it this way as well.

**Comment by fabian-hiller** [comment]
Thank you for your recommendation! I like your idea and will think about it!

**Comment by fabian-hiller** [comment]
I am currently investigating your suggestion and think I will follow it.

**Comment by fabian-hiller** [comment]
v1.0.0-beta.3 is available
