### ISSUE TITLE
Need help using number schema with string values

### ISSUE THREAD

**Issue by stackoverfloweth** [fabian-hiller/valibot#881]
There are [several reasons](https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/) why an input that expects a number would use `type="text"`. Fundamentally that means my model is going to have a `string` but I want to use `v.number()` with all the min/max/etc actions.

I also hoped that I could use `v.parse` to ensure that if the string value passes validation, valibot can also be responsible for parsing the string to number before doing anything with the data.

When I try to pass a string value into schema `v.number()` I get 

> Invalid type: Expected number but received "123"

**Comment by stackoverfloweth** [comment]
@fabian-hiller thank you for this!
I think I understand what's happening, though I'm a bit confused why `v.decimal()` is special? I expected to be able to also just `v.integer()` but that's not true. 
Furthermore, I though okay that's fine that `v.decimal()` is special, I can always narrow it to being an integer with an additional action like 

```ts
v.pipe(
  v.string(),
  v.decimal(),
  v.transform(Number),
  v.integer(),
  v.minValue(10),
  v.maxValue(20)
);
```

However, this seems to fail

> ValiError: Invalid decimal: Received "13.23"

I tried changing `v.transform(Number)` to `v-transform(parseFloat)` but that didn't change the error

**Comment by fabian-hiller** [comment]
What version of Valibot are you using? We changed/fixed `decimal` a few weeks ago.

**Comment by stackoverfloweth** [comment]
thanks @fabian-hiller, I'll update to latest and see if that helps. I noticed a similar deal with dates, do you have a suggestion for values stored as `string` but expected to output to `Date`. For example when you're using `<input type="date">`.

**Comment by fabian-hiller** [comment]
Yes, you could expect a string, check its formatting and transform it to a date. Here is an example. Check it out in this [playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgGUmALAUxDI4AXkwA6MMDB8AFPTjiOUYKwDmMgJQAaeeOCoIAEWQxZ23RjEwoydtmggZMlWACuMDSIB8cVnwDucMamzqxuHuYaDMxsHHBQfKiupPCilqjI2HwACshQqLLc-IJaRABMAAxlACwAtACMFbVlAMyEUYzA2HAyCUkpYklMTImongDeuizsEKR8YqQQ6oQAKqB8cCpwALKccKgqI3D1AJwA7BUAXISlfckwYhDu4WKqfDBrIGYdAL5wfKQCnBJgppgY5mI+FA8FBeol7mJ9ElEr96EA).

```ts
import * as v from 'valibot';

const Schema = v.pipe(
  v.string(),
  v.isoDate(),
  v.transform((input) => new Date(input)),
);
```
