### ISSUE TITLE
Add option to hide warnings in `@valibot/to-json-schema`.

### ISSUE THREAD

**Issue by devcaeg** [fabian-hiller/valibot#889]
In the `@valibot/to-json-schema` package there should be an option to disable warning messages such as:

`The 'trim' action cannot be converted to JSON Schema.`

Since it causes the console to be filled with hundreds of warning messages

**Comment by fabian-hiller** [comment]
What would be your preferred API to configure this? Maybe instead of `force: boolean` we should change it to something like `invalid: 'throw' | 'warn' | 'ignore'`.

**Comment by devcaeg** [comment]
Yes exactly, it is better the option you propose.

**Comment by fabian-hiller** [comment]
I will think about it. Thank you for your feedback!
