### ISSUE TITLE
Small Deno compat issue

### ISSUE THREAD

**Issue by dgreensp** [fabian-hiller/valibot#899]
https://github.com/fabian-hiller/valibot/blob/414aa980b559d60bfeabb45e63ba2b89b8529985/library/src/actions/types.ts#L1

This import is not Deno-compatible, because it points to a directory, not a file.

This can cause an error when running `deno check` in a project.  Because it's a type-only import, it doesn't seem to affect Deno's ability to run code, but this could change.

It should probably point to `types/index.ts`.

**Comment by fabian-hiller** [comment]
Sorry about that! I will fix it asap. Maybe we should add `deno check` to our CI to prevent this kind of bugs.

**Comment by imcotton** [comment]
Would be great to have one patch release (i.e. **0.4.42**) by cherry-pick it from **1.0.0-beta.2**, for users not opted into beta release channel yet.

**Comment by fabian-hiller** [comment]
Does v0.42.1 also have this problem? The things I fixed are only related to our v1 code. Other than that, I recommend upgrading to v1 beta if you are not prevented from doing so by some external reason. v0 is basically a beta release as well and not "more" stable than our v1 beta. You should be able to upgrade without touching any code.

**Comment by imcotton** [comment]
> The things I fixed are only related to our v1 code

Oh I wasn't realize that, confirmed that only affects `v1` beta, sorry.

I've tested `1.0.0-beta.2` and it is indeed works as drop-in upgrade. Fingers crossed for its **v1** stable, thanks.
