### ISSUE TITLE
How to make a discriminatedUnion like in zod?

### ISSUE THREAD

**Issue by naveen-bharathi** [fabian-hiller/valibot#90]
How can I achieve a similar functionality to Zod's [`discriminatedUnion`](https://zod.dev/?id=discriminated-unions) API in Valibot? I want to enable dynamic properties in an object.

#### Example of zod's `discriminatedUnion` api:
```typescript
const response = z.discriminatedUnion("status", [
  z.object({
    status: z.literal("success"),
    data: z.string(),
  }),
  z.object({
    status: z.literal("failed"),
    error: z.instanceof(Error),
  }),
]);

myUnion.parse({
  status: "success",
  data: "yippie ki yay",
});
```

Ref: [`discriminatedUnion` in zod](https://zod.dev/?id=discriminated-unions)

**Comment by fabian-hiller** [comment]
Does it work with the following code?

```ts
import { instance, literal, object, parse, string, union } from "valibot";

const UnionSchema = union([
  object({
    status: literal("success"),
    data: string(),
  }),
  object({
    status: literal("failed"),
    error: instance(Error),
  }),
]);

const unionOutput = parse(UnionSchema, {
  status: "success",
  data: "hello world",
});
```

**Comment by fabian-hiller** [comment]
If I understand it correctly, `z.discriminatedUnion` exists only for performance reasons. So my code example should work as expected. In one of the next updates we could add `discriminatedUnion` to Valibot as well, if there is interest.

**Comment by naveen-bharathi** [comment]
Yes your example works, but with zod's `discrimatedUnion` api, we could add that to an already existing object schema using zod's `and` api

```javascript
const formSchema = (
  z.object({
    email: z.string(),
    password: z.string(),
  })
  .and(
    z.discriminatedUnion('isUsernameRequired', [
      z.object({
        isUsernameRequired: z.literal(true),
        username: z.string().optional(),
      }),
      z.object({
        isUsernameRequired: z.literal(false),
        username: z.string(),
      }),
    ])
  )
)
```

Using valibot's `union` api, it is not possible to add that to an object schema directly like this
```javascript
// ❌ This does not work

const formSchema = merge([
  object({
    email: string(),
    password: string(),
  }),
  union(
    object({
      isUsernameRequired: literal('true'),
      username: string(),
    }),
    object({
      isUsernameRequired: literal('false'),
      username: string(),
    }),
  ),
])
```

**Comment by fabian-hiller** [comment]
That is correct. As soon as I have the time, I'll improve that. Thanks for the hint.

**Comment by fabian-hiller** [comment]
There are plans to deprecate `z.discriminatedUnion` in Zod: https://github.com/colinhacks/zod/issues/2106

**Comment by naveen-bharathi** [comment]
Then i guess it would be useful to have zod's new Switch api implemented in valibot.

**Comment by naveen-bharathi** [comment]
I'll try to create a custom validation to achieve something similar to zod's Switch

**Comment by Karakatiza666** [comment]
Came across this. I need to do what naveen did in https://github.com/fabian-hiller/valibot/issues/90#issuecomment-1676729238 - merge a union with a simple object. Is there a way to do this, other than duplicating contents of a simple object?

**Comment by fabian-hiller** [comment]
You can use `merge` inside `union` to achieve this functionality with Valibot.

**Comment by fabian-hiller** [comment]
As soon as I have time, I will look into a `discriminatedUnion` or `switch` function for Valibot.

**Comment by Karakatiza666** [comment]
I'm not sure how idiomatic it is, but using `intersection` from https://github.com/fabian-hiller/valibot/pull/117 seems to work, and makes sense type-wise:
```
const obj = intersection([
  object(
    a: string()
  ),
  union([
    object(
      b: string()
    ),
    object(
      c: string()
    ),
  ])
])
// obj :: { a: string } & ( { b: string } | { c: string } )
```

**Comment by jsudelko** [comment]
The point of contention https://github.com/colinhacks/zod/issues/2106 seems to be that being able to introspect all possible types is strictly necessary for libraries like [zod-to-openapi](https://github.com/asteasolutions/zod-to-openapi) and [zod-to-json-schema](https://www.npmjs.com/package/zod-to-json-schema) to work, but `z.switch()` seems to be more generalizable and have some performance benefits but choses schemas at runtime and so it is not introspectable.

**Comment by lo1tuma** [comment]
Another reason why [`discriminatedUnion` was introduced](https://github.com/colinhacks/zod/issues/894) was the much simpler error message in case the validation fails. That was at least for me the most important reason to prefer `discriminatedUnion` over `union` wherever possible.

**Comment by fabian-hiller** [comment]
Do you guys like Zod's `discriminatedUnion` API, or is there something we can improve when implementing it for Valibot?

**Comment by Karakatiza666** [comment]
`zod.switch` seems to be a better API than `zod.discriminatedUnion`?

**Comment by lo1tuma** [comment]
IMHO `zod.switch` has the issue that it needs a pre-validation of the input shape, so you can safely perform the switch-logic. I would like to avoid such complicated validation chains whenever possible, so I would prefer `discriminatedUnion` although it is limited to objects and the discriminator must be a union of literals. The `switch` api could be a more generic solution that should be only used when `discriminatedUnion` is not sufficient.

**Comment by fabian-hiller** [comment]
Maybe we should add both. I haven't made a decision yet because I haven't had time to look into it.

**Comment by fabian-hiller** [comment]
I will try to give this issue priority in the next days to find a suitable solution (also related to #216).

**Comment by fabian-hiller** [comment]
Yes, I'm in the process of weighing the options right now.

I find a `switch` API as described [here](https://github.com/colinhacks/zod/issues/2106) to be very useful, but also problematic. The reason for this is that the schemas inside the function of the first argument are not created until validation, and thus are not accessible in advance. This causes problems with PR #211, for example. An alternative to this would be to add the ability to dynamically select the schema to be used to the current `union` implementation.

```ts
const Schema = union(
  [
    object({ type: literal('a'), foo: number() }),
    object({ type: literal('b'), bar: boolean() }),
  ],
  (input, [a, b]) => (input?.type === 'a' ? a : b)
);
```

The biggest problem here is that `input` is of type `unknown` and TypeScript will throw an error on `input?.type`. The solution would be to pass a general schema like `object({ type: string() }, unknown())` as another argument that applies to all options of the union to make the `input` of the function for type safe. However, this makes the API quite complicated and less powerful.

My current assumption is to add `discriminatedUnion` (at least experimentally). I will have a look at the implementation soon.

**Comment by fabian-hiller** [comment]
I have implemented `discriminatedUnion`. The API is expected to be available in the next release in a few days.

**Comment by lo1tuma** [comment]
That’s awesome. IMHO `discriminatedUnion` should probably cover the most common use-cases and also allows to generate easy to understand error messages. For other use-cases the regular `union` could still be used. It there is a big demand the approach you outlined [here](https://github.com/fabian-hiller/valibot/issues/90#issuecomment-1774140351) doesn’t sound too bad and could be shipped at some point in addition while `discrinatedUnion` is kept to provide a simple API for the most common use-cases and maybe a not so nice API for special cases.

**Comment by fabian-hiller** [comment]
v0.20.0 is now available
