### ISSUE TITLE
The "valibot" module does not have an exported withDefault member.

### ISSUE THREAD

**Issue by dukeofsoftware** [fabian-hiller/valibot#91]
Methods page has withDefault method but not in valibot
![image](https://github.com/fabian-hiller/valibot/assets/89215036/190fb9e9-1aa0-4e90-ae77-f84916e4c8dc)

**Comment by fabian-hiller** [comment]
Are you using the latest version of Valibot?

**Comment by dukeofsoftware** [comment]
okay I updated to 0.12.0 and resolved thanks
