### ISSUE TITLE
v.nullish(v.string(), undefined) alternative

### ISSUE THREAD

**Issue by akrynski-1** [fabian-hiller/valibot#913]
I updated valibot and discovered that after #878 the following pattern does not convert `null` to `undefined` anymore.

```
const schema = v.nullish(v.string(), undefined);
const result = v.parse(schema, null);
console.log(result); // null
```

Types also reflect that change, what is recommended way of doing this conversion now?

**Comment by fabian-hiller** [comment]
Hey, sorry for producing a bug in your code. [Here](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XlSYAsBTEZHAC8mAHSsArqXKpuACgyiOUYKwDmcgJQAaOFuEA+OBNYATXtlW9Tmhi3bwovVFPgjFYZFFS85XPgK6ktK2zGyoEKS8oqQQGk4upDChQA) is a fix:

```ts
const schema = v.nullish(v.string(), () => undefined);
const result = v.parse(schema, null);
console.log(result); // undefined
```

**Comment by akrynski-1** [comment]
Thank you for a quick reply, fix you provided does work for me
