### ISSUE TITLE
Valibot down?

### ISSUE THREAD

**Issue by killuox** [fabian-hiller/valibot#918]
I can't have access to the website (valibot.dev), its loading infinitely. Its been like that for at least a week.
Im from Canada

**Comment by awhitford** [comment]
I can confirm that that https://valibot.dev/ seems to be functioning fine.  (I'm in 🇺🇸)

**Comment by awhitford** [comment]
Works for me...
<img width="436" alt="image" src="https://github.com/user-attachments/assets/a488feda-5b1b-427c-b067-49f116490930">

**Comment by killuox** [comment]
I have a really basic antivirus, no VPN and ive tried incognito + cell service and wifi

**Comment by fabian-hiller** [comment]
Our website is distributed across several data centres around the world. Other users have reported similar problems in the past. As a workaround, you can use a VPN or run our website locally by cloning this repository. More info here: https://github.com/fabian-hiller/valibot/blob/main/website/README.md

**Comment by fabian-hiller** [comment]
There is not much we can do except change our hosting provider. So I will probably close this issue in the next few days.

**Comment by awhitford** [comment]
Now I'm dying to know which hosting provider you are using.  (It's 🇨🇦 -- how can they not support Canada?)

**Comment by fabian-hiller** [comment]
Netlify. I was already in contact with their support, but they didn't seem too interested in investigating it further. 😐

**Comment by fabian-hiller** [comment]
Related issue #751

**Comment by awhitford** [comment]
Aw, snap!  I use Netlify too and wasn't aware that their network was unreliable.

@killuox - Note that Opera has a free built-in VPN. Perhaps you can try that.

**Comment by fabian-hiller** [comment]
This happens very rarely and we don't know for sure if it is Netlify's fault or something else that is causing this problem.

**Comment by killuox** [comment]
Thanks for the responses.. I guess i have to fork the repo
