### ISSUE TITLE
Valibot playground, scroll down on new log messages

### ISSUE THREAD

**Issue by DrWarpMan** [fabian-hiller/valibot#920]
**Feature Request**

In the [Valibot playground](https://valibot.dev/playground/), scroll down automatically, when a new log message arrives.
You always have to scroll down manually to see latest log messages, which is annoying.
![image](https://github.com/user-attachments/assets/8821823d-f654-46bd-9e15-9017cede9137)

**Comment by fabian-hiller** [comment]
One tip, you can press `CMD + ENTER` or `STRG + ENTER` to execute the playground and `CMD + BACKSPACE` or `STRG + BACKSPACE` to clear the console.
