### ISSUE TITLE
jsr registry versions of valibot is out of date

### ISSUE THREAD

**Issue by hongkongkiwi** [fabian-hiller/valibot#927]
It seems like the [jsr published version](https://jsr.io/@valibot/valibot) is horribly out of date? 0.42.1

Is it possible to update the JSR repos as well as NPM?

**Comment by fabian-hiller** [comment]
JSR is not out of date. Our CI automatically releases our packages everywhere. I guess you have to tell JSR the exact version you want to install since v1 is in a pre-release.

**Comment by hongkongkiwi** [comment]
I see, that's really confusing.

I think because JSR considers anything without - as pre-release, so for example 1.0.0-beta.1 is considered pre-release and so is automatically hidden.

It only considers full versions as stable and it only shows the latest stable version on the home page. e.g. 
![Screenshot 2024-11-16 at 9 59 54 PM](https://github.com/user-attachments/assets/e0833e68-c0f2-40e1-a579-2738297fb216)

**Comment by fabian-hiller** [comment]
Yes, but I think JSR handles this much better than npm. Can I close this issue?
