### ISSUE TITLE
Type instantiation is excessively deep and possibly infinite.

### ISSUE THREAD

**Issue by ivanbarlog** [fabian-hiller/valibot#929]
When using `v.any()` with combination of `v.forward()` I get following error:

> Type instantiation is excessively deep and possibly infinite.

When `v.any()` is changed for instance to `v.record(v.string(), v.string())` the error dissapears.

Here is the [playground link](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6MA6MYMAUwAp65NmIFAFYcAxjC4BvXnzjAAJgC5+qGFGAA7AOZcAlABoZfechgcAjMpYmzew7Lg2OAJivMndo49PI3yDQCednAA9CFwAO4AFhwacAEQAK5wovggsfAwUcDo0ClR-loccpkQ-FBi0PJcLKrq2sG1apo6urpwWcUUHKQQEXAcUHhQmP45UTIAvgYyYXAAKgGcchqq-jDApsAQcTkDAB6iHKiowBg9AY4cHGAoGvJwkCeUpJea2JrAZsxczgCsAA4AJztAC0KWQiVQHAeFEuyCo534-iCuhkLGw0AiyCg1S8LFEMVEAGseA4+FJvGZzPoqS44NM4ABeAB8dPMzCKMHmoG47TZTmcnI43N5nnJRAAIqZiuY4CAofBunBupiKnBpWY4M5CPZZDMHABtQhOcyEAC6epmugYQA) which reproduces this bug.

**Comment by fabian-hiller** [comment]
Fixed in v1.0.0-beta.7 😎
