### ISSUE TITLE
v.optional output type is broken

### ISSUE THREAD

**Issue by sbking** [fabian-hiller/valibot#935]
I believe this bug was introduced in v1.0.0-beta.3. When wrapping a transform schema in `v.optional` with a default value, the inferred output type is now a union including the type of the default value. However, at runtime the default value is still parsed through the transform schema.

Tricky to explain, so [here is a playground example](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgAVkpUBTAJKsYAZSYALPiGRwAvJgB0YYGD4AKenEUcowVgHM1ASgA0mxQBNg+4DFTGzWjAphRk7bNBBqAcgFcQCj4oJR5+IRhTeiMGFnZ4MUlpOUUIMBhgNjI1bl5BYUSpZBMiAEYABkIYxgB6GrgAATsAWj4AD1UmGFaoPCgALjgAFXFgdDG4Cz5sPVs+UgBPFDhWAKCoEoo-eCGF1TFddLgYUdYAa3G7OAADVcDguAAfOAAiCpfr5jYOOCg+VD8pBggzu6xSzjAYXUhWkJT8rCmM1YfAs1S+7AgpD4ClIEEMfwBQJKMD2fAg2F+-0BkQYQA).

The schema will always return a `number`, but now TypeScript says it will return `number | "10"`

**Comment by fabian-hiller** [comment]
Thank you for reaching out! You are right! I am very sorry. I will fix this and add tests to make sure this cannot happen again.

`optional` allows you to define a default input to be used when the input is `undefined`. The behaviour you describe with the output as the "default" is similar to our `fallback` method.

**Comment by fabian-hiller** [comment]
Fixed 😎

**Comment by fabian-hiller** [comment]
What information do you miss in the docs? I am happy to improve it. Here is our guide and API reference:
- https://valibot.dev/guides/optionals/#default-values
- https://valibot.dev/api/optional/

**Comment by fabian-hiller** [comment]
Thank you. I will have another look at the docs at the end of the year to see if we can improve the explanation.
