### ISSUE TITLE
[feat]: Add copy button to code snippet 

### ISSUE THREAD

**Issue by dev-phantom** [fabian-hiller/valibot#94]
It would be nice to have a "Copy Code" button in the docs examples for easier code sharing and implementation.
![Screenshot_20230813-152938](https://github.com/fabian-hiller/valibot/assets/72051159/19ddf72a-2cb0-4632-8d46-18281491c7bc)

**Comment by fabian-hiller** [comment]
Good idea! But it will take me a while to get around to it. Maybe someone from the community can create a PR.

**Comment by dev-phantom** [comment]
I can work on this

Can I get assigned to it?

**Comment by fabian-hiller** [comment]
Fixed
