### ISSUE TITLE
Misleading example in docs / readme

### ISSUE THREAD

**Issue by thoughtspile** [fabian-hiller/valibot#952]
Hi there, and thanks for the wonderful library! I noticed a few issues with the first code example as seen in [readme](https://github.com/fabian-hiller/valibot?tab=readme-ov-file#example) and [the docs:](https://valibot.dev/guides/introduction/)

```js
import * as v from 'valibot'; // 1.24 kB

const LoginSchema = v.object({
  email: v.pipe(v.string(), v.email()),
  password: v.pipe(v.string(), v.minLength(8)),
});
```

1. The total bundle size is closer to 10 kB, not 1.24: https://bundlejs.com/?q=valibot&treeshake=%5B*%5D 
2. The practcal size for most use cases _would be_ under 2 kB, but to get there you'd need to use named imports.

I think it'd be best to write the example with named imports to encourage optimal usage:

```js
import { object, pipe, string, email, minLength } from 'valibot'; // 1.17 kB
```

Alternatively, we could update the example with the current full-bundle size, or remove the kB size altogether.

Which option would you prefer?

**Comment by fabian-hiller** [comment]
Should I close this issue?

**Comment by HugeLetters** [comment]
These are the results I get 
![image](https://github.com/user-attachments/assets/17a15418-df98-45d5-8018-081ee11c4e81)

I think there's a misunderstanding - it's a bit ambiguous if the initial example implies library total bundle size (it's around ~10kb gzipped) or only size of the actually used functions.

In practice this specific code example with most modern bundlers would result in ~1.25kb bundle - it's just that the phrasing is unclear if using more validator would increase this value and it's not the size of the whole library.

**Comment by fabian-hiller** [comment]
What exactly should I change?

**Comment by thoughtspile** [comment]
OK @fabian-hiller my bad, import syntax does not indeed affect bundle size (unless you materialize the namespace object by doing `this.validation = valibot` etc). Sorry for bothering =)
