### ISSUE TITLE
when redirect using next js link in local this 

### ISSUE THREAD

**Issue by mah12345o** [fabian-hiller/valibot#958]
[AddCityAdminApiFields?.PASSWORD]: v.nullish(
    v.pipe(
      v.string("invalid password"),
      v.nonEmpty("Please enter password."),
      v.minLength(
        8,
        "Your password is too short. Please use at least 8 characters."
      ),
      v.maxLength(
        50,
        "Your password is too long. Please limit it to a maximum of 50 characters."
      ),
      v.regex(/[\d]/, "Your password must contain a number."),
      v.regex(/[a-z]/, "Your password must contain a lowercase letter."),
      v.regex(/[A-Z]/, "Your password must contain a uppercase letter."),
      v.regex(
        /[@$!%*?&#]/,
        "Your password must contain a  special characters (@, $, !, %, *, ?, &, #)."
      )
    )
  ),

----------------------------------------------------------
 v.forward(
    v.partialCheck(
      [[AddCityAdminApiFields?.PASSWORD]],
      (input) =>
        !isAdminUpdateCityAdmin
          ? !!input?.[AddCityAdminApiFields?.PASSWORD]
          : true,
      "Please enter password"
    ),
    [AddCityAdminApiFields?.PASSWORD]
  )
----------------------------------------------------------
when redirect using next js link in local this 
==>
   !isAdminUpdateCityAdmin
          ? !!input?.[AddCityAdminApiFields?.PASSWORD]
          : true,
      "Please enter password"

triggerd and optional  paswword field error show ,and after refresh this error not show , after refresh this var isAdminUpdateCityAdmin have value .

**Comment by fabian-hiller** [comment]
I can't follow you. Can you try to explain more clearly what problem you encountered?
