### ISSUE TITLE
Unable to get nested errors messages type when schema type is passed in flatten

### ISSUE THREAD

**Issue by vladshcherbin** [fabian-hiller/valibot#965]
I've tried switching from `GenericSchema` to `ObjectSchema`, checked suggested way in other issues and passed `Schema` type to `flatten`. For whatever reason the `message` type is `unknown`

[Playground example](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BTAD0ljgBMntkBXUvGx8AdgGMYwCCMxlgnZDCYB5CgCsmEgDz04cAMpiAFkxDI4rJSM7oMAOlUaJhk2Z1699x5pgBRETBQwEyoADS6Hva+UHhQALIhqMgA5kxaXuo+AJKoqHxMAHxwAD5wotzYwCJMnBEF4QUAFKjGpsgAXAatZqGypPmdogDWIhAA7iIAlHAA3hFi0qjwM3DAuflhcBB8MGA7vXliYolwAL5wALyYdknYTAAKyFCoTM3dyL0k-Uy9cx4oVFg92AYCYviepAAnp1AvlwnpTpMGBFgNg4I0AISHY65aZ-DwLERLWZwapLGpnS7XbCkRRWLQuNpNNZ5EJIxj-VHoslKTh4iL-QnEpgxaDoK7eCR2JgBIIhRo8mrs-6nCKq1VAA)

Error messages type:

<img width="803" alt="image" src="https://github.com/user-attachments/assets/5ca8b3ea-ab3d-4956-a779-63cd35d331e6">

If I remove `Schema` from `flatten` the type is array of strings:

[Playground example](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BTAD0ljgBMntkBXUvGx8AdgGMYwCCMxlgnZDCYB5CgCsmEgDz04cAMpiAFkxDI4rJSM7oMAOlUaJhk2Z1699x5pgBRETBQwEyoADS6Hva+UHhQALIhqMgA5kxaXuo+AJKoqHxMAHxwAD5wotzYwCJMnBEF4QUAFKjGpsgAXAatZqGypPmdogDWIhAA7iIAlHAA3hFi0qjwM3DAuflhcBB8MGA7vXliYolwAL5wALyYdknYTAAKyFCoTM3dyL0k-Uy9cx4oVFg92AYCYviepAAnp1AvlwnpTpMGBFgNg4I0AISHY65aZ-DwLERLWZwapLGpnS7XbCkRRWRprPIhJGMf6o9FkpScPERf6E4lMGLQdBXbwSOxMAJBEKNTk1Fn-U4RJVKoA)

<img width="796" alt="image" src="https://github.com/user-attachments/assets/a1b5f9aa-71d4-4487-af82-8d923c54654c">

Is there a correct method that matches this types with schema defined?

valibot - 1.0.0-beta.9

**Comment by fabian-hiller** [comment]
`Schema` is a generic `ObjectSchema` and will never be strongly typed. Therefore, passing `Schema` to `flatten` has no advantage.

**Comment by vladshcherbin** [comment]
@fabian-hiller in one of issue code blocks I saw [you've used it this way](https://github.com/fabian-hiller/valibot/issues/779#issuecomment-2291099125), that's why I've tried the same in my project and got to this question. I didn't specify schema type before in `flatten`.

Since you've said there's no advantage I'd consider this resolved 🙌

p.s. It would be awesome if type was the same for schema/no schema to avoid such questions, but I'd consider this as low priority and this issue can serve as a reference

**Comment by fabian-hiller** [comment]
I reopen it because I would like to have a look at it in the next weeks.

**Comment by fabian-hiller** [comment]
I have investigated this issue further. It seems that this problem only occurs when using a generic. Therefore, it is probably not a problem we can fix simply by changing the type implementation of flatten. At least I have not found a solution yet. The following example works as expected without a generic.

```ts
import * as v from 'valibot';

const flatErrors = v.flatten<v.ObjectSchema<v.ObjectEntries, undefined>>([] as any);
if (flatErrors.nested) {
  const errors = Object.entries(flatErrors.nested); // [string, [string, ...string[]] | undefined][]
}
```

**Comment by fabian-hiller** [comment]
I am closing this issue as I am not sure if there is anything we can do, but if we find a possible solution in the future, I will be happy to reopen it.
