### ISSUE TITLE
Allow boolean literal

### ISSUE THREAD

**Issue by zkulbeda** [fabian-hiller/valibot#97]
Currently you can't create true or false as const in valibot because function generic argument must extend string or number

https://github.com/fabian-hiller/valibot/blob/ea4e6f39dce43cfc49eb542b1b200fb5a904b1ae/library/src/schemas/literal/literal.ts#L24-L27

![image](https://github.com/fabian-hiller/valibot/assets/24959171/e16f37b0-2e5d-491c-af7a-b0452c1db31f)

**Comment by fabian-hiller** [comment]
Thanks for the hint! I will improve that.
