### ISSUE TITLE
Using a unit type instead of a variant?

### ISSUE THREAD

**Issue by jawnothin** [fabian-hiller/valibot#971]
Is there a way to make use of a unit type instead of having to re-type it out as a picklist?

```
type Choices = 'a' | 'b' | 'c'

v.picklist<Choices>()
```

instead of having to do
```
v.picklist(['a', 'b', 'c'])
```

**Comment by fabian-hiller** [comment]
No, this would require a compiler to translate your TypeScript type into run-time code. TypeScript types do not exist at runtime and are removed before the transpiled JavaScript code is executed. However, you can retrieve the TypeScript type from the runtime code. Here is an example:

```ts
import * as v from 'valibot';

const options = ['a', 'b', 'c'] as const;
type Choices = typeof options[number];
const Schema = v.picklist(options);
```

**Comment by fabian-hiller** [comment]
If your main concern is a mismatch between the generated type and the schema, you could use the `satisfies` keyword:

```ts
import * as v from 'valibot';

type Choices = 'a' | 'b' | 'c';
const Schema = v.picklist(['a', 'b', 'c']) satisfies v.GenericSchema<Choices>;
```
