### ISSUE TITLE
JSR-published package contains unnecessary files

### ISSUE THREAD

**Issue by neoncitylights** [fabian-hiller/valibot#972]
Hi, thanks for making this package. :) I'm comparing the file contents of the package from how its published on NPM versus JSR, and on JSR it seems to contain a lot more files than needs be. 

- https://www.npmjs.com/package/valibot?activeTab=code, contains config files like vite.config.ts, eslint.config.js, etc
- https://jsr.io/@valibot/valibot/0.42.1/package.json, contains only what's needed

This fix though is easy as adding a `publish.include` field to `jsr.json`, see https://jsr.io/docs/package-configuration#include-and-exclude and https://jsr.io/docs/publishing-packages#filtering-files. Would be happy to write a PR

----

<img width="1193" alt="image" src="https://github.com/user-attachments/assets/1d336988-bd65-4fe8-94f0-9d40f25a7abb" />
<img width="785" alt="image" src="https://github.com/user-attachments/assets/789edacd-7527-4616-94c0-a6cf78449541" />

**Comment by fabian-hiller** [comment]
Thank you! I added a comment to your PR.
