### ISSUE TITLE
`keyof` on object with over 47 keys gives TS2589: Type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by andersk** [fabian-hiller/valibot#982]
```ts
import * as v from 'valibot';

const object_schema = v.object({
  key0: v.unknown(),
  key1: v.unknown(),
  …
  key62: v.unknown(),
  key63: v.unknown(),
});
const key_schema = v.keyof(object_schema);
```

```
test.ts:69:20 - error TS2589: Type instantiation is excessively deep and possibly infinite.

69 const key_schema = v.keyof(object_schema);
                      ~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in test.ts:69
```

[Playground link](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XggoCsBTJmAH1UTABa8QyOAF5MAOi58BACgDe9OHADWvAJ4AGAFzyArqy2sIAd1bKAlABoN2vQEZjGOWYvXbj5zq6AEweXuaWNvZOmoEAzKHeEX7RLroALAnhvlEBegCsmT6R-jF6AGyFSTmlugDsldklqQAcDcUpgQCcbcm5uq5Gplntfa7uQ0W9Na4hE1VNga7xc40dbhkrI9MFm1OprhW71fv1RwturWdr-d1XfUGDnomr9+NPw3uBQbPvk8dfy1+82uQQ2QJeNSCO3BW1SQUOMM+eiCp0R-2RlzR52Ctyx11ijzCf2xsTeROBfViP3JENSsUBNNhcTBjKRuli0NZ6PZCK5JNRfPxmMFlNxIpqaUJzyZejSZOlbLS1IV3LSDJV2LSLI11zSnJ1fTSvINEoFJtSaWF5sCaTF1vyUo+3Ly8qd2Lyyrd1zy6q9fTy2r9NTy+qDqTyxrDgTyZqj+Stcd0eTtibKjuJ1zKrozfTKnpzNTKvpzAF87AwWOx4IFhGIJFJZJ5AhBsMpFPwhCJxJJy-QgA).

**Comment by fabian-hiller** [comment]
Thank you for creating this issue. Seems like we already have a PR with a fix. I will review it soon.
