### ISSUE TITLE
toJsonSchema generates unsatisfiable schema for intersect of objects

### ISSUE THREAD

**Issue by pokutuna** [fabian-hiller/valibot#990]
## Problem

When using `toJsonSchema` with `intersect` of objects, it generates a JSON Schema that cannot be satisfied due to conflicting `additionalProperties: false` constraints.
I understand that Valibot is not primarily designed for JSON Schema compatibility, but this makes the conversion feature unusable for any JSON Schema interoperability scenarios.

## Reproduction
```typescript
import { object, string, number, intersect } from 'valibot';
import { toJsonSchema } from '@valibot/json-schema';

const schema = intersect([
  object({ foo: string() }),
  object({ bar: number() }),
]);
console.log(JSON.stringify(toJsonSchema(schema), null, 2));
/*
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "allOf": [
    {
      "type": "object",
      "properties": {
        "foo": {
          "type": "string"
        }
      },
      "required": [
        "foo"
      ],
      "additionalProperties": false
    },
    {
      "type": "object",
      "properties": {
        "bar": {
          "type": "number"
        }
      },
      "required": [
        "bar"
      ],
      "additionalProperties": false
    }
  ]
}
*/
```

## Current Behavior
The generated JSON Schema includes `additionalProperties: false` for each object in `allOf`, making it impossible to satisfy both constraints simultaneously.

## Expected Behavior
The generated JSON Schema should allow objects that have both properties, matching Valibot's runtime validation behavior.
Possible solutions:
- Remove `additionalProperties: false` from individual objects in allOf
- Add `additionalProperties: false` only at the parent level

### versions
```
$ npm list | grep valibot
...
├── @valibot/to-json-schema@1.0.0-beta.3
└── valibot@1.0.0-beta.9
```

**Comment by fabian-hiller** [comment]
Thank you for creating this issue. I will investigate and fix it in the next few weeks.

**Comment by fabian-hiller** [comment]
As a workaround you can try using [object merging](https://valibot.dev/guides/intersections/#merge-objects) instead of `intersect`:

```ts
import * as v from 'valibot';

const ObjectSchema1 = v.object({ foo: v.string(), baz: v.number() });
const ObjectSchema2 = v.object({ bar: v.string(), baz: v.boolean() });

const MergedSchema = v.object({
  ...ObjectSchema1.entries,
  ...ObjectSchema2.entries,
}); // { foo: string; bar: string; baz: boolean }
```

**Comment by andersk** [comment]
> Possible solutions:
>
> - Remove `additionalProperties: false` from individual objects in allOf
> - Add `additionalProperties: false` only at the parent level

That does not work ([try it](https://www.jsonschemavalidator.net/s/zfabfSxb)). You can, however, set [`unevaluatedProperties`](https://json-schema.org/understanding-json-schema/reference/object#unevaluatedproperties) to `false` at the parent level ([try it](https://www.jsonschemavalidator.net/s/eBARHYnF)).

**Comment by fabian-hiller** [comment]
Thank you for your feedback! If any of you have some time, feel free to research how other libraries, e.g. TypeBox, handle this case, or if there is an official recommendation on the official JSON schema website.

**Comment by 43081j** [comment]
fwiw that's pretty much what `unevaluatedProperties` is for

so when we combine multiple schemas (via `allOf` or similar), we can disallow additional properties to those in the combined set of sub-schemas

I suppose you could make an `intersect` of multiple `object` set `unevaluatedProperties: false` when converting to a schema

**Comment by fabian-hiller** [comment]
It seems that TypeBox (a JSON Schema library) does exactly what we do:

![Screenshot-TypeBox](https://github.com/user-attachments/assets/589e7847-b50d-47f5-bad2-f2ddf5ec000f)

**Comment by 43081j** [comment]
I opened #997 as one possible solution

the couple of zod JSON schema generators that exist seem to do what that PR does too

feel free to throw it away though if its not the direction you want to go

also note that we set `additionalProperties: false` but it doesn't look like TypeBox does that

**Comment by fabian-hiller** [comment]
Perhaps we should not add `.additionalProperties` at all when using `v.object({...})`. This will probably solve the problem.

**Comment by 43081j** [comment]
since we're coming from typescript types, I think we're correct in setting `additionalProperties: false` right now

especially since we support things like `objectWithRest` which do need to set `additionalProperties` to a non-false value

if we don't set it anymore, it means the typescript types and the JSON schema don't quite match up anymore and there'd be no difference between an object, and an object with rest

**Comment by fabian-hiller** [comment]
My idea was to add `additionalProperties: true` for `looseObject`, `additionalProperties: false` for `strictObject` and for the "normal" `object` schema we don't add `additionalProperties`. So we provide all possible three options.

**Comment by 43081j** [comment]
that could work

it would mean in an intersection of strict objects, we would still want to set `unevaluatedProperties: false`. the PR I threw together might already do that without many changes

**Comment by fabian-hiller** [comment]
Our implementation is still on Draft 07, where `unevaluatedProperties` is not supported. Perhaps we should ignore the `strictObject` problem for now, as it is probably a rare case, and upgrade to a newer draft for the v2 version of `toJsonSchema`.

**Comment by 43081j** [comment]
makes sense

it just means you wont be able to convert intersections of strict objects into a schema

validation will fail if you have properties from multiple sub-schemas

maybe we could temporarily throw in those cases until we do update to the newer draft? otherwise the schema it will produce isn't of much use

**Comment by fabian-hiller** [comment]
There is a workaround. Users could merge schemas instead of using `intersect` in most cases. https://valibot.dev/guides/intersections/#merge-objects

As a small bundle size is one of the main features of Valibot I am not sure if I want to add code to throw and error in this case.

**Comment by andersk** [comment]
> it just means you wont be able to convert intersections of strict objects into a schema

Actually `additionalProperties: false` is a faithful translation for `v.strictObject`, even under intersections. A Valibot intersection of `v.strictObject`s with conflicting key requirements is just as unsatisfiable in Valibot’s runtime as the corresponding JSON schema using `allOf` of objects with `additionalProperties: false`.

**Comment by 43081j** [comment]
🤔 interesting

So an intersection of two strict objects:

1. `{ foo: v.string() }`
2. `{ bar: v.string() }`

Is expected to fail for the input `{ foo: "x", bar: "x" }`?

The JSON schema will fail to validate that input. You're saying valibot will too?

**Comment by andersk** [comment]
Yes; [try it](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1QlIFMA6UiAOYAKDD1TJsXAArIoqLkPpxMPYKxhc5XJjCEBtJcpWoYUYDoDyFAFbbdAbxwQIALmOm1wgJRwAvl4AaQ2VREzNLGzshRwpZN1CPVm8-QMMAXVTlR2xnNwAiAA88gLhYqHyiv3ovL3ogA).

**Comment by 43081j** [comment]
I'm not at a laptop right now so couldn't try it myself. Thanks for the playground 👍

In that case, `object` seems to be more appropriate when using intersection (forgetting the fact you can use merging for now). And intersecting strict objects is meaningless

Dumbing the schema down to always allow additional properties is the easy way out then. Then object with rest is the same as object

**Comment by andersk** [comment]
It may still be meaningful to intersect strict objects with the same set of required keys, or intersect a strict object with a non-strict object.

What I’m saying is that adding `additionalProperties: false` for strict objects only is the correct resolution.

**Comment by 43081j** [comment]
Intersecting with a strict or non strict object which has extra keys can never validate in JSON schema if the input uses keys from both. That seems understood now at least

So yes, strict objects can have additional properties disabled and that won't help the OP

Going back to the OP, we could set additional properties to `true` on object schemas like Fabian suggested. This then makes `object` and `objectWithRest` mostly the same in JSON schema output (since we will have relaxed the type compared to the typescript type)

**Comment by andersk** [comment]
Removing `additionalProperties: false` for non-strict objects will help the OP. As far as JSON schema is concerned, there’s no difference between missing `additionalProperties`, `additionalProperties: {}`, and `additionalProperties: true`.

**Comment by 43081j** [comment]
Indeed it will. That is exactly what I was suggesting, the same as what Fabian suggested

> we could set additional properties to true on object schemas like Fabian suggested. This then makes object and objectWithRest mostly the same in JSON schema output (since we will have relaxed the type compared to the typescript type

Good to be agreed!

**Comment by fabian-hiller** [comment]
v1.0.0-beta.4 of `@valibot/to-json-schema` is available
