### ISSUE TITLE
Getting keys from schema

### ISSUE THREAD

**Issue by chertik77** [fabian-hiller/valibot#993]
```typescript
export const BoardSchema = v.object({
  title: v.string([
    v.toTrimmed(),
    v.minLength(3, 'Please enter at least 3 characters.')
  ]),
  icon: v.picklist(icons),
  background: v.string()
})
```
 
 How i can get an array of keys in my schema like this? 
 
```const fields = ['icon', 'title', 'background'] as const```

**Comment by andersk** [comment]
`v.keyof(BoardSchema).options`

Documentation: [`keyof`](https://valibot.dev/api/keyof/) → [`PicklistSchema.options`](https://valibot.dev/api/PicklistSchema/).

**Comment by chertik77** [comment]
> v.keyof(BoardSchema).options

Thanks a lot!

**Comment by fabian-hiller** [comment]
This might work too and is probably better if you don't care about the keyof schema:

```
const keys = Object.keys(BoardSchema.entries);
```

**Comment by andersk** [comment]
`Object.keys` returns type `string[]`, while `.options` gives the specific literal type `["title", "icon", "background"]` (which I assumed you wanted from `as const`).

**Comment by chertik77** [comment]
> `Object.keys` returns type `string[]`, while `.options` gives the specific literal type `["title", "icon", "background"]` (which I assumed you wanted from `as const`).

Exactly, I'm gonna know 2 approaches, thanks guys
